const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), crypto = require('node:crypto'), cp = require('node:child_process');
const repo = '/Users/stephan/Workspace/skunkworks/gomad/temporal', cwd = path.join(repo, 'tools/gomad3'), root = __dirname;
const go = '/home/agent/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.27.1.linux-arm64/bin/go';
const env = {...process.env, PATH:path.dirname(go)+':/usr/local/bin:/usr/bin:/bin', GOENV:'off', GOWORK:'off', GOTOOLCHAIN:'local', GOPROXY:'off', GOSUMDB:'off', GOFLAGS:'', GOMAXPROCS:'2'};
for (const key of ['GOMADSEED','GOMAD3_CHILD_SEED','GOMAD3_SEED']) delete env[key];
const git = (...args) => cp.execFileSync('git', args, {cwd:repo, encoding:'utf8'});
const sha = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const selected = git('ls-files','-z','tools/gomad3').split('\0').filter(Boolean).concat('tools/gomad3/target/adapter_source_set_test.go');
const inputs = ['run.cjs','source-selection-final.go','../source-selection.go','../../adapter-command-gap-2026-10-05/base-process-probe/probe.go'];
const snapshot = () => ({head:git('rev-parse','HEAD').trim(),files:Object.fromEntries(selected.map(f=>[f,sha(path.join(repo,f))])),inputs:Object.fromEntries([go,...inputs.map(f=>path.join(root,f))].map(f=>[f,sha(f)]))});
const write = (file, data) => fs.writeFileSync(file,data,{flag:'wx'});
const [label, command, ...args] = process.argv.slice(2);
if (!label || !command) throw Error('usage: run.cjs label command args');
const out = path.join(root,label); fs.mkdirSync(out);
const before = snapshot(); write(path.join(out,'before.json'),JSON.stringify(before,null,2)+'\n');
const executable = command==='go'?go:(command.includes('/')?command:env.PATH.split(':').map(d=>path.join(d,command)).find(f=>fs.existsSync(f)));
const tool_sha256 = sha(executable);
const started = new Date().toISOString(), start = process.hrtime.bigint();
const result = cp.spawnSync(command==='go'?go:command,args,{cwd,env,timeout:600000,killSignal:'SIGKILL',maxBuffer:64*1024*1024});
write(path.join(out,'stdout.txt'),result.stdout||Buffer.alloc(0)); write(path.join(out,'stderr.txt'),result.stderr||Buffer.alloc(0));
const after = snapshot(); write(path.join(out,'after.json'),JSON.stringify(after,null,2)+'\n');
const receipt = {label,command:[command==='go'?go:command,...args],cwd,started,finished:new Date().toISOString(),elapsed_ms:Number(process.hrtime.bigint()-start)/1e6,status:result.status,signal:result.signal,error:result.error?.message,executable,tool_sha256,tool_unchanged:tool_sha256===sha(executable),host:{platform:os.platform(),arch:os.arch(),release:os.release()},environment:Object.fromEntries(['PATH','GOENV','GOWORK','GOTOOLCHAIN','GOPROXY','GOSUMDB','GOFLAGS','GOMAXPROCS','GOMODCACHE','GOCACHE','GOROOT','GOEXPERIMENT','CGO_ENABLED'].map(k=>[k,env[k]??null])),unset:['GOMADSEED','GOMAD3_CHILD_SEED','GOMAD3_SEED'],inputs_unchanged:JSON.stringify(before)===JSON.stringify(after),stdout_sha256:sha(path.join(out,'stdout.txt')),stderr_sha256:sha(path.join(out,'stderr.txt'))};
write(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');
console.log(JSON.stringify(receipt));
if (!receipt.inputs_unchanged) throw Error('inputs changed during command');
process.exit(result.status===null?2:result.status);
