import Umpire.CoreTests
import Umpire.PropertyTests
import Umpire.BehaviorTests
import Umpire.PropertyImportTests
import Umpire.BehaviorImportTests
import Umpire.SearchImportTests
import Umpire.QueryTests
import Umpire.PlanningTests
import Umpire.PlanningVisibilityTests
import Umpire.Examples.SwitchTests
