import Umpire.CoreTests
import Umpire.Property.Tests
import Umpire.Behavior.Tests
import Umpire.Property.ImportTests
import Umpire.Behavior.ImportTests
import Umpire.SearchImportTests
import Umpire.Query.Tests
import Umpire.Planning.Tests
import Umpire.Planning.VisibilityTests
import Umpire.Examples.SwitchTests
