package main

import (
	"fmt"
	"strings"
)

func generateArtifacts(configuration generationConfig, projection projection) (map[string][]byte, error) {
	plan, err := buildLeanPlan(projection, configuration)
	if err != nil {
		return nil, err
	}
	artifacts := map[string][]byte{
		configuration.Layout.ProtoPath: renderProto(configuration.Layout),
		configuration.Layout.TypesPath: renderTypes(plan),
		configuration.Layout.APIPath:   renderAPI(plan, configuration.Layout),
	}
	if err := validateArtifactMap(configuration.Layout, artifacts); err != nil {
		return nil, err
	}
	return artifacts, nil
}

func renderProto(layout outputLayout) []byte {
	var generated strings.Builder
	writeGeneratedHeader(&generated)
	fmt.Fprintf(&generated, "\nnamespace %s.API.Proto\n\n", layout.RootModule)
	generated.WriteString(`structure Bytes where
  digest : String
  size : Nat
  deriving DecidableEq, Repr

structure MessageRef where
  descriptor : String
  remainingDepth : Nat
  deriving DecidableEq, Repr

structure Method (Request Response : Type) where
  fullName : String
  clientStreaming : Bool
  serverStreaming : Bool
  deprecated : Bool
  deriving DecidableEq, Repr

`)
	fmt.Fprintf(&generated, "end %s.API.Proto\n", layout.RootModule)
	return []byte(generated.String())
}

func renderTypes(plan leanPlan) []byte {
	var generated strings.Builder
	writeModuleHeader(&generated, plan.TypesModule)
	for _, namespace := range plan.Namespaces {
		fmt.Fprintf(&generated, "namespace %s\n\n", namespace.Name.String())
		for _, enum := range namespace.Enums {
			fmt.Fprintf(&generated, "structure %s where\n  number : Int\n  deriving DecidableEq, Repr\n\n", enum.RelativeName)
			fmt.Fprintf(&generated, "namespace %s\n", enum.RelativeName)
			for _, value := range enum.Values {
				fmt.Fprintf(&generated, "def %s : %s := { number := %d }\n",
					value.Name, enum.RelativeName, value.Projection.Number)
			}
			fmt.Fprintf(&generated, "end %s\n\n", enum.RelativeName)
		}
		for _, message := range namespace.Messages {
			for _, oneof := range message.Oneofs {
				fmt.Fprintf(&generated, "inductive %s where\n  | notSet\n", oneof.RelativeName)
				for _, constructor := range oneof.Constructors {
					fmt.Fprintf(&generated, "  | %s (value : %s)\n",
						constructor.Field.Name, renderLeanType(constructor.Field.BaseType))
				}
				generated.WriteString("  deriving Repr\n\n")
			}
			fmt.Fprintf(&generated, "structure %s where\n", message.RelativeName)
			for _, field := range message.StructureFields {
				fmt.Fprintf(&generated, "  %s : %s\n", field.Name, renderLeanType(field.Type))
			}
			if len(message.StructureFields) == 0 {
				generated.WriteString("  unit : Unit := ()\n")
			}
			generated.WriteString("  deriving Repr\n\n")
		}
		fmt.Fprintf(&generated, "end %s\n\n", namespace.Name.String())
	}
	return []byte(strings.TrimRight(generated.String(), "\n") + "\n")
}

func renderAPI(plan leanPlan, layout outputLayout) []byte {
	var generated strings.Builder
	writeModuleHeader(&generated, plan.APIModule)
	for _, service := range plan.Services {
		fmt.Fprintf(&generated, "namespace %s\n", service.Name.String())
		for _, method := range service.Methods {
			fmt.Fprintf(&generated, "def %s : %s.API.Proto.Method %s %s :=\n",
				method.Name, layout.RootModule, renderLeanType(method.InputType), renderLeanType(method.OutputType))
			fmt.Fprintf(&generated, "  { fullName := %q, clientStreaming := %t, serverStreaming := %t, deprecated := %t }\n",
				method.Projection.FullName, method.Projection.ClientStreaming,
				method.Projection.ServerStreaming, method.Projection.Deprecated)
		}
		fmt.Fprintf(&generated, "end %s\n\n", service.Name.String())
	}
	return []byte(strings.TrimRight(generated.String(), "\n") + "\n")
}

func writeGeneratedHeader(generated *strings.Builder) {
	generated.WriteString("-- Code generated by umpire-gen-lean-api. DO NOT EDIT.\n")
	generated.WriteString("-- This is a structural descriptor projection, not behavioral semantics.\n")
}

func writeModuleHeader(generated *strings.Builder, module leanModulePlan) {
	writeGeneratedHeader(generated)
	for _, imported := range module.Imports {
		fmt.Fprintf(generated, "import %s\n", imported)
	}
	generated.WriteString("\nset_option maxRecDepth 100000\n\n")
}
