import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,readdirSync,existsSync,statSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root='/Users/stephan/Workspace/skunkworks/gomad/temporal';
const out=dirname(fileURLToPath(import.meta.url));
const sha=b=>createHash('sha256').update(b).digest('hex');
const read=p=>readFileSync(resolve(root,p));
const json=p=>JSON.parse(readFileSync(resolve(out,p),'utf8'));
const head=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'});
assert.equal(head.status,0);
assert.equal(head.stdout.trim(),'8c8f8973c391dc74ae56f88b7bbac86d785e3745');
assert(!existsSync(resolve(out,'evidence.json')),'frozen handover exists');
const proof=json('source-proof.json'),standards=json('standards-proof.json'),transport=json('transport-proof.json');
for(const binding of [...proof.source_slice,...proof.references,...proof.user_files])assert.equal(sha(read(binding.path)),binding.sha256,binding.path);
const labels=readdirSync(out).filter(p=>p.endsWith('.json')).filter(p=>Array.isArray(json(p).argv)).sort();
const diagnostics=new Set(['configured-source-lint','configured-package-diagnostics']);
const retainedFailures=new Set(['source-binding-check','source-binding-final']);
const guards=new Set(['proof-overwrite-guard','receipt-overwrite-guard']);
const commandReceipts=labels.map(p=>{
 const r=json(p),label=p.slice(0,-5);
 assert.deepEqual(r.source_changes,[],label);
 assert.equal(r.sources_before_sha256,r.sources_after_sha256,label);
 assert.equal(sha(readFileSync(resolve(out,label+'.stdout'))),r.stdout_sha256,label);
 assert.equal(sha(readFileSync(resolve(out,label+'.stderr'))),r.stderr_sha256,label);
 assert.equal(r.error,null,label);assert.equal(r.signal,null,label);
 assert.equal(r.exit,diagnostics.has(label)?2:retainedFailures.has(label)||guards.has(label)?1:0,label);
 return {path:p,sha256:sha(readFileSync(resolve(out,p))),argv:r.argv,exit:r.exit,elapsed_seconds:r.elapsed_seconds,top_level_counts:r.top_level_counts,classification:diagnostics.has(label)?'inherited diagnostic findings':retainedFailures.has(label)?'retained source-helper failed attempt':guards.has(label)?'expected non-overwrite refusal':'current source observation'};
});
const passes=commandReceipts.filter(r=>r.path.startsWith('portable-')&&r.exit===0).reduce((n,r)=>n+r.top_level_counts.pass,0);
assert.equal(passes,47);
assert.equal(transport.receipts[0].exit,1);assert.equal(transport.receipts[1].exit,0);
for(const r of transport.receipts){
 assert.equal(sha(readFileSync(resolve(out,r.label+'.stdout'))),r.stdout_sha256);
 assert.equal(sha(readFileSync(resolve(out,r.label+'.stderr'))),r.stderr_sha256);
 assert.equal(sha(readFileSync(r.argv.at(-2))),r.source_sha256);
 assert.equal(sha(readFileSync(r.argv.at(-1))),r.fixture_sha256);
}
const fileList=spawnSync('git',['ls-files','-z'],{cwd:root,maxBuffer:32<<20});assert.equal(fileList.status,0);
const sources=Object.fromEntries(fileList.stdout.toString().split('\0').filter(p=>p&&!p.startsWith('.flow/')&&existsSync(resolve(root,p))&&statSync(resolve(root,p)).isFile()).sort().map(p=>[p,sha(read(p))]));
const sourceIdentity=sha(JSON.stringify(sources));
for(const p of labels)assert.equal(json(p).sources_after_sha256,sourceIdentity,p);
const state=spawnSync('/home/agent/.codex/scripts/flowctl',['show','fn-105-gomad-follow-ups-deferred-scope.31','--json'],{cwd:root,encoding:'utf8',maxBuffer:4<<20});assert.equal(state.status,0);assert.equal(JSON.parse(state.stdout).status,'in_progress');
const artifacts=readdirSync(out).sort().map(path=>({path,bytes:statSync(resolve(out,path)).size,sha256:sha(readFileSync(resolve(out,path)))}));
const evidence={task_id:'fn-105-gomad-follow-ups-deferred-scope.31',status:'in_progress',base_commit:head.stdout.trim(),commits:[],tests:commandReceipts.map(r=>r.argv.map(a=>JSON.stringify(a)).join(' ')),prs:[],scope:'source acceptance only; conductor owns review, lifecycle and commits',tier:'session (jev-unavailable(no_key)); explicit project implementer retained, gpt-6.1-sol at high',source_identity_sha256:sourceIdentity,current_portable_top_level_counts:{pass:passes,fail:0,skip:0},historical_causal_host_counts:{pass:1,fail:1,skip:0},command_receipts:commandReceipts,artifacts,native_qualification:false,review_verdict:null,limitations:['Original D26 native RED/GREEN execution receipts not found; fresh causal comparison is host arbiter source only.','Inherited runtime gofmt separator remains fn-109.13; no global format pass or waiver.','Unfiltered nested package lint has 24 inherited findings, none in original R26 paths/hunks.','Transferred patched/native fixtures, seeds 1-24, forward11/17 traced replay and full-host gates remain unverified.'],frozen_at:new Date().toISOString()};
writeFileSync(resolve(out,'evidence.json'),JSON.stringify(evidence,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({status:evidence.status,source_identity_sha256:sourceIdentity,command_receipts:commandReceipts.length,artifacts:artifacts.length,portable_passes:passes,evidence_sha256:sha(readFileSync(resolve(out,'evidence.json')))}));
