-- Code generated by umpire-gen-lean-api. DO NOT EDIT.
-- This is a structural descriptor projection, not behavioral semantics.

/-!
Common structural types used by the generated Temporal API projection.

`Bytes` and `MessageRef` retain opaque descriptor data, while `Method` records the request,
response, streaming, and deprecation shape of one gRPC method.
-/

set_option linter.missingDocs false

namespace EmptyFixture.API.Proto

structure Bytes where
  digest : String
  size : Nat
  deriving DecidableEq, Repr

structure MessageRef where
  descriptor : String
  remainingDepth : Nat
  deriving DecidableEq, Repr

structure Method (Request Response : Type) where
  fullName : String
  clientStreaming : Bool
  serverStreaming : Bool
  deprecated : Bool

-- Written out because deriving would require instances of the phantom payload types.
instance : DecidableEq (Method Request Response)
  | ⟨fullName, clientStreaming, serverStreaming, deprecated⟩,
    ⟨fullName', clientStreaming', serverStreaming', deprecated'⟩ =>
    decidable_of_iff (fullName = fullName' ∧ clientStreaming = clientStreaming' ∧
      serverStreaming = serverStreaming' ∧ deprecated = deprecated') (by simp)

instance : Repr (Method Request Response) where
  reprPrec method _ := Std.Format.bracket "{ "
    (f!"fullName := {repr method.fullName}," ++ Std.Format.line ++
      f!"clientStreaming := {method.clientStreaming}," ++ Std.Format.line ++
      f!"serverStreaming := {method.serverStreaming}," ++ Std.Format.line ++
      f!"deprecated := {method.deprecated}") " }"

end EmptyFixture.API.Proto
