import Umpire.Promotion
import Umpire.Examples.Switch

/-! Checked review-only regression source generated by Umpire.Promotion. -/

namespace Umpire.Promotion.Tests.Fixtures.CompiledSource

open Umpire

def promotionSourceDefinitionId : DefinitionId := (DefinitionId.of "umpire.promotion.source.switch-count-one")

def source : SourceLocation := { path := "Umpire/Promotion/Tests/Fixtures/CompiledSource.lean", line := 1, column := 1, provenance := "lean-model" }

def expectedTrace : BehaviorTrace := { setup := [{ role := (DefinitionId.of "switch.role.subject"), value := { definitionId := (DefinitionId.of "switch.state.power"), value := "off" } }], trace := { initialState := { definitionId := (DefinitionId.of "switch.state.power"), value := "off" }, steps := [{ selectedAction := { definitionId := (DefinitionId.of "switch.action.flip"), value := "flip" }, modelOutcome := { definitionId := (DefinitionId.of "switch.outcome.applied"), value := "applied" }, resultingState := { definitionId := (DefinitionId.of "switch.state.power"), value := "on" }, observations := [{ definitionId := (DefinitionId.of "switch.observation.power"), value := "on" }] }] } }

def promotedQueryResult :=
  checkPromotedQuery Umpire.Examples.Switch.exactActionQuery expectedTrace
    (DefinitionId.of "umpire.behavior.regression.switch-count-one")
    (DefinitionId.of "umpire.query.regression.switch-count-one") source

private theorem promotedQueryResult_isSome :
    promotedQueryResult.toOption.isSome = true := by
  native_decide

def promotedQuery :=
  promotedQueryResult.toOption.get promotedQueryResult_isSome

end Umpire.Promotion.Tests.Fixtures.CompiledSource
