// Code generated by cmd/gomadtool protocol-generate. DO NOT EDIT.

package gomadwire

import (
	"bytes"
	"encoding/binary"
	"errors"
	"io"
)

const (
	BootstrapFrameBytes      = 212
	BootstrapChecksumOffset  = 180
	TranscriptHeaderBytes    = 64
	TranscriptRecordBytes    = 128
	TranscriptOperationBytes = 22
	TerminalFrameBytes       = 104
	TerminalChecksumOffset   = 72
	MountRequestHeaderBytes  = 24
	MountResponseHeaderBytes = 40
	DigestBytes              = 32
	mountChildHeaderBytes    = 8
	wireVersion              = 1
)

var (
	bootstrapMagic          = [8]byte{'G', 'O', 'M', 'A', 'D', 'I', 'O', '\x01'}
	producedTranscriptMagic = [8]byte{'G', 'O', 'M', 'A', 'D', 'T', 'R', '\x01'}
	expectedTranscriptMagic = [8]byte{'G', 'O', 'M', 'A', 'D', 'X', 'T', '\x01'}
	terminalMagic           = [8]byte{'G', 'O', 'M', 'A', 'D', 'I', 'T', '\x01'}
	mountRequestMagic       = [8]byte{'G', 'O', 'M', 'A', 'D', 'R', 'O', '\x01'}
	mountResponseMagic      = [8]byte{'G', 'O', 'M', 'A', 'D', 'R', 'S', '\x01'}
)

type Bootstrap struct {
	InventoryHash      [DigestBytes]byte
	ImplementationHash [DigestBytes]byte
	TargetHash         [DigestBytes]byte
	RunnerHash         [DigestBytes]byte
	ArgvHash           [DigestBytes]byte
	Seed               uint64
}

func EncodeBootstrap(value Bootstrap) [BootstrapFrameBytes]byte {
	var frame [BootstrapFrameBytes]byte
	copy(frame[:8], bootstrapMagic[:])
	binary.BigEndian.PutUint16(frame[8:10], wireVersion)
	binary.BigEndian.PutUint16(frame[10:12], 1)
	offset := 12
	for _, digest := range [][DigestBytes]byte{value.InventoryHash, value.ImplementationHash, value.TargetHash, value.RunnerHash, value.ArgvHash} {
		copy(frame[offset:offset+DigestBytes], digest[:])
		offset += DigestBytes
	}
	binary.BigEndian.PutUint64(frame[offset:offset+8], value.Seed)
	checksum := sum256(frame[:BootstrapChecksumOffset])
	copy(frame[BootstrapChecksumOffset:], checksum[:])
	return frame
}

func DecodeBootstrap(frame []byte) (Bootstrap, error) {
	if len(frame) != BootstrapFrameBytes || !bytes.Equal(frame[:8], bootstrapMagic[:]) || binary.BigEndian.Uint16(frame[8:10]) != wireVersion || binary.BigEndian.Uint16(frame[10:12]) != 1 {
		return Bootstrap{}, errors.New("invalid I/O bootstrap frame")
	}
	checksum := sum256(frame[:BootstrapChecksumOffset])
	if !bytes.Equal(frame[BootstrapChecksumOffset:], checksum[:]) {
		return Bootstrap{}, errors.New("I/O bootstrap frame checksum mismatch")
	}
	value := Bootstrap{}
	offset := 12
	for _, destination := range []*[DigestBytes]byte{&value.InventoryHash, &value.ImplementationHash, &value.TargetHash, &value.RunnerHash, &value.ArgvHash} {
		copy(destination[:], frame[offset:offset+DigestBytes])
		offset += DigestBytes
	}
	value.Seed = binary.BigEndian.Uint64(frame[offset : offset+8])
	return value, nil
}

type ProducedTranscriptHeader struct {
	Capacity    uint64
	NextOffset  uint64
	RecordCount uint64
}

func EncodeProducedTranscriptHeader(capacity uint64) [TranscriptHeaderBytes]byte {
	var header [TranscriptHeaderBytes]byte
	copy(header[:8], producedTranscriptMagic[:])
	binary.BigEndian.PutUint32(header[8:12], wireVersion)
	binary.BigEndian.PutUint64(header[16:24], capacity)
	binary.BigEndian.PutUint64(header[24:32], TranscriptHeaderBytes)
	return header
}

func DecodeProducedTranscriptHeader(header []byte) (ProducedTranscriptHeader, error) {
	if len(header) != TranscriptHeaderBytes || !bytes.Equal(header[:8], producedTranscriptMagic[:]) || binary.BigEndian.Uint32(header[8:12]) != wireVersion || !zero(header[12:16]) || !zero(header[40:64]) {
		return ProducedTranscriptHeader{}, errors.New("invalid produced I/O transcript header")
	}
	value := ProducedTranscriptHeader{
		Capacity: binary.BigEndian.Uint64(header[16:24]), NextOffset: binary.BigEndian.Uint64(header[24:32]), RecordCount: binary.BigEndian.Uint64(header[32:40]),
	}
	if value.Capacity < TranscriptHeaderBytes || value.NextOffset < TranscriptHeaderBytes || value.NextOffset > value.Capacity || (value.NextOffset-TranscriptHeaderBytes)%TranscriptRecordBytes != 0 || value.RecordCount != (value.NextOffset-TranscriptHeaderBytes)/TranscriptRecordBytes {
		return ProducedTranscriptHeader{}, errors.New("invalid produced I/O transcript bounds")
	}
	return value, nil
}

func PublishProducedTranscript(header []byte, nextOffset, recordCount uint64) error {
	current, err := DecodeProducedTranscriptHeader(header)
	if err != nil {
		return err
	}
	if nextOffset < TranscriptHeaderBytes || nextOffset > current.Capacity || (nextOffset-TranscriptHeaderBytes)%TranscriptRecordBytes != 0 || recordCount != (nextOffset-TranscriptHeaderBytes)/TranscriptRecordBytes {
		return errors.New("invalid produced I/O transcript publication")
	}
	binary.BigEndian.PutUint64(header[24:32], nextOffset)
	binary.BigEndian.PutUint64(header[32:40], recordCount)
	return nil
}

type ExpectedTranscriptHeader struct {
	Replay       bool
	PayloadBytes uint64
	RecordCount  uint64
	PayloadHash  [DigestBytes]byte
}

func EncodeExpectedTranscriptHeader(replay bool, payload []byte) ([TranscriptHeaderBytes]byte, error) {
	var header [TranscriptHeaderBytes]byte
	if len(payload)%TranscriptRecordBytes != 0 {
		return header, errors.New("invalid expected I/O transcript payload length")
	}
	copy(header[:8], expectedTranscriptMagic[:])
	binary.BigEndian.PutUint32(header[8:12], wireVersion)
	if replay {
		header[12] = 1
	}
	binary.BigEndian.PutUint64(header[16:24], uint64(len(payload)))
	binary.BigEndian.PutUint64(header[24:32], uint64(len(payload))/TranscriptRecordBytes)
	digest := sum256(payload)
	copy(header[32:64], digest[:])
	return header, nil
}

func DecodeExpectedTranscriptHeader(header []byte, capacity uint64) (ExpectedTranscriptHeader, error) {
	if len(header) != TranscriptHeaderBytes || !bytes.Equal(header[:8], expectedTranscriptMagic[:]) || binary.BigEndian.Uint32(header[8:12]) != wireVersion || header[12] > 1 || !zero(header[13:16]) {
		return ExpectedTranscriptHeader{}, errors.New("invalid expected I/O transcript header")
	}
	value := ExpectedTranscriptHeader{Replay: header[12] == 1, PayloadBytes: binary.BigEndian.Uint64(header[16:24]), RecordCount: binary.BigEndian.Uint64(header[24:32])}
	copy(value.PayloadHash[:], header[32:64])
	if capacity < TranscriptHeaderBytes || value.PayloadBytes > capacity-TranscriptHeaderBytes || value.PayloadBytes%TranscriptRecordBytes != 0 || value.RecordCount != value.PayloadBytes/TranscriptRecordBytes {
		return ExpectedTranscriptHeader{}, errors.New("invalid expected I/O transcript bounds")
	}
	return value, nil
}

type TranscriptRecord struct {
	Ordinal      uint64
	Operation    string
	ArgumentHash [DigestBytes]byte
	ContentHash  [DigestBytes]byte
	Count        uint64
	Result       uint32
	EntropyStart uint64
	EntropyEnd   uint64
}

func EncodeTranscriptRecord(value TranscriptRecord) ([TranscriptRecordBytes]byte, error) {
	var record [TranscriptRecordBytes]byte
	if len(value.Operation) > TranscriptOperationBytes {
		return record, errors.New("I/O transcript operation exceeds its bound")
	}
	binary.BigEndian.PutUint64(record[:8], value.Ordinal)
	binary.BigEndian.PutUint16(record[8:10], uint16(len(value.Operation)))
	copy(record[10:32], value.Operation)
	copy(record[32:64], value.ArgumentHash[:])
	copy(record[64:96], value.ContentHash[:])
	binary.BigEndian.PutUint64(record[96:104], value.Count)
	binary.BigEndian.PutUint32(record[104:108], value.Result)
	binary.BigEndian.PutUint64(record[112:120], value.EntropyStart)
	binary.BigEndian.PutUint64(record[120:128], value.EntropyEnd)
	return record, nil
}

func DecodeTranscriptRecord(record []byte) (TranscriptRecord, error) {
	if len(record) != TranscriptRecordBytes || !zero(record[108:112]) {
		return TranscriptRecord{}, errors.New("invalid I/O transcript record")
	}
	operationBytes := int(binary.BigEndian.Uint16(record[8:10]))
	if operationBytes > TranscriptOperationBytes || !zero(record[10+operationBytes:32]) {
		return TranscriptRecord{}, errors.New("invalid I/O transcript operation")
	}
	value := TranscriptRecord{Ordinal: binary.BigEndian.Uint64(record[:8]), Operation: string(record[10 : 10+operationBytes]), Count: binary.BigEndian.Uint64(record[96:104]), Result: binary.BigEndian.Uint32(record[104:108]), EntropyStart: binary.BigEndian.Uint64(record[112:120]), EntropyEnd: binary.BigEndian.Uint64(record[120:128])}
	copy(value.ArgumentHash[:], record[32:64])
	copy(value.ContentHash[:], record[64:96])
	return value, nil
}

type TerminalState uint8

const (
	TerminalComplete         TerminalState = 1
	TerminalOverflow         TerminalState = 2
	TerminalReplayDivergence TerminalState = 3
)

type Terminal struct {
	State            TerminalState
	Records          uint64
	MappingBytes     uint64
	PayloadHash      [DigestBytes]byte
	DivergentOrdinal uint64
}

func EncodeTerminal(value Terminal) [TerminalFrameBytes]byte {
	var frame [TerminalFrameBytes]byte
	copy(frame[:8], terminalMagic[:])
	binary.BigEndian.PutUint32(frame[8:12], wireVersion)
	frame[12] = byte(value.State)
	binary.BigEndian.PutUint64(frame[16:24], value.Records)
	binary.BigEndian.PutUint64(frame[24:32], value.MappingBytes)
	copy(frame[32:64], value.PayloadHash[:])
	if value.State == TerminalReplayDivergence {
		binary.BigEndian.PutUint64(frame[64:72], value.DivergentOrdinal)
	}
	checksum := sum256(frame[:TerminalChecksumOffset])
	copy(frame[TerminalChecksumOffset:], checksum[:])
	return frame
}

func DecodeTerminal(frame []byte) (Terminal, error) {
	if len(frame) != TerminalFrameBytes || !bytes.Equal(frame[:8], terminalMagic[:]) || binary.BigEndian.Uint32(frame[8:12]) != wireVersion || !zero(frame[13:16]) {
		return Terminal{}, errors.New("invalid I/O terminal frame")
	}
	checksum := sum256(frame[:TerminalChecksumOffset])
	if !bytes.Equal(frame[TerminalChecksumOffset:], checksum[:]) {
		return Terminal{}, errors.New("I/O terminal frame checksum mismatch")
	}
	value := Terminal{State: TerminalState(frame[12]), Records: binary.BigEndian.Uint64(frame[16:24]), MappingBytes: binary.BigEndian.Uint64(frame[24:32]), DivergentOrdinal: binary.BigEndian.Uint64(frame[64:72])}
	copy(value.PayloadHash[:], frame[32:64])
	if value.State < TerminalComplete || value.State > TerminalReplayDivergence || value.MappingBytes < TranscriptHeaderBytes || (value.MappingBytes-TranscriptHeaderBytes)%TranscriptRecordBytes != 0 || value.Records != (value.MappingBytes-TranscriptHeaderBytes)/TranscriptRecordBytes {
		return Terminal{}, errors.New("invalid I/O terminal values")
	}
	if value.State != TerminalReplayDivergence && value.DivergentOrdinal != 0 {
		return Terminal{}, errors.New("invalid I/O terminal divergence ordinal")
	}
	return value, nil
}

type MountStatus uint16

const (
	MountStatusOK        MountStatus = 0
	MountStatusUnmounted MountStatus = 1
	MountStatusNotExist  MountStatus = 2
)

type MountKind uint8

const (
	MountKindFile      MountKind = 1
	MountKindDirectory MountKind = 2
)

type MountLimits struct {
	PathBytes        uint64
	FileBytes        uint64
	DirectoryEntries uint64
}

type MountRequest struct {
	Ordinal uint64
	Path    string
}

type MountChild struct {
	Name string
	Kind MountKind
	Mode uint32
}

type MountEntry struct {
	Kind     MountKind
	Mode     uint32
	Data     []byte
	Children []MountChild
}

type MountResponse struct {
	Ordinal uint64
	Status  MountStatus
	Entry   MountEntry
}

func WriteMountLookupRequest(writer io.Writer, request MountRequest, limits MountLimits) error {
	if uint64(len(request.Path)) > limits.PathBytes || len(request.Path) > int(^uint32(0)) {
		return errors.New("oversized read-only mount request path")
	}
	var header [MountRequestHeaderBytes]byte
	copy(header[:8], mountRequestMagic[:])
	binary.BigEndian.PutUint16(header[8:10], wireVersion)
	binary.BigEndian.PutUint16(header[10:12], 1)
	binary.BigEndian.PutUint64(header[12:20], request.Ordinal)
	binary.BigEndian.PutUint32(header[20:24], uint32(len(request.Path)))
	if err := writeFull(writer, header[:]); err != nil {
		return err
	}
	return writeFull(writer, []byte(request.Path))
}

func ReadMountLookupRequest(reader io.Reader, limits MountLimits) (MountRequest, error) {
	var header [MountRequestHeaderBytes]byte
	if _, err := io.ReadFull(reader, header[:]); err != nil {
		return MountRequest{}, err
	}
	if !bytes.Equal(header[:8], mountRequestMagic[:]) || binary.BigEndian.Uint16(header[8:10]) != wireVersion || binary.BigEndian.Uint16(header[10:12]) != 1 {
		return MountRequest{}, errors.New("invalid read-only mount request header")
	}
	pathBytes := uint64(binary.BigEndian.Uint32(header[20:24]))
	if pathBytes > limits.PathBytes || pathBytes > maxInt() {
		return MountRequest{}, errors.New("oversized read-only mount request path")
	}
	path := make([]byte, int(pathBytes))
	if _, err := io.ReadFull(reader, path); err != nil {
		return MountRequest{}, err
	}
	return MountRequest{Ordinal: binary.BigEndian.Uint64(header[12:20]), Path: string(path)}, nil
}

func WriteMountResponse(writer io.Writer, response MountResponse, limits MountLimits) error {
	if err := validateMountResponse(response, limits); err != nil {
		return err
	}
	var header [MountResponseHeaderBytes]byte
	copy(header[:8], mountResponseMagic[:])
	binary.BigEndian.PutUint16(header[8:10], wireVersion)
	binary.BigEndian.PutUint16(header[10:12], uint16(response.Status))
	binary.BigEndian.PutUint64(header[12:20], response.Ordinal)
	header[20] = byte(response.Entry.Kind)
	binary.BigEndian.PutUint32(header[24:28], response.Entry.Mode)
	binary.BigEndian.PutUint64(header[28:36], uint64(len(response.Entry.Data)))
	binary.BigEndian.PutUint32(header[36:40], uint32(len(response.Entry.Children)))
	if err := writeFull(writer, header[:]); err != nil {
		return err
	}
	if err := writeFull(writer, response.Entry.Data); err != nil {
		return err
	}
	for _, child := range response.Entry.Children {
		var childHeader [mountChildHeaderBytes]byte
		binary.BigEndian.PutUint16(childHeader[:2], uint16(len(child.Name)))
		childHeader[2] = byte(child.Kind)
		binary.BigEndian.PutUint32(childHeader[4:8], child.Mode)
		if err := writeFull(writer, childHeader[:]); err != nil {
			return err
		}
		if err := writeFull(writer, []byte(child.Name)); err != nil {
			return err
		}
	}
	return nil
}

func ReadMountResponse(reader io.Reader, limits MountLimits) (MountResponse, error) {
	var header [MountResponseHeaderBytes]byte
	if _, err := io.ReadFull(reader, header[:]); err != nil {
		return MountResponse{}, err
	}
	if !bytes.Equal(header[:8], mountResponseMagic[:]) || binary.BigEndian.Uint16(header[8:10]) != wireVersion || !zero(header[21:24]) {
		return MountResponse{}, errors.New("invalid read-only mount response header")
	}
	response := MountResponse{Ordinal: binary.BigEndian.Uint64(header[12:20]), Status: MountStatus(binary.BigEndian.Uint16(header[10:12])), Entry: MountEntry{Kind: MountKind(header[20]), Mode: binary.BigEndian.Uint32(header[24:28])}}
	dataBytes := binary.BigEndian.Uint64(header[28:36])
	children := uint64(binary.BigEndian.Uint32(header[36:40]))
	if response.Status > MountStatusNotExist {
		return MountResponse{}, errors.New("invalid read-only mount response status")
	}
	if response.Status != MountStatusOK {
		if response.Entry.Kind != 0 || response.Entry.Mode != 0 || dataBytes != 0 || children != 0 {
			return MountResponse{}, errors.New("invalid read-only mount response payload")
		}
		return response, nil
	}
	if !validMountKind(response.Entry.Kind) || response.Entry.Kind == MountKindFile && children != 0 || response.Entry.Kind == MountKindDirectory && dataBytes != 0 {
		return MountResponse{}, errors.New("invalid read-only mount response entry")
	}
	if dataBytes > limits.FileBytes || children > limits.DirectoryEntries || dataBytes > maxInt() || children > maxInt() {
		return MountResponse{}, errors.New("read-only mount response exceeds its bound")
	}
	response.Entry.Data = make([]byte, int(dataBytes))
	response.Entry.Children = make([]MountChild, 0, int(children))
	if _, err := io.ReadFull(reader, response.Entry.Data); err != nil {
		return MountResponse{}, err
	}
	for range children {
		var childHeader [mountChildHeaderBytes]byte
		if _, err := io.ReadFull(reader, childHeader[:]); err != nil {
			return MountResponse{}, err
		}
		nameBytes := uint64(binary.BigEndian.Uint16(childHeader[:2]))
		kind := MountKind(childHeader[2])
		if childHeader[3] != 0 || !validMountKind(kind) || nameBytes > limits.PathBytes || nameBytes > maxInt() {
			return MountResponse{}, errors.New("invalid read-only mount response child")
		}
		name := make([]byte, int(nameBytes))
		if _, err := io.ReadFull(reader, name); err != nil {
			return MountResponse{}, err
		}
		response.Entry.Children = append(response.Entry.Children, MountChild{Name: string(name), Kind: kind, Mode: binary.BigEndian.Uint32(childHeader[4:8])})
	}
	return response, nil
}

func validateMountResponse(response MountResponse, limits MountLimits) error {
	if response.Status > MountStatusNotExist {
		return errors.New("invalid read-only mount response status")
	}
	if response.Status != MountStatusOK {
		if response.Entry.Kind != 0 || response.Entry.Mode != 0 || len(response.Entry.Data) != 0 || len(response.Entry.Children) != 0 {
			return errors.New("invalid read-only mount response payload")
		}
		return nil
	}
	if !validMountKind(response.Entry.Kind) || response.Entry.Kind == MountKindFile && len(response.Entry.Children) != 0 || response.Entry.Kind == MountKindDirectory && len(response.Entry.Data) != 0 {
		return errors.New("invalid read-only mount response entry")
	}
	if uint64(len(response.Entry.Data)) > limits.FileBytes || uint64(len(response.Entry.Children)) > limits.DirectoryEntries || len(response.Entry.Children) > int(^uint32(0)) {
		return errors.New("read-only mount response exceeds its bound")
	}
	for _, child := range response.Entry.Children {
		if !validMountKind(child.Kind) || uint64(len(child.Name)) > limits.PathBytes || len(child.Name) > int(^uint16(0)) {
			return errors.New("invalid read-only mount response child")
		}
	}
	return nil
}

func validMountKind(kind MountKind) bool {
	return kind == MountKindFile || kind == MountKindDirectory
}

func writeFull(writer io.Writer, data []byte) error {
	for len(data) != 0 {
		written, err := writer.Write(data)
		if err != nil {
			return err
		}
		if written <= 0 || written > len(data) {
			return io.ErrShortWrite
		}
		data = data[written:]
	}
	return nil
}

func zero(data []byte) bool {
	for _, value := range data {
		if value != 0 {
			return false
		}
	}
	return true
}

func maxInt() uint64 {
	return uint64(^uint(0) >> 1)
}

func Hash(input []byte) [DigestBytes]byte {
	return sum256(input)
}

func sum256(input []byte) [DigestBytes]byte {
	state := [8]uint32{0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19}
	length := uint64(len(input)) * 8
	paddedLength := (len(input) + 9 + 63) &^ 63
	padded := make([]byte, paddedLength)
	copy(padded, input)
	padded[len(input)] = 0x80
	binary.BigEndian.PutUint64(padded[len(padded)-8:], length)
	for len(padded) != 0 {
		var words [64]uint32
		for index := 0; index < 16; index++ {
			words[index] = binary.BigEndian.Uint32(padded[index*4 : index*4+4])
		}
		for index := 16; index < 64; index++ {
			s0 := rotateRight(words[index-15], 7) ^ rotateRight(words[index-15], 18) ^ words[index-15]>>3
			s1 := rotateRight(words[index-2], 17) ^ rotateRight(words[index-2], 19) ^ words[index-2]>>10
			words[index] = words[index-16] + s0 + words[index-7] + s1
		}
		a, b, c, d := state[0], state[1], state[2], state[3]
		e, f, g, h := state[4], state[5], state[6], state[7]
		for index := 0; index < 64; index++ {
			s1 := rotateRight(e, 6) ^ rotateRight(e, 11) ^ rotateRight(e, 25)
			choice := e&f ^ (^e)&g
			temporary1 := h + s1 + choice + sha256Constants[index] + words[index]
			s0 := rotateRight(a, 2) ^ rotateRight(a, 13) ^ rotateRight(a, 22)
			majority := a&b ^ a&c ^ b&c
			temporary2 := s0 + majority
			h, g, f, e, d, c, b, a = g, f, e, d+temporary1, c, b, a, temporary1+temporary2
		}
		state[0] += a
		state[1] += b
		state[2] += c
		state[3] += d
		state[4] += e
		state[5] += f
		state[6] += g
		state[7] += h
		padded = padded[64:]
	}
	var result [DigestBytes]byte
	for index, value := range state {
		binary.BigEndian.PutUint32(result[index*4:index*4+4], value)
	}
	return result
}

func rotateRight(value uint32, bits uint) uint32 {
	return value>>bits | value<<(32-bits)
}

var sha256Constants = [64]uint32{
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
}
