// Code generated by internal/protocolgen. DO NOT EDIT.

package runtime

const (
	gomadChoiceWireVersion                   = 2
	gomadChoiceHeaderBytes                   = 64
	gomadChoiceRecordBytes                   = 96
	gomadChoiceTapeHeaderBytes               = 264
	gomadChoiceTapeRecordBytes               = 96
	gomadChoiceTapeChecksumOffset            = 232
	gomadChoiceTerminalBytes                 = 312
	gomadChoiceTerminalChecksumOffset        = 280
	gomadChoiceKindRunnable                  = 1
	gomadChoiceKindSelectPoll                = 2
	gomadChoiceKindSelectResult              = 3
	gomadChoiceFlagDecision                  = 1
	gomadChoiceFlagObservation               = 2
	gomadChoiceFlagSiteMissing               = 4
	gomadChoiceFlagRankOverride              = 8
	gomadChoiceTerminalComplete              = 1
	gomadChoiceTerminalOverflow              = 2
	gomadChoiceTerminalDiverged              = 3
	gomadChoiceModeSeed                      = 0
	gomadChoiceModeRecord                    = 1
	gomadChoiceModeReplay                    = 2
	gomadChoiceModePrefix                    = 3
	gomadChoiceDivergenceKind                = 1
	gomadChoiceDivergenceSite                = 2
	gomadChoiceDivergenceAlternatives        = 3
	gomadChoiceDivergenceSelected            = 4
	gomadChoiceDivergenceAlternativeSet      = 5
	gomadChoiceDivergenceTapeExhausted       = 6
	gomadChoiceDivergenceTapeUnconsumed      = 7
	gomadChoiceDivergenceIdentityMissing     = 8
	gomadChoiceDivergenceIdentityDuplicate   = 9
	gomadChoiceDivergenceAlternativeCapacity = 10
	gomadChoiceDivergenceObservation         = 11
)

var gomadChoiceTraceMagic = [8]byte{'G', 'O', 'M', 'A', 'D', 'C', 'H', '\x02'}
var gomadChoiceTapeMagic = [8]byte{'G', 'O', 'M', 'A', 'D', 'T', 'P', '\x02'}
var gomadChoiceTerminalMagic = [8]byte{'G', 'O', 'M', 'A', 'D', 'C', 'T', '\x02'}

func gomadChoicePut32(target []byte, value uint32) {
	target[0] = byte(value >> 24)
	target[1] = byte(value >> 16)
	target[2] = byte(value >> 8)
	target[3] = byte(value)
}

func gomadChoicePut64(target []byte, value uint64) {
	gomadChoicePut32(target[:4], uint32(value>>32))
	gomadChoicePut32(target[4:8], uint32(value))
}

func gomadChoiceRead32(source []byte) uint32 {
	return uint32(source[0])<<24 | uint32(source[1])<<16 | uint32(source[2])<<8 | uint32(source[3])
}

func gomadChoiceRead64(source []byte) uint64 {
	return uint64(gomadChoiceRead32(source[:4]))<<32 | uint64(gomadChoiceRead32(source[4:8]))
}

func gomadChoiceHash(input []byte) [32]byte {
	var hasher gomadChoiceHasher
	hasher.init()
	hasher.write(input)
	return hasher.sum()
}

type gomadChoiceHasher struct {
	state [8]uint32
	block [64]byte
	used  uint32
	bytes uint64
}

func (hasher *gomadChoiceHasher) init() {
	hasher.state = [8]uint32{0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19}
}

func (hasher *gomadChoiceHasher) write(input []byte) {
	hasher.bytes += uint64(len(input))
	for len(input) != 0 {
		count := min(len(input), len(hasher.block)-int(hasher.used))
		copy(hasher.block[hasher.used:], input[:count])
		hasher.used += uint32(count)
		input = input[count:]
		if hasher.used == uint32(len(hasher.block)) {
			hasher.compress()
			hasher.used = 0
		}
	}
}

func (hasher *gomadChoiceHasher) sum() [32]byte {
	length := hasher.bytes * 8
	hasher.block[hasher.used] = 0x80
	hasher.used++
	if hasher.used > 56 {
		for index := hasher.used; index < uint32(len(hasher.block)); index++ {
			hasher.block[index] = 0
		}
		hasher.compress()
		hasher.used = 0
	}
	for index := hasher.used; index < 56; index++ {
		hasher.block[index] = 0
	}
	gomadChoicePut64(hasher.block[56:64], length)
	hasher.compress()
	var result [32]byte
	for index, value := range hasher.state {
		gomadChoicePut32(result[index*4:index*4+4], value)
	}
	return result
}

func (hasher *gomadChoiceHasher) compress() {
	var words [64]uint32
	for index := 0; index < 16; index++ {
		words[index] = gomadChoiceRead32(hasher.block[index*4 : index*4+4])
	}
	for index := 16; index < 64; index++ {
		s0 := gomadChoiceRotateRight(words[index-15], 7) ^ gomadChoiceRotateRight(words[index-15], 18) ^ words[index-15]>>3
		s1 := gomadChoiceRotateRight(words[index-2], 17) ^ gomadChoiceRotateRight(words[index-2], 19) ^ words[index-2]>>10
		words[index] = words[index-16] + s0 + words[index-7] + s1
	}
	a, b, c, d := hasher.state[0], hasher.state[1], hasher.state[2], hasher.state[3]
	e, f, g, h := hasher.state[4], hasher.state[5], hasher.state[6], hasher.state[7]
	for index := 0; index < 64; index++ {
		s1 := gomadChoiceRotateRight(e, 6) ^ gomadChoiceRotateRight(e, 11) ^ gomadChoiceRotateRight(e, 25)
		choice := e&f ^ (^e)&g
		temporary1 := h + s1 + choice + gomadChoiceSHA256Constants[index] + words[index]
		s0 := gomadChoiceRotateRight(a, 2) ^ gomadChoiceRotateRight(a, 13) ^ gomadChoiceRotateRight(a, 22)
		majority := a&b ^ a&c ^ b&c
		temporary2 := s0 + majority
		h, g, f, e, d, c, b, a = g, f, e, d+temporary1, c, b, a, temporary1+temporary2
	}
	hasher.state[0] += a
	hasher.state[1] += b
	hasher.state[2] += c
	hasher.state[3] += d
	hasher.state[4] += e
	hasher.state[5] += f
	hasher.state[6] += g
	hasher.state[7] += h
}

func gomadChoiceRotateRight(value uint32, bits uint) uint32 { return value>>bits | value<<(32-bits) }

var gomadChoiceSHA256Constants = [64]uint32{
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
}
