// Code generated by umpire3-export; DO NOT EDIT.

package scenario

import protocolcatalog "go.temporal.io/server/tests/umpire3/protocol/catalog"

// NexusCancellationScenario selects the nexus-cancellation model family.
func NexusCancellationScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDNexusCancellation, resources, root)
}

// WorkflowUpdateLifecycleScenario selects the workflow-update-lifecycle model family.
func WorkflowUpdateLifecycleScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDWorkflowUpdateLifecycle, resources, root)
}

// FoundationBacklogAckScenario selects the foundation-backlog-ack model family.
func FoundationBacklogAckScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFoundationBacklogAck, resources, root)
}

// FeatureNexusScenario selects the feature-nexus model family.
func FeatureNexusScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFeatureNexus, resources, root)
}

// FeatureNexusProgressScenario selects the feature-nexus-progress model family.
func FeatureNexusProgressScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFeatureNexusProgress, resources, root)
}

// FeatureWorkflowSpeculativeDeliveryScenario selects the feature-workflow-speculative-delivery model family.
func FeatureWorkflowSpeculativeDeliveryScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFeatureWorkflowSpeculativeDelivery, resources, root)
}

// FoundationDeliverySafetyScenario selects the foundation-delivery-safety model family.
func FoundationDeliverySafetyScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFoundationDeliverySafety, resources, root)
}

// FoundationOwnershipFencingScenario selects the foundation-ownership-fencing model family.
func FoundationOwnershipFencingScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFoundationOwnershipFencing, resources, root)
}

// FoundationRoutingIsolationScenario selects the foundation-routing-isolation model family.
func FoundationRoutingIsolationScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDFoundationRoutingIsolation, resources, root)
}

// IntegrationActivityDeliveryScenario selects the integration-activity-delivery model family.
func IntegrationActivityDeliveryScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationActivityDelivery, resources, root)
}

// IntegrationCallbackNexusScenario selects the integration-callback-nexus model family.
func IntegrationCallbackNexusScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationCallbackNexus, resources, root)
}

// IntegrationCallbackWorkflowScenario selects the integration-callback-workflow model family.
func IntegrationCallbackWorkflowScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationCallbackWorkflow, resources, root)
}

// IntegrationNexusActivityScenario selects the integration-nexus-activity model family.
func IntegrationNexusActivityScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationNexusActivity, resources, root)
}

// IntegrationNexusTimeoutScenario selects the integration-nexus-timeout model family.
func IntegrationNexusTimeoutScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationNexusTimeout, resources, root)
}

// IntegrationWorkflowDeliveryScenario selects the integration-workflow-delivery model family.
func IntegrationWorkflowDeliveryScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDIntegrationWorkflowDelivery, resources, root)
}

// ProtocolAtomicScenario selects the protocol-atomic model family.
func ProtocolAtomicScenario(identifier string, resources []Resource, root Term) Scenario {
	return NewScenario(identifier, protocolcatalog.TargetIDProtocolAtomic, resources, root)
}

// NexusOperation identifies Nexus operation.
func NexusOperation(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindNexusOperation}
}

// NexusWorker identifies Nexus task worker.
func NexusWorker(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindNexusWorker}
}

// Workflow identifies Workflow execution.
func Workflow(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindWorkflow}
}

// WorkflowUpdate identifies Workflow Update.
func WorkflowUpdate(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindWorkflowUpdate}
}

// WorkflowTask identifies Workflow Task delivery lifecycle.
func WorkflowTask(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindWorkflowTask}
}

// Namespace identifies Temporal Namespace.
func Namespace(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindNamespace}
}

// TaskQueue identifies Temporal Task Queue.
func TaskQueue(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindTaskQueue}
}

// WorkflowRun identifies A concrete Workflow Execution run.
func WorkflowRun(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindWorkflowRun}
}

// Activity identifies Activity command identity.
func Activity(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindActivity}
}

// ActivityExecution identifies A concrete Activity attempt.
func ActivityExecution(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindActivityExecution}
}

// Callback identifies A callback registered by a Temporal operation.
func Callback(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocolcatalog.EntityKindCallback}
}

// ScheduleOperation creates sparse intent to schedule a Nexus operation.
func ScheduleOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindScheduleOperation, options...)
}

// DispatchTask creates sparse intent to dispatch a Nexus task.
func DispatchTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindDispatchTask, options...)
}

// WorkerReturnsSuccess creates sparse intent to return Nexus worker success.
func WorkerReturnsSuccess(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindWorkerReturnsSuccess, options...)
}

// RequestCancellation creates sparse intent to request Nexus cancellation.
func RequestCancellation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRequestCancellation, options...)
}

// CommitCancellation creates sparse intent to commit Nexus cancellation.
func CommitCancellation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCommitCancellation, options...)
}

// PersistSuccess creates sparse intent to persist Nexus success.
func PersistSuccess(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindPersistSuccess, options...)
}

// RetryTask creates sparse intent to retry Nexus task delivery.
func RetryTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRetryTask, options...)
}

// AcquireOwnership creates sparse intent to acquire a new ownership epoch.
func AcquireOwnership(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindAcquireOwnership, options...)
}

// CrashOwner creates sparse intent to crash the current owner.
func CrashOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCrashOwner, options...)
}

// RecoverOwner creates sparse intent to recover an owner.
func RecoverOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRecoverOwner, options...)
}

// AckTask creates sparse intent to acknowledge task delivery.
func AckTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindAckTask, options...)
}

// StartUpdate creates sparse intent to start a Workflow Update.
func StartUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindStartUpdate, options...)
}

// AcceptUpdate creates sparse intent to accept a Workflow Update.
func AcceptUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindAcceptUpdate, options...)
}

// CompleteUpdate creates sparse intent to complete a Workflow Update.
func CompleteUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCompleteUpdate, options...)
}

// RecordUpdateHistory creates sparse intent to record Update history.
func RecordUpdateHistory(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRecordUpdateHistory, options...)
}

// DispatchWorkflowTask creates sparse intent to dispatch a Workflow Task.
func DispatchWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindDispatchWorkflowTask, options...)
}

// CompleteWorkflowTask creates sparse intent to complete a Workflow Task.
func CompleteWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCompleteWorkflowTask, options...)
}

// EnqueueWorkflowTask creates sparse intent to enqueue a Workflow Task.
func EnqueueWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindEnqueueWorkflowTask, options...)
}

// DeliverWorkflowTask creates sparse intent to deliver a Workflow Task.
func DeliverWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindDeliverWorkflowTask, options...)
}

// AcknowledgeWorkflowTask creates sparse intent to acknowledge a Workflow Task.
func AcknowledgeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindAcknowledgeWorkflowTask, options...)
}

// CreateSpeculativeWorkflowTask creates sparse intent to create a speculative Workflow Task.
func CreateSpeculativeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCreateSpeculativeWorkflowTask, options...)
}

// CommitSpeculativeWorkflowTask creates sparse intent to commit a speculative Workflow Task.
func CommitSpeculativeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCommitSpeculativeWorkflowTask, options...)
}

// CloseNexusOperation creates sparse intent to close a Nexus operation.
func CloseNexusOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindCloseNexusOperation, options...)
}

// LinkNexusActivity creates sparse intent to create bidirectional Nexus and Activity links.
func LinkNexusActivity(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindLinkNexusActivity, options...)
}

// TimeoutNexusOperation creates sparse intent to record Nexus timeout semantics.
func TimeoutNexusOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindTimeoutNexusOperation, options...)
}

// RegisterCallback creates sparse intent to register a callback reference.
func RegisterCallback(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRegisterCallback, options...)
}

// RecordCallbackResponse creates sparse intent to record a callback response.
func RecordCallbackResponse(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRecordCallbackResponse, options...)
}

// DispatchAssuranceWorkflowTask creates sparse intent to dispatch a Workflow Task for progress.
func DispatchAssuranceWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindDispatchAssuranceWorkflowTask, options...)
}

// ProgressEntity creates sparse intent to advance an entity lifecycle.
func ProgressEntity(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindProgressEntity, options...)
}

// ContinueWorkflow creates sparse intent to continue a Workflow as a new run with explicit lineage.
func ContinueWorkflow(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindContinueWorkflow, options...)
}

// ResetWorkflow creates sparse intent to reset a Workflow into a new run with explicit lineage.
func ResetWorkflow(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindResetWorkflow, options...)
}

// RouteWorkflowTask creates sparse intent to route a Workflow Task through its declared Task Queue.
func RouteWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindRouteWorkflowTask, options...)
}

// FenceWorkflowOwner creates sparse intent to reject completion from a superseded Workflow Task owner.
func FenceWorkflowOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocolcatalog.ActionKindFenceWorkflowOwner, options...)
}

// NexusCompletionMode identifies a supported nexus-completion action mode.
type NexusCompletionMode string

const (
	NexusCompletionBeforeStart       NexusCompletionMode = "before-start"
	NexusCompletionFailed            NexusCompletionMode = "failed"
	NexusCompletionOpenAtCallerClose NexusCompletionMode = "open-at-caller-close"
	NexusCompletionOrdinary          NexusCompletionMode = "ordinary"
	NexusCompletionRetryStuck        NexusCompletionMode = "retry-stuck"
	NexusCompletionRetryThenSuccess  NexusCompletionMode = "retry-then-success"
)

// WithNexusCompletion supplies the typed nexus-completion action parameter.
func WithNexusCompletion(value NexusCompletionMode) ActionOption {
	return withStringArgument("nexus-completion", string(value))
}

// WithOperation supplies the typed operation action parameter.
func WithOperation(value Symbol) ActionOption {
	return withIdentityArgument("operation", value)
}

// WithReason supplies the typed reason action parameter.
func WithReason(value string) ActionOption {
	return withStringArgument("reason", value)
}

// WithUpdate supplies the typed update action parameter.
func WithUpdate(value Symbol) ActionOption {
	return withIdentityArgument("update", value)
}

// StaleWorkerCompletion creates sparse fault intent for a stale worker returns completion after ownership changes.
func StaleWorkerCompletion(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindStaleWorkerCompletion, options...)
}

// Drop creates sparse fault intent for drop a selected RPC or HTTP occurrence.
func Drop(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindDrop, options...)
}

// Delay creates sparse fault intent for delay a selected RPC or HTTP occurrence.
func Delay(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindDelay, options...)
}

// Duplicate creates sparse fault intent for duplicate a selected RPC or HTTP occurrence.
func Duplicate(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindDuplicate, options...)
}

// Reorder creates sparse fault intent for reorder selected RPC or HTTP occurrences.
func Reorder(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindReorder, options...)
}

// HoldRelease creates sparse fault intent for hold and deterministically release a selected occurrence.
func HoldRelease(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindHoldRelease, options...)
}

// Rejection creates sparse fault intent for reject a selected RPC or HTTP occurrence.
func Rejection(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindRejection, options...)
}

// ProcessCrash creates sparse fault intent for crash an isolated participant process.
func ProcessCrash(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindProcessCrash, options...)
}

// Restart creates sparse fault intent for restart an isolated participant process.
func Restart(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindRestart, options...)
}

// Partition creates sparse fault intent for partition selected isolated endpoints.
func Partition(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindPartition, options...)
}

// Failover creates sparse fault intent for trigger a selected ownership failover.
func Failover(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindFailover, options...)
}

// ClockSkew creates sparse fault intent for skew an isolated participant clock.
func ClockSkew(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindClockSkew, options...)
}

// PersistenceError creates sparse fault intent for inject an approved selected persistence error.
func PersistenceError(identifier string, options ...FaultOption) FaultIntent {
	return faultAtCaller(identifier, protocolcatalog.FaultKindPersistenceError, options...)
}

// RequireNexusCancellationWonExcludesSuccess selects the proved property Cancellation excludes a later stale success.
func RequireNexusCancellationWonExcludesSuccess() Term {
	return requireAtCaller(protocolcatalog.PropertyIDNexusCancellationWonExcludesSuccess)
}

// RequireWorkflowUpdateAcceptedCompletesThroughHistory selects the proved property Accepted Update completion is represented in history.
func RequireWorkflowUpdateAcceptedCompletesThroughHistory() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowUpdateAcceptedCompletesThroughHistory)
}

// RequireTaskDeliveryAcknowledgedRemovesBacklog selects the proved property Acknowledging a delivered Workflow Task removes it from backlog.
func RequireTaskDeliveryAcknowledgedRemovesBacklog() Term {
	return requireAtCaller(protocolcatalog.PropertyIDTaskDeliveryAcknowledgedRemovesBacklog)
}

// RequireWorkflowTaskSpeculativeCreation selects the proved property SpeculativeTaskCreation.
func RequireWorkflowTaskSpeculativeCreation() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowTaskSpeculativeCreation)
}

// RequireNexusOperationClosure selects the proved property NexusOperationClosure.
func RequireNexusOperationClosure() Term {
	return requireAtCaller(protocolcatalog.PropertyIDNexusOperationClosure)
}

// RequireNexusOperationProgress selects the proved property NexusOperationProgress.
func RequireNexusOperationProgress() Term {
	return requireAtCaller(protocolcatalog.PropertyIDNexusOperationProgress)
}

// RequireNexusActivityLinkConsistency selects the proved property NexusActivityLinkConsistency.
func RequireNexusActivityLinkConsistency() Term {
	return requireAtCaller(protocolcatalog.PropertyIDNexusActivityLinkConsistency)
}

// RequireNexusOperationTimeoutSemantics selects the proved property NexusOperationTimeoutSemantics.
func RequireNexusOperationTimeoutSemantics() Term {
	return requireAtCaller(protocolcatalog.PropertyIDNexusOperationTimeoutSemantics)
}

// RequireCallbackReferenceConsistency selects the proved property CallbackReferenceConsistency.
func RequireCallbackReferenceConsistency() Term {
	return requireAtCaller(protocolcatalog.PropertyIDCallbackReferenceConsistency)
}

// RequireCallbackResponseConsistency selects the proved property CallbackResponseConsistency.
func RequireCallbackResponseConsistency() Term {
	return requireAtCaller(protocolcatalog.PropertyIDCallbackResponseConsistency)
}

// RequireWorkflowTaskStarvation selects the proved property WorkflowTaskStarvation.
func RequireWorkflowTaskStarvation() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowTaskStarvation)
}

// RequireEntityProgress selects the proved property EntityProgress.
func RequireEntityProgress() Term {
	return requireAtCaller(protocolcatalog.PropertyIDEntityProgress)
}

// RequireWorkflowRunContinuationLineage selects the proved property ContinuationLineage.
func RequireWorkflowRunContinuationLineage() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowRunContinuationLineage)
}

// RequireWorkflowRunResetLineage selects the proved property ResetLineage.
func RequireWorkflowRunResetLineage() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowRunResetLineage)
}

// RequireWorkflowTaskRoutingIsolation selects the proved property WorkflowRoutingIsolation.
func RequireWorkflowTaskRoutingIsolation() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowTaskRoutingIsolation)
}

// RequireWorkflowTaskOwnershipFencing selects the proved property WorkflowOwnershipFencing.
func RequireWorkflowTaskOwnershipFencing() Term {
	return requireAtCaller(protocolcatalog.PropertyIDWorkflowTaskOwnershipFencing)
}

const (
	// OutcomeCancellationAccepted denotes Cancellation was accepted.
	OutcomeCancellationAccepted protocolcatalog.ObservationID = protocolcatalog.ObservationIDCancellationAccepted
	// OutcomeCancellationWon denotes Cancellation became authoritative.
	OutcomeCancellationWon protocolcatalog.ObservationID = protocolcatalog.ObservationIDCancellationWon
	// OutcomeStaleSuccessAbsent denotes No stale success became visible.
	OutcomeStaleSuccessAbsent protocolcatalog.ObservationID = protocolcatalog.ObservationIDStaleSuccessAbsent
	// OutcomeUpdateAccepted denotes Workflow Update was accepted.
	OutcomeUpdateAccepted protocolcatalog.ObservationID = protocolcatalog.ObservationIDUpdateAccepted
	// OutcomeUpdateCompleted denotes Workflow Update completed.
	OutcomeUpdateCompleted protocolcatalog.ObservationID = protocolcatalog.ObservationIDUpdateCompleted
	// OutcomeWorkflowTaskAcknowledged denotes The delivered Workflow Task was acknowledged.
	OutcomeWorkflowTaskAcknowledged protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowTaskAcknowledged
	// OutcomeSpeculativeTaskValid denotes Speculative Workflow Task creation is valid.
	OutcomeSpeculativeTaskValid protocolcatalog.ObservationID = protocolcatalog.ObservationIDSpeculativeTaskValid
	// OutcomeNexusOperationClosed denotes A closed Nexus operation is terminal.
	OutcomeNexusOperationClosed protocolcatalog.ObservationID = protocolcatalog.ObservationIDNexusOperationClosed
	// OutcomeNexusOperationProgressed denotes A retrying Nexus operation settled within its progress deadline.
	OutcomeNexusOperationProgressed protocolcatalog.ObservationID = protocolcatalog.ObservationIDNexusOperationProgressed
	// OutcomeNexusActivityLinksConsistent denotes Nexus and Activity links agree.
	OutcomeNexusActivityLinksConsistent protocolcatalog.ObservationID = protocolcatalog.ObservationIDNexusActivityLinksConsistent
	// OutcomeNexusTimeoutValid denotes Nexus timeout state is terminal and recorded.
	OutcomeNexusTimeoutValid protocolcatalog.ObservationID = protocolcatalog.ObservationIDNexusTimeoutValid
	// OutcomeCallbackReferenceValid denotes Callback reference resolves to its owner.
	OutcomeCallbackReferenceValid protocolcatalog.ObservationID = protocolcatalog.ObservationIDCallbackReferenceValid
	// OutcomeCallbackResponseConsistent denotes Callback response agrees with its reference.
	OutcomeCallbackResponseConsistent protocolcatalog.ObservationID = protocolcatalog.ObservationIDCallbackResponseConsistent
	// OutcomeWorkflowTaskNotStarved denotes An available worker permits Workflow Task progress.
	OutcomeWorkflowTaskNotStarved protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowTaskNotStarved
	// OutcomeEntityProgressed denotes The selected entity made lifecycle progress.
	OutcomeEntityProgressed protocolcatalog.ObservationID = protocolcatalog.ObservationIDEntityProgressed
	// OutcomeWorkflowContinuationLineageValid denotes The continued run names its predecessor and chain root.
	OutcomeWorkflowContinuationLineageValid protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowContinuationLineageValid
	// OutcomeWorkflowResetLineageValid denotes The reset run names the reset predecessor and chain root.
	OutcomeWorkflowResetLineageValid protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowResetLineageValid
	// OutcomeWorkflowRoutingIsolated denotes Workflow Tasks were scheduled on and completed from the declared Task Queue.
	OutcomeWorkflowRoutingIsolated protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowRoutingIsolated
	// OutcomeWorkflowOwnershipFenced denotes A superseded Workflow Task completion was rejected before the current owner completed.
	OutcomeWorkflowOwnershipFenced protocolcatalog.ObservationID = protocolcatalog.ObservationIDWorkflowOwnershipFenced
)

const (
	// RelationTaskDeliveryCurrentCompletion denotes A completion belongs to the current ownership epoch.
	RelationTaskDeliveryCurrentCompletion protocolcatalog.RelationID = protocolcatalog.RelationIDTaskDeliveryCurrentCompletion
	// RelationNamespaceContainsTaskQueue denotes A Task Queue belongs to a Namespace.
	RelationNamespaceContainsTaskQueue protocolcatalog.RelationID = protocolcatalog.RelationIDNamespaceContainsTaskQueue
	// RelationWorkflowHasRun denotes A Workflow identity has concrete runs.
	RelationWorkflowHasRun protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowHasRun
	// RelationWorkflowRunUsesTaskQueue denotes A Workflow run routes Workflow Tasks through a Task Queue.
	RelationWorkflowRunUsesTaskQueue protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowRunUsesTaskQueue
	// RelationWorkflowRunHasTask denotes A Workflow Task belongs to a Workflow run.
	RelationWorkflowRunHasTask protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowRunHasTask
	// RelationWorkflowRunHasActivity denotes An Activity belongs to a Workflow run.
	RelationWorkflowRunHasActivity protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowRunHasActivity
	// RelationActivityHasExecution denotes An Activity has concrete attempts.
	RelationActivityHasExecution protocolcatalog.RelationID = protocolcatalog.RelationIDActivityHasExecution
	// RelationNexusOperationLinksActivity denotes Nexus and Activity references agree in both directions.
	RelationNexusOperationLinksActivity protocolcatalog.RelationID = protocolcatalog.RelationIDNexusOperationLinksActivity
	// RelationNexusOperationHasCallback denotes A Nexus operation registers a callback.
	RelationNexusOperationHasCallback protocolcatalog.RelationID = protocolcatalog.RelationIDNexusOperationHasCallback
	// RelationWorkflowRunHasCallback denotes A Workflow run registers a callback.
	RelationWorkflowRunHasCallback protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowRunHasCallback
	// RelationWorkflowRunContinuesAs denotes A continued or reset run retains explicit lineage.
	RelationWorkflowRunContinuesAs protocolcatalog.RelationID = protocolcatalog.RelationIDWorkflowRunContinuesAs
)

const (
	// CapabilityNexus requests Nexus operation authority.
	CapabilityNexus protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDNexus
	// CapabilityNexusWorkerControl requests Nexus worker task authority.
	CapabilityNexusWorkerControl protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDNexusWorkerControl
	// CapabilityNexusObservation requests Nexus state observation.
	CapabilityNexusObservation protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDNexusObservation
	// CapabilityFailoverControl requests Ownership failover authority.
	CapabilityFailoverControl protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFailoverControl
	// CapabilityUpdate requests Workflow Update authority.
	CapabilityUpdate protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDUpdate
	// CapabilityWorkflowTaskControl requests Workflow Task authority.
	CapabilityWorkflowTaskControl protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDWorkflowTaskControl
	// CapabilityHistoryObservation requests Workflow history observation.
	CapabilityHistoryObservation protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDHistoryObservation
	// CapabilityFaultRpc requests Scoped RPC and HTTP fault authority.
	CapabilityFaultRpc protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFaultRpc
	// CapabilityFaultProcess requests Isolated participant process fault authority.
	CapabilityFaultProcess protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFaultProcess
	// CapabilityFaultNetwork requests Isolated network partition authority.
	CapabilityFaultNetwork protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFaultNetwork
	// CapabilityFaultClock requests Isolated clock-control authority.
	CapabilityFaultClock protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFaultClock
	// CapabilityFaultPersistence requests Selected persistence fault authority.
	CapabilityFaultPersistence protocolcatalog.CapabilityID = protocolcatalog.CapabilityIDFaultPersistence
)
