// Code generated by umpire3-export; DO NOT EDIT.

package scenario

import "go.temporal.io/server/tests/umpire3/protocol"

// NexusOperation identifies Nexus operation.
func NexusOperation(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindNexusOperation}
}

// NexusWorker identifies Nexus task worker.
func NexusWorker(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindNexusWorker}
}

// Workflow identifies Workflow execution.
func Workflow(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindWorkflow}
}

// WorkflowUpdate identifies Workflow Update.
func WorkflowUpdate(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindWorkflowUpdate}
}

// WorkflowTask identifies Workflow Task delivery lifecycle.
func WorkflowTask(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindWorkflowTask}
}

// Namespace identifies Temporal Namespace.
func Namespace(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindNamespace}
}

// TaskQueue identifies Temporal Task Queue.
func TaskQueue(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindTaskQueue}
}

// WorkflowRun identifies A concrete Workflow Execution run.
func WorkflowRun(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindWorkflowRun}
}

// Activity identifies Activity command identity.
func Activity(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindActivity}
}

// ActivityExecution identifies A concrete Activity attempt.
func ActivityExecution(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindActivityExecution}
}

// Callback identifies A callback registered by a Temporal operation.
func Callback(identifier string) Resource {
	return Resource{Identifier: identifier, Kind: protocol.EntityKindCallback}
}

// ScheduleOperation creates sparse intent to schedule a Nexus operation.
func ScheduleOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindScheduleOperation, options...)
}

// DispatchTask creates sparse intent to dispatch a Nexus task.
func DispatchTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindDispatchTask, options...)
}

// WorkerReturnsSuccess creates sparse intent to return Nexus worker success.
func WorkerReturnsSuccess(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindWorkerReturnsSuccess, options...)
}

// RequestCancellation creates sparse intent to request Nexus cancellation.
func RequestCancellation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRequestCancellation, options...)
}

// CommitCancellation creates sparse intent to commit Nexus cancellation.
func CommitCancellation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCommitCancellation, options...)
}

// PersistSuccess creates sparse intent to persist Nexus success.
func PersistSuccess(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindPersistSuccess, options...)
}

// RetryTask creates sparse intent to retry Nexus task delivery.
func RetryTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRetryTask, options...)
}

// AcquireOwnership creates sparse intent to acquire a new ownership epoch.
func AcquireOwnership(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindAcquireOwnership, options...)
}

// CrashOwner creates sparse intent to crash the current owner.
func CrashOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCrashOwner, options...)
}

// RecoverOwner creates sparse intent to recover an owner.
func RecoverOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRecoverOwner, options...)
}

// AckTask creates sparse intent to acknowledge task delivery.
func AckTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindAckTask, options...)
}

// StartUpdate creates sparse intent to start a Workflow Update.
func StartUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindStartUpdate, options...)
}

// AcceptUpdate creates sparse intent to accept a Workflow Update.
func AcceptUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindAcceptUpdate, options...)
}

// CompleteUpdate creates sparse intent to complete a Workflow Update.
func CompleteUpdate(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCompleteUpdate, options...)
}

// RecordUpdateHistory creates sparse intent to record Update history.
func RecordUpdateHistory(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRecordUpdateHistory, options...)
}

// DispatchWorkflowTask creates sparse intent to dispatch a Workflow Task.
func DispatchWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindDispatchWorkflowTask, options...)
}

// CompleteWorkflowTask creates sparse intent to complete a Workflow Task.
func CompleteWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCompleteWorkflowTask, options...)
}

// EnqueueWorkflowTask creates sparse intent to enqueue a Workflow Task.
func EnqueueWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindEnqueueWorkflowTask, options...)
}

// DeliverWorkflowTask creates sparse intent to deliver a Workflow Task.
func DeliverWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindDeliverWorkflowTask, options...)
}

// AcknowledgeWorkflowTask creates sparse intent to acknowledge a Workflow Task.
func AcknowledgeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindAcknowledgeWorkflowTask, options...)
}

// CreateSpeculativeWorkflowTask creates sparse intent to create a speculative Workflow Task.
func CreateSpeculativeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCreateSpeculativeWorkflowTask, options...)
}

// CommitSpeculativeWorkflowTask creates sparse intent to commit a speculative Workflow Task.
func CommitSpeculativeWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCommitSpeculativeWorkflowTask, options...)
}

// CloseNexusOperation creates sparse intent to close a Nexus operation.
func CloseNexusOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindCloseNexusOperation, options...)
}

// LinkNexusActivity creates sparse intent to create bidirectional Nexus and Activity links.
func LinkNexusActivity(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindLinkNexusActivity, options...)
}

// TimeoutNexusOperation creates sparse intent to record Nexus timeout semantics.
func TimeoutNexusOperation(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindTimeoutNexusOperation, options...)
}

// RegisterCallback creates sparse intent to register a callback reference.
func RegisterCallback(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRegisterCallback, options...)
}

// RecordCallbackResponse creates sparse intent to record a callback response.
func RecordCallbackResponse(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRecordCallbackResponse, options...)
}

// DispatchAssuranceWorkflowTask creates sparse intent to dispatch a Workflow Task for progress.
func DispatchAssuranceWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindDispatchAssuranceWorkflowTask, options...)
}

// ProgressEntity creates sparse intent to advance an entity lifecycle.
func ProgressEntity(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindProgressEntity, options...)
}

// ContinueWorkflow creates sparse intent to continue a Workflow as a new run with explicit lineage.
func ContinueWorkflow(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindContinueWorkflow, options...)
}

// ResetWorkflow creates sparse intent to reset a Workflow into a new run with explicit lineage.
func ResetWorkflow(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindResetWorkflow, options...)
}

// RouteWorkflowTask creates sparse intent to route a Workflow Task through its declared Task Queue.
func RouteWorkflowTask(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindRouteWorkflowTask, options...)
}

// FenceWorkflowOwner creates sparse intent to reject completion from a superseded Workflow Task owner.
func FenceWorkflowOwner(identifier string, options ...ActionOption) Term {
	return actionAtCaller(identifier, protocol.ActionKindFenceWorkflowOwner, options...)
}

// StaleWorkerCompletion creates sparse fault intent for a stale worker returns completion after ownership changes.
func StaleWorkerCompletion(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindStaleWorkerCompletion, options...)
}

// Drop creates sparse fault intent for drop a selected RPC or HTTP occurrence.
func Drop(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindDrop, options...)
}

// Delay creates sparse fault intent for delay a selected RPC or HTTP occurrence.
func Delay(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindDelay, options...)
}

// Duplicate creates sparse fault intent for duplicate a selected RPC or HTTP occurrence.
func Duplicate(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindDuplicate, options...)
}

// Reorder creates sparse fault intent for reorder selected RPC or HTTP occurrences.
func Reorder(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindReorder, options...)
}

// HoldRelease creates sparse fault intent for hold and deterministically release a selected occurrence.
func HoldRelease(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindHoldRelease, options...)
}

// Rejection creates sparse fault intent for reject a selected RPC or HTTP occurrence.
func Rejection(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindRejection, options...)
}

// ProcessCrash creates sparse fault intent for crash an isolated participant process.
func ProcessCrash(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindProcessCrash, options...)
}

// Restart creates sparse fault intent for restart an isolated participant process.
func Restart(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindRestart, options...)
}

// Partition creates sparse fault intent for partition selected isolated endpoints.
func Partition(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindPartition, options...)
}

// Failover creates sparse fault intent for trigger a selected ownership failover.
func Failover(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindFailover, options...)
}

// ClockSkew creates sparse fault intent for skew an isolated participant clock.
func ClockSkew(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindClockSkew, options...)
}

// PersistenceError creates sparse fault intent for inject an approved selected persistence error.
func PersistenceError(identifier string, options ...ActionOption) FaultIntent {
	return faultAtCaller(identifier, protocol.FaultKindPersistenceError, options...)
}

// RequireNexusCancellationWonExcludesSuccess selects the proved property Cancellation excludes a later stale success.
func RequireNexusCancellationWonExcludesSuccess() Term {
	return requireAtCaller(protocol.PropertyIDNexusCancellationWonExcludesSuccess)
}

// RequireWorkflowUpdateAcceptedCompletesThroughHistory selects the proved property Accepted Update completion is represented in history.
func RequireWorkflowUpdateAcceptedCompletesThroughHistory() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowUpdateAcceptedCompletesThroughHistory)
}

// RequireTaskDeliveryAcknowledgedRemovesBacklog selects the proved property Acknowledging a delivered Workflow Task removes it from backlog.
func RequireTaskDeliveryAcknowledgedRemovesBacklog() Term {
	return requireAtCaller(protocol.PropertyIDTaskDeliveryAcknowledgedRemovesBacklog)
}

// RequireWorkflowTaskSpeculativeCreation selects the proved property SpeculativeTaskCreation.
func RequireWorkflowTaskSpeculativeCreation() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowTaskSpeculativeCreation)
}

// RequireNexusOperationClosure selects the proved property NexusOperationClosure.
func RequireNexusOperationClosure() Term {
	return requireAtCaller(protocol.PropertyIDNexusOperationClosure)
}

// RequireNexusActivityLinkConsistency selects the proved property NexusActivityLinkConsistency.
func RequireNexusActivityLinkConsistency() Term {
	return requireAtCaller(protocol.PropertyIDNexusActivityLinkConsistency)
}

// RequireNexusOperationTimeoutSemantics selects the proved property NexusOperationTimeoutSemantics.
func RequireNexusOperationTimeoutSemantics() Term {
	return requireAtCaller(protocol.PropertyIDNexusOperationTimeoutSemantics)
}

// RequireCallbackReferenceConsistency selects the proved property CallbackReferenceConsistency.
func RequireCallbackReferenceConsistency() Term {
	return requireAtCaller(protocol.PropertyIDCallbackReferenceConsistency)
}

// RequireCallbackResponseConsistency selects the proved property CallbackResponseConsistency.
func RequireCallbackResponseConsistency() Term {
	return requireAtCaller(protocol.PropertyIDCallbackResponseConsistency)
}

// RequireWorkflowTaskStarvation selects the proved property WorkflowTaskStarvation.
func RequireWorkflowTaskStarvation() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowTaskStarvation)
}

// RequireEntityProgress selects the proved property EntityProgress.
func RequireEntityProgress() Term {
	return requireAtCaller(protocol.PropertyIDEntityProgress)
}

// RequireWorkflowRunContinuationLineage selects the proved property ContinuationLineage.
func RequireWorkflowRunContinuationLineage() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowRunContinuationLineage)
}

// RequireWorkflowRunResetLineage selects the proved property ResetLineage.
func RequireWorkflowRunResetLineage() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowRunResetLineage)
}

// RequireWorkflowTaskRoutingIsolation selects the proved property WorkflowRoutingIsolation.
func RequireWorkflowTaskRoutingIsolation() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowTaskRoutingIsolation)
}

// RequireWorkflowTaskOwnershipFencing selects the proved property WorkflowOwnershipFencing.
func RequireWorkflowTaskOwnershipFencing() Term {
	return requireAtCaller(protocol.PropertyIDWorkflowTaskOwnershipFencing)
}

const (
	// OutcomeCancellationAccepted denotes Cancellation was accepted.
	OutcomeCancellationAccepted protocol.ObservationID = protocol.ObservationIDCancellationAccepted
	// OutcomeCancellationWon denotes Cancellation became authoritative.
	OutcomeCancellationWon protocol.ObservationID = protocol.ObservationIDCancellationWon
	// OutcomeStaleSuccessAbsent denotes No stale success became visible.
	OutcomeStaleSuccessAbsent protocol.ObservationID = protocol.ObservationIDStaleSuccessAbsent
	// OutcomeUpdateAccepted denotes Workflow Update was accepted.
	OutcomeUpdateAccepted protocol.ObservationID = protocol.ObservationIDUpdateAccepted
	// OutcomeUpdateCompleted denotes Workflow Update completed.
	OutcomeUpdateCompleted protocol.ObservationID = protocol.ObservationIDUpdateCompleted
	// OutcomeWorkflowTaskAcknowledged denotes The delivered Workflow Task was acknowledged.
	OutcomeWorkflowTaskAcknowledged protocol.ObservationID = protocol.ObservationIDWorkflowTaskAcknowledged
	// OutcomeSpeculativeTaskValid denotes Speculative Workflow Task creation is valid.
	OutcomeSpeculativeTaskValid protocol.ObservationID = protocol.ObservationIDSpeculativeTaskValid
	// OutcomeNexusOperationClosed denotes A closed Nexus operation is terminal.
	OutcomeNexusOperationClosed protocol.ObservationID = protocol.ObservationIDNexusOperationClosed
	// OutcomeNexusActivityLinksConsistent denotes Nexus and Activity links agree.
	OutcomeNexusActivityLinksConsistent protocol.ObservationID = protocol.ObservationIDNexusActivityLinksConsistent
	// OutcomeNexusTimeoutValid denotes Nexus timeout state is terminal and recorded.
	OutcomeNexusTimeoutValid protocol.ObservationID = protocol.ObservationIDNexusTimeoutValid
	// OutcomeCallbackReferenceValid denotes Callback reference resolves to its owner.
	OutcomeCallbackReferenceValid protocol.ObservationID = protocol.ObservationIDCallbackReferenceValid
	// OutcomeCallbackResponseConsistent denotes Callback response agrees with its reference.
	OutcomeCallbackResponseConsistent protocol.ObservationID = protocol.ObservationIDCallbackResponseConsistent
	// OutcomeWorkflowTaskNotStarved denotes An available worker permits Workflow Task progress.
	OutcomeWorkflowTaskNotStarved protocol.ObservationID = protocol.ObservationIDWorkflowTaskNotStarved
	// OutcomeEntityProgressed denotes The selected entity made lifecycle progress.
	OutcomeEntityProgressed protocol.ObservationID = protocol.ObservationIDEntityProgressed
	// OutcomeWorkflowContinuationLineageValid denotes The continued run names its predecessor and chain root.
	OutcomeWorkflowContinuationLineageValid protocol.ObservationID = protocol.ObservationIDWorkflowContinuationLineageValid
	// OutcomeWorkflowResetLineageValid denotes The reset run names the reset predecessor and chain root.
	OutcomeWorkflowResetLineageValid protocol.ObservationID = protocol.ObservationIDWorkflowResetLineageValid
	// OutcomeWorkflowRoutingIsolated denotes Workflow Tasks were scheduled on and completed from the declared Task Queue.
	OutcomeWorkflowRoutingIsolated protocol.ObservationID = protocol.ObservationIDWorkflowRoutingIsolated
	// OutcomeWorkflowOwnershipFenced denotes A superseded Workflow Task completion was rejected before the current owner completed.
	OutcomeWorkflowOwnershipFenced protocol.ObservationID = protocol.ObservationIDWorkflowOwnershipFenced
)

const (
	// RelationTaskDeliveryCurrentCompletion denotes A completion belongs to the current ownership epoch.
	RelationTaskDeliveryCurrentCompletion protocol.RelationID = protocol.RelationIDTaskDeliveryCurrentCompletion
	// RelationNamespaceContainsTaskQueue denotes A Task Queue belongs to a Namespace.
	RelationNamespaceContainsTaskQueue protocol.RelationID = protocol.RelationIDNamespaceContainsTaskQueue
	// RelationWorkflowHasRun denotes A Workflow identity has concrete runs.
	RelationWorkflowHasRun protocol.RelationID = protocol.RelationIDWorkflowHasRun
	// RelationWorkflowRunUsesTaskQueue denotes A Workflow run routes Workflow Tasks through a Task Queue.
	RelationWorkflowRunUsesTaskQueue protocol.RelationID = protocol.RelationIDWorkflowRunUsesTaskQueue
	// RelationWorkflowRunHasTask denotes A Workflow Task belongs to a Workflow run.
	RelationWorkflowRunHasTask protocol.RelationID = protocol.RelationIDWorkflowRunHasTask
	// RelationWorkflowRunHasActivity denotes An Activity belongs to a Workflow run.
	RelationWorkflowRunHasActivity protocol.RelationID = protocol.RelationIDWorkflowRunHasActivity
	// RelationActivityHasExecution denotes An Activity has concrete attempts.
	RelationActivityHasExecution protocol.RelationID = protocol.RelationIDActivityHasExecution
	// RelationNexusOperationLinksActivity denotes Nexus and Activity references agree in both directions.
	RelationNexusOperationLinksActivity protocol.RelationID = protocol.RelationIDNexusOperationLinksActivity
	// RelationNexusOperationHasCallback denotes A Nexus operation registers a callback.
	RelationNexusOperationHasCallback protocol.RelationID = protocol.RelationIDNexusOperationHasCallback
	// RelationWorkflowRunHasCallback denotes A Workflow run registers a callback.
	RelationWorkflowRunHasCallback protocol.RelationID = protocol.RelationIDWorkflowRunHasCallback
	// RelationWorkflowRunContinuesAs denotes A continued or reset run retains explicit lineage.
	RelationWorkflowRunContinuesAs protocol.RelationID = protocol.RelationIDWorkflowRunContinuesAs
)

const (
	// CapabilityNexus requests Nexus operation authority.
	CapabilityNexus protocol.CapabilityID = protocol.CapabilityIDNexus
	// CapabilityNexusWorkerControl requests Nexus worker task authority.
	CapabilityNexusWorkerControl protocol.CapabilityID = protocol.CapabilityIDNexusWorkerControl
	// CapabilityNexusObservation requests Nexus state observation.
	CapabilityNexusObservation protocol.CapabilityID = protocol.CapabilityIDNexusObservation
	// CapabilityFailoverControl requests Ownership failover authority.
	CapabilityFailoverControl protocol.CapabilityID = protocol.CapabilityIDFailoverControl
	// CapabilityUpdate requests Workflow Update authority.
	CapabilityUpdate protocol.CapabilityID = protocol.CapabilityIDUpdate
	// CapabilityWorkflowTaskControl requests Workflow Task authority.
	CapabilityWorkflowTaskControl protocol.CapabilityID = protocol.CapabilityIDWorkflowTaskControl
	// CapabilityHistoryObservation requests Workflow history observation.
	CapabilityHistoryObservation protocol.CapabilityID = protocol.CapabilityIDHistoryObservation
	// CapabilityFaultRpc requests Scoped RPC and HTTP fault authority.
	CapabilityFaultRpc protocol.CapabilityID = protocol.CapabilityIDFaultRpc
	// CapabilityFaultProcess requests Isolated participant process fault authority.
	CapabilityFaultProcess protocol.CapabilityID = protocol.CapabilityIDFaultProcess
	// CapabilityFaultNetwork requests Isolated network partition authority.
	CapabilityFaultNetwork protocol.CapabilityID = protocol.CapabilityIDFaultNetwork
	// CapabilityFaultClock requests Isolated clock-control authority.
	CapabilityFaultClock protocol.CapabilityID = protocol.CapabilityIDFaultClock
	// CapabilityFaultPersistence requests Selected persistence fault authority.
	CapabilityFaultPersistence protocol.CapabilityID = protocol.CapabilityIDFaultPersistence
)
