import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const out=path.dirname(new URL(import.meta.url).pathname),hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const receipts=fs.readdirSync(out).filter(file=>file.endsWith('-receipt.json')).sort().map(file=>{const bytes=fs.readFileSync(path.join(out,file)),record=JSON.parse(bytes);return {name:record.name,path:file,sha256:hash(bytes),command:record.command,exit_code:record.exit_code,signal:record.signal,duration:record.elapsed_seconds,terminal_handle:record.terminal_handle,counts:record.counts,source:record.source,tools:record.tools,controls:record.controls,stdout:record.stdout,stderr:record.stderr,environment_sha256:record.environment_sha256,source_unchanged:record.source_unchanged,tools_unchanged:record.tools_unchanged,controls_unchanged:record.controls_unchanged};});
for(const record of receipts){for(const stream of [record.stdout,record.stderr])if(hash(fs.readFileSync(path.join(out,stream.path)))!==stream.sha256)throw Error('stream hash mismatch '+record.name);for(const input of [record.source,record.tools,record.controls])if(hash(fs.readFileSync(path.join(out,input.manifest)))!==input.sha256)throw Error('manifest hash mismatch '+record.name);}
const final=receipts.filter(record=>record.name.startsWith('frozen-')),files=['handover.md','frozen-control-comparison.json','frozen-adapter-comparison.json','adapter-baseline-inputs.json','adapter-baseline-verification.json','adapter-executable-inputs.json','final-control-inputs.json','default-preservation-final.json','standard-stderr-inputs.json','standard-stderr-comparison.json','literal-selection-comparison.json','command-inventory.md','tmp-relocation.json'];
const evidence={base_commit:'29c80199cdf1a7444f3a3aa99388e2f408e3cf73',commits:[],tests:final.map(record=>record.command),prs:[],task:'fn-109-gomad-deepen-modules-and-tool-interfaces.9',status:'in_progress',review:'host-deferred; no worker review dispatch/verdict or acceptance',source_manifest:'source-0cc145589ba5b275ce6b66312e8d301ba02539353cd4d3d29312cdbef7b6f6b9.json',source_sha256:'0cc145589ba5b275ce6b66312e8d301ba02539353cd4d3d29312cdbef7b6f6b9',selected_input_count:1042,tier:'Tier: session (jev-unavailable(no_key))',execution:'All worker command/session handles terminal; no outstanding Go/build/test/lint/generation lane owner process.',baseline:'No full green task9 baseline/handoff asserted. Coherent d635 original controls, pre-edit source baseline and retained native/tooling/assertion REDs remain separately identified.',final_receipts:final,all_receipts:receipts,artifacts:files.map(file=>({path:file,sha256:hash(fs.readFileSync(path.join(out,file)))})),unproved:['Final defaults exit1:90pass/1empty-PID assertion failure; matching narrow HEAD control exit0 does not resolve final full gate','Upgrade publication full selection exit1:29pass/2fail repeated; HEADfull31pass/currentnarrow4pass do not reconcile cause','Public Review two originally bounded overflow error text/type differences: unresolved R18, no waiver','Scopedlint two unchanged ST1005 sites context.go40,59; owner policy answers absent','Integratedlint24other-owner findings; integratederrortypeunreached; no suppression/full-clean claim','Task40 Todo genuine deferred-close/simultaneous cleanup-fault/dependency acceptance unresolved, no approved amendment','Formal acceptance/review/native assertions, Darwinfn149/LinuxCI fn128/patched compiler/pin/approval/publication qualification unverified'],inconclusive:['frozen-task8-composition zero selection retained; corrected exact source test7passes','frozen-adapter-compile-original failed missing API at d635; correct empirical0c2 completegraph used separately','Historical/tmp adapter reproduction ENOSPC before execution after admitted recoverable relocation; fresh matchedworkspace control is not historical reproduction','Pre-execution telemetry mmap faults and producer-status-masked old format receipt not green','Original v1 listing short-write producer does not establish overflow; checkedv2 actual counts/hashes separately retained']};
console.log(JSON.stringify(evidence,null,2));
