import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {read,write as writeOriginal,git,sha,sources,root} from './capture.mjs';
const final=process.argv.includes('--final');
const output=process.argv.find(a=>a.startsWith('--output='))?.slice(9)??'final-source-proof.json';
assert(/^[a-z0-9-]+\.json$/.test(output));
const write=(n,v)=>writeOriginal(final&&n==='source-proof.json'?output:n,final?{...v,product_edits:git(['diff','--name-only','HEAD','--','tools/gomad3']).toString().trim().split('\n').filter(Boolean)}:v);
export const dir='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-9';
export const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
export function functions(s){return [...s.matchAll(/^func (?:\([^)]*\) )?(\w+)\([^\n]*\n/gm)].map(m=>{const oneLine=m[0].trimEnd().endsWith('}'),end=oneLine?m.index+m[0].length-1:s.indexOf('\n}',m.index)+3;assert(end>m.index,m[1]);return {name:m[1],start:s.slice(0,m.index).split('\n').length,body:s.slice(m.index,end)+'\n'};});}
export const named=(s,n)=>functions(s).find(f=>f.name===n);
const commits=['97f221c7ea','ebc5ea1e09','7ba322acc8'].map(v=>{const full=git(['rev-parse',v]).toString().trim();return {commit:full,parent:git(['rev-parse',full+'^']).toString().trim(),metadata:git(['show','-s','--format=%H%n%P%n%B',full]).toString()};});
const mapping=read(dir+'/mapping.tsv').toString().trim().split('\n').filter(l=>!l.startsWith('#')).slice(1).map(l=>{const [packageName,old,old_status,replacement,new_status,note]=l.split('\t');return {package:packageName,old,old_status,replacement,new_status,note};});
const changed=commits.flatMap(c=>git(['diff','--name-only',c.parent,c.commit,'--','tools/gomad3']).toString().trim().split('\n').filter(Boolean));
const sourcePaths=[...new Set(changed)].sort(),current=sources();
const histories=sourcePaths.map(path=>({path,current_sha256:current[path]??null,original_versions:commits.map(c=>({commit:c.commit,parent:c.parent,parent_sha256:git(['ls-tree',c.parent,'--',path]).length?sha(git(['show',c.parent+':'+path])):null,post_sha256:git(['ls-tree',c.commit,'--',path]).length?sha(git(['show',c.commit+':'+path])):null})),later_owners:git(['log','--full-history','--format=%H','7ba322acc8..HEAD','--',path]).toString().trim().split('\n').filter(Boolean).map(commit=>{const parents=git(['show','-s','--format=%P',commit]).toString().trim().split(' ');return {commit,metadata:git(['show','-s','--format=%H%n%P%n%B',commit]).toString(),parents:parents.map(parent=>({parent,patch_sha256:sha(git(['diff','--no-ext-diff','--no-renames',parent,commit,'--',path]))}))};})}));
const testPaths=Object.keys(current).filter(p=>p.endsWith('_test.go')),currentFunctions=testPaths.flatMap(path=>functions(read(path).toString()).map(f=>({path,...f,sha256:sha(f.body)})));
const originalFunctions=[];for(const c of commits.slice(0,2))for(const path of git(['diff','--name-only',c.parent,c.commit,'--','tools/gomad3']).toString().trim().split('\n').filter(p=>p.endsWith('_test.go'))){if(!git(['ls-tree',c.parent,'--',path]).length)continue;for(const f of functions(git(['show',c.parent+':'+path]).toString()))if(f.name.startsWith('Test'))originalFunctions.push({path,commit:c.parent,...f,sha256:sha(f.body)});}
const rows=mapping.map(row=>{const origin=originalFunctions.find(f=>f.name===row.old.split('/')[0]),replacement=row.replacement==='-'?null:currentFunctions.find(f=>f.name===row.replacement.split('/')[0]);assert(origin,'original function '+row.old);assert(row.replacement==='-'||replacement,'current replacement '+row.replacement);return {...row,original:{path:origin.path,commit:origin.commit,function:origin.name,body_sha256:origin.sha256,start:origin.start},current:replacement?{path:replacement.path,function:replacement.name,body_sha256:replacement.sha256,start:replacement.start}:null,scope:row.replacement==='-'?'Original individually authorized housekeeping removal':'Concrete current row requires complete shared body conditions; historical recorded status is not current execution'};});
if(final)for(const row of rows)if(/^Test(?:Sprig|Validator|Pebble|CactusStatsD|Memberlist|Sentry|HashicorpMetrics)RejectsChangedIdentity$/.test(row.old)){row.original_replacement=row.replacement;row.replacement+='/empty';row.current.row='empty';row.scope='Original empty-cache pre-read identity assertion restored; populated-cache row separately retained, not a substitute.';}
if(final)for(const row of rows)if(row.old==='TestAssessWorldValidatesTheRecordAgainstItsSeed/seed_mismatch'){const f=currentFunctions.find(f=>f.name==='TestAssessWorldValidatesTheRecordAgainstItsSeed');assert(f);row.original_replacement=row.replacement;row.replacement=row.old;row.current={path:f.path,function:f.name,body_sha256:f.sha256,start:f.start,row:'seed_mismatch'};row.scope='Exact original recordseed7/expectedseed8 row restored; public recordseed8/expectedseed7 row retained separately, not same-input replacement.';}
const replacementBodies=[...new Set(rows.flatMap(r=>r.current?[r.current.function]:[]))].map(n=>currentFunctions.find(f=>f.name===n));
const originalsAtReviewed={};for(const path of sourcePaths)if(path.endsWith('_test.go')){const owner=path.includes('/deterministicio/')||path.endsWith('/architecture_test.go')?commits[0].commit:commits[2].commit;if(git(['ls-tree',owner,'--',path]).length)originalsAtReviewed[path]={owner,functions:functions(git(['show',owner+':'+path]).toString())};}
const unaffected=originalFunctions.filter(f=>!mapping.some(r=>r.old.split('/')[0]===f.name)).map(f=>{const reviewed=originalsAtReviewed[f.path]?.functions.find(g=>g.name===f.name),now=currentFunctions.find(g=>g.name===f.name&&g.path===f.path);return {path:f.path,name:f.name,original_commit:f.commit,original_sha256:f.sha256,reviewed_commit:originalsAtReviewed[f.path]?.owner??null,reviewed_sha256:reviewed?sha(reviewed.body):null,current:now?{path:now.path,sha256:now.sha256,start:now.start}:null,unchanged_during_task:reviewed?.body===f.body,unchanged_current:now?.body===f.body,original_assertion_lines:f.body.split('\n').filter(l=>/t\.(?:Fatal|Error)|^\s*if /.test(l))};});
const fixture='tools/gomad3/runner/testdata/campaign_options_characterization.json',goldenBefore=JSON.parse(git(['show',commits[1].parent+':'+fixture])),goldenNow=JSON.parse(read(fixture));assert.equal(goldenBefore.length,125);assert.equal(goldenNow.length,126);for(const row of goldenBefore)assert.deepEqual(goldenNow.find(r=>r.name===row.name),row);
const proof6='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-6/source-acceptance-20261008/final-source-proof.json',six=JSON.parse(read(proof6));assert.equal(six.test_function_mapping.length,403);let bound6=0;for(const f of six.test_function_mapping)if(f.current){const path=f.current.path??f.path,lines=read(path).toString().split('\n');assert.equal(lines.slice(f.current.start-1,f.current.end).join('\n'),f.current.body);bound6++;}
const proof3='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-3/source-acceptance-20261008/accepted-coverage-proof.json',three=JSON.parse(read(proof3));assert.equal(three.current_functions.length,4);for(const f of three.current_functions){const lines=read(f.path).toString().split('\n');assert.equal(lines.slice(f.start-1,f.end).join('\n'),f.body);}
const binding='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-5/source-acceptance-20261008/source-binding.json',b=JSON.parse(read(binding));for(const e of b.exact_bindings)assert.equal(sha(read(e.path)),e.sha256,e.path+' exact runtime binding');assert.equal(sha(read(b.archive.path)),b.archive.sha256);
const raw=JSON.parse(read(b.retained_raw_manifest.path));let decodedBytes=0;for(const e of raw){const p=b.retained_raw_manifest.path.replace('/raw-manifest.json','/raw/')+(e.retained_name??e.name),bytes=read(p);if(e.retained_name)assert.equal(sha(bytes),e.retained_sha256);const decoded=e.encoding==='utf8-json-string'?Buffer.from(JSON.parse(bytes).value):bytes;assert.equal(sha(decoded),e.sha256);assert.equal(decoded.length,e.bytes);decodedBytes+=decoded.length;}
const baseline='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-21/baseline-reconstruction',first=JSON.parse(read(baseline+'/evidence.json')),firstRows=read(baseline+'/source.sha256').toString().trim().split('\n');for(const line of firstRows)assert.equal(sha(read(first.scratch_path+'/'+line.slice(66))),line.slice(0,64));
const closure=b.input_closure.map(e=>({path:e.path,verified_sha256:e.current_sha256,current_sha256:sha(read(e.path)),unchanged:e.current_sha256===sha(read(e.path)),old_pass_reused:e.current_sha256===sha(read(e.path))}));
const inventoryReceipt=JSON.parse(read(b.positive_inventory.receipt));assert.equal(sha(read(b.positive_inventory.receipt)),b.positive_inventory.receipt_sha256);assert.equal(inventoryReceipt.exit,0);assert.equal(sha(read(b.positive_inventory.receipt.replace(/\.json$/,'.stdout'))),b.positive_inventory.log_sha256);
const comments=sourcePaths.filter(p=>p.endsWith('_test.go')).map(path=>{const reviewed=originalsAtReviewed[path];if(!reviewed||!existsSync(resolve(root,path)))return {path,current_absent:true};const old=git(['show',reviewed.owner+':'+path]).toString(),now=read(path).toString(),extract=s=>s.split('\n').filter(l=>/^\s*\/\//.test(l));return {path,reviewed_owner:reviewed.owner,reviewed_comments:extract(old),missing_current_comment_lines:extract(old).filter(l=>!extract(now).includes(l))};});
const fixturePaths=git(['ls-tree','-r','--name-only',commits[0].parent,'--','tools/gomad3/deterministicio/testdata','tools/gomad3/runner/testdata']).toString().trim().split('\n').filter(Boolean),fixtureBindings=fixturePaths.map(path=>({path,original_commit:commits[0].parent,original_sha256:sha(git(['show',commits[0].parent+':'+path])),current_sha256:current[path]??null}));
write('source-proof.json',{base_commit:'a7d99f4e64990839f81df4acd9bc150b842f8ea6',head:git(['rev-parse','HEAD']).toString().trim(),original_commits:commits,current_sources:current,original_mapping:ref(dir+'/mapping.tsv'),recorded_before:ref(dir+'/behaviors-before.tsv'),recorded_after:ref(dir+'/behaviors-after.tsv'),mapping_rows:rows,current_shared_assertion_bodies:replacementBodies,unaffected_function_bindings:unaffected,comments,histories,fixtureBindings,golden:{current:ref(fixture),original_owner:commits[1].parent,original_rows:125,current_rows:126,all_original_rows_exact:true,only_added_row:goldenNow.filter(r=>!goldenBefore.some(o=>o.name===r.name)).map(r=>r.name)},accepted_owner_proofs:{task6:{proof:ref(proof6),named_mapping_count:403,current_exact_body_bindings:bound6,historical_board_not_reverified:true},task3:{proof:ref(proof3),current_functions:three.current_functions.map(f=>({path:f.path,start:f.start,end:f.end,sha256:sha(f.body)})),all_four_exact:true}},static:{binding:ref(binding),runtime_input_count:b.exact_bindings.length,runtime_inputs:b.exact_bindings,archive:b.archive,retained_raw_manifest:ref(b.retained_raw_manifest.path),raw_files:raw.length,decoded_bytes:decodedBytes,first_baseline:{revision:first.base_revision,kind:first.baseline_kind,manifest:ref(baseline+'/source.sha256'),inputs:firstRows.length,all_original_bytes_rechecked:true},prior_static_receipt:b.positive_inventory,current_closure:closure,changed_unreused:closure.filter(e=>!e.unchanged),native:false},historical_size:[ref(dir+'/size-test-go.txt'),ref(dir+'/size-test-go-cli-runner.txt')],counting_script:ref('.flow/artifacts/fn-108-gomad-reduce-code-size-without-removing/size-count.sh'),user_files:['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(ref),product_edits:[],review_verdict:null,native:false,full_host_pass:false});
console.log(JSON.stringify({mapping_rows:rows.length,current_shared_bodies:replacementBodies.length,original_unaffected_functions:unaffected.length,static_runtime_inputs:b.exact_bindings.length,changed_static_closure:closure.filter(e=>!e.unchanged).map(e=>e.path)}));
