-- Code generated by umpire-gen-lean-api. DO NOT EDIT.
-- This is a structural descriptor projection, not behavioral semantics.

namespace Fixture.API.Proto

structure Bytes where
  digest : String
  size : Nat
  deriving DecidableEq, Repr

structure MessageRef where
  descriptor : String
  remainingDepth : Nat
  deriving DecidableEq, Repr

structure Method (Request Response : Type) where
  fullName : String
  clientStreaming : Bool
  serverStreaming : Bool
  deprecated : Bool
  deriving DecidableEq, Repr

end Fixture.API.Proto
