-- Code generated by umpire-gen-lean-api. DO NOT EDIT.
-- This is a structural descriptor projection, not behavioral semantics.

/-!
Common structural types used by the generated Temporal API projection.

`Bytes` and `MessageRef` retain opaque descriptor data, while `Method` records the request,
response, streaming, and deprecation shape of one gRPC method.
-/

set_option linter.missingDocs false

namespace Fixture.API.Proto

structure Bytes where
  digest : String
  size : Nat
  deriving DecidableEq, Repr

structure MessageRef where
  descriptor : String
  remainingDepth : Nat
  deriving DecidableEq, Repr

structure Method (Request Response : Type) where
  fullName : String
  clientStreaming : Bool
  serverStreaming : Bool
  deprecated : Bool
  deriving DecidableEq, Repr

end Fixture.API.Proto
