import fs from 'node:fs';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out = '.flow/artifacts/fn-113-gomad-reduce-version-pin-maintenance/task-2/source-acceptance-20261008';
const base = 'ca6fd855868fac364b69cb31394c87ad2912e623';
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const git = (...args) => { const r = spawnSync('git', args, {encoding:'utf8'}); if (r.status) throw Error(r.stderr); return r.stdout; };
const previous = file => git('show', base+':'+file);
const functionBody = (source, marker) => { const start=source.indexOf(marker); if(start<0) throw Error(marker); const end=source.indexOf('\n}\n', start)+3; if(end<start) throw Error(marker); return source.slice(start,end); };
const body = source => source.slice(source.indexOf('{\n')+2,source.lastIndexOf('\n}'));
const proofs=[];
const compare = (file, oldMarker, helperMarker, startMarker, transform=value=>value) => {
  const oldFunction=functionBody(previous(file),oldMarker), helper=functionBody(fs.readFileSync(file,'utf8'),helperMarker);
  const tail=oldFunction.slice(oldFunction.indexOf(startMarker),oldFunction.lastIndexOf('\n}'));
  const expected=transform(tail), actual=body(helper);
  const equal=expected===actual;
  proofs.push({file,oldMarker,helperMarker,original_function_sha256:hash(oldFunction),original_tail_sha256:hash(tail),expected_transformed_tail_sha256:hash(expected),actual_helper_body_sha256:hash(actual),equal});
  if(!equal) throw Error('extraction tail differs: '+file);
};
compare('tools/gomad3/deterministicio/adapter_registry.go','func (profile Spec) VerifyAdapters(','func (registry adapterRegistry) verify(','\tif adapters == nil',value=>value.replaceAll('definition.adapters.definitions','registry.definitions'));
compare('tools/gomad3/deterministicio/requirements.go','func (profile Spec) Requirements(','func projectAdapterRequirements(','\tevidence := packageRequirementEvidence');
compare('tools/gomad3/deterministicio/bootstrap.go','func (profile Spec) BootstrapFrame(','func encodeBootstrapFrame(','\targv, err := canonicalJSON');
compare('tools/gomad3/deterministicio/profile.go','func (profile Spec) ValidatePreparedTarget(','func validatePreparedTargetShape(','\tif spec.Kind',value=>value.slice(0,value.indexOf('\tif err := profile.VerifyAdapters')).trimEnd().replaceAll('return fmt.Errorf(','return nil, fmt.Errorf(')+'\n\treturn adapters, nil');
const signatures=proofs.map(({file,oldMarker})=>{const old=functionBody(previous(file),oldMarker), current=functionBody(fs.readFileSync(file,'utf8'),oldMarker); const oldHeader=old.slice(0,old.indexOf('{')),currentHeader=current.slice(0,current.indexOf('{')); return {file,signature:oldHeader,unchanged:oldHeader===currentHeader};});
if(signatures.some(p=>!p.unchanged)) throw Error('public signature changed');
const files=git('ls-files','tools/gomad3','go.mod','go.sum','tools/gomad3integration/go.mod','tools/gomad3integration/go.sum').trim().split('\n');
const changed=files.filter(file=>hash(previous(file))!==hash(fs.readFileSync(file)));
const allowed=['tools/gomad3/cmd/gomadtool/adapter_regenerate.go','tools/gomad3/deterministicio/adapter_regenerate_test.go','tools/gomad3/upgrade/adapterregen/publication_cleanup_test.go','tools/gomad3/upgrade/adapterregen/transaction.go','tools/gomad3/toolchain/version/descriptor_test.go',...proofs.map(p=>p.file)];
if(changed.some(file=>!allowed.includes(file))) throw Error('unexpected preservation change: '+changed);
const originalTests='tools/gomad3/deterministicio/adapter_regenerate_test.go';
const guards=['func pinnedReleaseGo(','func newRegenerationFixture('].map(marker=>({marker,unchanged:functionBody(previous(originalTests),marker)===functionBody(fs.readFileSync(originalTests,'utf8'),marker)}));
if(guards.some(p=>!p.unchanged)) throw Error('native test guard changed');
const stderrCalls=source=>source.split('\n').filter(line=>line.includes('fmt.Fprint')&&line.includes('stderr')).map(line=>line.slice(line.indexOf('fmt.Fprint')).replace(/; writeErr.*$/,'').trim());
const cli='tools/gomad3/cmd/gomadtool/adapter_regenerate.go';
const beforeCalls=stderrCalls(previous(cli)),afterCalls=stderrCalls(fs.readFileSync(cli,'utf8'));
if(JSON.stringify(beforeCalls)!==JSON.stringify(afterCalls)||afterCalls.length!==12) throw Error('stderr arguments/order changed');
const mod=fs.readFileSync('go.mod','utf8'), sums=fs.readFileSync('go.sum','utf8');
const adapters=JSON.parse(fs.readFileSync('tools/gomad3/toolchain/version/version.json','utf8')).adapters;
const pins=adapters.map(adapter=>{const line=mod.split('\n').map(line=>line.trim().split(/\s+/)).find(fields=>fields[0]===adapter.module); const sum=sums.split('\n').find(line=>line.startsWith(adapter.module+' '+adapter.version+' ')); return {...adapter,selected:!!line,selected_version:line?.[1]??null,exact:!line||(line[1]===adapter.version&&sum===adapter.module+' '+adapter.version+' '+adapter.sum)};});
if(pins.some(pin=>!pin.exact)) throw Error('root pin moved');
const userFiles=['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(file=>({file,sha256:hash(fs.readFileSync(file))}));
const evidence={base_commit:base,proofs,signatures,changed_tracked_paths:changed,unchanged_tracked_count:files.length-changed.length,native_guard_proofs:guards,stderr_calls:afterCalls,root_pins:pins,root_selected:pins.filter(p=>p.selected).length,root_absent:pins.filter(p=>!p.selected).length,root_moved:pins.filter(p=>!p.exact).length,root_go_mod_sha256:hash(mod),root_go_sum_sha256:hash(sums),userFiles};
fs.writeFileSync(out+'/preservation.json',JSON.stringify(evidence,null,2)+'\n');
console.log(JSON.stringify({tail_proofs:proofs.length,changed,root_selected:evidence.root_selected,root_absent:evidence.root_absent,root_moved:evidence.root_moved}));
