import fs from 'node:fs';
import crypto from 'node:crypto';
const out='.flow/artifacts/fn-113-gomad-reduce-version-pin-maintenance/task-2/source-acceptance-20261008';
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const baseline=fs.readFileSync(out+'/baseline-parent-quick.log','utf8');
const failed=new Set([...baseline.matchAll(/^--- FAIL: (Test\w+)/gm)].map(match=>match[1]));
failed.delete('TestRegenerateAdapterRefusesCustomPreparation');
const names=fs.readdirSync('tools/gomad3/deterministicio').filter(file=>file.endsWith('_test.go')).flatMap(file=>{const source=fs.readFileSync('tools/gomad3/deterministicio/'+file,'utf8');return [...source.matchAll(/^func (Test\w+)\(/gm)].map(match=>({name:match[1],file,source_sha256:hash(source)}));}).sort((a,b)=>a.name.localeCompare(b.name));
const binding=JSON.parse(fs.readFileSync(out+'/retained-assertions-binding.json','utf8'));
const origins=binding.origins??binding.mapping??binding.functions;
if(!origins) throw Error('overlay mapping absent');
const overlays=new Map(origins.filter(origin=>origin.function.startsWith('Test')).map(origin=>[origin.function,origin.portable]));
const mapping=name=>{
  if(overlays.has(name)) return {portable:[overlays.get(name)],reason:'original bootstrap requires absent patched driver; admitted retained assertion overlay executes same assertions, not original/native credit'};
  if(name.includes('RegenerateAdapter')||name.includes('AdapterSourceEdits')||name.includes('VerifyRegisteredAdapter')) return {portable:['TestPortableAdapterRegenerationSourceEdits','TestPortableAdapterRegenerationRefusals','TestPortableLibcRegeneration'],reason:'original pinnedReleaseGo/cache bootstrap unavailable; actual pinned stock source rewrite/verification and exact refusal controls'};
  if(name==='TestToolchainLeavesFD5ForProcessesWithoutIOProfile') return {portable:[],reason:'actual patched runtime FD5 process assertion only; native owners fn149.2/fn128.4 (aggregates fn149.4/fn128.7)'};
  if(name.includes('Requirements')) return {portable:['TestPortableRequirementsProjection','TestPortableSelectedAdapterIdentities','TestPortableProfilePublicGuardsRemainFirst'],reason:'actual production comparator/projection; unchanged public qualified-host wrapper remains native'};
  if(name.includes('Bootstrap')) return {portable:['TestPortableBootstrapFrameIdentity','TestPortableBootstrapPlatformGoldens','TestPortableProfilePublicGuardsRemainFirst'],reason:'actual production codec/identity helpers; unchanged public qualified-host wrapper remains native'};
  if(name==='TestDeterministicProfileAcceptsArbitraryTargetArguments') return {portable:['TestPortablePreparedTargetShape','TestPortableProfilePublicGuardsRemainFirst'],reason:'actual shape helper argv/build projection; public host validation preserved'};
  if(name==='TestProfileVerifiesSelectedAdapterIdentities') return {portable:['TestPortableSelectedAdapterIdentities','TestPortableProfilePublicGuardsRemainFirst'],reason:'actual comparator valid/modified identity; public host validation preserved'};
  if(name.includes('PreparedPackageSourceSetIdentity')||name.includes('PreparedSourceSetIdentity')) return {portable:['TestPortableAdapterPreparedSourcePins','TestPortableServerGraphPreparedSourceIdentities','TestPortableRewrittenModuleConsumers'],reason:'actual preparation and both-platform source listings, root dependency context when selected; public profile/capability/native wrapper unclaimed'};
  if(name.includes('Libc')) return {portable:['TestPortableLibcPreparedContract','TestPortableLibcSelectionConfiguration','TestPortableAdapterPreparedSourcePins'],reason:'actual libc preparation, projection, shim checks and selection refusals; public wrapper and patched internal/gomadio compilation native'};
  if(name==='TestHashicorpMetricsAdapterConsumer') return {portable:['TestPortableMetricsConsumer','TestPortableAdapterConfigurationRefusals'],reason:'real stock fixture behavior, exact private registry and both-platform source listing; qualified public profile/capability wrapper native'};
  if(name==='TestPrepareTargetBuildAdaptersRejectsMissingSumBeforeDownloading') return {portable:['TestAdapterModuleSumRecords','TestAdapterRegistryClassifiesMissingTargetModuleSumsAsInvalidConfiguration','TestPortableAdapterConfigurationRefusals'],reason:'actual selected sum validation and no-write private preparation; public unchanged pre-download ordering source preservation, qualified wrapper native'};
  if(name==='TestPrepareBuildAdaptersClassifiesInvalidTargetConfiguration'||name==='TestProfileRejectsAdapterConfigurationDrift') return {portable:['TestPortableAdapterConfigurationRefusals','TestPortableLibcSelectionConfiguration'],reason:'actual registry typed invalid-input refusals; qualified public wrapper native'};
  if(name==='TestProfileSelectsSentryAdapter'||name==='TestProfileSelectsDownstreamAdapters'||name==='TestRewrittenModuleConsumers') return {portable:['TestPortableRewrittenModuleConsumers','TestPortableMetricsConsumer'],reason:'real stock original consumers and private selection/source listings; public profile/capability/runtime wrapper remains native'};
  return {portable:['TestPortableAdapterSourcePreservation','TestPortableAdapterPreparedSourcePins'],reason:'actual immutable prepared inventories, exact pins, comments and identity/inventory negatives; original cache bootstrap unavailable'};
};
const excluded=names.filter(({name})=>failed.has(name)).map(test=>({...test,...mapping(test.name)}));
const selected=names.filter(({name})=>!failed.has(name));
const expression='^('+selected.map(test=>test.name).join('|')+')$';
fs.writeFileSync(out+'/deterministicio-selection.json',JSON.stringify({source_bootstrap_failures_are_not_native_waivers:true,selected,excluded,overlay_selected:origins.filter(origin=>origin.function.startsWith('Test')),expression},null,2)+'\n');
console.log(expression);
