// Code generated by internal/protocolgen. DO NOT EDIT.

package gomadchoicewire

import (
	"bytes"
	"encoding/binary"
	"errors"
)

const (
	Profile                = "gomadv3-choice-trace/v1"
	HeaderBytes            = 64
	RecordBytes            = 48
	TerminalFrameBytes     = 96
	TerminalChecksumOffset = 64
	DigestBytes            = 32
	wireVersion            = 1
)

var (
	traceMagic                 = [8]byte{'G', 'O', 'M', 'A', 'D', 'C', 'H', '\x01'}
	terminalMagic              = [8]byte{'G', 'O', 'M', 'A', 'D', 'C', 'T', '\x01'}
	ImplementationSourceSHA256 = [DigestBytes]byte{'\x00', 'À', 'B', 'ê', 'Ë', '1', '\u008d', 'Ó', ';', '\x16', 'Ê', '°', '\u0097', 'd', '\x1e', '!', '\u0087', '¯', 'Ã', '\u0091', 'z', 'Í', '³', 'p', 'æ', 'ë', 'õ', '\x13', 'ê', '*', '®', 'ô'}
)

type Kind uint8

const (
	KindRunnable     Kind = 1
	KindSelectPoll   Kind = 2
	KindSelectResult Kind = 3
)

type Flags uint8

const (
	FlagDecision    Flags = 1
	FlagObservation Flags = 2
	FlagSiteMissing Flags = 4
)

type Header struct {
	Capacity    uint64
	NextOffset  uint64
	RecordCount uint64
}

func EncodeHeader(capacity uint64) [HeaderBytes]byte {
	var header [HeaderBytes]byte
	copy(header[:8], traceMagic[:])
	binary.BigEndian.PutUint32(header[8:12], wireVersion)
	binary.BigEndian.PutUint64(header[16:24], capacity)
	binary.BigEndian.PutUint64(header[24:32], HeaderBytes)
	return header
}

func DecodeHeader(header []byte) (Header, error) {
	if len(header) != HeaderBytes || !bytes.Equal(header[:8], traceMagic[:]) || binary.BigEndian.Uint32(header[8:12]) != wireVersion || !zero(header[12:16]) || !zero(header[40:64]) {
		return Header{}, errors.New("invalid choice trace header")
	}
	value := Header{Capacity: binary.BigEndian.Uint64(header[16:24]), NextOffset: binary.BigEndian.Uint64(header[24:32]), RecordCount: binary.BigEndian.Uint64(header[32:40])}
	if value.Capacity < HeaderBytes+RecordBytes || value.NextOffset < HeaderBytes || value.NextOffset > value.Capacity || (value.NextOffset-HeaderBytes)%RecordBytes != 0 || value.RecordCount != (value.NextOffset-HeaderBytes)/RecordBytes {
		return Header{}, errors.New("invalid choice trace bounds")
	}
	return value, nil
}

func PublishHeader(header []byte, nextOffset, recordCount uint64) error {
	current, err := DecodeHeader(header)
	if err != nil {
		return err
	}
	if nextOffset < HeaderBytes || nextOffset > current.Capacity || (nextOffset-HeaderBytes)%RecordBytes != 0 || recordCount != (nextOffset-HeaderBytes)/RecordBytes {
		return errors.New("invalid choice trace publication")
	}
	binary.BigEndian.PutUint64(header[24:32], nextOffset)
	binary.BigEndian.PutUint64(header[32:40], recordCount)
	return nil
}

type Record struct {
	Ordinal      uint64
	Kind         Kind
	Flags        Flags
	Alternatives uint32
	Selected     uint32
	Data         uint32
	SiteOffset   uint64
}

func EncodeRecord(value Record) ([RecordBytes]byte, error) {
	var record [RecordBytes]byte
	if err := validateRecord(value); err != nil {
		return record, err
	}
	binary.BigEndian.PutUint64(record[:8], value.Ordinal)
	record[8] = byte(value.Kind)
	record[9] = byte(value.Flags)
	binary.BigEndian.PutUint32(record[12:16], value.Alternatives)
	binary.BigEndian.PutUint32(record[16:20], value.Selected)
	binary.BigEndian.PutUint32(record[20:24], value.Data)
	binary.BigEndian.PutUint64(record[24:32], value.SiteOffset)
	return record, nil
}

func DecodeRecord(record []byte) (Record, error) {
	if len(record) != RecordBytes || !zero(record[10:12]) || !zero(record[32:48]) {
		return Record{}, errors.New("invalid choice trace record")
	}
	value := Record{Ordinal: binary.BigEndian.Uint64(record[:8]), Kind: Kind(record[8]), Flags: Flags(record[9]), Alternatives: binary.BigEndian.Uint32(record[12:16]), Selected: binary.BigEndian.Uint32(record[16:20]), Data: binary.BigEndian.Uint32(record[20:24]), SiteOffset: binary.BigEndian.Uint64(record[24:32])}
	if err := validateRecord(value); err != nil {
		return Record{}, err
	}
	return value, nil
}

func validateRecord(value Record) error {
	if value.Kind < KindRunnable || value.Kind > KindSelectResult {
		return errors.New("invalid choice trace kind")
	}
	if value.Flags & ^(FlagDecision|FlagObservation|FlagSiteMissing) != 0 || value.Flags&(FlagDecision|FlagObservation) == 0 || value.Flags&(FlagDecision|FlagObservation) == FlagDecision|FlagObservation {
		return errors.New("invalid choice trace flags")
	}
	if value.Kind == KindSelectResult && value.Flags&FlagObservation == 0 || value.Kind != KindSelectResult && value.Flags&FlagDecision == 0 {
		return errors.New("invalid choice trace kind flags")
	}
	if value.Alternatives == 0 || value.Selected >= value.Alternatives {
		return errors.New("invalid choice trace selection")
	}
	if value.Flags&FlagSiteMissing != 0 && value.SiteOffset != 0 {
		return errors.New("invalid missing choice trace site")
	}
	return nil
}

type TerminalState uint8

const (
	TerminalComplete TerminalState = 1
	TerminalOverflow TerminalState = 2
)

type Terminal struct {
	State        TerminalState
	Records      uint64
	MappingBytes uint64
	PayloadHash  [DigestBytes]byte
}

func EncodeTerminal(value Terminal) [TerminalFrameBytes]byte {
	var frame [TerminalFrameBytes]byte
	copy(frame[:8], terminalMagic[:])
	binary.BigEndian.PutUint32(frame[8:12], wireVersion)
	frame[12] = byte(value.State)
	binary.BigEndian.PutUint64(frame[16:24], value.Records)
	binary.BigEndian.PutUint64(frame[24:32], value.MappingBytes)
	copy(frame[32:64], value.PayloadHash[:])
	checksum := sum256(frame[:TerminalChecksumOffset])
	copy(frame[TerminalChecksumOffset:], checksum[:])
	return frame
}

func DecodeTerminal(frame []byte) (Terminal, error) {
	if len(frame) != TerminalFrameBytes || !bytes.Equal(frame[:8], terminalMagic[:]) || binary.BigEndian.Uint32(frame[8:12]) != wireVersion || !zero(frame[13:16]) {
		return Terminal{}, errors.New("invalid choice terminal frame")
	}
	checksum := sum256(frame[:TerminalChecksumOffset])
	if !bytes.Equal(frame[TerminalChecksumOffset:], checksum[:]) {
		return Terminal{}, errors.New("choice terminal checksum mismatch")
	}
	value := Terminal{State: TerminalState(frame[12]), Records: binary.BigEndian.Uint64(frame[16:24]), MappingBytes: binary.BigEndian.Uint64(frame[24:32])}
	copy(value.PayloadHash[:], frame[32:64])
	if value.State < TerminalComplete || value.State > TerminalOverflow || value.MappingBytes < HeaderBytes || (value.MappingBytes-HeaderBytes)%RecordBytes != 0 || value.Records != (value.MappingBytes-HeaderBytes)/RecordBytes {
		return Terminal{}, errors.New("invalid choice terminal values")
	}
	return value, nil
}

func zero(data []byte) bool {
	for _, value := range data {
		if value != 0 {
			return false
		}
	}
	return true
}

func Hash(input []byte) [DigestBytes]byte { return sum256(input) }

func sum256(input []byte) [DigestBytes]byte {
	state := [8]uint32{0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19}
	length := uint64(len(input)) * 8
	paddedLength := (len(input) + 9 + 63) &^ 63
	padded := make([]byte, paddedLength)
	copy(padded, input)
	padded[len(input)] = 0x80
	binary.BigEndian.PutUint64(padded[len(padded)-8:], length)
	for len(padded) != 0 {
		var words [64]uint32
		for index := 0; index < 16; index++ {
			words[index] = binary.BigEndian.Uint32(padded[index*4 : index*4+4])
		}
		for index := 16; index < 64; index++ {
			s0 := rotateRight(words[index-15], 7) ^ rotateRight(words[index-15], 18) ^ words[index-15]>>3
			s1 := rotateRight(words[index-2], 17) ^ rotateRight(words[index-2], 19) ^ words[index-2]>>10
			words[index] = words[index-16] + s0 + words[index-7] + s1
		}
		a, b, c, d := state[0], state[1], state[2], state[3]
		e, f, g, h := state[4], state[5], state[6], state[7]
		for index := 0; index < 64; index++ {
			s1 := rotateRight(e, 6) ^ rotateRight(e, 11) ^ rotateRight(e, 25)
			choice := e&f ^ (^e)&g
			temporary1 := h + s1 + choice + sha256Constants[index] + words[index]
			s0 := rotateRight(a, 2) ^ rotateRight(a, 13) ^ rotateRight(a, 22)
			majority := a&b ^ a&c ^ b&c
			temporary2 := s0 + majority
			h, g, f, e, d, c, b, a = g, f, e, d+temporary1, c, b, a, temporary1+temporary2
		}
		state[0] += a
		state[1] += b
		state[2] += c
		state[3] += d
		state[4] += e
		state[5] += f
		state[6] += g
		state[7] += h
		padded = padded[64:]
	}
	var result [DigestBytes]byte
	for index, value := range state {
		binary.BigEndian.PutUint32(result[index*4:index*4+4], value)
	}
	return result
}

func rotateRight(value uint32, bits uint) uint32 { return value>>bits | value<<(32-bits) }

var sha256Constants = [64]uint32{
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
}
