// Code generated by umpire-gen-regression-projections. DO NOT EDIT.
// This verifies a Lean model projection only; it does not execute Temporal or represent evidence.

package regression

import "testing"

// TestWorkflowNexusQueryExactActionCallerClosure verifies the checked-in projection for workflow-nexus.query.exact-action-caller-closure.
// Lean source: model/Temporal/Feature/Nexus/Experimental/CallerClosure.lean
// Semantic fingerprint: sha256:4e04aacc52a317a0c9341652f32f6416e9158168af8a2e94c7bae5e0a8f32563
func TestWorkflowNexusQueryExactActionCallerClosure(t *testing.T) {
	RequireProjection(t, Reference{
		FormatVersion: "umpire-experiment/v1",
		Identity:      "workflow-nexus.query.exact-action-caller-closure",
		FixturePath:   "model/Temporal/Feature/Nexus/Experimental/testdata/nexus-caller-closure-experiment-spec.json",
		Sources: []string{
			"Temporal/Feature/Nexus/Experimental/CallerClosure.lean",
		},
		Properties: []string{
			"workflow-nexus.property.caller-closure",
		},
		ObservationRequirements: []string{
			"nexus.observation.cancellation-delivered",
			"nexus.observation.pending-cancellation-count",
			"workflow-nexus.relation.owns-operation",
		},
		SemanticFingerprint: "sha256:4e04aacc52a317a0c9341652f32f6416e9158168af8a2e94c7bae5e0a8f32563",
	})
}
