// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package umpire

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type Model to the protobuf v3 wire format
func (val *Model) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type Model from the protobuf v3 wire format
func (val *Model) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *Model) Size() int {
	return proto.Size(val)
}

// Equal returns whether two Model values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *Model) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *Model
	switch t := that.(type) {
	case *Model:
		that1 = t
	case Model:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
