// The Umpire model IR: a semantic transition system, independent of the language a Model is authored
// in. A front end (model/irgen lifts Scala) emits it; the Go reader in tools/umpire/{ir,interp,check}
// validates it, interprets it, and derives every table, identity and fingerprint from it. Like the
// Testpilot protocol, it is an internal wire with no compatibility promise. The
// evaluation rules are written in model/SEMANTICS.md; neither front end nor interpreter
// defines them.
//
// The IR carries declarations, never derived tables: steps are pure functions over values, and the
// tables are what the interpreter computes from them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/umpire/v1/ir.proto

package umpire

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Model: its types, its pure functions, its actions, and its machines.
// It also carries the declarations checks read over them.
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the Model was lifted from, for diagnostics and provenance.
	Source    string      `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Types     []*Type     `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Functions []*Function `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	Actions   []*Action   `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Machines  []*Machine  `protobuf:"bytes,5,rep,name=machines,proto3" json:"machines,omitempty"`
	// The IR's major version. model/SEMANTICS.md defines version 0, which every Model written
	// before this field was is in; a reader rejects a version it does not know.
	Version       uint32         `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Channels      []*Channel     `protobuf:"bytes,7,rep,name=channels,proto3" json:"channels,omitempty"`
	Monitors      []*Monitor     `protobuf:"bytes,8,rep,name=monitors,proto3" json:"monitors,omitempty"`
	Assumptions   []*Assumption  `protobuf:"bytes,9,rep,name=assumptions,proto3" json:"assumptions,omitempty"`
	Holes         []*Hole        `protobuf:"bytes,10,rep,name=holes,proto3" json:"holes,omitempty"`
	Compositions  []*Composition `protobuf:"bytes,11,rep,name=compositions,proto3" json:"compositions,omitempty"`
	Properties    []*Property    `protobuf:"bytes,12,rep,name=properties,proto3" json:"properties,omitempty"`
	Scenarios     []*Scenario    `protobuf:"bytes,13,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	Queries       []*Query       `protobuf:"bytes,14,rep,name=queries,proto3" json:"queries,omitempty"`
	Progress      []*Progress    `protobuf:"bytes,15,rep,name=progress,proto3" json:"progress,omitempty"`
	Realizations  []*Realization `protobuf:"bytes,16,rep,name=realizations,proto3" json:"realizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_temporal_server_api_umpire_v1_ir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_ir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_ir_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Model) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Model) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Model) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Model) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *Model) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Model) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Model) GetMonitors() []*Monitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

func (x *Model) GetAssumptions() []*Assumption {
	if x != nil {
		return x.Assumptions
	}
	return nil
}

func (x *Model) GetHoles() []*Hole {
	if x != nil {
		return x.Holes
	}
	return nil
}

func (x *Model) GetCompositions() []*Composition {
	if x != nil {
		return x.Compositions
	}
	return nil
}

func (x *Model) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Model) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *Model) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *Model) GetProgress() []*Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *Model) GetRealizations() []*Realization {
	if x != nil {
		return x.Realizations
	}
	return nil
}

var File_temporal_server_api_umpire_v1_ir_proto protoreflect.FileDescriptor

const file_temporal_server_api_umpire_v1_ir_proto_rawDesc = "" +
	"\n" +
	"&temporal/server/api/umpire/v1/ir.proto\x12\x1dtemporal.server.api.umpire.v1\x1a)temporal/server/api/umpire/v1/claim.proto\x1a.temporal/server/api/umpire/v1/expression.proto\x1a+temporal/server/api/umpire/v1/machine.proto\x1a/temporal/server/api/umpire/v1/realization.proto\x1a)temporal/server/api/umpire/v1/value.proto\"\x85\b\n" +
	"\x05Model\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x129\n" +
	"\x05types\x18\x02 \x03(\v2#.temporal.server.api.umpire.v1.TypeR\x05types\x12E\n" +
	"\tfunctions\x18\x03 \x03(\v2'.temporal.server.api.umpire.v1.FunctionR\tfunctions\x12?\n" +
	"\aactions\x18\x04 \x03(\v2%.temporal.server.api.umpire.v1.ActionR\aactions\x12B\n" +
	"\bmachines\x18\x05 \x03(\v2&.temporal.server.api.umpire.v1.MachineR\bmachines\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\x12B\n" +
	"\bchannels\x18\a \x03(\v2&.temporal.server.api.umpire.v1.ChannelR\bchannels\x12B\n" +
	"\bmonitors\x18\b \x03(\v2&.temporal.server.api.umpire.v1.MonitorR\bmonitors\x12K\n" +
	"\vassumptions\x18\t \x03(\v2).temporal.server.api.umpire.v1.AssumptionR\vassumptions\x129\n" +
	"\x05holes\x18\n" +
	" \x03(\v2#.temporal.server.api.umpire.v1.HoleR\x05holes\x12N\n" +
	"\fcompositions\x18\v \x03(\v2*.temporal.server.api.umpire.v1.CompositionR\fcompositions\x12G\n" +
	"\n" +
	"properties\x18\f \x03(\v2'.temporal.server.api.umpire.v1.PropertyR\n" +
	"properties\x12E\n" +
	"\tscenarios\x18\r \x03(\v2'.temporal.server.api.umpire.v1.ScenarioR\tscenarios\x12>\n" +
	"\aqueries\x18\x0e \x03(\v2$.temporal.server.api.umpire.v1.QueryR\aqueries\x12C\n" +
	"\bprogress\x18\x0f \x03(\v2'.temporal.server.api.umpire.v1.ProgressR\bprogress\x12N\n" +
	"\frealizations\x18\x10 \x03(\v2*.temporal.server.api.umpire.v1.RealizationR\frealizationsBP\n" +
	" io.temporal.server.api.umpire.v1P\x01Z*go.temporal.io/server/api/umpire/v1;umpireb\x06proto3"

var (
	file_temporal_server_api_umpire_v1_ir_proto_rawDescOnce sync.Once
	file_temporal_server_api_umpire_v1_ir_proto_rawDescData []byte
)

func file_temporal_server_api_umpire_v1_ir_proto_rawDescGZIP() []byte {
	file_temporal_server_api_umpire_v1_ir_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_umpire_v1_ir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_umpire_v1_ir_proto_rawDesc), len(file_temporal_server_api_umpire_v1_ir_proto_rawDesc)))
	})
	return file_temporal_server_api_umpire_v1_ir_proto_rawDescData
}

var file_temporal_server_api_umpire_v1_ir_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_temporal_server_api_umpire_v1_ir_proto_goTypes = []any{
	(*Model)(nil),       // 0: temporal.server.api.umpire.v1.Model
	(*Type)(nil),        // 1: temporal.server.api.umpire.v1.Type
	(*Function)(nil),    // 2: temporal.server.api.umpire.v1.Function
	(*Action)(nil),      // 3: temporal.server.api.umpire.v1.Action
	(*Machine)(nil),     // 4: temporal.server.api.umpire.v1.Machine
	(*Channel)(nil),     // 5: temporal.server.api.umpire.v1.Channel
	(*Monitor)(nil),     // 6: temporal.server.api.umpire.v1.Monitor
	(*Assumption)(nil),  // 7: temporal.server.api.umpire.v1.Assumption
	(*Hole)(nil),        // 8: temporal.server.api.umpire.v1.Hole
	(*Composition)(nil), // 9: temporal.server.api.umpire.v1.Composition
	(*Property)(nil),    // 10: temporal.server.api.umpire.v1.Property
	(*Scenario)(nil),    // 11: temporal.server.api.umpire.v1.Scenario
	(*Query)(nil),       // 12: temporal.server.api.umpire.v1.Query
	(*Progress)(nil),    // 13: temporal.server.api.umpire.v1.Progress
	(*Realization)(nil), // 14: temporal.server.api.umpire.v1.Realization
}
var file_temporal_server_api_umpire_v1_ir_proto_depIdxs = []int32{
	1,  // 0: temporal.server.api.umpire.v1.Model.types:type_name -> temporal.server.api.umpire.v1.Type
	2,  // 1: temporal.server.api.umpire.v1.Model.functions:type_name -> temporal.server.api.umpire.v1.Function
	3,  // 2: temporal.server.api.umpire.v1.Model.actions:type_name -> temporal.server.api.umpire.v1.Action
	4,  // 3: temporal.server.api.umpire.v1.Model.machines:type_name -> temporal.server.api.umpire.v1.Machine
	5,  // 4: temporal.server.api.umpire.v1.Model.channels:type_name -> temporal.server.api.umpire.v1.Channel
	6,  // 5: temporal.server.api.umpire.v1.Model.monitors:type_name -> temporal.server.api.umpire.v1.Monitor
	7,  // 6: temporal.server.api.umpire.v1.Model.assumptions:type_name -> temporal.server.api.umpire.v1.Assumption
	8,  // 7: temporal.server.api.umpire.v1.Model.holes:type_name -> temporal.server.api.umpire.v1.Hole
	9,  // 8: temporal.server.api.umpire.v1.Model.compositions:type_name -> temporal.server.api.umpire.v1.Composition
	10, // 9: temporal.server.api.umpire.v1.Model.properties:type_name -> temporal.server.api.umpire.v1.Property
	11, // 10: temporal.server.api.umpire.v1.Model.scenarios:type_name -> temporal.server.api.umpire.v1.Scenario
	12, // 11: temporal.server.api.umpire.v1.Model.queries:type_name -> temporal.server.api.umpire.v1.Query
	13, // 12: temporal.server.api.umpire.v1.Model.progress:type_name -> temporal.server.api.umpire.v1.Progress
	14, // 13: temporal.server.api.umpire.v1.Model.realizations:type_name -> temporal.server.api.umpire.v1.Realization
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_temporal_server_api_umpire_v1_ir_proto_init() }
func file_temporal_server_api_umpire_v1_ir_proto_init() {
	if File_temporal_server_api_umpire_v1_ir_proto != nil {
		return
	}
	file_temporal_server_api_umpire_v1_claim_proto_init()
	file_temporal_server_api_umpire_v1_expression_proto_init()
	file_temporal_server_api_umpire_v1_machine_proto_init()
	file_temporal_server_api_umpire_v1_realization_proto_init()
	file_temporal_server_api_umpire_v1_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_umpire_v1_ir_proto_rawDesc), len(file_temporal_server_api_umpire_v1_ir_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_umpire_v1_ir_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_umpire_v1_ir_proto_depIdxs,
		MessageInfos:      file_temporal_server_api_umpire_v1_ir_proto_msgTypes,
	}.Build()
	File_temporal_server_api_umpire_v1_ir_proto = out.File
	file_temporal_server_api_umpire_v1_ir_proto_goTypes = nil
	file_temporal_server_api_umpire_v1_ir_proto_depIdxs = nil
}
