// The Umpire IR's finite values: the types a Model declares and the values of them. A file of the
// IR schema rooted at ir.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/umpire/v1/value.proto

package umpire

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A finite type, with its members in catalog order.
type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified, e.g. `temporal.nexuscaller.kernel.ProtocolState`.
	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// Types that are valid to be assigned to Shape:
	//
	//	*Type_Enum
	//	*Type_Record
	Shape         isType_Shape `protobuf_oneof:"shape"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Type) GetShape() isType_Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Type) GetEnum() *Enum {
	if x != nil {
		if x, ok := x.Shape.(*Type_Enum); ok {
			return x.Enum
		}
	}
	return nil
}

func (x *Type) GetRecord() *Record {
	if x != nil {
		if x, ok := x.Shape.(*Type_Record); ok {
			return x.Record
		}
	}
	return nil
}

type isType_Shape interface {
	isType_Shape()
}

type Type_Enum struct {
	// A sum of cases, each with its own finite fields; a case without fields is one member.
	Enum *Enum `protobuf:"bytes,3,opt,name=enum,proto3,oneof"`
}

type Type_Record struct {
	// A product of finite fields, the last field varying fastest.
	Record *Record `protobuf:"bytes,4,opt,name=record,proto3,oneof"`
}

func (*Type_Enum) isType_Shape() {}

func (*Type_Record) isType_Shape() {}

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cases         []*Case                `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{1}
}

func (x *Enum) GetCases() []*Case {
	if x != nil {
		return x.Cases
	}
	return nil
}

type Case struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{2}
}

func (x *Case) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Case) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{3}
}

func (x *Record) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *TypeRef               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

// A reference to a finite type: a declared type, the Booleans, or an integer range.
type TypeRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*TypeRef_Named
	//	*TypeRef_Bool
	//	*TypeRef_IntRange
	//	*TypeRef_List
	//	*TypeRef_Int
	//	*TypeRef_Channel
	Ref           isTypeRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRef) Reset() {
	*x = TypeRef{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRef) ProtoMessage() {}

func (x *TypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRef.ProtoReflect.Descriptor instead.
func (*TypeRef) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{5}
}

func (x *TypeRef) GetRef() isTypeRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *TypeRef) GetNamed() string {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_Named); ok {
			return x.Named
		}
	}
	return ""
}

func (x *TypeRef) GetBool() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *TypeRef) GetIntRange() *IntRange {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_IntRange); ok {
			return x.IntRange
		}
	}
	return nil
}

func (x *TypeRef) GetList() *TypeRef {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *TypeRef) GetInt() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_Int); ok {
			return x.Int
		}
	}
	return nil
}

func (x *TypeRef) GetChannel() string {
	if x != nil {
		if x, ok := x.Ref.(*TypeRef_Channel); ok {
			return x.Channel
		}
	}
	return ""
}

type isTypeRef_Ref interface {
	isTypeRef_Ref()
}

type TypeRef_Named struct {
	Named string `protobuf:"bytes,1,opt,name=named,proto3,oneof"`
}

type TypeRef_Bool struct {
	Bool *emptypb.Empty `protobuf:"bytes,2,opt,name=bool,proto3,oneof"`
}

type TypeRef_IntRange struct {
	IntRange *IntRange `protobuf:"bytes,3,opt,name=int_range,json=intRange,proto3,oneof"`
}

type TypeRef_List struct {
	// A list of values, for a step's facts and a function's results; not a state field.
	List *TypeRef `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type TypeRef_Int struct {
	// An integer with no declared range: a function parameter, never a state field.
	Int *emptypb.Empty `protobuf:"bytes,5,opt,name=int,proto3,oneof"`
}

type TypeRef_Channel struct {
	// What a declared channel holds, named by the channel's id: a state field's bounded collection.
	Channel string `protobuf:"bytes,6,opt,name=channel,proto3,oneof"`
}

func (*TypeRef_Named) isTypeRef_Ref() {}

func (*TypeRef_Bool) isTypeRef_Ref() {}

func (*TypeRef_IntRange) isTypeRef_Ref() {}

func (*TypeRef_List) isTypeRef_Ref() {}

func (*TypeRef_Int) isTypeRef_Ref() {}

func (*TypeRef_Channel) isTypeRef_Ref() {}

type IntRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int64                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          int64                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntRange) Reset() {
	*x = IntRange{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRange) ProtoMessage() {}

func (x *IntRange) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRange.ProtoReflect.Descriptor instead.
func (*IntRange) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{6}
}

func (x *IntRange) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *IntRange) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

// A value of a finite type.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_Bool
	//	*Value_Int
	//	*Value_Enum
	//	*Value_Record
	//	*Value_List
	//	*Value_Text
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{7}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetInt() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Value) GetEnum() *EnumValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_Enum); ok {
			return x.Enum
		}
	}
	return nil
}

func (x *Value) GetRecord() *RecordValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *Value) GetList() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Value) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,1,opt,name=bool,proto3,oneof"`
}

type Value_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Value_Enum struct {
	Enum *EnumValue `protobuf:"bytes,3,opt,name=enum,proto3,oneof"`
}

type Value_Record struct {
	Record *RecordValue `protobuf:"bytes,4,opt,name=record,proto3,oneof"`
}

type Value_List struct {
	List *ListValue `protobuf:"bytes,5,opt,name=list,proto3,oneof"`
}

type Value_Text struct {
	Text string `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

func (*Value_Bool) isValue_Kind() {}

func (*Value_Int) isValue_Kind() {}

func (*Value_Enum) isValue_Kind() {}

func (*Value_Record) isValue_Kind() {}

func (*Value_List) isValue_Kind() {}

func (*Value_Text) isValue_Kind() {}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Case          string                 `protobuf:"bytes,2,opt,name=case,proto3" json:"case,omitempty"`
	Fields        []*Value               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{8}
}

func (x *EnumValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnumValue) GetCase() string {
	if x != nil {
		return x.Case
	}
	return ""
}

func (x *EnumValue) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RecordValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Fields        []*Value               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordValue) Reset() {
	*x = RecordValue{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordValue) ProtoMessage() {}

func (x *RecordValue) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordValue.ProtoReflect.Descriptor instead.
func (*RecordValue) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{9}
}

func (x *RecordValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecordValue) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_umpire_v1_value_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP(), []int{10}
}

func (x *ListValue) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_temporal_server_api_umpire_v1_value_proto protoreflect.FileDescriptor

const file_temporal_server_api_umpire_v1_value_proto_rawDesc = "" +
	"\n" +
	")temporal/server/api/umpire/v1/value.proto\x12\x1dtemporal.server.api.umpire.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a*temporal/server/api/umpire/v1/common.proto\"\xe4\x01\n" +
	"\x04Type\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\bposition\x18\x02 \x01(\v2'.temporal.server.api.umpire.v1.PositionR\bposition\x129\n" +
	"\x04enum\x18\x03 \x01(\v2#.temporal.server.api.umpire.v1.EnumH\x00R\x04enum\x12?\n" +
	"\x06record\x18\x04 \x01(\v2%.temporal.server.api.umpire.v1.RecordH\x00R\x06recordB\a\n" +
	"\x05shape\"A\n" +
	"\x04Enum\x129\n" +
	"\x05cases\x18\x01 \x03(\v2#.temporal.server.api.umpire.v1.CaseR\x05cases\"X\n" +
	"\x04Case\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06fields\x18\x02 \x03(\v2$.temporal.server.api.umpire.v1.FieldR\x06fields\"F\n" +
	"\x06Record\x12<\n" +
	"\x06fields\x18\x01 \x03(\v2$.temporal.server.api.umpire.v1.FieldR\x06fields\"W\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\x04type\x18\x02 \x01(\v2&.temporal.server.api.umpire.v1.TypeRefR\x04type\"\xa4\x02\n" +
	"\aTypeRef\x12\x16\n" +
	"\x05named\x18\x01 \x01(\tH\x00R\x05named\x12,\n" +
	"\x04bool\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x04bool\x12F\n" +
	"\tint_range\x18\x03 \x01(\v2'.temporal.server.api.umpire.v1.IntRangeH\x00R\bintRange\x12<\n" +
	"\x04list\x18\x04 \x01(\v2&.temporal.server.api.umpire.v1.TypeRefH\x00R\x04list\x12*\n" +
	"\x03int\x18\x05 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03int\x12\x1a\n" +
	"\achannel\x18\x06 \x01(\tH\x00R\achannelB\x05\n" +
	"\x03ref\"0\n" +
	"\bIntRange\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x03R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x03R\x04high\"\x95\x02\n" +
	"\x05Value\x12\x14\n" +
	"\x04bool\x18\x01 \x01(\bH\x00R\x04bool\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x03H\x00R\x03int\x12>\n" +
	"\x04enum\x18\x03 \x01(\v2(.temporal.server.api.umpire.v1.EnumValueH\x00R\x04enum\x12D\n" +
	"\x06record\x18\x04 \x01(\v2*.temporal.server.api.umpire.v1.RecordValueH\x00R\x06record\x12>\n" +
	"\x04list\x18\x05 \x01(\v2(.temporal.server.api.umpire.v1.ListValueH\x00R\x04list\x12\x14\n" +
	"\x04text\x18\x06 \x01(\tH\x00R\x04textB\x06\n" +
	"\x04kind\"q\n" +
	"\tEnumValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04case\x18\x02 \x01(\tR\x04case\x12<\n" +
	"\x06fields\x18\x03 \x03(\v2$.temporal.server.api.umpire.v1.ValueR\x06fields\"_\n" +
	"\vRecordValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\x06fields\x18\x02 \x03(\v2$.temporal.server.api.umpire.v1.ValueR\x06fields\"G\n" +
	"\tListValue\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.temporal.server.api.umpire.v1.ValueR\x05itemsBP\n" +
	" io.temporal.server.api.umpire.v1P\x01Z*go.temporal.io/server/api/umpire/v1;umpireb\x06proto3"

var (
	file_temporal_server_api_umpire_v1_value_proto_rawDescOnce sync.Once
	file_temporal_server_api_umpire_v1_value_proto_rawDescData []byte
)

func file_temporal_server_api_umpire_v1_value_proto_rawDescGZIP() []byte {
	file_temporal_server_api_umpire_v1_value_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_umpire_v1_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_umpire_v1_value_proto_rawDesc), len(file_temporal_server_api_umpire_v1_value_proto_rawDesc)))
	})
	return file_temporal_server_api_umpire_v1_value_proto_rawDescData
}

var file_temporal_server_api_umpire_v1_value_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_temporal_server_api_umpire_v1_value_proto_goTypes = []any{
	(*Type)(nil),          // 0: temporal.server.api.umpire.v1.Type
	(*Enum)(nil),          // 1: temporal.server.api.umpire.v1.Enum
	(*Case)(nil),          // 2: temporal.server.api.umpire.v1.Case
	(*Record)(nil),        // 3: temporal.server.api.umpire.v1.Record
	(*Field)(nil),         // 4: temporal.server.api.umpire.v1.Field
	(*TypeRef)(nil),       // 5: temporal.server.api.umpire.v1.TypeRef
	(*IntRange)(nil),      // 6: temporal.server.api.umpire.v1.IntRange
	(*Value)(nil),         // 7: temporal.server.api.umpire.v1.Value
	(*EnumValue)(nil),     // 8: temporal.server.api.umpire.v1.EnumValue
	(*RecordValue)(nil),   // 9: temporal.server.api.umpire.v1.RecordValue
	(*ListValue)(nil),     // 10: temporal.server.api.umpire.v1.ListValue
	(*Position)(nil),      // 11: temporal.server.api.umpire.v1.Position
	(*emptypb.Empty)(nil), // 12: google.protobuf.Empty
}
var file_temporal_server_api_umpire_v1_value_proto_depIdxs = []int32{
	11, // 0: temporal.server.api.umpire.v1.Type.position:type_name -> temporal.server.api.umpire.v1.Position
	1,  // 1: temporal.server.api.umpire.v1.Type.enum:type_name -> temporal.server.api.umpire.v1.Enum
	3,  // 2: temporal.server.api.umpire.v1.Type.record:type_name -> temporal.server.api.umpire.v1.Record
	2,  // 3: temporal.server.api.umpire.v1.Enum.cases:type_name -> temporal.server.api.umpire.v1.Case
	4,  // 4: temporal.server.api.umpire.v1.Case.fields:type_name -> temporal.server.api.umpire.v1.Field
	4,  // 5: temporal.server.api.umpire.v1.Record.fields:type_name -> temporal.server.api.umpire.v1.Field
	5,  // 6: temporal.server.api.umpire.v1.Field.type:type_name -> temporal.server.api.umpire.v1.TypeRef
	12, // 7: temporal.server.api.umpire.v1.TypeRef.bool:type_name -> google.protobuf.Empty
	6,  // 8: temporal.server.api.umpire.v1.TypeRef.int_range:type_name -> temporal.server.api.umpire.v1.IntRange
	5,  // 9: temporal.server.api.umpire.v1.TypeRef.list:type_name -> temporal.server.api.umpire.v1.TypeRef
	12, // 10: temporal.server.api.umpire.v1.TypeRef.int:type_name -> google.protobuf.Empty
	8,  // 11: temporal.server.api.umpire.v1.Value.enum:type_name -> temporal.server.api.umpire.v1.EnumValue
	9,  // 12: temporal.server.api.umpire.v1.Value.record:type_name -> temporal.server.api.umpire.v1.RecordValue
	10, // 13: temporal.server.api.umpire.v1.Value.list:type_name -> temporal.server.api.umpire.v1.ListValue
	7,  // 14: temporal.server.api.umpire.v1.EnumValue.fields:type_name -> temporal.server.api.umpire.v1.Value
	7,  // 15: temporal.server.api.umpire.v1.RecordValue.fields:type_name -> temporal.server.api.umpire.v1.Value
	7,  // 16: temporal.server.api.umpire.v1.ListValue.items:type_name -> temporal.server.api.umpire.v1.Value
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_temporal_server_api_umpire_v1_value_proto_init() }
func file_temporal_server_api_umpire_v1_value_proto_init() {
	if File_temporal_server_api_umpire_v1_value_proto != nil {
		return
	}
	file_temporal_server_api_umpire_v1_common_proto_init()
	file_temporal_server_api_umpire_v1_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Type_Enum)(nil),
		(*Type_Record)(nil),
	}
	file_temporal_server_api_umpire_v1_value_proto_msgTypes[5].OneofWrappers = []any{
		(*TypeRef_Named)(nil),
		(*TypeRef_Bool)(nil),
		(*TypeRef_IntRange)(nil),
		(*TypeRef_List)(nil),
		(*TypeRef_Int)(nil),
		(*TypeRef_Channel)(nil),
	}
	file_temporal_server_api_umpire_v1_value_proto_msgTypes[7].OneofWrappers = []any{
		(*Value_Bool)(nil),
		(*Value_Int)(nil),
		(*Value_Enum)(nil),
		(*Value_Record)(nil),
		(*Value_List)(nil),
		(*Value_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_umpire_v1_value_proto_rawDesc), len(file_temporal_server_api_umpire_v1_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_umpire_v1_value_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_umpire_v1_value_proto_depIdxs,
		MessageInfos:      file_temporal_server_api_umpire_v1_value_proto_msgTypes,
	}.Build()
	File_temporal_server_api_umpire_v1_value_proto = out.File
	file_temporal_server_api_umpire_v1_value_proto_goTypes = nil
	file_temporal_server_api_umpire_v1_value_proto_depIdxs = nil
}
