// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gomadintercept

var fileReceiver = &receiverSpec{Name: "File", Pointer: true}
var connReceiver = &receiverSpec{Name: "conn", Pointer: true}
var dialerReceiver = &receiverSpec{Name: "Dialer", Pointer: true}
var listenConfigReceiver = &receiverSpec{Name: "ListenConfig", Pointer: true}
var tcpConnReceiver = &receiverSpec{Name: "TCPConn", Pointer: true}
var tcpListenerReceiver = &receiverSpec{Name: "TCPListener", Pointer: true}

var specs = []spec{
	{PackagePath: "os", Function: "OpenFile", Hook: "gomadInterceptOpenFile"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Read", Hook: "gomadInterceptFileRead"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Close", Hook: "gomadInterceptFileClose"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Readdir", Hook: "gomadInterceptFileReaddir"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Readdirnames", Hook: "gomadInterceptFileReaddirnames"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "ReadDir", Hook: "gomadInterceptFileReadDir"},
	{PackagePath: "os", Function: "ReadDir", Hook: "gomadInterceptReadDir"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "ReadAt", Hook: "gomadInterceptFileReadAt"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Write", Hook: "gomadInterceptFileWrite"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "WriteAt", Hook: "gomadInterceptFileWriteAt"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Seek", Hook: "gomadInterceptFileSeek"},
	{PackagePath: "os", Function: "Mkdir", Hook: "gomadInterceptMkdir"},
	{PackagePath: "os", Function: "Chdir", Hook: "gomadInterceptChdir"},
	{PackagePath: "os", Function: "Rename", Hook: "gomadInterceptRename"},
	{PackagePath: "os", Function: "Readlink", Hook: "gomadInterceptReadlink"},
	{PackagePath: "os", Function: "Chmod", Hook: "gomadInterceptChmod"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Chmod", Hook: "gomadInterceptFileChmod"},
	{PackagePath: "os", Function: "Chown", Hook: "gomadInterceptChown"},
	{PackagePath: "os", Function: "Lchown", Hook: "gomadInterceptLchown"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Chown", Hook: "gomadInterceptFileChown"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Truncate", Hook: "gomadInterceptFileTruncate"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Sync", Hook: "gomadInterceptFileSync"},
	{PackagePath: "os", Function: "Chtimes", Hook: "gomadInterceptChtimes"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Chdir", Hook: "gomadInterceptFileChdir"},
	{PackagePath: "os", Function: "Truncate", Hook: "gomadInterceptTruncate"},
	{PackagePath: "os", Function: "Remove", Hook: "gomadInterceptRemove"},
	{PackagePath: "os", Function: "Link", Hook: "gomadInterceptLink"},
	{PackagePath: "os", Function: "Symlink", Hook: "gomadInterceptSymlink"},
	{PackagePath: "os", Function: "Getwd", Hook: "gomadInterceptGetwd"},
	{PackagePath: "os", Function: "MkdirAll", Hook: "gomadInterceptMkdirAll"},
	{PackagePath: "os", Function: "RemoveAll", Hook: "gomadInterceptRemoveAll"},
	{PackagePath: "os", Function: "Stat", Hook: "gomadInterceptStat"},
	{PackagePath: "os", Function: "Lstat", Hook: "gomadInterceptLstat"},
	{PackagePath: "os", Receiver: fileReceiver, Function: "Stat", Hook: "gomadInterceptFileStat"},
	{PackagePath: "os", Function: "Hostname", Hook: "gomadInterceptHostname"},
	{PackagePath: "net", Receiver: dialerReceiver, Function: "DialContext", Hook: "gomadInterceptDialContext"},
	{PackagePath: "net", Receiver: listenConfigReceiver, Function: "Listen", Hook: "gomadInterceptListen"},
	{PackagePath: "net", Receiver: connReceiver, Function: "Read", Hook: "gomadInterceptConnRead"},
	{PackagePath: "net", Receiver: connReceiver, Function: "Write", Hook: "gomadInterceptConnWrite"},
	{PackagePath: "net", Receiver: connReceiver, Function: "Close", Hook: "gomadInterceptConnClose"},
	{PackagePath: "net", Receiver: connReceiver, Function: "LocalAddr", Hook: "gomadInterceptConnLocalAddr"},
	{PackagePath: "net", Receiver: connReceiver, Function: "RemoteAddr", Hook: "gomadInterceptConnRemoteAddr"},
	{PackagePath: "net", Receiver: connReceiver, Function: "SetDeadline", Hook: "gomadInterceptConnSetDeadline"},
	{PackagePath: "net", Receiver: connReceiver, Function: "SetReadDeadline", Hook: "gomadInterceptConnSetReadDeadline"},
	{PackagePath: "net", Receiver: connReceiver, Function: "SetWriteDeadline", Hook: "gomadInterceptConnSetWriteDeadline"},
	{PackagePath: "net", Receiver: connReceiver, Function: "SetReadBuffer", Hook: "gomadInterceptConnSetReadBuffer"},
	{PackagePath: "net", Receiver: connReceiver, Function: "SetWriteBuffer", Hook: "gomadInterceptConnSetWriteBuffer"},
	{PackagePath: "net", Receiver: connReceiver, Function: "File", Hook: "gomadInterceptConnFile"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SyscallConn", Hook: "gomadInterceptTCPConnSyscallConn"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "CloseRead", Hook: "gomadInterceptTCPConnCloseRead"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "CloseWrite", Hook: "gomadInterceptTCPConnCloseWrite"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SetLinger", Hook: "gomadInterceptTCPConnSetLinger"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SetKeepAlive", Hook: "gomadInterceptTCPConnSetKeepAlive"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SetKeepAlivePeriod", Hook: "gomadInterceptTCPConnSetKeepAlivePeriod"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SetNoDelay", Hook: "gomadInterceptTCPConnSetNoDelay"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "MultipathTCP", Hook: "gomadInterceptTCPConnMultipathTCP"},
	{PackagePath: "net", Function: "dialTCP", Hook: "gomadInterceptDialTCP"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "SyscallConn", Hook: "gomadInterceptTCPListenerSyscallConn"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "AcceptTCP", Hook: "gomadInterceptTCPListenerAcceptTCP"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "Accept", Hook: "gomadInterceptTCPListenerAccept"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "Close", Hook: "gomadInterceptTCPListenerClose"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "Addr", Hook: "gomadInterceptTCPListenerAddr"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "SetDeadline", Hook: "gomadInterceptTCPListenerSetDeadline"},
	{PackagePath: "net", Receiver: tcpListenerReceiver, Function: "File", Hook: "gomadInterceptTCPListenerFile"},
	{PackagePath: "net", Function: "ListenTCP", Hook: "gomadInterceptListenTCP"},
	{PackagePath: "net", Receiver: tcpConnReceiver, Function: "SetKeepAliveConfig", Hook: "gomadInterceptTCPConnSetKeepAliveConfig"},
	{PackagePath: "gomadv3.test/intercept", Function: "Function", Hook: "gomadInterceptFunction"},
	{PackagePath: "gomadv3.test/intercept", Function: "Notify", Hook: "gomadInterceptNotify"},
	{
		PackagePath: "gomadv3.test/intercept",
		Receiver:    &receiverSpec{Name: "Value", Pointer: true},
		Function:    "Add",
		Hook:        "gomadInterceptValueAdd",
	},
	{PackagePath: "gomadv3.test/interceptfail/missing_target", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/missing_hook", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/bad_parameter", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/bad_result", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/bad_handled", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/duplicate_target", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/duplicate_target", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/bodyless_target", Function: "Target", Hook: "Hook"},
	{PackagePath: "gomadv3.test/interceptfail/variadic", Function: "Target", Hook: "Hook"},
}
