import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { root, out, worker, read, sha, sources } from './capture.mjs';
import { named, reconstruct, staticNarrow, walk } from '../source-acceptance-20261008/proof.mjs';
const json = (dir, label) => JSON.parse(readFileSync(resolve(dir, label + '.json')));
const freeze = json(worker, 'freeze');
assert.equal(freeze.files.length, 144);
assert.deepEqual(walk(worker).map(p => p.slice(worker.length + 1)).sort(), [...freeze.files.map(e => e.name), 'freeze.json'].sort());
for (const entry of freeze.files) {
  const bytes = read(resolve(worker, entry.name));
  assert.equal(bytes.length, entry.bytes);
  assert.equal(sha(bytes), entry.sha256);
}
const cliPath = 'tools/gomad3/cmd/gomad/internal/cli/cli.go';
const cli = read(cliPath).toString(), original = reconstruct();
const oldCli = read(resolve(out, 'writer-negative-cli.go')).toString();
const originalHelper = named(original.images[cliPath], 'reportExploreFailure').body;
const currentHelper = named(cli, 'reportExploreFailure').body;
assert.equal(currentHelper, originalHelper);
assert.equal(oldCli.replace(named(oldCli, 'reportExploreFailure').body, currentHelper), cli);
assert.equal(sha(oldCli), '2552263399fc975fd5a8c2e125f30f8494bf74a6da8b7e19e27138382ec5a277');
const final = json(worker, 'source-proof-final');
assert.equal(final.source_identity_sha256, sha(JSON.stringify(sources())));
assert.equal(final.restoration.original_function_sha256, sha(currentHelper));
const baseline = json(worker, 'sources-current');
for (const [path, hash] of Object.entries(baseline)) if (path !== cliPath) assert.equal(sha(read(path)), hash, path);
const current = sources(), known = new Set([...Object.keys(baseline), 'tools/gomad3/cmd/gomad/internal/cli/explore_failure_writer_test.go']);
assert(Object.keys(current).every(p => known.has(p)), 'Unexpected new source input');
const labels = ['worker-integrity', 'writer-negative-control', 'restored-portable-cli', 'restored-portable-runner', 'restored-architecture-installation', 'restored-qualification-control', 'restored-generators', 'restored-errortype', 'restored-format-check', 'restored-fast-lint', 'restored-unfiltered-lint'];
const receipts = labels.map(label => {
  const receipt = json(out, label), expected = label === 'writer-negative-control' ? 1 : label.endsWith('lint') ? 2 : 0;
  assert.equal(receipt.exit, expected, label);
  assert.equal(receipt.signal, null);
  assert.equal(receipt.error, null);
  assert.deepEqual(receipt.source_changes, []);
  assert.equal(receipt.sources_before_sha256, receipt.sources_after_sha256);
  assert.equal(receipt.sources_after_sha256, sha(JSON.stringify(current)));
  assert.equal(receipt.stdout_sha256, sha(read(resolve(out, label + '.stdout'))));
  assert.equal(receipt.stderr_sha256, sha(read(resolve(out, label + '.stderr'))));
  return { label, sha256: sha(read(resolve(out, label + '.json'))), exit: receipt.exit };
});
const testLabels = labels.filter(l => /^restored-(portable|architecture|qualification)/.test(l));
const terminal = x => x.tests.map(t => JSON.stringify(t)).sort();
for (const label of testLabels) assert.deepEqual(terminal(json(out, label)), terminal(json(worker, label)), label);
const tests = testLabels.flatMap(label => json(out, label).tests), top = tests.filter(t => !t.test.includes('/'));
assert.equal(top.length, 139);
assert(top.every(t => t.action === 'pass'));
assert.equal(new Set(top.map(t => t.package + ' ' + t.test)).size, 139);
const negative = json(out, 'writer-negative-control');
assert.deepEqual(negative.top_level_counts, { pass: 0, fail: 1, skip: 0 });
assert.equal(negative.tests.filter(t => t.action === 'fail').length, 3);
assert(negative.tests.every(t => t.action === 'fail' && t.test.startsWith('TestExploreErrorJoinsDiagnosticAndReporterWriterFailures')));
const negativeOutput = read(resolve(out, 'writer-negative-control.stdout')).toString();
assert(negativeOutput.includes('diagnostic write failed'));
const passNames = new Set(tests.filter(t => t.action === 'pass').map(t => t.test));
const mappings = final.characterization.functions.flatMap(f => f.retained_fn1129_mapping);
for (const row of mappings) assert(passNames.has(row[3]), 'Mapped assertion not freshly executed: ' + row[3]);
const unmatched = final.characterization.functions.filter(f => !f.exact && !f.retained_fn1129_mapping.length && f.unmatched_original_lines.length);
assert.deepEqual([...new Set(unmatched.map(f => f.test))].sort(), ['TestQualifyGrammarPreservesEnvironmentTagsAndTargetArguments', 'TestRunDoctorReportsAvailableContractAsJSON', 'TestRunDoctorReportsRepairCommandWhenToolchainIsMissing', 'TestRunExploreReportsFlagErrorsAsJSON']);
assert(unmatched.every(f => f.unmatched_original_lines.length === 1));
const lintRows = b => b.toString().split('\n').filter(l => /^tools\/gomad3\/[^:]+:\d+:\d+: .+ \([^)]+\)$/.test(l));
for (const label of ['restored-fast-lint', 'restored-unfiltered-lint']) assert.deepEqual(lintRows(read(resolve(out, label + '.stdout'))), lintRows(read(resolve(worker, label + '.stdout'))));
assert.equal(lintRows(read(resolve(out, 'restored-fast-lint.stdout'))).length, 66);
assert.equal(lintRows(read(resolve(out, 'restored-unfiltered-lint.stdout'))).length, 68);
const reconciliation = json(worker, 'lint-reconciliation');
assert.equal(new Set(reconciliation.bounded_unmatched.map(e => e.path + ':' + e.line)).size, 5);
assert.deepEqual(reconciliation.new_waivers, []);
assert.equal(reconciliation.restored_explore_helper_exact, true);
const staticBinding = staticNarrow();
assert.equal(staticBinding.unchanged_closure, 1219);
assert.equal(staticBinding.changed_unreused.length, 4);
const userFiles = [['.turbo/plans/gomad3-glossary-update.md', '97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188'], ['.turbo/technical-debt.md', 'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287']];
for (const [path, digest] of userFiles) assert.equal(sha(read(path)), digest);
const result = { task: 'fn-109-gomad-deepen-modules-and-tool-interfaces.5', readonly: true, no_go: true, source_identity_sha256: sha(JSON.stringify(current)), receipts, worker_evidence_sha256: sha(read(resolve(worker, 'evidence.json'))), worker_freeze_sha256: sha(read(resolve(worker, 'freeze.json'))), original_helper_restoration_sha256: sha(currentHelper), only_original_helper_and_additive_test_changed: true, fresh_portable_unique_pass: 139, fresh_portable_fail: 0, fresh_portable_skip: 0, negative_control_top_fail: 1, negative_control_subcase_fail: 2, mapped_assertion_terminal_bindings: [...new Set(mappings.map(r => r[3]))].sort(), unmapped_single_construction_seams: unmatched.map(f => ({ origin: f.origin, test: f.test, old: f.unmatched_original_lines })), static_binding: staticBinding, lint: { configured_fast: 66, unfiltered_cli: 51, unfiltered_runner: 17, reconciliation_sha256: sha(read(resolve(worker, 'lint-reconciliation.json'))), generic_exceptions: [], global_green: false }, native: false, full_host_pass: false };
if (process.argv[2]) writeFileSync(resolve(out, process.argv[2]), JSON.stringify(result, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify({ readonly: true, portable_pass: 139, negative_control_fail: 1, fast_lint: 66, scoped_lint: 68, unchanged_closure: 1219, native: false }));
