const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');
const crypto = require('node:crypto');
const os = require('node:os');
const repo = '/Users/stephan/Workspace/skunkworks/gomad/temporal';
const goBin = '/home/agent/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.27.1.linux-arm64/bin';
const env = {...process.env, PATH: goBin + ':/usr/local/bin:/usr/bin:/bin', GOENV: 'off', GOWORK: 'off', GOTOOLCHAIN: 'local', GOPROXY: 'off', GOSUMDB: 'off', GOFLAGS: '', GOMAXPROCS: '2'};
for (const key of ['GOMADSEED', 'GOMAD3_CHILD_SEED', 'GOMAD3_SEED']) delete env[key];
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const fileHash = file => hash(fs.readFileSync(file));
const git = (...args) => cp.execFileSync('git', args, {cwd: repo, encoding: 'utf8'});
const files = [...new Set(git('ls-files', '-z', 'tools/gomad3').split('\0').filter(Boolean).concat('tools/gomad3/target/adapter_source_set_test.go', '.github/.golangci.yml', 'Makefile'))].sort();
const tools = [goBin + '/go', goBin + '/gofmt', '/tmp/fn109-lint-tools.ZdNe1t50/golangci-lint-v2.13.0', '/tmp/fn109-lint-tools.ZdNe1t50/errortype', '/usr/bin/node'];
const snapshot = () => ({head: git('rev-parse', 'HEAD').trim(), source_count: files.length, source_manifest_sha256: hash(files.map(f => f + '\0' + fileHash(path.join(repo, f)) + '\n').join('')), edited_sources: Object.fromEntries(['tools/gomad3/target/adapter_source_set.go', 'tools/gomad3/target/adapter_source_set_test.go', 'tools/gomad3/ARCHITECTURE.md'].map(f => [f, fileHash(path.join(repo, f))])), tools: Object.fromEntries(tools.map(f => [f, fileHash(f)])), runner_sha256: fileHash(__filename)});
const [label, relativeCwd, command, ...args] = process.argv.slice(2);
if (!label || !relativeCwd || !command || !/^[a-z0-9-]+$/.test(label)) throw Error('usage: root-checks.cjs label relative-cwd command args');
const output = path.join(__dirname, label);
fs.mkdirSync(output);
const cwd = path.resolve(repo, relativeCwd);
const before = snapshot(), started = new Date().toISOString(), clock = process.hrtime.bigint();
const executable = command.includes('/') ? command : env.PATH.split(':').map(p => path.join(p, command)).find(p => fs.existsSync(p));
const executableHash = fileHash(executable);
const result = cp.spawnSync(executable, args, {cwd, env, timeout: 900000, killSignal: 'SIGKILL', maxBuffer: 64 * 1024 * 1024});
const stdout = result.stdout || Buffer.alloc(0), stderr = result.stderr || Buffer.alloc(0);
const after = snapshot();
const receipt = {command: [executable, ...args], cwd, started, finished: new Date().toISOString(), elapsed_ms: Number(process.hrtime.bigint() - clock) / 1e6, status: result.status, signal: result.signal, error: result.error?.message, host: {platform: os.platform(), arch: os.arch(), release: os.release()}, environment: Object.fromEntries(['PATH', 'GOENV', 'GOWORK', 'GOTOOLCHAIN', 'GOPROXY', 'GOSUMDB', 'GOFLAGS', 'GOMAXPROCS', 'GOMODCACHE', 'GOCACHE', 'GOROOT', 'GOEXPERIMENT', 'CGO_ENABLED'].map(k => [k, env[k] ?? null])), unset: ['GOMADSEED', 'GOMAD3_CHILD_SEED', 'GOMAD3_SEED'], executable_sha256: executableHash, executable_unchanged: executableHash === fileHash(executable), before, after, inputs_unchanged: JSON.stringify(before) === JSON.stringify(after), stdout_sha256: hash(stdout), stderr_sha256: hash(stderr)};
for (const [name, data] of [['stdout.txt', stdout], ['stderr.txt', stderr], ['receipt.json', JSON.stringify(receipt, null, 2) + '\n']]) fs.writeFileSync(path.join(output, name), data, {flag: 'wx'});
console.log(JSON.stringify({label, status: receipt.status, signal: receipt.signal, elapsed_ms: receipt.elapsed_ms, inputs_unchanged: receipt.inputs_unchanged}));
if (!receipt.inputs_unchanged) throw Error('source or tool changed during command');
process.exit(result.status === null ? 2 : result.status);
