// Code generated by umpire3-export; DO NOT EDIT.

package protocol

type SemanticTypeID string

const (
	SemanticTypeIDString      SemanticTypeID = "string"
	SemanticTypeIDInteger     SemanticTypeID = "integer"
	SemanticTypeIDBoolean     SemanticTypeID = "boolean"
	SemanticTypeIDDuration    SemanticTypeID = "duration"
	SemanticTypeIDEnum        SemanticTypeID = "enum"
	SemanticTypeIDBytesDigest SemanticTypeID = "bytes-digest"
	SemanticTypeIDIdentity    SemanticTypeID = "identity"
	SemanticTypeIDList        SemanticTypeID = "list"
	SemanticTypeIDRecord      SemanticTypeID = "record"
)

const (
	CapabilityIDNexus               CapabilityID = "nexus"
	CapabilityIDNexusWorkerControl  CapabilityID = "nexus-worker-control"
	CapabilityIDNexusObservation    CapabilityID = "nexus-observation"
	CapabilityIDFailoverControl     CapabilityID = "failover-control"
	CapabilityIDUpdate              CapabilityID = "update"
	CapabilityIDWorkflowTaskControl CapabilityID = "workflow-task-control"
	CapabilityIDHistoryObservation  CapabilityID = "history-observation"
	CapabilityIDFaultRpc            CapabilityID = "fault-rpc"
	CapabilityIDFaultProcess        CapabilityID = "fault-process"
	CapabilityIDFaultNetwork        CapabilityID = "fault-network"
	CapabilityIDFaultClock          CapabilityID = "fault-clock"
	CapabilityIDFaultPersistence    CapabilityID = "fault-persistence"
)

type ActionKind string

const (
	ActionKindScheduleOperation             ActionKind = "schedule-operation"
	ActionKindDispatchTask                  ActionKind = "dispatch-task"
	ActionKindWorkerReturnsSuccess          ActionKind = "worker-returns-success"
	ActionKindRequestCancellation           ActionKind = "request-cancellation"
	ActionKindCommitCancellation            ActionKind = "commit-cancellation"
	ActionKindPersistSuccess                ActionKind = "persist-success"
	ActionKindRetryTask                     ActionKind = "retry-task"
	ActionKindAcquireOwnership              ActionKind = "acquire-ownership"
	ActionKindCrashOwner                    ActionKind = "crash-owner"
	ActionKindRecoverOwner                  ActionKind = "recover-owner"
	ActionKindAckTask                       ActionKind = "ack-task"
	ActionKindStartUpdate                   ActionKind = "start-update"
	ActionKindAcceptUpdate                  ActionKind = "accept-update"
	ActionKindCompleteUpdate                ActionKind = "complete-update"
	ActionKindRecordUpdateHistory           ActionKind = "record-update-history"
	ActionKindDispatchWorkflowTask          ActionKind = "dispatch-workflow-task"
	ActionKindCompleteWorkflowTask          ActionKind = "complete-workflow-task"
	ActionKindEnqueueWorkflowTask           ActionKind = "enqueue-workflow-task"
	ActionKindDeliverWorkflowTask           ActionKind = "deliver-workflow-task"
	ActionKindAcknowledgeWorkflowTask       ActionKind = "acknowledge-workflow-task"
	ActionKindCreateSpeculativeWorkflowTask ActionKind = "create-speculative-workflow-task"
	ActionKindCommitSpeculativeWorkflowTask ActionKind = "commit-speculative-workflow-task"
	ActionKindCloseNexusOperation           ActionKind = "close-nexus-operation"
	ActionKindLinkNexusActivity             ActionKind = "link-nexus-activity"
	ActionKindTimeoutNexusOperation         ActionKind = "timeout-nexus-operation"
	ActionKindRegisterCallback              ActionKind = "register-callback"
	ActionKindRecordCallbackResponse        ActionKind = "record-callback-response"
	ActionKindDispatchAssuranceWorkflowTask ActionKind = "dispatch-assurance-workflow-task"
	ActionKindProgressEntity                ActionKind = "progress-entity"
	ActionKindContinueWorkflow              ActionKind = "continue-workflow"
	ActionKindResetWorkflow                 ActionKind = "reset-workflow"
	ActionKindRouteWorkflowTask             ActionKind = "route-workflow-task"
	ActionKindFenceWorkflowOwner            ActionKind = "fence-workflow-owner"
)

type EntityKind string

const (
	EntityKindNexusOperation    EntityKind = "nexus-operation"
	EntityKindNexusWorker       EntityKind = "nexus-worker"
	EntityKindWorkflow          EntityKind = "workflow"
	EntityKindWorkflowUpdate    EntityKind = "workflow-update"
	EntityKindWorkflowTask      EntityKind = "workflow-task"
	EntityKindNamespace         EntityKind = "namespace"
	EntityKindTaskQueue         EntityKind = "task-queue"
	EntityKindWorkflowRun       EntityKind = "workflow-run"
	EntityKindActivity          EntityKind = "activity"
	EntityKindActivityExecution EntityKind = "activity-execution"
	EntityKindCallback          EntityKind = "callback"
)

type RelationID string

const (
	RelationIDTaskDeliveryCurrentCompletion RelationID = "task-delivery.current-completion"
	RelationIDNamespaceContainsTaskQueue    RelationID = "namespace.contains-task-queue"
	RelationIDWorkflowHasRun                RelationID = "workflow.has-run"
	RelationIDWorkflowRunUsesTaskQueue      RelationID = "workflow-run.uses-task-queue"
	RelationIDWorkflowRunHasTask            RelationID = "workflow-run.has-task"
	RelationIDWorkflowRunHasActivity        RelationID = "workflow-run.has-activity"
	RelationIDActivityHasExecution          RelationID = "activity.has-execution"
	RelationIDNexusOperationLinksActivity   RelationID = "nexus-operation.links-activity"
	RelationIDNexusOperationHasCallback     RelationID = "nexus-operation.has-callback"
	RelationIDWorkflowRunHasCallback        RelationID = "workflow-run.has-callback"
	RelationIDWorkflowRunContinuesAs        RelationID = "workflow-run.continues-as"
)

type ObservationID string

const (
	ObservationIDCancellationAccepted             ObservationID = "cancellation-accepted"
	ObservationIDCancellationWon                  ObservationID = "cancellation-won"
	ObservationIDStaleSuccessAbsent               ObservationID = "stale-success-absent"
	ObservationIDUpdateAccepted                   ObservationID = "update-accepted"
	ObservationIDUpdateCompleted                  ObservationID = "update-completed"
	ObservationIDWorkflowTaskAcknowledged         ObservationID = "workflow-task-acknowledged"
	ObservationIDSpeculativeTaskValid             ObservationID = "speculative-task-valid"
	ObservationIDNexusOperationClosed             ObservationID = "nexus-operation-closed"
	ObservationIDNexusActivityLinksConsistent     ObservationID = "nexus-activity-links-consistent"
	ObservationIDNexusTimeoutValid                ObservationID = "nexus-timeout-valid"
	ObservationIDCallbackReferenceValid           ObservationID = "callback-reference-valid"
	ObservationIDCallbackResponseConsistent       ObservationID = "callback-response-consistent"
	ObservationIDWorkflowTaskNotStarved           ObservationID = "workflow-task-not-starved"
	ObservationIDEntityProgressed                 ObservationID = "entity-progressed"
	ObservationIDWorkflowContinuationLineageValid ObservationID = "workflow-continuation-lineage-valid"
	ObservationIDWorkflowResetLineageValid        ObservationID = "workflow-reset-lineage-valid"
	ObservationIDWorkflowRoutingIsolated          ObservationID = "workflow-routing-isolated"
	ObservationIDWorkflowOwnershipFenced          ObservationID = "workflow-ownership-fenced"
)

type EvidenceID string

const (
	EvidenceIDSourceSequence  EvidenceID = "source-sequence"
	EvidenceIDCausal          EvidenceID = "causal"
	EvidenceIDIdentityLineage EvidenceID = "identity-lineage"
)

type PropertyID string

const (
	PropertyIDNexusCancellationWonExcludesSuccess           PropertyID = "nexus.cancellation.won-excludes-success"
	PropertyIDWorkflowUpdateAcceptedCompletesThroughHistory PropertyID = "workflow-update.accepted-completes-through-history"
	PropertyIDTaskDeliveryAcknowledgedRemovesBacklog        PropertyID = "task-delivery.acknowledged-removes-backlog"
	PropertyIDWorkflowTaskSpeculativeCreation               PropertyID = "workflow-task.speculative-creation"
	PropertyIDNexusOperationClosure                         PropertyID = "nexus-operation.closure"
	PropertyIDNexusActivityLinkConsistency                  PropertyID = "nexus-activity.link-consistency"
	PropertyIDNexusOperationTimeoutSemantics                PropertyID = "nexus-operation.timeout-semantics"
	PropertyIDCallbackReferenceConsistency                  PropertyID = "callback.reference-consistency"
	PropertyIDCallbackResponseConsistency                   PropertyID = "callback.response-consistency"
	PropertyIDWorkflowTaskStarvation                        PropertyID = "workflow-task.starvation"
	PropertyIDEntityProgress                                PropertyID = "entity.progress"
	PropertyIDWorkflowRunContinuationLineage                PropertyID = "workflow-run.continuation-lineage"
	PropertyIDWorkflowRunResetLineage                       PropertyID = "workflow-run.reset-lineage"
	PropertyIDWorkflowTaskRoutingIsolation                  PropertyID = "workflow-task.routing-isolation"
	PropertyIDWorkflowTaskOwnershipFencing                  PropertyID = "workflow-task.ownership-fencing"
)

type PolicyKind string

const (
	PolicyKindDuring PolicyKind = "during"
)

type FaultKind string

const (
	FaultKindStaleWorkerCompletion FaultKind = "stale-worker-completion"
	FaultKindDrop                  FaultKind = "drop"
	FaultKindDelay                 FaultKind = "delay"
	FaultKindDuplicate             FaultKind = "duplicate"
	FaultKindReorder               FaultKind = "reorder"
	FaultKindHoldRelease           FaultKind = "hold-release"
	FaultKindRejection             FaultKind = "rejection"
	FaultKindProcessCrash          FaultKind = "process-crash"
	FaultKindRestart               FaultKind = "restart"
	FaultKindPartition             FaultKind = "partition"
	FaultKindFailover              FaultKind = "failover"
	FaultKindClockSkew             FaultKind = "clock-skew"
	FaultKindPersistenceError      FaultKind = "persistence-error"
)

type ModuleID string

const (
	ModuleIDTemporalProductNexus                ModuleID = "Temporal.Product.Nexus"
	ModuleIDTemporalSystemNexusTasks            ModuleID = "Temporal.System.NexusTasks"
	ModuleIDTemporalRefinementNexusTasks        ModuleID = "Temporal.Refinement.NexusTasks"
	ModuleIDTemporalProductUpdate               ModuleID = "Temporal.Product.Update"
	ModuleIDTemporalSystemUpdateTasks           ModuleID = "Temporal.System.UpdateTasks"
	ModuleIDTemporalRefinementUpdateTasks       ModuleID = "Temporal.Refinement.UpdateTasks"
	ModuleIDTemporalSystemTaskDelivery          ModuleID = "Temporal.System.TaskDelivery"
	ModuleIDTemporalProductTaskAck              ModuleID = "Temporal.Product.TaskAck"
	ModuleIDTemporalProductNexusLifecycle       ModuleID = "Temporal.Product.NexusLifecycle"
	ModuleIDTemporalProductNexusClosure         ModuleID = "Temporal.Product.NexusClosure"
	ModuleIDTemporalSystemNexusClosure          ModuleID = "Temporal.System.NexusClosure"
	ModuleIDTemporalRefinementNexusClosure      ModuleID = "Temporal.Refinement.NexusClosure"
	ModuleIDTemporalProductNexusTimeout         ModuleID = "Temporal.Product.NexusTimeout"
	ModuleIDTemporalSystemNexusTimeout          ModuleID = "Temporal.System.NexusTimeout"
	ModuleIDTemporalRefinementNexusTimeout      ModuleID = "Temporal.Refinement.NexusTimeout"
	ModuleIDTemporalProductNexusActivityLink    ModuleID = "Temporal.Product.NexusActivityLink"
	ModuleIDTemporalSystemNexusActivityLink     ModuleID = "Temporal.System.NexusActivityLink"
	ModuleIDTemporalRefinementNexusActivityLink ModuleID = "Temporal.Refinement.NexusActivityLink"
	ModuleIDTemporalProductCallbackReference    ModuleID = "Temporal.Product.CallbackReference"
	ModuleIDTemporalSystemCallbackReference     ModuleID = "Temporal.System.CallbackReference"
	ModuleIDTemporalRefinementCallbackReference ModuleID = "Temporal.Refinement.CallbackReference"
	ModuleIDTemporalProductCallbackResponse     ModuleID = "Temporal.Product.CallbackResponse"
	ModuleIDTemporalSystemCallbackResponse      ModuleID = "Temporal.System.CallbackResponse"
	ModuleIDTemporalRefinementCallbackResponse  ModuleID = "Temporal.Refinement.CallbackResponse"
	ModuleIDTemporalProductWorkflowLineage      ModuleID = "Temporal.Product.WorkflowLineage"
	ModuleIDTemporalSystemWorkflowLineage       ModuleID = "Temporal.System.WorkflowLineage"
	ModuleIDTemporalRefinementWorkflowLineage   ModuleID = "Temporal.Refinement.WorkflowLineage"
	ModuleIDTemporalProductWorkflowRouting      ModuleID = "Temporal.Product.WorkflowRouting"
	ModuleIDTemporalSystemWorkflowRouting       ModuleID = "Temporal.System.WorkflowRouting"
	ModuleIDTemporalRefinementWorkflowRouting   ModuleID = "Temporal.Refinement.WorkflowRouting"
	ModuleIDTemporalProductWorkflowOwnership    ModuleID = "Temporal.Product.WorkflowOwnership"
	ModuleIDTemporalSystemWorkflowOwnership     ModuleID = "Temporal.System.WorkflowOwnership"
	ModuleIDTemporalRefinementWorkflowOwnership ModuleID = "Temporal.Refinement.WorkflowOwnership"
	ModuleIDTemporalProductSpeculativeTask      ModuleID = "Temporal.Product.SpeculativeTask"
	ModuleIDTemporalSystemSpeculativeTask       ModuleID = "Temporal.System.SpeculativeTask"
	ModuleIDTemporalRefinementSpeculativeTask   ModuleID = "Temporal.Refinement.SpeculativeTask"
	ModuleIDTemporalProductWorkflowProgress     ModuleID = "Temporal.Product.WorkflowProgress"
	ModuleIDTemporalSystemWorkflowProgress      ModuleID = "Temporal.System.WorkflowProgress"
	ModuleIDTemporalRefinementWorkflowProgress  ModuleID = "Temporal.Refinement.WorkflowProgress"
)

type TargetID string

const (
	TargetIDNexusCancellation                  TargetID = "nexus-cancellation"
	TargetIDWorkflowUpdateLifecycle            TargetID = "workflow-update-lifecycle"
	TargetIDFoundationBacklogAck               TargetID = "foundation-backlog-ack"
	TargetIDFeatureNexus                       TargetID = "feature-nexus"
	TargetIDFeatureWorkflowSpeculativeDelivery TargetID = "feature-workflow-speculative-delivery"
	TargetIDFoundationDeliverySafety           TargetID = "foundation-delivery-safety"
	TargetIDFoundationOwnershipFencing         TargetID = "foundation-ownership-fencing"
	TargetIDFoundationRoutingIsolation         TargetID = "foundation-routing-isolation"
	TargetIDIntegrationActivityDelivery        TargetID = "integration-activity-delivery"
	TargetIDIntegrationCallbackNexus           TargetID = "integration-callback-nexus"
	TargetIDIntegrationCallbackWorkflow        TargetID = "integration-callback-workflow"
	TargetIDIntegrationNexusActivity           TargetID = "integration-nexus-activity"
	TargetIDIntegrationNexusTimeout            TargetID = "integration-nexus-timeout"
	TargetIDIntegrationWorkflowDelivery        TargetID = "integration-workflow-delivery"
	TargetIDProtocolAtomic                     TargetID = "protocol-atomic"
)
