direction: right

Wrapper: {
	label: ""
	style.fill: transparent

	Loop: {
		label: "loop"
		style.text-transform: lowercase

		Server -> Worker: Workflow Task
		Worker -> Server: Command
	}
	Starter -> Loop.Server: Start Workflow
	Starter <- Loop.Server: Complete Workflow
}
