version: '3'

output: prefixed

vars:
  # GOMAD: go run github.com/temporalio/gomad/cmd/gomad
  GOMAD: $(pwd)/.gomad/gomadtool
  SIMPACKAGES: ./internal/tests/behavior ./nemesis

tasks:
  fix-fmt:
    cmds:
      - .ci/gofmt fix

  check-fmt:
    cmds:
      - .ci/gofmt check

  go-generate:
    cmds:
      - go generate ./...

  gomad-tool:
    run: once
    cmds:
      - mkdir -p ./.gomad && go build -o ./.gomad/gomadtool ./cmd/gomad

  gomad-prepare-selftest:
    run: once
    cmds:
      - "{{.GOMAD}} prepare-selftest"
    deps:
      - gomad-tool

  go-test:
    cmds:
      - "{{.GOMAD}} build-tests {{.SIMPACKAGES}}"
      - go test -ldflags=-checklinkname=0 -tags=linkname ./...
    deps:
      - gomad-tool
      - gomad-prepare-selftest

  go-race-test:
    cmds:
      - "{{.GOMAD}} build-tests -race {{.SIMPACKAGES}} ./internal/tests/race/testdata"
      # todo: get rid of this janky thing???
      - go test -ldflags=-checklinkname=0 -tags=linkname -race ./...
    deps:
      - gomad-tool
      - gomad-prepare-selftest

  test:
    deps:
      - check-fmt
      - go-test
      - go-race-test

