// Code generated by "stringer -type=checksumKey"; DO NOT EDIT.

package gosimruntime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[checksumKeyRunPick-0]
	_ = x[checksumKeyRunResult-1]
	_ = x[checksumKeyLogWrite-2]
	_ = x[checksumKeyCreating-3]
	_ = x[checksumKeyRunStarted-4]
	_ = x[checksumKeyRunFinished-5]
	_ = x[checksumKeyTimeNow-6]
}

const _checksumKey_name = "checksumKeyRunPickchecksumKeyRunResultchecksumKeyLogWritechecksumKeyCreatingchecksumKeyRunStartedchecksumKeyRunFinishedchecksumKeyTimeNow"

var _checksumKey_index = [...]uint8{0, 18, 38, 57, 76, 97, 119, 137}

func (i checksumKey) String() string {
	if i >= checksumKey(len(_checksumKey_index)-1) {
		return "checksumKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _checksumKey_name[_checksumKey_index[i]:_checksumKey_index[i+1]]
}
