// The lifter reads TASTy, so its compiler must be at least as new as the one that compiled
// ../scala. Its IR classes are generated by ../gen.sh; the JDK and scala-cli come from mise.toml.
//> using scala 3.9.0
//> using options -deprecation -feature -unchecked -Wunused:imports
//> using dep org.scala-lang::scala3-tasty-inspector:3.9.0
//> using dep com.google.protobuf:protobuf-java:4.29.5
//> using dep com.google.protobuf:protobuf-java-util:4.29.5
//> using jar ../gen/ir-proto.jar
