import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = '/Users/stephan/Workspace/skunkworks/gomad/temporal';
const artifacts = dirname(fileURLToPath(import.meta.url));
const toolchain = '/home/agent/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.27.1.linux-arm64/bin';
const env = { ...process.env, PATH: toolchain + ':/usr/local/bin:/usr/bin:/bin', GOENV: 'off', GOWORK: 'off', GOTOOLCHAIN: 'local', GOPROXY: 'off', GOSUMDB: 'off', GOFLAGS: '', GOMAXPROCS: '2' };
for (const name of ['GOMADSEED', 'GOMAD3_CHILD_SEED', 'GOMAD3_SEED']) delete env[name];
const [label, cwd, command, ...args] = process.argv.slice(2);
const hash = path => createHash('sha256').update(readFileSync(path)).digest('hex');
const pins = ['tools/gomad3/internal/compatibilitypack/schema.go', 'tools/gomad3/internal/compatibilitypack/mutation_test.go', 'tools/gomad3/internal/compatibilitypack/schema_timezone_test.go', 'tools/gomad3/go.mod', 'tools/gomad3/go.sum', '.github/.golangci.yml'];
const binaries = [toolchain + '/go', toolchain + '/gofmt', '/tmp/fn109-lint-tools.ZdNe1t50/golangci-lint-v2.13.0', '/tmp/fn109-lint-tools.ZdNe1t50/errortype', '/usr/bin/node'];
const identities = () => ({ files: Object.fromEntries(pins.map(path => [path, hash(resolve(root, path))])), binaries: Object.fromEntries(binaries.map(path => [path, hash(path)])) });
const git = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' });
if (git.status !== 0) throw new Error(git.stderr);
const before = identities();
const started_at = new Date().toISOString();
const start = performance.now();
const result = spawnSync(command, args, { cwd: resolve(root, cwd), env, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
const elapsed_seconds = (performance.now() - start) / 1000;
const events = (result.stdout || '').split('\n').flatMap(line => { try { const event = JSON.parse(line); return event?.Action ? [event] : []; } catch { return []; } });
const test_counts = Object.fromEntries(['pass', 'fail', 'skip'].map(action => [action, events.filter(event => event.Action === action && event.Test).length]));
const skips = events.filter(event => event.Action === 'skip').map(event => ({ package: event.Package, test: event.Test }));
const after = identities();
const output = { head: git.stdout.trim(), command: [command, ...args], cwd: resolve(root, cwd), started_at, finished_at: new Date().toISOString(), elapsed_seconds, exit_code: result.status, signal: result.signal, error: result.error?.message, before, after, test_counts, skips, stdout: result.stdout, stderr: result.stderr };
writeFileSync(resolve(artifacts, label + '.json'), JSON.stringify(output, null, 2) + '\n');
console.log(JSON.stringify({ label, exit_code: result.status, elapsed_seconds, unchanged_inputs: JSON.stringify(before) === JSON.stringify(after), test_counts, skips }));
if (result.status !== 0 && !events.length) console.log((result.stdout || '') + (result.stderr || ''));
process.exitCode = result.status ?? 1;
