import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = '/Users/stephan/Workspace/skunkworks/gomad/temporal';
const artifacts = dirname(fileURLToPath(import.meta.url));
const baseline = JSON.parse(readFileSync(resolve(artifacts, 'baseline.json')));
const final = JSON.parse(readFileSync(resolve(artifacts, 'final.json')));
const prefix = 'tools/gomad3/internal/compatibilitypack/';
const candidatePaths = ['schema.go', 'policy_exhaustive_test.go', 'schema_admission_test.go', 'external_test.go', 'authoring/request_test.go', 'authoring/generate_test.go'].map(path => prefix + path);
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const git = args => {
  const result = spawnSync('git', args, { cwd: root, encoding: 'utf8' });
  if (result.status !== 0) throw new Error(result.stderr);
  return result.stdout;
};
const original = path => git(['show', baseline.head + ':' + prefix + path]);
const current = path => readFileSync(resolve(root, prefix + path), 'utf8');
const checks = {};
const priorSchema = original('schema.go');
const start = priorSchema.indexOf('// unadmittableCapabilities');
const end = priorSchema.indexOf('\n\ntype Pack struct', start);
const finalSchema = current('schema.go');
const finalStart = finalSchema.indexOf('// unadmittableCapabilities');
const finalEnd = finalSchema.indexOf('\n\ntype Pack struct', finalStart);
checks.schema_only_admission_and_comment = priorSchema.slice(0, start) === finalSchema.slice(0, finalStart) && priorSchema.slice(end) === finalSchema.slice(finalEnd);
checks.schema_only_two_new_entries = finalSchema.includes('var unadmittableCapabilities = []string{"import:os/exec", "import:os/signal", "import:os/user", "import:plugin", "import:runtime/cgo"}');
const priorPolicy = original('policy_exhaustive_test.go');
checks.policy_only_two_authorized_expectations = current('policy_exhaustive_test.go') === priorPolicy.replace('{"import:plugin", ""}', '{"import:plugin", "compatibility pack rule 0: capability import:plugin is never admitted"}').replace('{"import:runtime/cgo", ""}', '{"import:runtime/cgo", "compatibility pack rule 0: capability import:runtime/cgo is never admitted"}');
const canonicalImport = '\n\t"go.temporal.io/server/tools/gomad3/internal/canonicaljson"';
const external = current('external_test.go');
checks.external_existing_bytes_preserved = external.slice(0, external.indexOf('\nfunc TestExternalPackAdmission')).replace('\n' + canonicalImport + '\n', '\n') === original('external_test.go');
const request = current('authoring/request_test.go');
checks.request_existing_bytes_preserved = request.slice(0, request.indexOf('\nfunc TestRequestAdmission')) + request.slice(request.indexOf('\nfunc validRequest()')) === original('authoring/request_test.go');
let generation = current('authoring/generate_test.go');
generation = generation.slice(0, generation.indexOf('\nfunc TestGenerateAdmission'));
for (const added of ['fmt', 'io/fs', 'maps', 'slices', 'strings']) generation = generation.replace('\n\t"' + added + '"', '');
generation = generation.replace('\n' + canonicalImport + '\n\tcompatibility "go.temporal.io/server/tools/gomad3/internal/compatibilitypack"\n', '\n');
checks.generation_existing_bytes_preserved = generation === original('authoring/generate_test.go');
const changed = Object.keys(baseline.files).filter(path => baseline.files[path] !== final.files[path]);
checks.only_five_existing_candidate_files_changed = changed.length === 5 && changed.every(path => candidatePaths.includes(path));
checks.tool_binaries_unchanged = JSON.stringify(baseline.binaries) === JSON.stringify(final.binaries);
const protectedPaths = Object.keys(baseline.files).filter(path => !candidatePaths.includes(path));
const generatedPaths = protectedPaths.filter(path => /_generated\.|\/compatibilitypack\/(packs|requests|reports)\/|\/generation\.json$|\/version\/version\.json$/.test(path));
checks.protected_bytes_unchanged = protectedPaths.every(path => baseline.files[path] === final.files[path]);
checks.admission_source_matches_reviewed_base = git(['diff', '--name-only', '43d264e24cae659ed57b81b9028e14fccb5a1fa3', baseline.head, '--', 'tools/gomad3', '.github', 'Makefile', 'go.mod', 'go.sum', '.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-42']).trim() === '';
checks.generated_output_bytes_unchanged = generatedPaths.every(path => baseline.files[path] === final.files[path]);
const candidates = Object.fromEntries(candidatePaths.map(path => [path, hash(readFileSync(resolve(root, path)))]));
const redSources = JSON.parse(readFileSync(resolve(artifacts, 'red-sources.json'))).stdout.trim().split('\n').map(line => line.split(/\s+/));
checks.red_final_test_bytes_identical = redSources.filter(([, path]) => path !== prefix + 'schema.go').every(([digest, path]) => candidates[path] === digest);
const diffs = Object.fromEntries(candidatePaths.filter(path => existsSync(resolve(root, path))).map(path => [path, git(['diff', baseline.head, '--', path])]));
diffs[prefix + 'schema_admission_test.go'] = current('schema_admission_test.go');
const output = { captured_at: new Date().toISOString(), source_base: '43d264e24cae659ed57b81b9028e14fccb5a1fa3', admission: baseline.head, candidate_hashes: candidates, checks, changed, protected_count: protectedPaths.length, generated_or_pin_count: generatedPaths.length, generated_or_pin_paths: generatedPaths, diffs };
writeFileSync(resolve(artifacts, 'preservation-proof.json'), JSON.stringify(output, null, 2) + '\n');
console.log(JSON.stringify({ checks, changed, protected_count: protectedPaths.length, generated_or_pin_count: generatedPaths.length }));
if (Object.values(checks).some(value => !value)) process.exitCode = 1;
