import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),file='tools/gomad3/upgrade/upgrade_test.go',source=fs.readFileSync(file,'utf8');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const body=source.slice(source.indexOf('func writeUpgradeFixtureForPlatforms('),source.indexOf('func createArchive('));
const platform='["linux/arm64"]';
const unquote=literal=>literal.startsWith('`')?literal.slice(1,-1):JSON.parse(literal);
const patch=unquote(body.match(/patch := ("(?:\\.|[^"\\])*")/)[1]);
const manifestExpression=body.match(/manifest := ([^\n]+)/)[1];
const manifest=[...manifestExpression.matchAll(/`[^`]*`|"(?:\\.|[^"\\])*"|string\(platforms\)/g)].map(x=>x[0]==='string(platforms)'?platform:unquote(x[0])).join('');
JSON.parse(manifest);
const descriptorTemplate=body.match(/descriptor := fmt\.Sprintf\((`[\s\S]*?`), digest, platforms\)/)[1];
const descriptor=unquote(descriptorTemplate).replace('%x','0'.repeat(64)).replace('%s',platform);
JSON.parse(descriptor);
const literals=[{path:'toolchain/runtime/go1.26.4.patch',contents:patch},{path:'toolchain/runtime/overlay/src/os/gomad.go',contents:'package os\n'},{path:'deterministicio/boundary/manifest.json',contents:manifest},{path:'expected-intercepts-go1.26.4.txt',contents:'os.OpenFile -> os.gomadInterceptOpenFile\n'},{path:'toolchain/version/version.json',contents:descriptor},{path:'evidence prior dossier (layout varies by subcase)',contents:'{"prior":"complete dossier"}\n'}].map(({path,contents})=>({path,bytes:Buffer.byteLength(contents)}));
const command=(...args)=>{const r=spawnSync(args[0],args.slice(1),{encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);return r.stdout;};
const result={original_source:{path:file,sha256:hash(source)},dynamic_peak_measurement_available:false,dynamic_peak_limitation:'The original and instrumented test fixtures were removed by their unchanged checked cleanup; the admitted instrumentation measured prior-file metadata/hash, not entire-tree peak bytes. No further test was run to obtain a missing measurement.',source_derived_literal_sizes:literals,source_derived_literal_total_bytes:literals.reduce((sum,x)=>sum+x.bytes,0),archive:{path:'.toolchain/downloads/go1.26.4.src.tar.gz',files_in_tar:1,source_bytes:16,uncompressed_tar_bytes:2048,compressed_bytes_not_observed:true},source_derived_file_bound:{initial_fixture_files:6,prior_file:1,maximum_additional_staged_replacement:1,maximum_live_regular_files:8,conservative_data_budget_bytes:65536,note:'Conservative source-derived budget, not an observed dynamic maximum. The permission case creates no replacement when CreateTemp returns EACCES; the rename-refusal case can briefly hold one JSON dossier replacement.'},executables:[{path:'/bin/sh',arguments:['-c','printf failed-output; exit 23'],cwd:'synthetic fixture root',fixture_executable:false,output_destination:'hostexec pipes, bounded memory',note:'absolute external shell; printf is its builtin; no Go command, generator or fixture executable is launched by this exact parent'}],source_owners:['tools/gomad3/upgrade/upgrade.go','tools/gomad3/internal/hostfs/replace.go','tools/gomad3/internal/hostexec/command_unix.go'].map(path=>({path,sha256:hash(fs.readFileSync(path))})),tmpfs_mount:command('findmnt','-T','/dev/shm'),tmpfs_capacity:command('df','-B1','/dev/shm'),tmpfs_available_bytes:67108864,tmpfs_noexec:true,required_workspace_locations:{GOTMPDIR:'/Users/stephan/Workspace/skunkworks/.gomad-source-gates-UsyTMX',GOCACHE:'/Users/stephan/Workspace/skunkworks/.gomad-fn1129-cache-EseD1r',GOMODCACHE:'/Users/stephan/Workspace/skunkworks/.gomad-fn1132-module-cache-g4UAforc'},acceptance_relocation_admitted:false};
fs.writeFileSync(path.join(out,'upgrade-parent-fixture-budget.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({literal_bytes:result.source_derived_literal_total_bytes,max_files_source_bound:8,dynamic_peak:'not captured; no further test',tmpfs_available_bytes:result.tmpfs_available_bytes,executables:'/bin/sh outside fixture only'}));
