import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const out=path.dirname(new URL(import.meta.url).pathname),source='tools/gomad3/upgrade/upgrade_test.go';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const before=hash(fs.readFileSync(source)),mount=spawnSync('findmnt',['-T','/dev/shm'],{encoding:'utf8'}),capacity=fs.statfsSync('/dev/shm');
if(mount.status!==0 || !mount.stdout.includes('tmpfs') || !mount.stdout.includes('noexec') || capacity.bavail*capacity.bsize<65536)throw Error('tmpfs admission prerequisites absent');
const parent=fs.mkdtempSync('/dev/shm/gomad-fn1133-publication-'),stat=fs.statSync(parent);
if((stat.mode&0o777)!==0o700 || stat.uid!==process.getuid() || fs.readdirSync(parent).length!==0)throw Error('private parent admission failed');
const command='TMPDIR='+parent+' go -C tools/gomad3 test -tags test_dep -count=1 -json -p=1 -run="^TestRunReportsPublicationFailureAndKeepsPriorDossier$" ./upgrade';
const result=spawnSync('node',[path.join(out,'run.mjs'),'publication-parent-tmpfs',command,'any'],{stdio:'inherit'});
if(result.status!==0)throw Error('test harness failed');
const receipt=JSON.parse(fs.readFileSync(path.join(out,'publication-parent-tmpfs-receipt.json'))),events=fs.readFileSync(path.join(out,receipt.log),'utf8').trim().split('\n').map(JSON.parse);
const expected=['TestRunReportsPublicationFailureAndKeepsPriorDossier','TestRunReportsPublicationFailureAndKeepsPriorDossier/replacement_cannot_be_created','TestRunReportsPublicationFailureAndKeepsPriorDossier/parent_is_a_file','TestRunReportsPublicationFailureAndKeepsPriorDossier/replacement_cannot_be_renamed'];
const actual=events.filter(e=>e.Action==='pass'&&e.Test).map(e=>e.Test);
if(before!==hash(fs.readFileSync(source)))throw Error('original test changed');
const remaining=fs.readdirSync(parent);
if(remaining.length!==0)throw Error('tmpfs parent not empty after checked original cleanup: '+remaining);
fs.rmdirSync(parent);
if(fs.existsSync(parent))throw Error('private parent cleanup failed');
const binding={admission:'root exact original parent only; filesystem-separated source acceptance, no cause or repair claim',command,original_file:source,original_sha256:before,original_unchanged:true,overlay:null,parent,mode:'0700',uid:stat.uid,mount:mount.stdout,available_bytes:capacity.bavail*capacity.bsize,budget:'upgrade-parent-fixture-budget.json',effective_environment:{...receipt.environment,TMPDIR:parent},only_environment_difference:{TMPDIR:{before:receipt.environment.TMPDIR,after:parent}},GOTMPDIR_unchanged:true,build_tool_module_caches_unchanged:true,fixture_executables:false,absolute_child_executable:'/bin/sh',test_receipt:'publication-parent-tmpfs-receipt.json',expected_tests:expected,actual_passed_tests:actual,actual_counts:receipt.counts,original_permission_and_prior_bytes_assertions_unchanged:true,errno_observation_limit:'Original test asserts errors.Is(os.ErrPermission) and exact prior bytes, not a printed numeric Run errno. Separate same-filesystem primitive probe records EACCES. No syscall trace or numeric Run errno is claimed.',observed_post_test_entries:remaining,checked_empty_and_removed:true,peak_fixture_footprint_not_observed:true};
fs.writeFileSync(path.join(out,'publication-parent-tmpfs-binding.json'),JSON.stringify(binding,null,2)+'\n');
if(receipt.exit_code!==0||receipt.counts.fail!==0||receipt.counts.skip!==0||JSON.stringify([...actual].sort())!==JSON.stringify([...expected].sort()))throw Error('original parent did not fully pass');
console.log(JSON.stringify({actual_counts:receipt.counts,original_unchanged:true,parent_removed:true,only_changed_input:'exact-parent TMPDIR'}));
