import Umpire.Search.Tests.Artifacts
import Umpire.Search.Tests.CaseAnalysis
import Umpire.Search.Tests.Enumeration
import Umpire.Search.Tests.KnownGaps
import Umpire.Search.Tests.Outcomes
import Umpire.Search.Tests.Endpoints
import Umpire.Search.SemanticsImportTests
import Umpire.Search.Tests.Parameterized
import Umpire.Search.Tests.Admission
import Umpire.Search.Tests.Product
import Umpire.Search.Tests.Monitor
import Umpire.Search.Tests.BackendVeil
import Umpire.Search.Tests.Replay
import Umpire.Search.Tests.Differential
