import assert from 'node:assert/strict';
import {existsSync,readdirSync,statSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {root,out,read,sha,git,sources,board,write} from './capture.mjs';
import {apply,patchImages} from '../../task-2/source-acceptance-20261008/owner-chain.mjs';
import {spans,reconstruct as four} from '../../task-4/source-acceptance-20261008/proof.mjs';
import {alignment,assertions as fourAssertions} from '../../task-4/source-acceptance-20261008/attribution.mjs';
export const original='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-5';
export const base='adf32d48330e6768309244b4fc61a5a81ce3e204';
export const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
export const name=f=>/^func (?:\([^)]*\) )?(\w+)/.exec(f.signature)[1];
export const named=(s,n)=>spans(s).find(f=>name(f)===n);
export function walk(dir){return readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>e.isDirectory()?walk(dir+'/'+e.name):[dir+'/'+e.name]);}
export function reconstruct(){
 const manifest=JSON.parse(read(original+'/preimage-manifest.json')),final=JSON.parse(read(original+'/final-source.json')),patch=patchImages(5),review=JSON.parse(read(original+'/working-tree-review.json'));
 assert.equal(Object.keys(manifest).length,10);assert.equal(patch.paths,9);assert.equal(sha(read(original+'/task-only.patch')),final.patch_sha256);
 for(const [p,e] of Object.entries(manifest)){assert.equal(sha(read(e.before)),e.sha256,p);assert.equal(read(e.before).length,e.bytes,p);}
 assert.equal(review.findings.baseSha,'d635e23f00d926a43b942f25a9d05bd0ccb72025');assert.equal(review.findings.headSha,review.findings.baseSha);assert.equal(git(['rev-parse','a3b9f80efab9356c0be2080779133337e2471ac0^']).toString().trim(),review.findings.baseSha);
 const fixes=JSON.parse(read(original+'/review-fix-preimage.json')),fixpatch=read(original+'/review-fix.patch').toString(),headers=[...fixpatch.matchAll(/^--- a\/([^\n]+)\n\+\+\+ b\/([^\n]+)\n/gm)],fixed=[];
 for(let i=0;i<headers.length;i++){const h=headers[i],p=h[2],pre=read(original+'/review-fix-before/'+p).toString(),after=apply(fixpatch.slice(h.index+h[0].length,i+1<headers.length?headers[i+1].index:fixpatch.length),pre,p);assert.equal(sha(pre),final.review_fix[p].before_sha256);assert.equal(sha(after),final.review_fix[p].after_sha256);fixed.push({path:p,pre_sha256:sha(pre),post_sha256:sha(after)});}
 return {manifest,pre:Object.fromEntries(Object.entries(manifest).map(([p,e])=>[p,read(e.before).toString()])),images:patch.images,patch_sha256:patch.patch_sha256,review_parent:review.findings.baseSha,review_fix_patch_sha256:sha(fixpatch),review_fix:fixed};
}
export function lineage(path){
 const starts=['d635e23f00d926a43b942f25a9d05bd0ccb72025','9032202898117bce5a38aa04078da136e4f767bf'],commits=[...new Set(starts.flatMap(start=>git(['log','--ancestry-path','--full-history','--format=%H',start+'..HEAD','--',path]).toString().trim().split('\n').filter(Boolean)))];
 return commits.flatMap(commit=>{const metadata=git(['show','-s','--format=%H%n%P%n%B',commit]).toString(),parents=metadata.split('\n')[1].split(' ').filter(Boolean);return parents.map(parent=>({commit,parent,metadata,patch:git(['diff','--no-ext-diff','--no-renames',parent,commit,'--',path]).toString()})).filter(r=>r.patch).map(r=>({...r,patch_sha256:sha(r.patch)}));});
}
export function characterize(){
 const r=reconstruct(),f=four(),cli='tools/gomad3/cmd/gomad/internal/cli/',maps=[];
 const mappingPath='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-9/mapping.tsv',mapping=read(mappingPath).toString().trim().split('\n').map(line=>line.split('\t')).filter(c=>c.length>=6);
 for(const [origin,images] of [['original-task4',f.images],['original-task5-before',r.pre],['original-task5-final',r.images]])for(const [p,s] of Object.entries(images))if(p.endsWith('_test.go')&&(origin!=='original-task4'||p.endsWith('/application_characterization_test.go'))){
  const current=read(p).toString();for(const old of spans(s).filter(v=>name(v).startsWith('Test'))){let now=named(current,name(old));const mapped=mapping.filter(c=>c[1].split('/')[0]===name(old));if(!now&&mapped.length)now=named(current,mapped[0][3].split('/')[0]);assert(now,p+' '+name(old));const pairs=alignment(old.body,now.body),unmatched=old.body.split('\n').map((line,i)=>({line,i})).filter(e=>!pairs.some(m=>m.before===e.i));
   maps.push({origin,path:p,test:name(old),original:old,current:now,original_sha256:sha(old.body),current_sha256:sha(now.body),exact:old.body===now.body,alignment:pairs,unmatched_original_lines:unmatched,retained_fn1129_mapping:mapped,owner_parent_hunks:old.body===now.body?[]:lineage(p),classification:old.body===now.body?'exact function bytes':mapped.length?'fn112.9 retained consolidation mapping with complete original/current assertions and actual owner-parent hunks':'Changed construction/source seam; exact original assertions and owner-parent hunks retained for conductor review; no weakening admitted.'});
  }
 }
 const fixtures=['tools/gomad3/runner/testdata/campaign-options-before.json','tools/gomad3/runner/testdata/campaign-options-request-after.json'];
 const fixtureRows=fixtures.map((p,i)=>{const bytes=read(p),oldPath=original.replace(/task-5$/,'task-2')+'/'+(i===0?'campaign-options-before-complete.json':'campaign-options-request-after.json'),old=read(oldPath);assert.equal(sha(bytes),sha(old),p);const rows=JSON.parse(bytes);assert.equal(rows.length,76);return {...ref(p),retained_original:ref(oldPath),rows:rows.map(row=>({name:row.name,sha256:sha(JSON.stringify(row))})),fixed_supplied_inputs:true,fixture_recapture:false};});
 const historical=JSON.parse(read(original.replace(/task-5$/,'task-2')+'/campaign-options-before.json')),current76=JSON.parse(read(fixtures[0]));assert.equal(historical.length,75);for(const row of historical)assert.deepEqual(current76.find(e=>e.name===row.name),row);assert.deepEqual(current76.filter(e=>!historical.some(h=>h.name===e.name)).map(e=>e.name),['coverage-choice-probes']);
 return {functions:maps,canonical_options:fixtureRows,current_harnesses:['tools/gomad3/runner/campaign_options_characterization_test.go','tools/gomad3/runner/campaign_options_legacy_characterization_test.go','tools/gomad3/cmd/gomad/internal/cli/characterization_test.go','tools/gomad3/cmd/gomad/internal/cli/plan_characterization_test.go'].filter(p=>existsSync(root+'/'+p)).map(p=>({source:ref(p),body:read(p).toString(),owner_parent_hunks:lineage(p)})),old_passes_reused:false};
}
export function staticNarrow(){
 const prior=JSON.parse(read(out+'/source-proof.json')).static_bindings,b=JSON.parse(read(prior.binding.path));
 assert.equal(sha(read(prior.binding.path)),prior.binding.sha256);assert.equal(sha(read(prior.first_fn109_baseline.manifest.path)),prior.first_fn109_baseline.manifest.sha256);
 const first='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-21/baseline-reconstruction',be=JSON.parse(read(first+'/evidence.json'));
 const rows=read(first+'/source.sha256').toString().trim().split('\n');assert.equal(rows.length,670);for(const row of rows)assert.equal(sha(read(be.scratch_path+'/'+row.slice(66))),row.slice(0,64));
 for(const e of b.exact_bindings)assert.equal(sha(read(e.path)),e.sha256);assert.equal(b.exact_bindings.length,87);assert.equal(sha(read(b.archive.path)),b.archive.sha256);
 const rawPath=b.retained_raw_manifest.path,raw=JSON.parse(read(rawPath));assert.equal(sha(read(rawPath)),b.retained_raw_manifest.sha256);let bytes=0;
 for(const e of raw){const retained=read(rawPath.replace('/raw-manifest.json','/raw/')+(e.retained_name??e.name));if(e.retained_name)assert.equal(sha(retained),e.retained_sha256);const decoded=e.encoding==='utf8-json-string'?Buffer.from(JSON.parse(retained).value):retained;assert.equal(sha(decoded),e.sha256);assert.equal(decoded.length,e.bytes);bytes+=decoded.length;}assert.equal(raw.length,72);assert.equal(bytes,521317);
 const changed=b.input_closure.filter(e=>sha(read(e.path))!==e.current_sha256),expected=['tools/gomad3/cmd/gomad/internal/cli/cli.go','tools/gomad3/runner/completion_characterization_test.go','tools/gomad3/runner/internal/campaign/retained_evidence_test.go','tools/gomad3/runner/runner_test.go'];assert.deepEqual(changed.map(e=>e.path).sort(),expected);assert.equal(b.input_closure.length,1223);
 assert.equal(sha(read(b.positive_inventory.receipt)),b.positive_inventory.receipt_sha256);const receipt=JSON.parse(read(b.positive_inventory.receipt)),log=read(b.positive_inventory.receipt.replace(/\.json$/,'.stdout'));assert.equal(receipt.exit,0);assert.equal(sha(log),b.positive_inventory.log_sha256);assert(log.toString().includes('platforms=[darwin/arm64 linux/amd64] draw rows=273 seeded rows=86 clock rows=48 goroutine rows=10'));
 return {...prior,unchanged_closure:1219,changed_unreused:changed.map(e=>({path:e.path,current_sha256:sha(read(e.path)),original_closure_sha256:e.current_sha256,owner:e.path.endsWith('/cli.go')?'fn109.5 explicitly admitted exact original-function restoration':e.path.endsWith('retained_evidence_test.go')?'Done fn112.16':'Done fn109.3 exact statistics restoration',old_pass_reused:false})),new_regression_outside_original_closure:ref('tools/gomad3/cmd/gomad/internal/cli/explore_failure_writer_test.go'),fourth_change_is_not_a_static_runtime_input:true,native:false};
}
export function restoration(){
 const p='tools/gomad3/cmd/gomad/internal/cli/cli.go',r=reconstruct(),old=named(r.images[p],'reportExploreFailure'),current=named(read(p).toString(),'reportExploreFailure');assert.equal(current.body,old.body,'Exact original helper restoration');
 const snapshots=JSON.parse(read(out+'/sources-current.json'));for(const [path,digest] of Object.entries(snapshots))if(path!==p)assert.equal(sha(read(path)),digest,path+' unchanged pre-restoration tracked bytes');
 return {path:p,original_function_sha256:sha(old.body),current_function_sha256:sha(current.body),byte_exact:true,original_owner:'a3b9f80efab9356c0be2080779133337e2471ac0',old_assertions_untouched:true,regression:{...ref('tools/gomad3/cmd/gomad/internal/cli/explore_failure_writer_test.go'),body:read('tools/gomad3/cmd/gomad/internal/cli/explore_failure_writer_test.go').toString()},current_parent:git(['rev-parse','HEAD']).toString().trim(),dirty_parent_patch:git(['diff','--no-ext-diff','--',p]).toString(),admission:ref('.flow/tasks/fn-109-gomad-deepen-modules-and-tool-interfaces.5.md')};
}
export function build(){
 const r=reconstruct(),six=patchImages(6),a3='a3b9f80efab9356c0be2080779133337e2471ac0',rows=[];
 for(const [p,post] of Object.entries(r.images)){
  let image=post;const later=[];if(Object.hasOwn(six.pre,p)){assert.equal(image,six.pre[p],p+' task6 adjacency');image=six.images[p];later.push({task:6,pre_sha256:sha(six.pre[p]),post_sha256:sha(image),patch_sha256:six.patch_sha256});}
  for(const task of [7,8]){
   const directory=original.replace(/task-5$/,`task-${task}`),patch=read(directory+'/task-only.patch').toString(),headers=[...patch.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],i=headers.findIndex(h=>h[2]===p);if(i<0)continue;
   const before=read(directory+'/preimages/'+p).toString();assert.equal(image,before,p+' task'+task+' adjacency');image=apply(patch.slice(headers[i].index+headers[i][0].length,i+1<headers.length?headers[i+1].index:patch.length),image,p);
   const final=JSON.parse(read(directory+(task===7?'/final-source.json':'/source-freeze.json')));assert.equal(sha(image),(final.source??final.sources)[p]);later.push({task,pre_sha256:sha(before),post_sha256:sha(image),patch_sha256:sha(patch)});
  }
  const integrated=git(['show',a3+':'+p]);assert.equal(sha(image),sha(integrated),p+' dirty local integration');
  rows.push({path:p,original_pre_sha256:r.pre[p]?sha(r.pre[p]):null,original_post_sha256:sha(post),local_later_owners:later,local_integrated_sha256:sha(integrated),current_sha256:sha(read(p)),current_equals_original:sha(read(p))===sha(post),actual_owner_transitions:lineage(p)});
 }
 const cliPath='tools/gomad3/cmd/gomad/internal/cli/cli.go',cli=read(cliPath).toString(),parse=named(cli,'parseCampaignRequest'),explore=named(cli,'runExploreWith'),plan=named(cli,'runPlanWith');assert(parse&&explore&&plan);assert.equal(spans(cli).filter(f=>name(f)==='parseCampaignRequest').length,1);assert.equal((explore.body.match(/dependencies\.explore\(/g)??[]).length,1);assert.equal((plan.body.match(/dependencies\.plan\(/g)??[]).length,1);assert(!plan.body.includes('runExplore'));assert(!parse.body.includes('__plan'));assert(parse.body.includes('flags.Set("on-failure", string(runner.PolicyAll))'));
 const functions=[...spans(cli).filter(f=>['parseCampaignRequest','runExploreWith','runPlanWith','reportExploreFailure','resolveExploreStrategy','resolveExploreGuidance','resolveExploreSeeds','resolveExploreCoverage','resolveChoiceTrace'].includes(name(f))).map(f=>({path:cliPath,...f,sha256:sha(f.body)})),...['tools/gomad3/runner/campaign_options.go','tools/gomad3/runner/runner.go','tools/gomad3/runner/campaign_plan.go','tools/gomad3/runner/portable_plan.go'].flatMap(path=>spans(read(path).toString()).filter(f=>/Normalize|Validate|validate|ParseSingle|requireSingle|createCampaignPlan|campaignRequestFromSpec|campaignPlanFor/.test(name(f))).map(f=>({path,...f,sha256:sha(f.body)})))];
 const userFiles=['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(ref);assert.equal(userFiles[0].sha256,'97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188');assert.equal(userFiles[1].sha256,'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287');
return {base_commit:base,head:git(['rev-parse','HEAD']).toString().trim(),source_identity_sha256:sha(JSON.stringify(sources())),board:board(),original:{preimage_count:10,postimage_count:9,manifest:ref(original+'/preimage-manifest.json'),patch:ref(original+'/task-only.patch'),final:ref(original+'/final-source.json'),actual_review_metadata:ref(original+'/working-tree-review.json'),committed_lint_parent:r.review_parent,parent_derivation:'Actual original review baseSha/headSha and actual parent of a3b9f80; dirty task5 pre/postimages reconstructed independently',review_fix:r.review_fix,review_fix_patch_sha256:r.review_fix_patch_sha256},owners:rows,ownership_and_order:functions,characterization:characterize(),static_bindings:staticNarrow(),host_assertions:fourAssertions(),bounded_identity_decision:['.flow/specs/fn-109-gomad-deepen-modules-and-tool-interfaces.md','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-4/source-acceptance-20261008/identity-admission.json','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-4/conductor-source-acceptance-20261008/audit.json'].map(ref),user_files:userFiles,restoration:restoration(),product_edits:['tools/gomad3/cmd/gomad/internal/cli/cli.go','tools/gomad3/cmd/gomad/internal/cli/explore_failure_writer_test.go'],native:false,review_verdict:null};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){write('source-proof-final.json',build());write('sources-current-final.json',sources());console.log('final task5 source proof retained');}
