import assert from 'node:assert/strict';
import {writeFileSync,existsSync,lstatSync} from 'node:fs';
import {root,out,original,read,git,sha,reconstruct} from './reconstruct.mjs';
import {apply,patchImages} from './owner-chain.mjs';
const ref=p=>({path:p,sha256:sha(read(p)),bytes:read(p).length});
function onePatch(task,path,before){const p=read(original.replace(/task-2$/,`task-${task}`)+'/task-only.patch').toString(),headers=[...p.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],i=headers.findIndex(h=>h[2]===path);assert(i>=0);return apply(p.slice(headers[i].index+headers[i][0].length,i+1<headers.length?headers[i+1].index:p.length),before,path);}
const mount=s=>s.slice(s.indexOf('\tif len(config.IOROMounts) != 0 {'),s.indexOf('\tenvironment, err := parseEnvironment(config.Environment)',s.indexOf('\tif len(config.IOROMounts) != 0 {')));
export function buildDelta(){
 const r=reconstruct(),five=patchImages(5),six=patchImages(6),rp='tools/gomad3/runner/runner.go',pp='tools/gomad3/runner/portable_plan.go',d3=original.replace(/task-2$/,'task-3'),d7=original.replace(/task-2$/,'task-7');
 const pre3=read(d3+'/preimages/'+rp).toString();assert.equal(pre3,r.images[rp]);const after3=onePatch(3,rp,pre3);assert.equal(sha(after3),JSON.parse(read(d3+'/source-post.json'))[rp]);assert.equal(after3,five.pre[rp]);
 const chain7=[rp,pp].map(path=>{const before=read(d7+'/preimages/'+path).toString();assert.equal(before,six.images[path]);const after=onePatch(7,path,before);assert.equal(sha(after),JSON.parse(read(d7+'/final-source.json')).source[path]);assert.equal(sha(after),sha(git(['show','a3b9f80efa:'+path])));return {path,task6_sha256:sha(before),task7_sha256:sha(after),equals_integrated_a3:true,equals_current:sha(after)===sha(read(path))};});
 const oldMount=mount(r.images[rp]),newMount=mount(read(rp).toString());assert(oldMount.length>400);assert.equal(oldMount,newMount);assert(oldMount.indexOf('readonlymount.ParseMappings')<oldMount.indexOf('readonlymount.Prepare(nil, limits)'));
 const mountFiles=['tools/gomad3/deterministicio/readonlymount/config.go','tools/gomad3/deterministicio/readonlymount/capture.go'].map(path=>{const before=git(['show','1b970bc1444f4da6428c843a91d3d0fa998dbde3:'+path]);assert(before.equals(read(path)));return {...ref(path),original_base_sha256:sha(before),identical:true};});
 assert.equal(sha(read(out+'/matched-mount-original-config.go')),mountFiles[0].sha256);
 const currentTest=read('tools/gomad3/runner/campaign_options_characterization_test.go').toString(),originalTest=r.images['tools/gomad3/runner/campaign_options_characterization_test.go'];
 const adjustment='\t\tif want.Name == "mount-limits" {\n\t\t\tif source, err := os.Lstat("/tmp"); err == nil && source.IsDir() {\n\t\t\t\twant.Error = "read-only mount limits must be positive"\n\t\t\t}\n\t\t}\n';assert.equal(currentTest.replace(adjustment,''),originalTest);
 const mounts=['matched-mount-original','matched-mount-current'].map(label=>{const e=JSON.parse(read(out+'/'+label+'.json'));assert.equal(e.exit,0);assert.deepEqual(e.top_level_counts,{pass:4,fail:0,skip:0});assert.equal(sha(read(out+'/'+label+'.stdout')),e.stdout_sha256);assert.equal(sha(read(out+'/'+label+'.stderr')),e.stderr_sha256);return {label,...e};});assert.deepEqual(mounts[0].tests,mounts[1].tests);
 const options=r.images['tools/gomad3/runner/campaign_options.go'],currentOptions=read('tools/gomad3/runner/campaign_options.go').toString(),groups=[...options.matchAll(/^type (campaign\w*Options) struct \{[^]*?^\}/gm)].map(m=>{const now=currentOptions.match(new RegExp('^type '+m[1]+' struct \\{[^]*?^\\}', 'm'))?.[0];assert.equal(now,m[0]);return {name:m[1],original_sha256:sha(m[0]),current_sha256:sha(now),identical:true};});assert.equal(groups.length,8);
 const owners={
 'campaign_plan.go':['fn109.5 retained semantic-owner patch; f608449c016b751a8fd4e19561518e979ebfc31e helper additions via ca334; fn109.26 current CLI presentation restoration fec3ce56e7ea2f1498617148cb2c6d47f1297bc0'],
 'campaign_shard_execution.go':['fn109.6 exact current postimage'],
 'choice_exploration_campaign.go':['fn109.6 exact a3 postimage; fn112.16 StoreKeyExecution via 6be0755fef727146f86bac6658436f6874680cc8 / ca334'],
 'choice_exploration_divergence_test.go':['fn109.6 exact current postimage'],
 'coordinator_transport_test.go':['fn109.6 private Executor consumer map migration; exact current postimage'],
 'guidance.go':['fn109.6 private replay execution dependency propagation via a619f541b83728fd9aacfc6f7747300a2d100f91 / ca334'],
 'minimize_operation.go':['fn109.6 retained dependency migration; fn109.12 detached/opened Artifact ownership 3a3c31b0a7b22ab2c669735743d3f1e2d2985bab'],
 'portable_plan.go':['fn109.6 retained dependency migration; fn109.7 retained preparation owner patch, exact a3/current postimage'],
 'resume.go':['fn109.5 then fn109.6 byte-exact retained chain; fn109.12 detached/opened Artifact ownership 3a3c31b0a7b22ab2c669735743d3f1e2d2985bab'],
 'runner.go':['fn109.3 exact retained pre/post between task2 and task5; fn109.5 then fn109.6 then fn109.7 exact retained chain to a3; ca334 adopts fn109.3 completion constructors from 09c1f3ccaf6d119eb12f998756e95a896e00d672 and fn109.6 replay dependencies; fn112.16 StoreKeyExecution 6be0755fef727146f86bac6658436f6874680cc8'],
 'simulation_exploration_campaign.go':['fn109.6 exact a3 postimage; fn112.16 StoreKeyExecution 6be0755fef727146f86bac6658436f6874680cc8 via ca334'],
 'retention_test.go':['fn109.6 exact a3 postimage; fn112.16 stronger disk/journal counts 6be0755fef727146f86bac6658436f6874680cc8 via ca334; fn109.12 opened Artifact methods 3a3c31b0a7b22ab2c669735743d3f1e2d2985bab'],
 'runner_test.go':['fn109.6 exact a3 postimage; fn109.12 opened Artifact methods 3a3c31b0a7b22ab2c669735743d3f1e2d2985bab; fn112.9 table consolidation ebc5ea1e099777c9a3bda922666c200e56c9540e'],
 'campaign_options.go':['fn109.5 then fn109.6 exact retained chain to a3; ca334 retains request slice/pointer ownership from rebased fn109.2 normalization implementation 7fe6c833c0f03b46d9b2876d9f6a1b59d5f7c2ac; current normalization test mutates original lists to enforce isolation'],
 'campaign_options_characterization_test.go':['ca3345469a2541b7686606268b0f19cde030a8fe merge resolution adds only host-/tmp five-line adjustment; all other source byte-equal to retained task2 postimage']};
 const rows=r.rows.map(e=>({...e,owners:e.current_equals_original?['task2 exact retained postimage']:owners[e.path.split('/').at(-1)]}));for(const e of rows)assert(e.owners?.length);
 const refs=[d3+'/task-only.patch',d3+'/source-pre.json',d3+'/source-post.json',d7+'/task-only.patch',d7+'/preimages.json',d7+'/final-source.json',original.replace(/task-2$/,'task-5')+'/task-only.patch',original.replace(/task-2$/,'task-5')+'/final-source.json',original.replace(/task-2$/,'task-6')+'/task-only.patch',original.replace(/task-2$/,'task-6')+'/final-source.json','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-26/source-checkpoint-verification.json','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/go-interface-changes.md','tools/gomad3/runner/internal/campaign/resume_plan.go','tools/gomad3/runner/portable_plan.go'].map(ref);
 return {rows,runner_task3_post_sha256:sha(after3),preparation_chain:chain7,private_options_groups:groups,matched_mount:{original_branch_sha256:sha(oldMount),current_branch_sha256:sha(newMount),branch_byte_identical:true,order:'ParseMappings (Lstat directory/symlink refusal) before Prepare/validateLimits',files:mountFiles,tmp_identity:{mode:lstatSync('/tmp').mode,is_directory:lstatSync('/tmp').isDirectory(),is_symlink:lstatSync('/tmp').isSymbolicLink()},host_adjustment:{commit:'ca3345469a2541b7686606268b0f19cde030a8fe',original_test_sha256:sha(originalTest),current_test_sha256:sha(currentTest),only_delta:adjustment,fixture_edit:false,waiver:false,scope:'Matched filesystem type preserves exact validation source and precedence. Historical Darwin symlink error and Linux directory limits error are not claimed byte-equal.'},receipts:mounts,limitation:'Two runs exercise original byte-bound parser overlay and current parser with current tests; capture/limits source and Runner mount branch are exactly original bytes. This is not whole-original Runner execution or native evidence.'},references:refs,native_qualification:false,review_verdict:null};
}
if(process.argv[1]===new URL(import.meta.url).pathname){assert(!existsSync(out+'/delta-proof.json'));const p=buildDelta();writeFileSync(out+'/delta-proof.json',JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({rows:p.rows.length,groups:p.private_options_groups.length,mount_branch_exact:p.matched_mount.branch_byte_identical}));}
