import assert from 'node:assert/strict';
import {writeFileSync,existsSync,statSync} from 'node:fs';
import {root,out,original,sha,read,git,reconstruct} from './reconstruct.mjs';
import {chain} from './owner-chain.mjs';
export const base='bad15a4b58711ed3fffdab0eb2c6cafc10d62e8a';
export const labels=['portable-options','portable-transport','portable-transport-controls','architecture','validate','configured-original-task-lint','actual-task2-base-lint','current-cli-consumers','unfiltered-options-package-lint','portable-plan-resume','portable-options-helpers','check-format','configured-errortype'];
export function sourceMap(){return Object.fromEntries(git(['ls-files','-z']).toString().split('\0').filter(p=>p&&!p.startsWith('.flow/')&&existsSync(root+'/'+p)&&statSync(root+'/'+p).isFile()).sort().map(p=>[p,sha(read(p))]));}
const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
const struct=(s,name)=>s.match(new RegExp('^type '+name+' struct \\{[^]*?^\\}', 'm'))?.[0];
export function build(){
 const r=reconstruct(),owners=chain(),identity=sha(JSON.stringify(sourceMap()));
 const pre=struct(r.preimages['tools/gomad3/runner/runner.go'],'CampaignSpec'),post=struct(r.images['tools/gomad3/runner/runner.go'],'CampaignSpec'),current=struct(read('tools/gomad3/runner/runner.go').toString(),'CampaignSpec');
 assert.equal(pre,post);assert.equal(sha(pre),'00271a0d64a930ee9937f2d9f62edb0a33acad8d902b52ab462053c45a9dfb21');
 const fields=s=>s.split('\n').flatMap(l=>{const m=/^\t([A-Z]\w*)\s/.exec(l);return m?[m[1]]:[];});assert.equal(fields(post).length,48);assert.deepEqual(fields(post).filter(f=>!fields(current).includes(f)),['Executor']);assert.deepEqual(fields(current).filter(f=>!fields(post).includes(f)),[]);
 for(const row of r.rows.filter(e=>e.preimage_sha256&&e.origin.startsWith('git blob')))assert.equal(sha(git(['show','1b970bc1444f4da6428c843a91d3d0fa998dbde3:'+row.path])),row.preimage_sha256);
 const hist=JSON.parse(read(original+'/campaign-options-before.json')),fixed=JSON.parse(read('tools/gomad3/runner/testdata/campaign-options-before.json'));assert.equal(hist.length,75);assert.equal(fixed.length,76);
 const hnames=hist.map(e=>e.name??e.Name),fnames=fixed.map(e=>e.name??e.Name);const added=fnames.filter(n=>!hnames.includes(n));assert.deepEqual(added,['coverage-choice-probes']);
 for(const e of hist){const f=fixed.find(x=>(x.name??x.Name)===(e.name??e.Name));assert.deepEqual(f,e,e.name??e.Name);}
 const baselineDir='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-21/baseline-reconstruction',be=JSON.parse(read(baselineDir+'/evidence.json')),manifest=read(baselineDir+'/source.sha256');assert.equal(sha(manifest),'d78601b3176195f8cc06860f5499e757a2d04333b9211f0ed13a92976b017845');
 const baselineRows=manifest.toString().trim().split('\n').map(l=>{const m=/^([a-f0-9]{64})  (.+)$/.exec(l);assert(m);assert.equal(sha(read(be.scratch_path+'/'+m[2])),m[1],m[2]);return {path:m[2],sha256:m[1]};});assert.equal(baselineRows.length,670);
 const bindingPath='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-5/source-acceptance-20261008/source-binding.json',binding=JSON.parse(read(bindingPath));assert.equal(binding.exact_bindings.length,87);for(const e of binding.exact_bindings)assert.equal(sha(read(e.path)),e.sha256,e.path);assert.equal(sha(read(binding.archive.path)),binding.archive.sha256);
 const changed=binding.input_closure.filter(e=>sha(read(e.path))!==e.current_sha256);assert.equal(binding.input_closure.length,1223);assert.equal(changed.length,1);assert.equal(changed[0].path,'tools/gomad3/runner/internal/campaign/retained_evidence_test.go');
 const rawPath=binding.retained_raw_manifest.path,raw=JSON.parse(read(rawPath));assert.equal(sha(read(rawPath)),binding.retained_raw_manifest.sha256);let rawBytes=0;
 for(const e of raw){const stored=read(rawPath.replace('/raw-manifest.json','/raw/')+(e.retained_name??e.name));if(e.retained_name)assert.equal(sha(stored),e.retained_sha256);const decoded=e.encoding==='utf8-json-string'?Buffer.from(JSON.parse(stored).value):stored;assert.equal(decoded.length,e.bytes);assert.equal(sha(decoded),e.sha256);rawBytes+=decoded.length;}assert.equal(raw.length,72);assert.equal(rawBytes,521317);
 const inventory='.flow/artifacts/fn-110-gomad-minimize-the-runtime-patch/task-2/source-acceptance-20261007/raw/source-inventories-pinned';assert.equal(sha(read(inventory+'.json')),'d467060c7b6af8b4eb05f1d353854c32d76442fa72088031caaa149726cd97d0');assert.equal(sha(read(inventory+'.stdout')),'e5db8479e0f26b36dcac62da353bd3141aab8747b246d6c031efd6e056260635');
 const receipts=labels.map(label=>{const path=out+'/'+label+'.json',e=JSON.parse(read(path));assert.equal(e.sources_before_sha256,identity,label);assert.equal(e.sources_after_sha256,identity,label);assert.deepEqual(e.source_changes,[]);assert.equal(sha(read(out+'/'+label+'.stdout')),e.stdout_sha256);assert.equal(sha(read(out+'/'+label+'.stderr')),e.stderr_sha256);return {label,...e};});
 const findingsFor=label=>read(out+'/'+label+'.stdout').toString().split('\n').flatMap(l=>{const m=/^(tools\/gomad3\/[^:]+):(\d+):(\d+): (.*) \((\w+)\)$/.exec(l);if(!m)return [];const path=m[1],line=+m[2],body=read(path).toString().split('\n')[line-1],blame=git(['blame','--porcelain','-L',line+','+line,'--',path]).toString();const before=r.preimages[path]?.includes(body.trim())??false,after=r.images[path]?.includes(body.trim())??false;return [{path,line,column:+m[3],message:m[4],rule:m[5],source_sha256:sha(read(path)),line_sha256:sha(body),line_body:body,blame_commit:blame.split(' ')[0],blame_summary:blame.match(/^summary (.+)$/m)?.[1],in_original_twenty_paths:path in r.images,statement_in_original_preimage:before,statement_in_original_postimage:after,task2_introduced_statement:after&&!before,correction_owner:'fn-109-gomad-deepen-modules-and-tool-interfaces.21 (aggregate R18; preserve originating source-owner attribution)',waived:false}];});
 const lint={actual_task2_base:'1b970bc1444f4da6428c843a91d3d0fa998dbde3',adjacent_base_diagnostic:'97bdba0fde',actual_base_findings:findingsFor('actual-task2-base-lint'),unfiltered_runner_findings:findingsFor('unfiltered-options-package-lint'),adjacent_base_findings:findingsFor('configured-original-task-lint'),config:ref('.github/.golangci.yml'),tools:[ref('/tmp/fn109-lint-tools.ZdNe1t50/golangci-lint-v2.13.0'),ref('/tmp/fn109-lint-tools.ZdNe1t50/errortype')],global_lint_pass:false};
 assert.equal(lint.actual_base_findings.length,68);assert.equal(lint.unfiltered_runner_findings.length,17);assert.equal(lint.adjacent_base_findings.length,80);assert.equal(lint.unfiltered_runner_findings.filter(e=>e.task2_introduced_statement).length,0);
 const referencePaths=[original+'/own-work.patch',original+'/source-pre-complete.json',original+'/source-post-complete.json',original+'/parent-verified-predirty.patch',original+'/parent-verification.json',original+'/parent-public-contract.json',original+'/parent-verified-preimages/runner_test.go',original+'/parent-verified-preimages/retention_test.go',original+'/campaign-options-before.json',original+'/campaign-options-before-complete.json',original+'/campaign-options-request-after.json',baselineDir+'/reconstruct.py',baselineDir+'/reconstruction.md',baselineDir+'/evidence.json',baselineDir+'/source.sha256',baselineDir+'/input.sha256',bindingPath,rawPath,inventory+'.json',inventory+'.stdout'];
 const sourcePaths=[...new Set([...r.rows.map(e=>e.path),'tools/gomad3/runner/campaign_options_test.go','tools/gomad3/runner/campaign_options_cli_test.go','tools/gomad3/runner/coordinator_dispatch.go','tools/gomad3/cmd/gomad/internal/cli/cli.go','tools/gomad3/cmd/gomad/internal/cli/campaign_semantics_ownership_test.go','tools/gomad3/runner/internal/campaign/plan.go','tools/gomad3/runner/internal/campaign/lifecycle.go','tools/gomad3/runner/internal/campaign/choice_exploration_start_test.go','tools/gomad3/runner/internal/campaign/campaign_journal_test.go','tools/gomad3/runner/internal/campaign/lifecycle_test.go'])].filter(p=>existsSync(root+'/'+p));
 const userFiles=[ref('.turbo/plans/gomad3-glossary-update.md'),ref('.turbo/technical-debt.md')];assert.equal(userFiles[0].sha256,'97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188');assert.equal(userFiles[1].sha256,'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287');
 return {base_commit:base,source_identity_sha256:identity,original_task2: {immediate_base:lint.actual_task2_base,full_postimages:20,exact_current:5,later_owned_changes:15,public_spec:{pre_sha256:sha(pre),post_sha256:sha(post),original_exported_fields:fields(post),current_sha256:sha(current),current_exported_fields:fields(current),removed:['Executor'],removal_owner:'fn109.6 / a619f541 + retained task6 patch; not task2 API migration'},owners},first_fn109_baseline:{commit:be.base_revision,kind:be.baseline_kind,inputs:670,manifest_sha256:sha(manifest),reused_only_as_original_baseline:true,later38957053_substitution:false},fixture_preservation:{historically_executed_rows:75,historical_sha256:sha(read(original+'/campaign-options-before.json')),current_rows:76,additional_row:added[0],additional_row_kind:'historically reconstructed, not a 76th historical execution',all75_rows_deep_equal:true,source_fixture:ref('tools/gomad3/runner/testdata/campaign-options-before.json'),exact_after_request_fixture:ref('tools/gomad3/runner/testdata/campaign-options-request-after.json')},reused:{exact_runtime_inputs:87,raw_files:72,raw_original_bytes:rawBytes,archive:binding.archive,unchanged_closure:1222,changed_unreused:changed.map(e=>({path:e.path,old:e.current_sha256,current:sha(read(e.path)),owner:'DONE fn112.16',reused:false})),platforms:['darwin/arm64','linux/amd64'],kind:'exact source binding to retained materialized inventories; no native runtime or old whole-closure test pass reused'},source_files:sourcePaths.map(ref),references:referencePaths.map(ref),user_files:userFiles,command_receipts:receipts,lint,format:{listed:read(out+'/check-format.stdout').toString().trim().split('\n'),owner:'inherited fn109.13 runtime overlay separator; no edits, no fn110 exact642-byte waiver expanded',clean:false},native_qualification:false,review_verdict:null,product_edits:[]};
}
if(process.argv[1]===new URL(import.meta.url).pathname){assert(!existsSync(out+'/source-proof.json'));const proof=build();writeFileSync(out+'/source-proof.json',JSON.stringify(proof,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({source_files:proof.source_files.length,postimages:20,commands:proof.command_receipts.length,lint17:proof.lint.unfiltered_runner_findings.length,source_identity:proof.source_identity_sha256,native:false}));}
