import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {out,read,sha,write} from './capture.mjs';
import {reconstruct,spans} from './proof.mjs';
export function admission(){
 const files=['contract-task-at-freeze.md','contract-spec-at-freeze.md'],blocks=files.map(p=>{const s=read(out+'/'+p).toString(),lines=s.split('\n'),start=lines.findIndex(l=>/^#{2,3} Bounded retained CLI identity decision \(2026-10-08\)$/.test(l));assert(start>=0);let end=start+1;while(end<lines.length&&!/^#{1,3} /.test(lines[end]))end++;return {path:p,sha256:sha(s),text:lines.slice(start+1,end).join('\n')};});assert.equal(blocks[0].text+'\n',blocks[1].text,'Exact amendment paragraphs differ; spec retains one additional section-separator newline');
 return {chronological_gap:{path:'source-gaps.json',sha256:sha(read(out+'/source-gaps.json')),initial_contract_snapshots:['initial-contract-0.md','initial-contract-1.md'].map(p=>({path:p,sha256:sha(read(out+'/'+p))}))},current_dated_amendment:blocks,scope:'Only existing shared-installation digestRunner reuse, regular/executable validation, staged open/stat/hash/close failures and wrapping; normal SHA identity and original analysis hash dependency remain. All unrelated CLI grammar/default/bytes/writer behavior/comments/identity preservation remains strict.',new_validator:false,product_or_test_edits:[],new_lint_waiver:false,retroactive_original_equivalence_claim:false,source_owner_commits:['debca5eb56e7719c566eb4552a04279631982671','a3b9f80efab9356c0be2080779133337e2471ac0','ca3345469a2541b7686606268b0f19cde030a8fe'],review_verdict:null,native:false};
}
export function writers(){
 const r=reconstruct(),cli='tools/gomad3/cmd/gomad/internal/cli/',oldDoctor=spans(r.images[cli+'cli.go']).find(f=>f.signature.startsWith('func runDoctorWithApplication(')),currentDoctor=spans(read(cli+'cli.go').toString()).find(f=>f.signature.startsWith('func (app application) runDoctor(')),oldRun=spans(r.images[cli+'cli.go']).find(f=>f.signature.startsWith('func Run(')),currentPrivate=spans(read(cli+'application.go').toString()).find(f=>f.signature.startsWith('func (app application) runPrivateMode('));assert(oldDoctor&&currentDoctor&&oldRun&&currentPrivate);
 return {original_doctor:{...oldDoctor,sha256:sha(oldDoctor.body)},current_doctor:{...currentDoctor,sha256:sha(currentDoctor.body)},original_private_dispatch:{...oldRun,sha256:sha(oldRun.body)},current_private_dispatch:{...currentPrivate,sha256:sha(currentPrivate.body)},branch_bindings:[{branch:'Executable discovery failure',original:'writeCommandError(stderr,3,"resolve gomad executable: %v\\n", err)',current:'app.executablePath wraps resolve gomad executable: %w; fmt.Fprintln(stderr,err); return3',writes:1,stdout_bytes:'',stderr_format:'resolve gomad executable: <error>\n',successful_writer_status:3,failed_writer_status:3},{branch:'Absolute executable path failure',original:'fmt.Fprintf(stderr,"resolve gomad executable path: %v\\n",err);return3',current:'absoluteExecutable wraps resolve gomad executable path: %w;fmt.Fprintln(stderr,err);return3',writes:1,successful_writer_status:3,failed_writer_status:3},{branch:'Absolute artifact directory failure',original_and_current:'fmt.Fprintf(stderr,"resolve artifact directory: %v\\n",err);return2',writes:1,successful_writer_status:2,failed_writer_status:2},{branch:'Installation resolution failure',original:'app.installation wraps resolve Gomad installation: %w; checked fmt.Fprintf(stderr,"%v\\n",err)',current:'app.resolveInstallation returns resolver error; checked fmt.Fprintf(stderr,"resolve Gomad installation: %v\\n",err)',writes:1,successful_writer_status:2,failed_writer_status:3},{branch:'Doctor JSON stdout',original_and_current:'fmt.Fprintf(stdout,"%s\\n",encoded) return ignored, followed by report availability classification',writes:1,available_status:0,unavailable_status:1,failed_writer_status:'same0/1',pre_existing:true},{branch:'Private dispatch failure',original:'app.dispatchPrivateMode -> Runner dispatcher; fmt.Fprintln(stderr,err);return3',current:'app.dispatch using private process streams; fmt.Fprintln(stderr,err);return3',writes:1,successful_writer_status:3,failed_writer_status:3}],basis:'Exact retained function bodies plus current wrapper definitions; source equivalence table is separate from actual test observations. No failed-writer0/1 repair or new waiver.',runtime_original_reproduction:false};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){write('identity-admission.json',admission());write('writer-equivalence.json',writers());console.log('Dated bounded criterion and exact writer branches bound; no worker verdict.');}
