import assert from 'node:assert/strict';
import {readdirSync,statSync,existsSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {root,out,read,sha,git,sources,write} from './capture.mjs';
import {base,original,ref} from './proof.mjs';
export function walk(directory){return readdirSync(directory).sort().flatMap(n=>{const p=resolve(directory,n);return statSync(p).isDirectory()?walk(p):[p];});}
export function receipts(){return readdirSync(out).filter(n=>n.endsWith('.json')).sort().flatMap(n=>{const r=JSON.parse(read(out+'/'+n));if(!r.argv)return [];assert.equal(sha(read(out+'/'+n.replace(/\.json$/,'.stdout'))),r.stdout_sha256);assert.equal(sha(read(out+'/'+n.replace(/\.json$/,'.stderr'))),r.stderr_sha256);assert.deepEqual(r.source_changes,[]);return [{path:n,sha256:sha(read(out+'/'+n)),...r}];});}
export function counts(rs){
 const observations=rs.flatMap(r=>r.tests.filter(t=>!t.test.includes('/')).map(t=>({receipt:r.path,...t,key:t.package+'::'+t.test}))),keys=[...new Set(observations.map(t=>t.key))].sort(),unique=keys.map(key=>({key,observations:observations.filter(t=>t.key===key)}));
 return {unique_top_level:unique.length,unique_pass:unique.filter(t=>t.observations.every(x=>x.action==='pass')).length,unique_fail:unique.filter(t=>t.observations.some(x=>x.action==='fail')).length,unique_skip:unique.filter(t=>t.observations.every(x=>x.action==='skip')).length,duplicated_observations:observations.length-unique.length,observations,unique,zero_match_suites:rs.filter(r=>r.argv.includes('test')&&r.tests.length===0).map(r=>({receipt:r.path,exit:r.exit,error:r.error}))};
}
function prepare(){
 const rs=receipts(),c=counts(rs);assert.equal(c.unique_pass,129);assert.equal(c.unique_fail,3);assert.equal(c.duplicated_observations,29);
 const s=sources();write('sources-current.json',s);write('milestones-ip.md',read('MILESTONES.md'));
 const oldFiles=walk(resolve(root,original)).filter(p=>!p.startsWith(out+'/')).map(p=>ref(relative(root,p)));write('original-records.json',oldFiles);
 const helpers=['.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-2/source-acceptance-20261008/owner-chain.mjs','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-2/source-acceptance-20261008/reconstruct.mjs'];write('import-bindings.json',helpers.map(ref));
 write('coverage.json',c);
 const task='.flow/tasks/fn-109-gomad-deepen-modules-and-tool-interfaces.4.md',spec='.flow/specs/fn-109-gomad-deepen-modules-and-tool-interfaces.md';write('contract-task-at-freeze.md',read(task));write('contract-spec-at-freeze.md',read(spec));
 const e={task:'fn-109-gomad-deepen-modules-and-tool-interfaces.4',status:'in_progress',review_verdict:null,native:false,base_commit:base,head:git(['rev-parse','HEAD']).toString().trim(),commits:[],prs:[],tier:'session (jev-unavailable(no_key))',tests:rs.map(r=>r.argv.join(' ')),receipts:rs.map(r=>({path:r.path,sha256:r.sha256,exit:r.exit,signal:r.signal,error:r.error,started:r.started,ended:r.ended,source_changes:r.source_changes,counts:r.top_level_counts,environment:r.environment})),coverage:{path:'coverage.json',...Object.fromEntries(['unique_top_level','unique_pass','unique_fail','unique_skip','duplicated_observations','zero_match_suites'].map(k=>[k,c[k]]))},source_identity:{manifest:'sources-current.json',sha256:sha(JSON.stringify(s)),milestones:ref('MILESTONES.md'),user_files:JSON.parse(read(out+'/source-proof-final.json')).user_files},proofs:['source-proof-final.json','lint-attribution-frozen.json','host-assertions-frozen.json','source-gaps.json','original-records.json','import-bindings.json'],baseline:'red; missing patched driver, initial full CLI ENOSPC then actual host-bound full CLI failures; no source edits',gates:{fast_lint:{exit:2,findings:68},unfiltered_cli_lint:{exit:2,findings:53,errcheck:52,staticcheck:1},configured_cli_errortype:{exit:0},generators:{exit:0},cli_format:{exit:0},architecture_installation:{exit:0,pass:17},qualification_control:{exit:0,pass:23},full_cli:{exit:1,pass:89,fail:3},focused_cli:{exit:0,pass:29,duplicate_full_cli:true}},limits:['Canonical patched-driver Quick commands unavailable. Availability receipt exit1 is a prerequisite observation, not a collected test pass.','Full actual CLI source run is red with three retained host-bound assertions. No shim, assertion relaxation or native qualification.','Original doctor JSON ignored-writer status0/1 is pre-existing and unchanged, with no new waiver.','source-gaps.json is the chronological unresolved identity-validation delta observed before conductor criterion amendment; inspect the exact frozen task/spec amendment before acceptance.','Initial function-attribution.json has incorrect first-baseline key prefix and incomplete split-function aliases. function-attribution-corrected.json improves mapping; final-function-attribution.json and lint-attribution-frozen.json leave unmatched exact pre/post statements open for conductor classification, not waived.','source-reconstruction.json and source-reconstruction-corrected.json are helper authoring failures. source-reconstruction-complete.json and final-source-proof.json are the corrected proof runs.','R6 parsing half remains task5; no full R6, spec, native or aggregate completion claimed.','New receipts after freeze must live outside this directory; strict verifier rejects any additional file.'],product_edits:[],assertion_edits:[],waivers_added:[],stage:'impl-review - skipped(policy: host-deferred - conductor owns the gate)',commands_closed:true,lane_released_at_return:true};
 write('evidence.json',e);console.log(JSON.stringify({evidence_sha256:sha(read(out+'/evidence.json')),coverage:c.unique_top_level,pass:c.unique_pass,fail:c.unique_fail,duplicate:c.duplicated_observations,source_identity:e.source_identity.sha256}));
}
function freeze(){
 assert(existsSync(out+'/handover.md'));const before=walk(out).filter(p=>p!==out+'/freeze.json'),checks=before.map(p=>{const r=spawnSync('git',['diff','--no-index','--check','--','/dev/null',p],{cwd:root,maxBuffer:64<<20});assert([0,1,2].includes(r.status)&&!r.stderr.length,p+' whitespace-check tooling failed');return {path:relative(out,p),exit:r.status,stdout:r.stdout.toString(),stderr:r.stderr.toString(),sha256:sha(read(p)),findings:r.stdout.length>0,raw_bytes_preserved:true};});
 write('artifact-whitespace.json',{method:'Every existing new untracked artifact checked against /dev/null with git diff --no-index --check, without staging. Raw byte findings are retained verbatim; no whitespace suppression or waiver is inferred.',checks});
 const files=walk(out).filter(p=>p!==out+'/freeze.json').map(p=>({path:relative(out,p),bytes:read(p).length,sha256:sha(read(p))}));write('freeze.json',{task:'fn-109-gomad-deepen-modules-and-tool-interfaces.4',base_commit:base,captured_head:git(['rev-parse','HEAD']).toString().trim(),files,strict_directory:true,extra_files_allowed:[],verifier_receipts_must_be_external:true,native:false,review_verdict:null});console.log(JSON.stringify({files:files.length,freeze_sha256:sha(read(out+'/freeze.json')),evidence_sha256:sha(read(out+'/evidence.json'))}));
}
if(process.argv[1]===fileURLToPath(import.meta.url)){if(process.argv[2]==='prepare')prepare();else if(process.argv[2]==='freeze')freeze();else throw Error('Expected prepare or freeze');}
