import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {read,sha,git,write} from './capture.mjs';
import {reconstruct,spans,original,ref} from './proof.mjs';
const cli='tools/gomad3/cmd/gomad/internal/cli/';
function functionAt(source,n){const f=spans(source).find(f=>new RegExp('^func (?:\\([^)]*\\) )?'+n+'\\(').test(f.signature));assert(f,n);return {...f,sha256:sha(f.body)};}
export function gaps(){
 const r=reconstruct(),app=cli+'application.go',oldIdentity=functionAt(r.images[app],'identity'),currentInstall=functionAt(read(app).toString(),'install'),validator=functionAt(read(app).toString(),'digestRunner'),oldValidator=functionAt(r.images[app],'hashExecutable'),assertionPath=cli+'application_test.go',assertion=functionAt(read(assertionPath).toString(),'TestApplicationInstallFailsClosed');
 assert.equal(sha(git(['show','a3b9f80efab9356c0be2080779133337e2471ac0:'+app])),sha(r.images[app]));
 const reuseOwner='debca5eb56e7719c566eb4552a04279631982671',reuseParent=git(['rev-parse',reuseOwner+'^']).toString().trim(),patch=git(['diff','--no-ext-diff',reuseParent,reuseOwner,'--',app,assertionPath]).toString();
 const analyze='tools/gomad3/cmd/gomad/internal/cli/analyze.go',oldAnalyze=functionAt(r.images[analyze],'runAnalyzeWithApplication'),currentAnalyze=functionAt(read(analyze).toString(),'runAnalyze'),toolchainOnly=functionAt(read(app).toString(),'installedToolchain');
 return {status:'unresolved source-preservation gap; no expansion admitted',native_transferred:false,original_dirty_postimage_sha256:sha(r.images[app]),actual_original_commit:'a3b9f80efab9356c0be2080779133337e2471ac0',original_identity:oldIdentity,original_doctor_only_validator:oldValidator,current_install:currentInstall,current_shared_validator:validator,current_assertion:{path:assertionPath,...assertion},reuse_owner:{commit:reuseOwner,parent:reuseParent,metadata:git(['show','-s','--format=%H%n%P%n%B',reuseOwner]).toString(),actual_patch:patch,sha256:sha(patch)},validator_current_blame:git(['blame','--porcelain','-L',validator.start+','+validator.end,'--',app]).toString(),toolchain_only_analysis:{original_wrapper:oldAnalyze,current_wrapper:currentAnalyze,current_toolchain_method:toolchainOnly,original_already_hashed:true,mechanism:'Original runAnalyzeWithApplication injects app.identity, which resolves installation and hashes with os.ReadFile; current runAnalyze injects app.installedToolchain calling app.install and digestRunner. Existing hash dependency remains; shared mode/stat/read/close tightening and staged error changes apply.'},trigger:{construction:'Readable regular executable-path fixture containing runner bytes with mode0600, valid adjacent .toolchain, no prior identity cache',original:'application.identity resolves installation, os.ReadFile succeeds, returns sha256 Runner identity and private child commands',current:'application.install resolves installation, digestRunner rejects mode&0111==0 and returns hash gomad executable: Runner is not a regular executable: <path>',observed_current_assertion:'TestApplicationInstallFailsClosed/runner not executable passed in both retained CLI runs',original_runtime_reproduction_run:false,interpretation:'Exact source-level delta; no old-source test execution or preserved-behavior claim for this trigger'},error_text_delta:{original_missing:'hash gomad executable: <os.ReadFile error>',current_missing:'hash gomad executable: open Runner: <os.Open error>',additional_checks:['stat error','regular executable mode','io.Copy failure','Close failure'],close_precedence:'Current deferred Close failure changes successful digest into an error only if retErr is nil; original os.ReadFile does not expose an explicit Close error through its call site.'},contracts:[ref('.flow/tasks/fn-109-gomad-deepen-modules-and-tool-interfaces.4.md'),ref('.flow/specs/fn-109-gomad-deepen-modules-and-tool-interfaces.md'),ref('tools/gomad3/CLI.md')],waiver:null,product_or_test_edits:[],conductor_action:'Review this source-only preservation delta with exact original/current trigger before any completion or new mutation authority.'};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){write('source-gaps.json',gaps());console.log('Unresolved source-preservation gap retained; no native transfer or waiver.');}
