import assert from 'node:assert/strict';
import {existsSync,readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {root,out,read,sha,git,sources,write} from './capture.mjs';
import {apply,patchImages} from '../../task-2/source-acceptance-20261008/owner-chain.mjs';
export const original='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-4';
export const base='ec00b9d5aa17848edb74b3644a7f34cb1661803f';
export const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
export function spans(s){const lines=s.split('\n'),starts=lines.flatMap((l,i)=>l.startsWith('func ')?[i]:[]);return starts.map((n,i)=>({signature:lines[n],start:n+1,end:starts[i+1]??lines.length,body:lines.slice(n,starts[i+1]??lines.length).join('\n')}));}
export function reconstruct(){
 const pre=JSON.parse(read(original+'/preimage-manifest.json')),post=JSON.parse(read(original+'/final-source-manifest.json')),patch=read(original+'/task-only.patch').toString(),headers=[...patch.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],images={},preimages={},rows=[];
 assert.equal(headers.length,10);assert.equal(pre.length,21);
 for(const e of pre){assert.equal(sha(read(original+'/preimage/'+e.path)),e.sha256);assert.equal(read(original+'/preimage/'+e.path).length,e.bytes);}
 for(let i=0;i<headers.length;i++){
  const h=headers[i],path=h[2],before=h[1]==='/dev/null'?'':read(original+'/preimage/'+path).toString(),p=post.find(e=>e.path===path);assert(p);
  assert.equal(before?sha(before):null,p.before_sha256);const section=patch.slice(h.index+h[0].length,i+1<headers.length?headers[i+1].index:patch.length),after=apply(section,before,path);assert.equal(sha(after),p.after_sha256);assert.equal(Buffer.byteLength(after),p.after_bytes);
  images[path]=after;preimages[path]=before;rows.push({path,pre_sha256:before?sha(before):null,post_sha256:sha(after),current_sha256:sha(read(path)),unchanged:sha(after)===sha(read(path)),hunks:[...section.matchAll(/^@@.*$/gm)].map(m=>m[0])});
 }
 return {pre,images,preimages,rows,patch_sha256:sha(patch)};
}
export function staticProof(){
 const firstDir='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-21/baseline-reconstruction',be=JSON.parse(read(firstDir+'/evidence.json')),manifest=read(firstDir+'/source.sha256');assert.equal(sha(manifest),'d78601b3176195f8cc06860f5499e757a2d04333b9211f0ed13a92976b017845');
 const rows=manifest.toString().trim().split('\n').map(l=>{const m=/^([a-f0-9]{64})  (.+)$/.exec(l);assert(m);assert.equal(sha(read(be.scratch_path+'/'+m[2])),m[1]);return {path:m[2],sha256:m[1]};});assert.equal(rows.length,670);
 const bp='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-5/source-acceptance-20261008/source-binding.json',b=JSON.parse(read(bp));assert.equal(b.exact_bindings.length,87);for(const e of b.exact_bindings)assert.equal(sha(read(e.path)),e.sha256);assert.equal(sha(read(b.archive.path)),b.archive.sha256);
 const rawPath=b.retained_raw_manifest.path,raw=JSON.parse(read(rawPath));assert.equal(sha(read(rawPath)),b.retained_raw_manifest.sha256);let rawBytes=0;for(const e of raw){const bytes=read(rawPath.replace('/raw-manifest.json','/raw/')+(e.retained_name??e.name));if(e.retained_name)assert.equal(sha(bytes),e.retained_sha256);const decoded=e.encoding==='utf8-json-string'?Buffer.from(JSON.parse(bytes).value):bytes;assert.equal(decoded.length,e.bytes);assert.equal(sha(decoded),e.sha256);rawBytes+=decoded.length;}assert.equal(rawBytes,521317);assert.equal(raw.length,72);
 const changed=b.input_closure.filter(e=>sha(read(e.path))!==e.current_sha256);assert.deepEqual(changed.map(e=>e.path).sort(),['tools/gomad3/runner/completion_characterization_test.go','tools/gomad3/runner/internal/campaign/retained_evidence_test.go','tools/gomad3/runner/runner_test.go']);
 assert.equal(sha(read(b.positive_inventory.receipt)),b.positive_inventory.receipt_sha256);assert.deepEqual(b.positive_inventory.platforms,['darwin/arm64','linux/amd64']);
 const inventoryReceipt=JSON.parse(read(b.positive_inventory.receipt)),inventoryLog=read(b.positive_inventory.receipt.replace(/\.json$/,'.stdout'));assert.equal(inventoryReceipt.exit,0);assert.equal(sha(inventoryLog),b.positive_inventory.log_sha256);assert.equal(inventoryReceipt.stdout_sha256,sha(inventoryLog));assert(inventoryLog.toString().split('\n').some(l=>l.includes('platforms=[darwin/arm64 linux/amd64] draw rows=273 seeded rows=86 clock rows=48 goroutine rows=10')));assert(!inventoryLog.toString().split('\n').some(l=>l.startsWith('--- SKIP:')));
 return {first_fn109_baseline:{commit:be.base_revision,kind:be.baseline_kind,inputs:670,manifest:ref(firstDir+'/source.sha256'),later38957053_substituted:false},runtime_inputs:b.exact_bindings,retained_raw_files:72,retained_decoded_bytes:rawBytes,archive:b.archive,supported_static_inventories:b.positive_inventory,binding:ref(bp),unchanged_closure:1220,changed_unreused:changed.map(e=>({path:e.path,current_sha256:sha(read(e.path)),owner:e.path.endsWith('retained_evidence_test.go')?'Done fn112.16':'Done fn109.3 exact statistics restoration',old_pass_reused:false})),native:false};
}
function lineage(path){
 const commits=[...new Set(['d635e23f00d926a43b942f25a9d05bd0ccb72025','9032202898117bce5a38aa04078da136e4f767bf'].flatMap(start=>git(['log','--ancestry-path','--full-history','--format=%H',start+'..HEAD','--',path]).toString().trim().split('\n').filter(Boolean)))],rows=[];
 for(const commit of commits){
  const metadata=git(['show','-s','--format=%H%n%P%n%s%n%B',commit]).toString(),parents=metadata.split('\n')[1].split(' ').filter(Boolean);
  for(const parent of parents){const d=git(['diff','--no-ext-diff','--no-renames',parent,commit,'--',path]).toString();if(d)rows.push({commit,parent,metadata,patch_sha256:sha(d),patch:d});}
 }
 return rows;
}
export function build(){
 const r=reconstruct(),five=patchImages(5),six=patchImages(6),a3='a3b9f80efab9356c0be2080779133337e2471ac0',merge='ca3345469a2541b7686606268b0f19cde030a8fe',rebased='debca5eb56e7719c566eb4552a04279631982671',oldReview=JSON.parse(read(original+'/working-tree-review.json'));
 assert.equal(oldReview.findings.baseSha,'d635e23f00d926a43b942f25a9d05bd0ccb72025');assert.equal(git(['rev-parse',a3+'^']).toString().trim(),oldReview.findings.baseSha);
 const owners=r.rows.map(row=>{let image=r.images[row.path];const later=[];for(const [id,patch] of [[5,five],[6,six]]){if(Object.hasOwn(patch.pre,row.path)){assert.equal(image,patch.pre[row.path],row.path+' task'+id+' adjacency');image=patch.images[row.path];later.push({task:id,pre_sha256:sha(patch.pre[row.path]),post_sha256:sha(image),patch_sha256:patch.patch_sha256});}}
  const integrated=git(['show',a3+':'+row.path]),remote=git(['ls-tree',rebased,'--',row.path]).length?git(['show',rebased+':'+row.path]):null,current=read(row.path),merged=git(['show',merge+':'+row.path]);
  if(row.path.endsWith('/analyze.go')){const directory=original.replace(/task-4$/,'task-8'),patch=read(directory+'/task-only.patch').toString(),heads=[...patch.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],i=heads.findIndex(h=>h[2]===row.path);assert(i>=0);assert.equal(image,read(directory+'/preimages/'+row.path).toString());image=apply(patch.slice(heads[i].index+heads[i][0].length,i+1<heads.length?heads[i+1].index:patch.length),image,row.path);assert.equal(sha(image),JSON.parse(read(directory+'/source-freeze.json')).sources[row.path]);later.push({task:8,post_sha256:sha(image),patch_sha256:sha(patch)});}
  assert.equal(sha(image),sha(integrated),row.path+' old integrated after later local owners');
  return {...row,local_later_owners:later,local_integrated_sha256:sha(integrated),rebased_task4_sha256:remote?sha(remote):null,merge_sha256:sha(merged),current_equals_merge:sha(current)===sha(merged),actual_owner_transitions:lineage(row.path)};
 });
 const cli='tools/gomad3/cmd/gomad/internal/cli',files=git(['ls-files',cli]).toString().trim().split('\n').filter(Boolean),consumerFiles=files.filter(p=>p.endsWith('.go')&&!p.endsWith('_test.go'));
 const consumers=consumerFiles.flatMap(path=>spans(read(path).toString()).filter(f=>/app\.(?:install|installedToolchain|resolveInstallation|executablePath|run|exploreDependencies)|installed\.(?:supervisorCommand|coordinatorCommand)/.test(f.body)).map(f=>({path,...f,sha256:sha(f.body),actual_blame:git(['blame','--porcelain','-L',f.start+','+f.end,'--',path]).toString()})));
 const resolution=consumerFiles.flatMap(path=>read(path).toString().split('\n').flatMap((line,i)=>/os\.Executable|toolchain\.ResolveInstallation/.test(line)?[{path,line:i+1,text:line}]:[]));assert.equal(resolution.length,2);assert(resolution.every(e=>e.path===cli+'/application.go'));
 const charPath=cli+'/application_characterization_test.go',oldChars=spans(r.images[charPath]).filter(f=>/^func Test/.test(f.signature)),currentChars=spans(read(charPath).toString());const chars=oldChars.map(f=>{const found=currentChars.find(c=>c.signature===f.signature);assert(found);return {signature:f.signature,original_body:f.body,original_sha256:sha(f.body),current_body:found.body,current_sha256:sha(found.body),unchanged:f.body===found.body,current_blame:git(['blame','--porcelain','-L',found.start+','+found.end,'--',charPath]).toString()};});
 assert.equal(chars.length,4);assert.equal(chars.filter(e=>e.unchanged).length,3);const qualify=chars.find(e=>!e.unchanged),marker='\t\targuments :=';assert(qualify.original_body.indexOf(marker)>=0);assert.equal(qualify.original_body.slice(qualify.original_body.indexOf(marker)),qualify.current_body.slice(qualify.current_body.indexOf(marker)));qualify.assertions_and_argv_suffix_sha256=sha(qualify.original_body.slice(qualify.original_body.indexOf(marker)));qualify.change_bound='Only dependency-construction prefix differs; all original argv/environment/tag/output/status assertions from arguments declaration through function end are exact bytes.';
 const dependencies=consumerFiles.filter(p=>/Dependencies struct/.test(read(p).toString())).map(path=>({source:ref(path),structs:[...read(path).toString().matchAll(/type (\w+Dependencies) struct \{[\s\S]*?\n\}/g)].map(m=>m[0])}));
 const userFiles=['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(ref);assert.equal(userFiles[0].sha256,'97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188');assert.equal(userFiles[1].sha256,'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287');
 return {base_commit:base,source_identity_sha256:sha(JSON.stringify(sources())),original:{snapshot_count:21,modified_postimages:7,added_postimages:3,patch:ref(original+'/task-only.patch'),committed_lint_parent:oldReview.findings.baseSha,parent_derivation:'actual original review metadata baseSha and git parent of a3b9f80; dirty original task4 postimages separately rederived from retained21 preimages and exact10 patch sections',preimages:r.pre,postimages:r.rows},owners,consumer_inventory:consumers,resolution_owner:resolution,dependency_seams:dependencies,characterization:chars,current_cli_sources:files.map(ref),contracts:['tools/gomad3/CLI.md','tools/gomad3/toolchain/installation.go','tools/gomad3/toolchain/installation/installation.go','tools/gomad3/go.mod','.github/.golangci.yml','Makefile','tools/gomad3/Makefile'].filter(p=>existsSync(root+'/'+p)).map(ref),static_bindings:staticProof(),user_files:userFiles,product_edits:[],native:false,review_verdict:null};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){write('source-proof-final.json',build());console.log('final source proof written; original checkpoint retained');}
