// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/testpilot/v1/event.proto

package testpilot

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunEventKind names the lifecycle fact one Run Event records.
// (-- api-linter: core::0191::file-layout=disabled
//
//	core::0216::synonyms=disabled --)
type RunEventKind int32

const (
	RUN_EVENT_KIND_UNSPECIFIED           RunEventKind = 0
	RUN_EVENT_KIND_RUN_OPENED            RunEventKind = 1
	RUN_EVENT_KIND_ACTIVATION_OPENED     RunEventKind = 2
	RUN_EVENT_KIND_INSTRUCTION_STARTED   RunEventKind = 3
	RUN_EVENT_KIND_INSTRUCTION_COMPLETED RunEventKind = 4
	RUN_EVENT_KIND_INSTRUCTION_TIMED_OUT RunEventKind = 5
	RUN_EVENT_KIND_ACTIVATION_CLOSED     RunEventKind = 6
	RUN_EVENT_KIND_CLEANUP_STARTED       RunEventKind = 7
	RUN_EVENT_KIND_CLEANUP_COMPLETED     RunEventKind = 8
	RUN_EVENT_KIND_RUN_CLOSED            RunEventKind = 9
	RUN_EVENT_KIND_DIAGNOSTIC            RunEventKind = 10
	RUN_EVENT_KIND_FAULT_INJECTED        RunEventKind = 11
)

// Enum value maps for RunEventKind.
var (
	RunEventKind_name = map[int32]string{
		0:  "RUN_EVENT_KIND_UNSPECIFIED",
		1:  "RUN_EVENT_KIND_RUN_OPENED",
		2:  "RUN_EVENT_KIND_ACTIVATION_OPENED",
		3:  "RUN_EVENT_KIND_INSTRUCTION_STARTED",
		4:  "RUN_EVENT_KIND_INSTRUCTION_COMPLETED",
		5:  "RUN_EVENT_KIND_INSTRUCTION_TIMED_OUT",
		6:  "RUN_EVENT_KIND_ACTIVATION_CLOSED",
		7:  "RUN_EVENT_KIND_CLEANUP_STARTED",
		8:  "RUN_EVENT_KIND_CLEANUP_COMPLETED",
		9:  "RUN_EVENT_KIND_RUN_CLOSED",
		10: "RUN_EVENT_KIND_DIAGNOSTIC",
		11: "RUN_EVENT_KIND_FAULT_INJECTED",
	}
	RunEventKind_value = map[string]int32{
		"RUN_EVENT_KIND_UNSPECIFIED":           0,
		"RUN_EVENT_KIND_RUN_OPENED":            1,
		"RUN_EVENT_KIND_ACTIVATION_OPENED":     2,
		"RUN_EVENT_KIND_INSTRUCTION_STARTED":   3,
		"RUN_EVENT_KIND_INSTRUCTION_COMPLETED": 4,
		"RUN_EVENT_KIND_INSTRUCTION_TIMED_OUT": 5,
		"RUN_EVENT_KIND_ACTIVATION_CLOSED":     6,
		"RUN_EVENT_KIND_CLEANUP_STARTED":       7,
		"RUN_EVENT_KIND_CLEANUP_COMPLETED":     8,
		"RUN_EVENT_KIND_RUN_CLOSED":            9,
		"RUN_EVENT_KIND_DIAGNOSTIC":            10,
		"RUN_EVENT_KIND_FAULT_INJECTED":        11,
	}
)

func (x RunEventKind) Enum() *RunEventKind {
	p := new(RunEventKind)
	*p = x
	return p
}

func (x RunEventKind) String() string {
	switch x {
	case RUN_EVENT_KIND_UNSPECIFIED:
		return "Unspecified"
	case RUN_EVENT_KIND_RUN_OPENED:
		return "RunOpened"
	case RUN_EVENT_KIND_ACTIVATION_OPENED:
		return "ActivationOpened"
	case RUN_EVENT_KIND_INSTRUCTION_STARTED:
		return "InstructionStarted"
	case RUN_EVENT_KIND_INSTRUCTION_COMPLETED:
		return "InstructionCompleted"
	case RUN_EVENT_KIND_INSTRUCTION_TIMED_OUT:
		return "InstructionTimedOut"
	case RUN_EVENT_KIND_ACTIVATION_CLOSED:
		return "ActivationClosed"
	case RUN_EVENT_KIND_CLEANUP_STARTED:

		// Deprecated: Use RunEventKind.Descriptor instead.
		return "CleanupStarted"
	case RUN_EVENT_KIND_CLEANUP_COMPLETED:
		return "CleanupCompleted"
	case RUN_EVENT_KIND_RUN_CLOSED:
		return "RunClosed"
	case RUN_EVENT_KIND_DIAGNOSTIC:
		return "Diagnostic"
	case

		// RunEventField names one coordinate every Run Event has. Kind-specific data is read through the
		// event's payload instead.
		RUN_EVENT_KIND_FAULT_INJECTED:
		return "FaultInjected"
	default:
		return strconv.Itoa(int(x))
	}

}

func (RunEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_event_proto_enumTypes[0].Descriptor()
}

func (RunEventKind) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_event_proto_enumTypes[0]
}

func (x RunEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (RunEventKind) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_event_proto_rawDescGZIP(), []int{0}
}

type RunEventField int32

const (
	RUN_EVENT_FIELD_UNSPECIFIED          RunEventField = 0
	RUN_EVENT_FIELD_SEQUENCE             RunEventField = 1
	RUN_EVENT_FIELD_ELAPSED_MILLISECONDS RunEventField = 2
	RUN_EVENT_FIELD_KIND                 RunEventField = 3
	RUN_EVENT_FIELD_ENTRYPOINT_ID        RunEventField = 4
	RUN_EVENT_FIELD_ACTIVATION_ID        RunEventField = 5
	RUN_EVENT_FIELD_INSTRUCTION_ID       RunEventField = 6
	RUN_EVENT_FIELD_ATTEMPT              RunEventField = 7
	RUN_EVENT_FIELD_SOURCE_ID            RunEventField = 8
	RUN_EVENT_FIELD_RUN_ID               RunEventField = 9
)

// Enum value maps for RunEventField.
var (
	RunEventField_name = map[int32]string{
		0: "RUN_EVENT_FIELD_UNSPECIFIED",
		1: "RUN_EVENT_FIELD_SEQUENCE",
		2: "RUN_EVENT_FIELD_ELAPSED_MILLISECONDS",
		3: "RUN_EVENT_FIELD_KIND",
		4: "RUN_EVENT_FIELD_ENTRYPOINT_ID",
		5: "RUN_EVENT_FIELD_ACTIVATION_ID",
		6: "RUN_EVENT_FIELD_INSTRUCTION_ID",
		7: "RUN_EVENT_FIELD_ATTEMPT",
		8: "RUN_EVENT_FIELD_SOURCE_ID",
		9: "RUN_EVENT_FIELD_RUN_ID",
	}
	RunEventField_value = map[string]int32{
		"RUN_EVENT_FIELD_UNSPECIFIED":          0,
		"RUN_EVENT_FIELD_SEQUENCE":             1,
		"RUN_EVENT_FIELD_ELAPSED_MILLISECONDS": 2,
		"RUN_EVENT_FIELD_KIND":                 3,
		"RUN_EVENT_FIELD_ENTRYPOINT_ID":        4,
		"RUN_EVENT_FIELD_ACTIVATION_ID":        5,
		"RUN_EVENT_FIELD_INSTRUCTION_ID":       6,
		"RUN_EVENT_FIELD_ATTEMPT":              7,
		"RUN_EVENT_FIELD_SOURCE_ID":            8,
		"RUN_EVENT_FIELD_RUN_ID":               9,
	}
)

func (x RunEventField) Enum() *RunEventField {
	p := new(RunEventField)
	*p = x
	return p
}

func (x RunEventField) String() string {
	switch x {
	case RUN_EVENT_FIELD_UNSPECIFIED:
		return "Unspecified"
	case RUN_EVENT_FIELD_SEQUENCE:
		return "Sequence"
	case RUN_EVENT_FIELD_ELAPSED_MILLISECONDS:
		return "ElapsedMilliseconds"
	case RUN_EVENT_FIELD_KIND:
		return "Kind"
	case RUN_EVENT_FIELD_ENTRYPOINT_ID:
		return "EntrypointId"
	case RUN_EVENT_FIELD_ACTIVATION_ID:
		return "ActivationId"
	case RUN_EVENT_FIELD_INSTRUCTION_ID:
		return "InstructionId"
	case RUN_EVENT_FIELD_ATTEMPT:
		return "Attempt"
	case RUN_EVENT_FIELD_SOURCE_ID:
		return "SourceId"

		// Deprecated: Use RunEventField.Descriptor instead.
	case RUN_EVENT_FIELD_RUN_ID:
		return "RunId"
	default:
		return strconv.Itoa(int(x))
	}

}

func (RunEventField) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_event_proto_enumTypes[1].Descriptor()
}

func (RunEventField) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_event_proto_enumTypes[1]
}

func (x RunEventField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (RunEventField) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_event_proto_rawDescGZIP(), []int{1}
}

// RunEventFilter selects the Run Events a Contract transition considers by kind.
type RunEventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []RunEventKind         `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=temporal.server.api.testpilot.v1.RunEventKind" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEventFilter) Reset() {
	*x = RunEventFilter{}
	mi := &file_temporal_server_api_testpilot_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEventFilter) ProtoMessage() {}

func (x *RunEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEventFilter.ProtoReflect.Descriptor instead.
func (*RunEventFilter) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *RunEventFilter) GetKinds() []RunEventKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

var File_temporal_server_api_testpilot_v1_event_proto protoreflect.FileDescriptor

const file_temporal_server_api_testpilot_v1_event_proto_rawDesc = "" +
	"\n" +
	",temporal/server/api/testpilot/v1/event.proto\x12 temporal.server.api.testpilot.v1\"V\n" +
	"\x0eRunEventFilter\x12D\n" +
	"\x05kinds\x18\x01 \x03(\x0e2..temporal.server.api.testpilot.v1.RunEventKindR\x05kinds*\xc0\x03\n" +
	"\fRunEventKind\x12\x1e\n" +
	"\x1aRUN_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RUN_EVENT_KIND_RUN_OPENED\x10\x01\x12$\n" +
	" RUN_EVENT_KIND_ACTIVATION_OPENED\x10\x02\x12&\n" +
	"\"RUN_EVENT_KIND_INSTRUCTION_STARTED\x10\x03\x12(\n" +
	"$RUN_EVENT_KIND_INSTRUCTION_COMPLETED\x10\x04\x12(\n" +
	"$RUN_EVENT_KIND_INSTRUCTION_TIMED_OUT\x10\x05\x12$\n" +
	" RUN_EVENT_KIND_ACTIVATION_CLOSED\x10\x06\x12\"\n" +
	"\x1eRUN_EVENT_KIND_CLEANUP_STARTED\x10\a\x12$\n" +
	" RUN_EVENT_KIND_CLEANUP_COMPLETED\x10\b\x12\x1d\n" +
	"\x19RUN_EVENT_KIND_RUN_CLOSED\x10\t\x12\x1d\n" +
	"\x19RUN_EVENT_KIND_DIAGNOSTIC\x10\n" +
	"\x12!\n" +
	"\x1dRUN_EVENT_KIND_FAULT_INJECTED\x10\v*\xd4\x02\n" +
	"\rRunEventField\x12\x1f\n" +
	"\x1bRUN_EVENT_FIELD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RUN_EVENT_FIELD_SEQUENCE\x10\x01\x12(\n" +
	"$RUN_EVENT_FIELD_ELAPSED_MILLISECONDS\x10\x02\x12\x18\n" +
	"\x14RUN_EVENT_FIELD_KIND\x10\x03\x12!\n" +
	"\x1dRUN_EVENT_FIELD_ENTRYPOINT_ID\x10\x04\x12!\n" +
	"\x1dRUN_EVENT_FIELD_ACTIVATION_ID\x10\x05\x12\"\n" +
	"\x1eRUN_EVENT_FIELD_INSTRUCTION_ID\x10\x06\x12\x1b\n" +
	"\x17RUN_EVENT_FIELD_ATTEMPT\x10\a\x12\x1d\n" +
	"\x19RUN_EVENT_FIELD_SOURCE_ID\x10\b\x12\x1a\n" +
	"\x16RUN_EVENT_FIELD_RUN_ID\x10\tB2Z0go.temporal.io/server/api/testpilot/v1;testpilotb\x06proto3"

var (
	file_temporal_server_api_testpilot_v1_event_proto_rawDescOnce sync.Once
	file_temporal_server_api_testpilot_v1_event_proto_rawDescData []byte
)

func file_temporal_server_api_testpilot_v1_event_proto_rawDescGZIP() []byte {
	file_temporal_server_api_testpilot_v1_event_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_testpilot_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_event_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_event_proto_rawDesc)))
	})
	return file_temporal_server_api_testpilot_v1_event_proto_rawDescData
}

var file_temporal_server_api_testpilot_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_temporal_server_api_testpilot_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_temporal_server_api_testpilot_v1_event_proto_goTypes = []any{
	(RunEventKind)(0),      // 0: temporal.server.api.testpilot.v1.RunEventKind
	(RunEventField)(0),     // 1: temporal.server.api.testpilot.v1.RunEventField
	(*RunEventFilter)(nil), // 2: temporal.server.api.testpilot.v1.RunEventFilter
}
var file_temporal_server_api_testpilot_v1_event_proto_depIdxs = []int32{
	0, // 0: temporal.server.api.testpilot.v1.RunEventFilter.kinds:type_name -> temporal.server.api.testpilot.v1.RunEventKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_temporal_server_api_testpilot_v1_event_proto_init() }
func file_temporal_server_api_testpilot_v1_event_proto_init() {
	if File_temporal_server_api_testpilot_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_event_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_testpilot_v1_event_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_testpilot_v1_event_proto_depIdxs,
		EnumInfos:         file_temporal_server_api_testpilot_v1_event_proto_enumTypes,
		MessageInfos:      file_temporal_server_api_testpilot_v1_event_proto_msgTypes,
	}.Build()
	File_temporal_server_api_testpilot_v1_event_proto = out.File
	file_temporal_server_api_testpilot_v1_event_proto_goTypes = nil
	file_temporal_server_api_testpilot_v1_event_proto_depIdxs = nil
}
