// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/testpilot/v1/evidence.proto

package testpilot

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	expr "cel.dev/expr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvidenceDeclaration owns extraction; independent Contract policies own retention and admission.
type EvidenceDeclaration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId     string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	EvidenceSource string                 `protobuf:"bytes,2,opt,name=evidence_source,json=evidenceSource,proto3" json:"evidence_source,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*EvidenceDeclaration_HistoryEvent
	//	*EvidenceDeclaration_RunEvent
	//	*EvidenceDeclaration_Read
	//	*EvidenceDeclaration_Projected
	Source        isEvidenceDeclaration_Source `protobuf_oneof:"source"`
	Scope         []*NamedExpression           `protobuf:"bytes,7,rep,name=scope,proto3" json:"scope,omitempty"`
	Operation     *Expression                  `protobuf:"bytes,8,opt,name=operation,proto3" json:"operation,omitempty"`
	Fields        []*NamedExpression           `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	Guard         *Expression                  `protobuf:"bytes,10,opt,name=guard,proto3" json:"guard,omitempty"`
	Kind          string                       `protobuf:"bytes,11,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceDeclaration) Reset() {
	*x = EvidenceDeclaration{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceDeclaration) ProtoMessage() {}

func (x *EvidenceDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceDeclaration.ProtoReflect.Descriptor instead.
func (*EvidenceDeclaration) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceDeclaration) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *EvidenceDeclaration) GetEvidenceSource() string {
	if x != nil {
		return x.EvidenceSource
	}
	return ""
}

func (x *EvidenceDeclaration) GetSource() isEvidenceDeclaration_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *EvidenceDeclaration) GetHistoryEvent() *HistoryEventSource {
	if x != nil {
		if x, ok := x.Source.(*EvidenceDeclaration_HistoryEvent); ok {
			return x.HistoryEvent
		}
	}
	return nil
}

func (x *EvidenceDeclaration) GetRunEvent() *RunEventSource {
	if x != nil {
		if x, ok := x.Source.(*EvidenceDeclaration_RunEvent); ok {
			return x.RunEvent
		}
	}
	return nil
}

func (x *EvidenceDeclaration) GetRead() *ReadSource {
	if x != nil {
		if x, ok := x.Source.(*EvidenceDeclaration_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *EvidenceDeclaration) GetProjected() *ProjectedSource {
	if x != nil {
		if x, ok := x.Source.(*EvidenceDeclaration_Projected); ok {
			return x.Projected
		}
	}
	return nil
}

func (x *EvidenceDeclaration) GetScope() []*NamedExpression {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *EvidenceDeclaration) GetOperation() *Expression {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *EvidenceDeclaration) GetFields() []*NamedExpression {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EvidenceDeclaration) GetGuard() *Expression {
	if x != nil {
		return x.Guard
	}
	return nil
}

func (x *EvidenceDeclaration) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type isEvidenceDeclaration_Source interface {
	isEvidenceDeclaration_Source()
}

type EvidenceDeclaration_HistoryEvent struct {
	HistoryEvent *HistoryEventSource `protobuf:"bytes,3,opt,name=history_event,json=historyEvent,proto3,oneof"`
}

type EvidenceDeclaration_RunEvent struct {
	RunEvent *RunEventSource `protobuf:"bytes,4,opt,name=run_event,json=runEvent,proto3,oneof"`
}

type EvidenceDeclaration_Read struct {
	Read *ReadSource `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type EvidenceDeclaration_Projected struct {
	Projected *ProjectedSource `protobuf:"bytes,6,opt,name=projected,proto3,oneof"`
}

func (*EvidenceDeclaration_HistoryEvent) isEvidenceDeclaration_Source() {}

func (*EvidenceDeclaration_RunEvent) isEvidenceDeclaration_Source() {}

func (*EvidenceDeclaration_Read) isEvidenceDeclaration_Source() {}

func (*EvidenceDeclaration_Projected) isEvidenceDeclaration_Source() {}

// HistoryEventSource selects one descriptor-checked history attributes member.
type HistoryEventSource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttributesField string                 `protobuf:"bytes,1,opt,name=attributes_field,json=attributesField,proto3" json:"attributes_field,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoryEventSource) Reset() {
	*x = HistoryEventSource{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEventSource) ProtoMessage() {}

func (x *HistoryEventSource) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEventSource.ProtoReflect.Descriptor instead.
func (*HistoryEventSource) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryEventSource) GetAttributesField() string {
	if x != nil {
		return x.AttributesField
	}
	return ""
}

// RunEventSource restricts extraction to one event kind and optional controller instruction.
type RunEventSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          RunEventKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=temporal.server.api.testpilot.v1.RunEventKind" json:"kind,omitempty"`
	Instruction   *InstructionReference  `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	RunKeyed      bool                   `protobuf:"varint,3,opt,name=run_keyed,json=runKeyed,proto3" json:"run_keyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEventSource) Reset() {
	*x = RunEventSource{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEventSource) ProtoMessage() {}

func (x *RunEventSource) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEventSource.ProtoReflect.Descriptor instead.
func (*RunEventSource) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{2}
}

func (x *RunEventSource) GetKind() RunEventKind {
	if x != nil {
		return x.Kind
	}
	return RUN_EVENT_KIND_UNSPECIFIED
}

func (x *RunEventSource) GetInstruction() *InstructionReference {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *RunEventSource) GetRunKeyed() bool {
	if x != nil {
		return x.RunKeyed
	}
	return false
}

// The descriptor-checked path determines singular versus repeated source values.
type ReadSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSource) Reset() {
	*x = ReadSource{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSource) ProtoMessage() {}

func (x *ReadSource) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSource.ProtoReflect.Descriptor instead.
func (*ReadSource) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{3}
}

func (x *ReadSource) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReadSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ProjectedSource declares the exact type accepted from a response lift.
type ProjectedSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *ValueType             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectedSource) Reset() {
	*x = ProjectedSource{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectedSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectedSource) ProtoMessage() {}

func (x *ProjectedSource) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectedSource.ProtoReflect.Descriptor instead.
func (*ProjectedSource) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectedSource) GetType() *ValueType {
	if x != nil {
		return x.Type
	}
	return nil
}

// Response declarations are selected in this order, stopping at the first matching guard.
type CorrelatedEvidenceProjection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservationId string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	EvidenceIds   []string               `protobuf:"bytes,2,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelatedEvidenceProjection) Reset() {
	*x = CorrelatedEvidenceProjection{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedEvidenceProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedEvidenceProjection) ProtoMessage() {}

func (x *CorrelatedEvidenceProjection) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedEvidenceProjection.ProtoReflect.Descriptor instead.
func (*CorrelatedEvidenceProjection) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{5}
}

func (x *CorrelatedEvidenceProjection) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *CorrelatedEvidenceProjection) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

// NamedExpression computes one scope or evidence field using its admitted CEL environment.
type NamedExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value         *Expression            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedExpression) Reset() {
	*x = NamedExpression{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedExpression) ProtoMessage() {}

func (x *NamedExpression) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedExpression.ProtoReflect.Descriptor instead.
func (*NamedExpression) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{6}
}

func (x *NamedExpression) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *NamedExpression) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

// Source ordinals and causal parents carry semantic order independently of Run elapsed time.
type CorrelatedEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *CorrelatedIdentity    `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Parents       []*CorrelatedIdentity  `protobuf:"bytes,4,rep,name=parents,proto3" json:"parents,omitempty"`
	Fields        []*NamedValue          `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelatedEvidence) Reset() {
	*x = CorrelatedEvidence{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedEvidence) ProtoMessage() {}

func (x *CorrelatedEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedEvidence.ProtoReflect.Descriptor instead.
func (*CorrelatedEvidence) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{7}
}

func (x *CorrelatedEvidence) GetIdentity() *CorrelatedIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CorrelatedEvidence) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CorrelatedEvidence) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CorrelatedEvidence) GetParents() []*CorrelatedIdentity {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *CorrelatedEvidence) GetFields() []*NamedValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// CorrelatedIdentity names one occurrence in a dense source stream within an explicit scope.
type CorrelatedIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          []*NamedValue          `protobuf:"bytes,1,rep,name=scope,proto3" json:"scope,omitempty"`
	EvidenceSource string                 `protobuf:"bytes,2,opt,name=evidence_source,json=evidenceSource,proto3" json:"evidence_source,omitempty"`
	Ordinal        int64                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CorrelatedIdentity) Reset() {
	*x = CorrelatedIdentity{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedIdentity) ProtoMessage() {}

func (x *CorrelatedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedIdentity.ProtoReflect.Descriptor instead.
func (*CorrelatedIdentity) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{8}
}

func (x *CorrelatedIdentity) GetScope() []*NamedValue {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CorrelatedIdentity) GetEvidenceSource() string {
	if x != nil {
		return x.EvidenceSource
	}
	return ""
}

func (x *CorrelatedIdentity) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// NamedValue carries one scope or evidence field; an absent value records redaction.
type NamedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value         *expr.Value            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValue) Reset() {
	*x = NamedValue{}
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValue) ProtoMessage() {}

func (x *NamedValue) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValue.ProtoReflect.Descriptor instead.
func (*NamedValue) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP(), []int{9}
}

func (x *NamedValue) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *NamedValue) GetValue() *expr.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_temporal_server_api_testpilot_v1_evidence_proto protoreflect.FileDescriptor

const file_temporal_server_api_testpilot_v1_evidence_proto_rawDesc = "" +
	"\n" +
	"/temporal/server/api/testpilot/v1/evidence.proto\x12 temporal.server.api.testpilot.v1\x1a\x14cel/expr/value.proto\x1a,temporal/server/api/testpilot/v1/event.proto\x1a1temporal/server/api/testpilot/v1/expression.proto\x1a,temporal/server/api/testpilot/v1/value.proto\"\xe6\x05\n" +
	"\x13EvidenceDeclaration\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12'\n" +
	"\x0fevidence_source\x18\x02 \x01(\tR\x0eevidenceSource\x12[\n" +
	"\rhistory_event\x18\x03 \x01(\v24.temporal.server.api.testpilot.v1.HistoryEventSourceH\x00R\fhistoryEvent\x12O\n" +
	"\trun_event\x18\x04 \x01(\v20.temporal.server.api.testpilot.v1.RunEventSourceH\x00R\brunEvent\x12B\n" +
	"\x04read\x18\x05 \x01(\v2,.temporal.server.api.testpilot.v1.ReadSourceH\x00R\x04read\x12Q\n" +
	"\tprojected\x18\x06 \x01(\v21.temporal.server.api.testpilot.v1.ProjectedSourceH\x00R\tprojected\x12G\n" +
	"\x05scope\x18\a \x03(\v21.temporal.server.api.testpilot.v1.NamedExpressionR\x05scope\x12J\n" +
	"\toperation\x18\b \x01(\v2,.temporal.server.api.testpilot.v1.ExpressionR\toperation\x12I\n" +
	"\x06fields\x18\t \x03(\v21.temporal.server.api.testpilot.v1.NamedExpressionR\x06fields\x12B\n" +
	"\x05guard\x18\n" +
	" \x01(\v2,.temporal.server.api.testpilot.v1.ExpressionR\x05guard\x12\x12\n" +
	"\x04kind\x18\v \x01(\tR\x04kindB\b\n" +
	"\x06source\"?\n" +
	"\x12HistoryEventSource\x12)\n" +
	"\x10attributes_field\x18\x01 \x01(\tR\x0fattributesField\"\xd2\x01\n" +
	"\x0eRunEventSource\x12B\n" +
	"\x04kind\x18\x01 \x01(\x0e2..temporal.server.api.testpilot.v1.RunEventKindR\x04kind\x12X\n" +
	"\vinstruction\x18\x02 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\vinstruction\x12\x1b\n" +
	"\trun_keyed\x18\x03 \x01(\bR\brunKeyedR\x05guard\"F\n" +
	"\n" +
	"ReadSource\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04pathJ\x04\b\x03\x10\x04R\x06single\"R\n" +
	"\x0fProjectedSource\x12?\n" +
	"\x04type\x18\x01 \x01(\v2+.temporal.server.api.testpilot.v1.ValueTypeR\x04type\"h\n" +
	"\x1cCorrelatedEvidenceProjection\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12!\n" +
	"\fevidence_ids\x18\x02 \x03(\tR\vevidenceIds\"p\n" +
	"\x0fNamedExpression\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.temporal.server.api.testpilot.v1.ExpressionR\x05value\"\xae\x02\n" +
	"\x12CorrelatedEvidence\x12P\n" +
	"\bidentity\x18\x01 \x01(\v24.temporal.server.api.testpilot.v1.CorrelatedIdentityR\bidentity\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12N\n" +
	"\aparents\x18\x04 \x03(\v24.temporal.server.api.testpilot.v1.CorrelatedIdentityR\aparents\x12D\n" +
	"\x06fields\x18\x05 \x03(\v2,.temporal.server.api.testpilot.v1.NamedValueR\x06fields\"\x9b\x01\n" +
	"\x12CorrelatedIdentity\x12B\n" +
	"\x05scope\x18\x01 \x03(\v2,.temporal.server.api.testpilot.v1.NamedValueR\x05scope\x12'\n" +
	"\x0fevidence_source\x18\x02 \x01(\tR\x0eevidenceSource\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x03R\aordinal\"N\n" +
	"\n" +
	"NamedValue\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.cel.expr.ValueR\x05valueB2Z0go.temporal.io/server/api/testpilot/v1;testpilotb\x06proto3"

var (
	file_temporal_server_api_testpilot_v1_evidence_proto_rawDescOnce sync.Once
	file_temporal_server_api_testpilot_v1_evidence_proto_rawDescData []byte
)

func file_temporal_server_api_testpilot_v1_evidence_proto_rawDescGZIP() []byte {
	file_temporal_server_api_testpilot_v1_evidence_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_testpilot_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_evidence_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_evidence_proto_rawDesc)))
	})
	return file_temporal_server_api_testpilot_v1_evidence_proto_rawDescData
}

var file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_temporal_server_api_testpilot_v1_evidence_proto_goTypes = []any{
	(*EvidenceDeclaration)(nil),          // 0: temporal.server.api.testpilot.v1.EvidenceDeclaration
	(*HistoryEventSource)(nil),           // 1: temporal.server.api.testpilot.v1.HistoryEventSource
	(*RunEventSource)(nil),               // 2: temporal.server.api.testpilot.v1.RunEventSource
	(*ReadSource)(nil),                   // 3: temporal.server.api.testpilot.v1.ReadSource
	(*ProjectedSource)(nil),              // 4: temporal.server.api.testpilot.v1.ProjectedSource
	(*CorrelatedEvidenceProjection)(nil), // 5: temporal.server.api.testpilot.v1.CorrelatedEvidenceProjection
	(*NamedExpression)(nil),              // 6: temporal.server.api.testpilot.v1.NamedExpression
	(*CorrelatedEvidence)(nil),           // 7: temporal.server.api.testpilot.v1.CorrelatedEvidence
	(*CorrelatedIdentity)(nil),           // 8: temporal.server.api.testpilot.v1.CorrelatedIdentity
	(*NamedValue)(nil),                   // 9: temporal.server.api.testpilot.v1.NamedValue
	(*Expression)(nil),                   // 10: temporal.server.api.testpilot.v1.Expression
	(RunEventKind)(0),                    // 11: temporal.server.api.testpilot.v1.RunEventKind
	(*InstructionReference)(nil),         // 12: temporal.server.api.testpilot.v1.InstructionReference
	(*ValueType)(nil),                    // 13: temporal.server.api.testpilot.v1.ValueType
	(*expr.Value)(nil),                   // 14: cel.expr.Value
}
var file_temporal_server_api_testpilot_v1_evidence_proto_depIdxs = []int32{
	1,  // 0: temporal.server.api.testpilot.v1.EvidenceDeclaration.history_event:type_name -> temporal.server.api.testpilot.v1.HistoryEventSource
	2,  // 1: temporal.server.api.testpilot.v1.EvidenceDeclaration.run_event:type_name -> temporal.server.api.testpilot.v1.RunEventSource
	3,  // 2: temporal.server.api.testpilot.v1.EvidenceDeclaration.read:type_name -> temporal.server.api.testpilot.v1.ReadSource
	4,  // 3: temporal.server.api.testpilot.v1.EvidenceDeclaration.projected:type_name -> temporal.server.api.testpilot.v1.ProjectedSource
	6,  // 4: temporal.server.api.testpilot.v1.EvidenceDeclaration.scope:type_name -> temporal.server.api.testpilot.v1.NamedExpression
	10, // 5: temporal.server.api.testpilot.v1.EvidenceDeclaration.operation:type_name -> temporal.server.api.testpilot.v1.Expression
	6,  // 6: temporal.server.api.testpilot.v1.EvidenceDeclaration.fields:type_name -> temporal.server.api.testpilot.v1.NamedExpression
	10, // 7: temporal.server.api.testpilot.v1.EvidenceDeclaration.guard:type_name -> temporal.server.api.testpilot.v1.Expression
	11, // 8: temporal.server.api.testpilot.v1.RunEventSource.kind:type_name -> temporal.server.api.testpilot.v1.RunEventKind
	12, // 9: temporal.server.api.testpilot.v1.RunEventSource.instruction:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	13, // 10: temporal.server.api.testpilot.v1.ProjectedSource.type:type_name -> temporal.server.api.testpilot.v1.ValueType
	10, // 11: temporal.server.api.testpilot.v1.NamedExpression.value:type_name -> temporal.server.api.testpilot.v1.Expression
	8,  // 12: temporal.server.api.testpilot.v1.CorrelatedEvidence.identity:type_name -> temporal.server.api.testpilot.v1.CorrelatedIdentity
	8,  // 13: temporal.server.api.testpilot.v1.CorrelatedEvidence.parents:type_name -> temporal.server.api.testpilot.v1.CorrelatedIdentity
	9,  // 14: temporal.server.api.testpilot.v1.CorrelatedEvidence.fields:type_name -> temporal.server.api.testpilot.v1.NamedValue
	9,  // 15: temporal.server.api.testpilot.v1.CorrelatedIdentity.scope:type_name -> temporal.server.api.testpilot.v1.NamedValue
	14, // 16: temporal.server.api.testpilot.v1.NamedValue.value:type_name -> cel.expr.Value
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_temporal_server_api_testpilot_v1_evidence_proto_init() }
func file_temporal_server_api_testpilot_v1_evidence_proto_init() {
	if File_temporal_server_api_testpilot_v1_evidence_proto != nil {
		return
	}
	file_temporal_server_api_testpilot_v1_event_proto_init()
	file_temporal_server_api_testpilot_v1_expression_proto_init()
	file_temporal_server_api_testpilot_v1_value_proto_init()
	file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes[0].OneofWrappers = []any{
		(*EvidenceDeclaration_HistoryEvent)(nil),
		(*EvidenceDeclaration_RunEvent)(nil),
		(*EvidenceDeclaration_Read)(nil),
		(*EvidenceDeclaration_Projected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_evidence_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_evidence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_testpilot_v1_evidence_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_testpilot_v1_evidence_proto_depIdxs,
		MessageInfos:      file_temporal_server_api_testpilot_v1_evidence_proto_msgTypes,
	}.Build()
	File_temporal_server_api_testpilot_v1_evidence_proto = out.File
	file_temporal_server_api_testpilot_v1_evidence_proto_goTypes = nil
	file_temporal_server_api_testpilot_v1_evidence_proto_depIdxs = nil
}
