// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/testpilot/v1/expression.proto

package testpilot

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	expr "cel.dev/expr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstructionOutcomeField names one field of an InstructionOutcome an expression may read.
type InstructionOutcomeField int32

const (
	INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED      InstructionOutcomeField = 0
	INSTRUCTION_OUTCOME_FIELD_STATUS           InstructionOutcomeField = 1
	INSTRUCTION_OUTCOME_FIELD_PROTOCOL_CODE    InstructionOutcomeField = 2
	INSTRUCTION_OUTCOME_FIELD_SDK_FAILURE_CODE InstructionOutcomeField = 3
	INSTRUCTION_OUTCOME_FIELD_DETAIL           InstructionOutcomeField = 4
	INSTRUCTION_OUTCOME_FIELD_VALUE            InstructionOutcomeField = 5
)

// Enum value maps for InstructionOutcomeField.
var (
	InstructionOutcomeField_name = map[int32]string{
		0: "INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED",
		1: "INSTRUCTION_OUTCOME_FIELD_STATUS",
		2: "INSTRUCTION_OUTCOME_FIELD_PROTOCOL_CODE",
		3: "INSTRUCTION_OUTCOME_FIELD_SDK_FAILURE_CODE",
		4: "INSTRUCTION_OUTCOME_FIELD_DETAIL",
		5: "INSTRUCTION_OUTCOME_FIELD_VALUE",
	}
	InstructionOutcomeField_value = map[string]int32{
		"INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED":      0,
		"INSTRUCTION_OUTCOME_FIELD_STATUS":           1,
		"INSTRUCTION_OUTCOME_FIELD_PROTOCOL_CODE":    2,
		"INSTRUCTION_OUTCOME_FIELD_SDK_FAILURE_CODE": 3,
		"INSTRUCTION_OUTCOME_FIELD_DETAIL":           4,
		"INSTRUCTION_OUTCOME_FIELD_VALUE":            5,
	}
)

func (x InstructionOutcomeField) Enum() *InstructionOutcomeField {
	p := new(InstructionOutcomeField)
	*p = x
	return p
}

func (x InstructionOutcomeField) String() string {
	switch x {
	case INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED:
		return "Unspecified"
	case INSTRUCTION_OUTCOME_FIELD_STATUS:
		return "Status"
	case INSTRUCTION_OUTCOME_FIELD_PROTOCOL_CODE:
		return "ProtocolCode"
	case INSTRUCTION_OUTCOME_FIELD_SDK_FAILURE_CODE:
		return "SdkFailureCode"
	case INSTRUCTION_OUTCOME_FIELD_DETAIL:
		return "Detail"
	case INSTRUCTION_OUTCOME_FIELD_VALUE:
		return "Value"
	default:
		return strconv.Itoa(int(x))
	}

}

func (InstructionOutcomeField) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_expression_proto_enumTypes[0].Descriptor()
}

func (InstructionOutcomeField) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_expression_proto_enumTypes[0]
}

func (x InstructionOutcomeField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstructionOutcomeField.Descriptor instead.
func (InstructionOutcomeField) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{0}
}

// CorrelatedStepField names the part of a correlated step a step reference reads.
// (-- api-linter: core::0191::file-layout=disabled --)
type CorrelatedStepField int32

const (
	CORRELATED_STEP_FIELD_UNSPECIFIED CorrelatedStepField = 0
	CORRELATED_STEP_FIELD_ACTION      CorrelatedStepField = 1
	CORRELATED_STEP_FIELD_OUTCOME     CorrelatedStepField = 2
	CORRELATED_STEP_FIELD_STATE       CorrelatedStepField = 3
	CORRELATED_STEP_FIELD_FACT        CorrelatedStepField = 4
)

// Enum value maps for CorrelatedStepField.
var (
	CorrelatedStepField_name = map[int32]string{
		0: "CORRELATED_STEP_FIELD_UNSPECIFIED",
		1: "CORRELATED_STEP_FIELD_ACTION",
		2: "CORRELATED_STEP_FIELD_OUTCOME",
		3: "CORRELATED_STEP_FIELD_STATE",
		4: "CORRELATED_STEP_FIELD_FACT",
	}
	CorrelatedStepField_value = map[string]int32{
		"CORRELATED_STEP_FIELD_UNSPECIFIED": 0,
		"CORRELATED_STEP_FIELD_ACTION":      1,
		"CORRELATED_STEP_FIELD_OUTCOME":     2,
		"CORRELATED_STEP_FIELD_STATE":       3,
		"CORRELATED_STEP_FIELD_FACT":        4,
	}
)

func (x CorrelatedStepField) Enum() *CorrelatedStepField {
	p := new(CorrelatedStepField)
	*p = x
	return p
}

func (x CorrelatedStepField) String() string {
	switch x {
	case CORRELATED_STEP_FIELD_UNSPECIFIED:
		return "Unspecified"
	case CORRELATED_STEP_FIELD_ACTION:
		return "Action"
	case CORRELATED_STEP_FIELD_OUTCOME:
		return "Outcome"
	case CORRELATED_STEP_FIELD_STATE:
		return "State"
	case CORRELATED_STEP_FIELD_FACT:
		return "Fact"
	default:
		return strconv.Itoa(int(x))
	}

}

func (CorrelatedStepField) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_expression_proto_enumTypes[1].Descriptor()
}

func (CorrelatedStepField) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_expression_proto_enumTypes[1]
}

func (x CorrelatedStepField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CorrelatedStepField.Descriptor instead.
func (CorrelatedStepField) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{1}
}

// Expression is the one closed expression language of a Case: instruction inputs and guards,
// Contract transition predicates, correlated rule conditions and evidence-lift guards. Which
// references an expression may use is a property of where it appears, and preparation rejects a
// reference outside its context.
type Expression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cel           *expr.ParsedExpr       `protobuf:"bytes,1,opt,name=cel,proto3" json:"cel,omitempty"`
	Bindings      []*ExpressionBinding   `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{0}
}

func (x *Expression) GetCel() *expr.ParsedExpr {
	if x != nil {
		return x.Cel
	}
	return nil
}

func (x *Expression) GetBindings() []*ExpressionBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// ExpressionBinding supplies a typed domain value to one CEL variable. Paths use protobuf field
// names, optional oneof members, map selectors, wildcard projection and explicit presence. Their
// authority is checked against the owning Case catalog before native CEL checking.
type ExpressionBinding struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Variable string                 `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*ExpressionBinding_Reference
	//	*ExpressionBinding_Literal
	Input         isExpressionBinding_Input `protobuf_oneof:"input"`
	Path          string                    `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionBinding) Reset() {
	*x = ExpressionBinding{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionBinding) ProtoMessage() {}

func (x *ExpressionBinding) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionBinding.ProtoReflect.Descriptor instead.
func (*ExpressionBinding) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{1}
}

func (x *ExpressionBinding) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

func (x *ExpressionBinding) GetInput() isExpressionBinding_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExpressionBinding) GetReference() *Reference {
	if x != nil {
		if x, ok := x.Input.(*ExpressionBinding_Reference); ok {
			return x.Reference
		}
	}
	return nil
}

func (x *ExpressionBinding) GetLiteral() *expr.Value {
	if x != nil {
		if x, ok := x.Input.(*ExpressionBinding_Literal); ok {
			return x.Literal
		}
	}
	return nil
}

func (x *ExpressionBinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type isExpressionBinding_Input interface {
	isExpressionBinding_Input()
}

type ExpressionBinding_Reference struct {
	Reference *Reference `protobuf:"bytes,2,opt,name=reference,proto3,oneof"`
}

type ExpressionBinding_Literal struct {
	Literal *expr.Value `protobuf:"bytes,3,opt,name=literal,proto3,oneof"`
}

func (*ExpressionBinding_Reference) isExpressionBinding_Input() {}

func (*ExpressionBinding_Literal) isExpressionBinding_Input() {}

// Reference reads one value an expression's context supplies. Instruction inputs and guards admit
// Slots, instruction outcomes, the Run and environment bindings; Contract transition predicates admit
// Observations, Run Event fields, captures and instance values; correlated rule conditions admit
// evidence fields, correlated captures and correlated steps; evidence-lift guards admit the projected
// value.
type Reference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reference:
	//
	//	*Reference_SlotId
	//	*Reference_Outcome
	//	*Reference_Run
	//	*Reference_EnvironmentBindingId
	//	*Reference_ObservationId
	//	*Reference_RunEvent
	//	*Reference_CaptureId
	//	*Reference_EvidenceFieldId
	//	*Reference_CorrelatedCapture
	//	*Reference_CorrelatedStep
	//	*Reference_ProjectedValue
	//	*Reference_InstanceValueId
	Reference     isReference_Reference `protobuf_oneof:"reference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{2}
}

func (x *Reference) GetReference() isReference_Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Reference) GetSlotId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_SlotId); ok {
			return x.SlotId
		}
	}
	return ""
}

func (x *Reference) GetOutcome() *InstructionOutcomeReference {
	if x != nil {
		if x, ok := x.Reference.(*Reference_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

func (x *Reference) GetRun() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Reference.(*Reference_Run); ok {
			return x.Run
		}
	}
	return nil
}

func (x *Reference) GetEnvironmentBindingId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_EnvironmentBindingId); ok {
			return x.EnvironmentBindingId
		}
	}
	return ""
}

func (x *Reference) GetObservationId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_ObservationId); ok {
			return x.ObservationId
		}
	}
	return ""
}

func (x *Reference) GetRunEvent() *RunEventReference {
	if x != nil {
		if x, ok := x.Reference.(*Reference_RunEvent); ok {
			return x.RunEvent
		}
	}
	return nil
}

func (x *Reference) GetCaptureId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_CaptureId); ok {
			return x.CaptureId
		}
	}
	return ""
}

func (x *Reference) GetEvidenceFieldId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_EvidenceFieldId); ok {
			return x.EvidenceFieldId
		}
	}
	return ""
}

func (x *Reference) GetCorrelatedCapture() *CorrelatedCaptureReference {
	if x != nil {
		if x, ok := x.Reference.(*Reference_CorrelatedCapture); ok {
			return x.CorrelatedCapture
		}
	}
	return nil
}

func (x *Reference) GetCorrelatedStep() *CorrelatedStepReference {
	if x != nil {
		if x, ok := x.Reference.(*Reference_CorrelatedStep); ok {
			return x.CorrelatedStep
		}
	}
	return nil
}

func (x *Reference) GetProjectedValue() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Reference.(*Reference_ProjectedValue); ok {
			return x.ProjectedValue
		}
	}
	return nil
}

func (x *Reference) GetInstanceValueId() string {
	if x != nil {
		if x, ok := x.Reference.(*Reference_InstanceValueId); ok {
			return x.InstanceValueId
		}
	}
	return ""
}

type isReference_Reference interface {
	isReference_Reference()
}

type Reference_SlotId struct {
	// The value assigned to a Slot, absent until the Slot is written.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3,oneof"`
}

type Reference_Outcome struct {
	Outcome *InstructionOutcomeReference `protobuf:"bytes,2,opt,name=outcome,proto3,oneof"`
}

type Reference_Run struct {
	Run *emptypb.Empty `protobuf:"bytes,3,opt,name=run,proto3,oneof"`
}

type Reference_EnvironmentBindingId struct {
	// A declared environment binding's value. It is admitted only as the whole value of an InvokeRpc
	// request assignment to a text field.
	EnvironmentBindingId string `protobuf:"bytes,4,opt,name=environment_binding_id,json=environmentBindingId,proto3,oneof"`
}

type Reference_ObservationId struct {
	// An Observation of the evaluated Run Event, absent when the event does not carry it.
	ObservationId string `protobuf:"bytes,5,opt,name=observation_id,json=observationId,proto3,oneof"`
}

type Reference_RunEvent struct {
	RunEvent *RunEventReference `protobuf:"bytes,6,opt,name=run_event,json=runEvent,proto3,oneof"`
}

type Reference_CaptureId struct {
	// A value the evaluated Rule instance captured earlier, absent until it is assigned.
	CaptureId string `protobuf:"bytes,7,opt,name=capture_id,json=captureId,proto3,oneof"`
}

type Reference_EvidenceFieldId struct {
	// One declared evidence field of the correlated step being admitted.
	EvidenceFieldId string `protobuf:"bytes,8,opt,name=evidence_field_id,json=evidenceFieldId,proto3,oneof"`
}

type Reference_CorrelatedCapture struct {
	CorrelatedCapture *CorrelatedCaptureReference `protobuf:"bytes,9,opt,name=correlated_capture,json=correlatedCapture,proto3,oneof"`
}

type Reference_CorrelatedStep struct {
	CorrelatedStep *CorrelatedStepReference `protobuf:"bytes,10,opt,name=correlated_step,json=correlatedStep,proto3,oneof"`
}

type Reference_ProjectedValue struct {
	// The value an evidence lift is projecting.
	ProjectedValue *emptypb.Empty `protobuf:"bytes,11,opt,name=projected_value,json=projectedValue,proto3,oneof"`
}

type Reference_InstanceValueId struct {
	// A value the evaluated Rule instance assigns; admitted only in a Contract transition predicate.
	InstanceValueId string `protobuf:"bytes,12,opt,name=instance_value_id,json=instanceValueId,proto3,oneof"`
}

func (*Reference_SlotId) isReference_Reference() {}

func (*Reference_Outcome) isReference_Reference() {}

func (*Reference_Run) isReference_Reference() {}

func (*Reference_EnvironmentBindingId) isReference_Reference() {}

func (*Reference_ObservationId) isReference_Reference() {}

func (*Reference_RunEvent) isReference_Reference() {}

func (*Reference_CaptureId) isReference_Reference() {}

func (*Reference_EvidenceFieldId) isReference_Reference() {}

func (*Reference_CorrelatedCapture) isReference_Reference() {}

func (*Reference_CorrelatedStep) isReference_Reference() {}

func (*Reference_ProjectedValue) isReference_Reference() {}

func (*Reference_InstanceValueId) isReference_Reference() {}

// InstructionReference names one instruction by its entrypoint and instruction ids.
type InstructionReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntrypointId  string                 `protobuf:"bytes,1,opt,name=entrypoint_id,json=entrypointId,proto3" json:"entrypoint_id,omitempty"`
	InstructionId string                 `protobuf:"bytes,2,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionReference) Reset() {
	*x = InstructionReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionReference) ProtoMessage() {}

func (x *InstructionReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionReference.ProtoReflect.Descriptor instead.
func (*InstructionReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{3}
}

func (x *InstructionReference) GetEntrypointId() string {
	if x != nil {
		return x.EntrypointId
	}
	return ""
}

func (x *InstructionReference) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

// LocalInstructionReference is scoped to its enclosing entrypoint.
type LocalInstructionReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalInstructionReference) Reset() {
	*x = LocalInstructionReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalInstructionReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalInstructionReference) ProtoMessage() {}

func (x *LocalInstructionReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalInstructionReference.ProtoReflect.Descriptor instead.
func (*LocalInstructionReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{4}
}

func (x *LocalInstructionReference) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

// InstructionOutcomeReference reads one declared field of an earlier instruction's outcome.
type InstructionOutcomeReference struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Instruction   *InstructionReference   `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Field         InstructionOutcomeField `protobuf:"varint,2,opt,name=field,proto3,enum=temporal.server.api.testpilot.v1.InstructionOutcomeField" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionOutcomeReference) Reset() {
	*x = InstructionOutcomeReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionOutcomeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionOutcomeReference) ProtoMessage() {}

func (x *InstructionOutcomeReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionOutcomeReference.ProtoReflect.Descriptor instead.
func (*InstructionOutcomeReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{5}
}

func (x *InstructionOutcomeReference) GetInstruction() *InstructionReference {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *InstructionOutcomeReference) GetField() InstructionOutcomeField {
	if x != nil {
		return x.Field
	}
	return INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED
}

// RunEventReference reads the evaluated Run Event: one of its coordinates, or its payload.
type RunEventReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selection:
	//
	//	*RunEventReference_Field
	//	*RunEventReference_Payload
	Selection     isRunEventReference_Selection `protobuf_oneof:"selection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEventReference) Reset() {
	*x = RunEventReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEventReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEventReference) ProtoMessage() {}

func (x *RunEventReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEventReference.ProtoReflect.Descriptor instead.
func (*RunEventReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{6}
}

func (x *RunEventReference) GetSelection() isRunEventReference_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *RunEventReference) GetField() RunEventField {
	if x != nil {
		if x, ok := x.Selection.(*RunEventReference_Field); ok {
			return x.Field
		}
	}
	return RUN_EVENT_FIELD_UNSPECIFIED
}

func (x *RunEventReference) GetPayload() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Selection.(*RunEventReference_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isRunEventReference_Selection interface {
	isRunEventReference_Selection()
}

type RunEventReference_Field struct {
	Field RunEventField `protobuf:"varint,1,opt,name=field,proto3,enum=temporal.server.api.testpilot.v1.RunEventField,oneof"`
}

type RunEventReference_Payload struct {
	Payload *emptypb.Empty `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*RunEventReference_Field) isRunEventReference_Selection() {}

func (*RunEventReference_Payload) isRunEventReference_Selection() {}

// CorrelatedCaptureReference reads one retained occurrence of a capture by its zero-based ordinal.
type CorrelatedCaptureReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptureId     string                 `protobuf:"bytes,1,opt,name=capture_id,json=captureId,proto3" json:"capture_id,omitempty"`
	Ordinal       int64                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelatedCaptureReference) Reset() {
	*x = CorrelatedCaptureReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedCaptureReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedCaptureReference) ProtoMessage() {}

func (x *CorrelatedCaptureReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedCaptureReference.ProtoReflect.Descriptor instead.
func (*CorrelatedCaptureReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{7}
}

func (x *CorrelatedCaptureReference) GetCaptureId() string {
	if x != nil {
		return x.CaptureId
	}
	return ""
}

func (x *CorrelatedCaptureReference) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// CorrelatedStepReference reads the model value of definition_id at one part of the correlated step
// being admitted, absent when that part carries none. A FACT reference reads the step's facts: it is
// present when any fact has the definition, and it equals a literal when any such fact does.
type CorrelatedStepReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field CorrelatedStepField    `protobuf:"varint,1,opt,name=field,proto3,enum=temporal.server.api.testpilot.v1.CorrelatedStepField" json:"field,omitempty"`
	// The Case-local name of the definition, as a ModelValue spells it. With a STATE field this is
	// either the whole state's definition or one state field's, because a structured Model carries
	// its fields beside the state atom and each field is a model value under its own definition.
	DefinitionId  string `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelatedStepReference) Reset() {
	*x = CorrelatedStepReference{}
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedStepReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedStepReference) ProtoMessage() {}

func (x *CorrelatedStepReference) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedStepReference.ProtoReflect.Descriptor instead.
func (*CorrelatedStepReference) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP(), []int{8}
}

func (x *CorrelatedStepReference) GetField() CorrelatedStepField {
	if x != nil {
		return x.Field
	}
	return CORRELATED_STEP_FIELD_UNSPECIFIED
}

func (x *CorrelatedStepReference) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

var File_temporal_server_api_testpilot_v1_expression_proto protoreflect.FileDescriptor

const file_temporal_server_api_testpilot_v1_expression_proto_rawDesc = "" +
	"\n" +
	"1temporal/server/api/testpilot/v1/expression.proto\x12 temporal.server.api.testpilot.v1\x1a,temporal/server/api/testpilot/v1/event.proto\x1a\x15cel/expr/syntax.proto\x1a\x14cel/expr/value.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n" +
	"\n" +
	"Expression\x12&\n" +
	"\x03cel\x18\x01 \x01(\v2\x14.cel.expr.ParsedExprR\x03cel\x12O\n" +
	"\bbindings\x18\x02 \x03(\v23.temporal.server.api.testpilot.v1.ExpressionBindingR\bbindings\"\xc6\x01\n" +
	"\x11ExpressionBinding\x12\x1a\n" +
	"\bvariable\x18\x01 \x01(\tR\bvariable\x12K\n" +
	"\treference\x18\x02 \x01(\v2+.temporal.server.api.testpilot.v1.ReferenceH\x00R\treference\x12+\n" +
	"\aliteral\x18\x03 \x01(\v2\x0f.cel.expr.ValueH\x00R\aliteral\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04pathB\a\n" +
	"\x05input\"\x84\x06\n" +
	"\tReference\x12\x19\n" +
	"\aslot_id\x18\x01 \x01(\tH\x00R\x06slotId\x12Y\n" +
	"\aoutcome\x18\x02 \x01(\v2=.temporal.server.api.testpilot.v1.InstructionOutcomeReferenceH\x00R\aoutcome\x12*\n" +
	"\x03run\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03run\x126\n" +
	"\x16environment_binding_id\x18\x04 \x01(\tH\x00R\x14environmentBindingId\x12'\n" +
	"\x0eobservation_id\x18\x05 \x01(\tH\x00R\robservationId\x12R\n" +
	"\trun_event\x18\x06 \x01(\v23.temporal.server.api.testpilot.v1.RunEventReferenceH\x00R\brunEvent\x12\x1f\n" +
	"\n" +
	"capture_id\x18\a \x01(\tH\x00R\tcaptureId\x12,\n" +
	"\x11evidence_field_id\x18\b \x01(\tH\x00R\x0fevidenceFieldId\x12m\n" +
	"\x12correlated_capture\x18\t \x01(\v2<.temporal.server.api.testpilot.v1.CorrelatedCaptureReferenceH\x00R\x11correlatedCapture\x12d\n" +
	"\x0fcorrelated_step\x18\n" +
	" \x01(\v29.temporal.server.api.testpilot.v1.CorrelatedStepReferenceH\x00R\x0ecorrelatedStep\x12A\n" +
	"\x0fprojected_value\x18\v \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0eprojectedValue\x12,\n" +
	"\x11instance_value_id\x18\f \x01(\tH\x00R\x0finstanceValueIdB\v\n" +
	"\treference\"b\n" +
	"\x14InstructionReference\x12#\n" +
	"\rentrypoint_id\x18\x01 \x01(\tR\fentrypointId\x12%\n" +
	"\x0einstruction_id\x18\x02 \x01(\tR\rinstructionId\"B\n" +
	"\x19LocalInstructionReference\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\"\xc8\x01\n" +
	"\x1bInstructionOutcomeReference\x12X\n" +
	"\vinstruction\x18\x01 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\vinstruction\x12O\n" +
	"\x05field\x18\x02 \x01(\x0e29.temporal.server.api.testpilot.v1.InstructionOutcomeFieldR\x05field\"\x9d\x01\n" +
	"\x11RunEventReference\x12G\n" +
	"\x05field\x18\x01 \x01(\x0e2/.temporal.server.api.testpilot.v1.RunEventFieldH\x00R\x05field\x122\n" +
	"\apayload\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\apayloadB\v\n" +
	"\tselection\"U\n" +
	"\x1aCorrelatedCaptureReference\x12\x1d\n" +
	"\n" +
	"capture_id\x18\x01 \x01(\tR\tcaptureId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x03R\aordinal\"\x8b\x01\n" +
	"\x17CorrelatedStepReference\x12K\n" +
	"\x05field\x18\x01 \x01(\x0e25.temporal.server.api.testpilot.v1.CorrelatedStepFieldR\x05field\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\tR\fdefinitionId*\x92\x02\n" +
	"\x17InstructionOutcomeField\x12)\n" +
	"%INSTRUCTION_OUTCOME_FIELD_UNSPECIFIED\x10\x00\x12$\n" +
	" INSTRUCTION_OUTCOME_FIELD_STATUS\x10\x01\x12+\n" +
	"'INSTRUCTION_OUTCOME_FIELD_PROTOCOL_CODE\x10\x02\x12.\n" +
	"*INSTRUCTION_OUTCOME_FIELD_SDK_FAILURE_CODE\x10\x03\x12$\n" +
	" INSTRUCTION_OUTCOME_FIELD_DETAIL\x10\x04\x12#\n" +
	"\x1fINSTRUCTION_OUTCOME_FIELD_VALUE\x10\x05*\xc2\x01\n" +
	"\x13CorrelatedStepField\x12%\n" +
	"!CORRELATED_STEP_FIELD_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCORRELATED_STEP_FIELD_ACTION\x10\x01\x12!\n" +
	"\x1dCORRELATED_STEP_FIELD_OUTCOME\x10\x02\x12\x1f\n" +
	"\x1bCORRELATED_STEP_FIELD_STATE\x10\x03\x12\x1e\n" +
	"\x1aCORRELATED_STEP_FIELD_FACT\x10\x04B2Z0go.temporal.io/server/api/testpilot/v1;testpilotb\x06proto3"

var (
	file_temporal_server_api_testpilot_v1_expression_proto_rawDescOnce sync.Once
	file_temporal_server_api_testpilot_v1_expression_proto_rawDescData []byte
)

func file_temporal_server_api_testpilot_v1_expression_proto_rawDescGZIP() []byte {
	file_temporal_server_api_testpilot_v1_expression_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_testpilot_v1_expression_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_expression_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_expression_proto_rawDesc)))
	})
	return file_temporal_server_api_testpilot_v1_expression_proto_rawDescData
}

var file_temporal_server_api_testpilot_v1_expression_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_temporal_server_api_testpilot_v1_expression_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_temporal_server_api_testpilot_v1_expression_proto_goTypes = []any{
	(InstructionOutcomeField)(0),        // 0: temporal.server.api.testpilot.v1.InstructionOutcomeField
	(CorrelatedStepField)(0),            // 1: temporal.server.api.testpilot.v1.CorrelatedStepField
	(*Expression)(nil),                  // 2: temporal.server.api.testpilot.v1.Expression
	(*ExpressionBinding)(nil),           // 3: temporal.server.api.testpilot.v1.ExpressionBinding
	(*Reference)(nil),                   // 4: temporal.server.api.testpilot.v1.Reference
	(*InstructionReference)(nil),        // 5: temporal.server.api.testpilot.v1.InstructionReference
	(*LocalInstructionReference)(nil),   // 6: temporal.server.api.testpilot.v1.LocalInstructionReference
	(*InstructionOutcomeReference)(nil), // 7: temporal.server.api.testpilot.v1.InstructionOutcomeReference
	(*RunEventReference)(nil),           // 8: temporal.server.api.testpilot.v1.RunEventReference
	(*CorrelatedCaptureReference)(nil),  // 9: temporal.server.api.testpilot.v1.CorrelatedCaptureReference
	(*CorrelatedStepReference)(nil),     // 10: temporal.server.api.testpilot.v1.CorrelatedStepReference
	(*expr.ParsedExpr)(nil),             // 11: cel.expr.ParsedExpr
	(*expr.Value)(nil),                  // 12: cel.expr.Value
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
	(RunEventField)(0),                  // 14: temporal.server.api.testpilot.v1.RunEventField
}
var file_temporal_server_api_testpilot_v1_expression_proto_depIdxs = []int32{
	11, // 0: temporal.server.api.testpilot.v1.Expression.cel:type_name -> cel.expr.ParsedExpr
	3,  // 1: temporal.server.api.testpilot.v1.Expression.bindings:type_name -> temporal.server.api.testpilot.v1.ExpressionBinding
	4,  // 2: temporal.server.api.testpilot.v1.ExpressionBinding.reference:type_name -> temporal.server.api.testpilot.v1.Reference
	12, // 3: temporal.server.api.testpilot.v1.ExpressionBinding.literal:type_name -> cel.expr.Value
	7,  // 4: temporal.server.api.testpilot.v1.Reference.outcome:type_name -> temporal.server.api.testpilot.v1.InstructionOutcomeReference
	13, // 5: temporal.server.api.testpilot.v1.Reference.run:type_name -> google.protobuf.Empty
	8,  // 6: temporal.server.api.testpilot.v1.Reference.run_event:type_name -> temporal.server.api.testpilot.v1.RunEventReference
	9,  // 7: temporal.server.api.testpilot.v1.Reference.correlated_capture:type_name -> temporal.server.api.testpilot.v1.CorrelatedCaptureReference
	10, // 8: temporal.server.api.testpilot.v1.Reference.correlated_step:type_name -> temporal.server.api.testpilot.v1.CorrelatedStepReference
	13, // 9: temporal.server.api.testpilot.v1.Reference.projected_value:type_name -> google.protobuf.Empty
	5,  // 10: temporal.server.api.testpilot.v1.InstructionOutcomeReference.instruction:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	0,  // 11: temporal.server.api.testpilot.v1.InstructionOutcomeReference.field:type_name -> temporal.server.api.testpilot.v1.InstructionOutcomeField
	14, // 12: temporal.server.api.testpilot.v1.RunEventReference.field:type_name -> temporal.server.api.testpilot.v1.RunEventField
	13, // 13: temporal.server.api.testpilot.v1.RunEventReference.payload:type_name -> google.protobuf.Empty
	1,  // 14: temporal.server.api.testpilot.v1.CorrelatedStepReference.field:type_name -> temporal.server.api.testpilot.v1.CorrelatedStepField
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_temporal_server_api_testpilot_v1_expression_proto_init() }
func file_temporal_server_api_testpilot_v1_expression_proto_init() {
	if File_temporal_server_api_testpilot_v1_expression_proto != nil {
		return
	}
	file_temporal_server_api_testpilot_v1_event_proto_init()
	file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[1].OneofWrappers = []any{
		(*ExpressionBinding_Reference)(nil),
		(*ExpressionBinding_Literal)(nil),
	}
	file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[2].OneofWrappers = []any{
		(*Reference_SlotId)(nil),
		(*Reference_Outcome)(nil),
		(*Reference_Run)(nil),
		(*Reference_EnvironmentBindingId)(nil),
		(*Reference_ObservationId)(nil),
		(*Reference_RunEvent)(nil),
		(*Reference_CaptureId)(nil),
		(*Reference_EvidenceFieldId)(nil),
		(*Reference_CorrelatedCapture)(nil),
		(*Reference_CorrelatedStep)(nil),
		(*Reference_ProjectedValue)(nil),
		(*Reference_InstanceValueId)(nil),
	}
	file_temporal_server_api_testpilot_v1_expression_proto_msgTypes[6].OneofWrappers = []any{
		(*RunEventReference_Field)(nil),
		(*RunEventReference_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_expression_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_expression_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_testpilot_v1_expression_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_testpilot_v1_expression_proto_depIdxs,
		EnumInfos:         file_temporal_server_api_testpilot_v1_expression_proto_enumTypes,
		MessageInfos:      file_temporal_server_api_testpilot_v1_expression_proto_msgTypes,
	}.Build()
	File_temporal_server_api_testpilot_v1_expression_proto = out.File
	file_temporal_server_api_testpilot_v1_expression_proto_goTypes = nil
	file_temporal_server_api_testpilot_v1_expression_proto_depIdxs = nil
}
