// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package testpilot

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

// Marshal an object of type InstructionRef to the protobuf v3 wire format
func (val *InstructionRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InstructionRef from the protobuf v3 wire format
func (val *InstructionRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InstructionRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InstructionRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InstructionRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InstructionRef
	switch t := that.(type) {
	case *InstructionRef:
		that1 = t
	case InstructionRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type SlotRef to the protobuf v3 wire format
func (val *SlotRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type SlotRef from the protobuf v3 wire format
func (val *SlotRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *SlotRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two SlotRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *SlotRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *SlotRef
	switch t := that.(type) {
	case *SlotRef:
		that1 = t
	case SlotRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type InstructionOutcomeRef to the protobuf v3 wire format
func (val *InstructionOutcomeRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InstructionOutcomeRef from the protobuf v3 wire format
func (val *InstructionOutcomeRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InstructionOutcomeRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InstructionOutcomeRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InstructionOutcomeRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InstructionOutcomeRef
	switch t := that.(type) {
	case *InstructionOutcomeRef:
		that1 = t
	case InstructionOutcomeRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type OutcomeFieldDefinition to the protobuf v3 wire format
func (val *OutcomeFieldDefinition) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type OutcomeFieldDefinition from the protobuf v3 wire format
func (val *OutcomeFieldDefinition) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *OutcomeFieldDefinition) Size() int {
	return proto.Size(val)
}

// Equal returns whether two OutcomeFieldDefinition values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *OutcomeFieldDefinition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *OutcomeFieldDefinition
	switch t := that.(type) {
	case *OutcomeFieldDefinition:
		that1 = t
	case OutcomeFieldDefinition:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type InstructionOutcomeDefinition to the protobuf v3 wire format
func (val *InstructionOutcomeDefinition) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InstructionOutcomeDefinition from the protobuf v3 wire format
func (val *InstructionOutcomeDefinition) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InstructionOutcomeDefinition) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InstructionOutcomeDefinition values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InstructionOutcomeDefinition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InstructionOutcomeDefinition
	switch t := that.(type) {
	case *InstructionOutcomeDefinition:
		that1 = t
	case InstructionOutcomeDefinition:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ObservationRef to the protobuf v3 wire format
func (val *ObservationRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ObservationRef from the protobuf v3 wire format
func (val *ObservationRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ObservationRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ObservationRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ObservationRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ObservationRef
	switch t := that.(type) {
	case *ObservationRef:
		that1 = t
	case ObservationRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type CaptureRef to the protobuf v3 wire format
func (val *CaptureRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type CaptureRef from the protobuf v3 wire format
func (val *CaptureRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *CaptureRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two CaptureRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *CaptureRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *CaptureRef
	switch t := that.(type) {
	case *CaptureRef:
		that1 = t
	case CaptureRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RunRef to the protobuf v3 wire format
func (val *RunRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RunRef from the protobuf v3 wire format
func (val *RunRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RunRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RunRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RunRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RunRef
	switch t := that.(type) {
	case *RunRef:
		that1 = t
	case RunRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RunEventFieldRef to the protobuf v3 wire format
func (val *RunEventFieldRef) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RunEventFieldRef from the protobuf v3 wire format
func (val *RunEventFieldRef) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RunEventFieldRef) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RunEventFieldRef values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RunEventFieldRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RunEventFieldRef
	switch t := that.(type) {
	case *RunEventFieldRef:
		that1 = t
	case RunEventFieldRef:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramPathExpression to the protobuf v3 wire format
func (val *ProgramPathExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramPathExpression from the protobuf v3 wire format
func (val *ProgramPathExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramPathExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramPathExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramPathExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramPathExpression
	switch t := that.(type) {
	case *ProgramPathExpression:
		that1 = t
	case ProgramPathExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramPresentExpression to the protobuf v3 wire format
func (val *ProgramPresentExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramPresentExpression from the protobuf v3 wire format
func (val *ProgramPresentExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramPresentExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramPresentExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramPresentExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramPresentExpression
	switch t := that.(type) {
	case *ProgramPresentExpression:
		that1 = t
	case ProgramPresentExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramEqualsExpression to the protobuf v3 wire format
func (val *ProgramEqualsExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramEqualsExpression from the protobuf v3 wire format
func (val *ProgramEqualsExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramEqualsExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramEqualsExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramEqualsExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramEqualsExpression
	switch t := that.(type) {
	case *ProgramEqualsExpression:
		that1 = t
	case ProgramEqualsExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramCompareExpression to the protobuf v3 wire format
func (val *ProgramCompareExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramCompareExpression from the protobuf v3 wire format
func (val *ProgramCompareExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramCompareExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramCompareExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramCompareExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramCompareExpression
	switch t := that.(type) {
	case *ProgramCompareExpression:
		that1 = t
	case ProgramCompareExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramNotExpression to the protobuf v3 wire format
func (val *ProgramNotExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramNotExpression from the protobuf v3 wire format
func (val *ProgramNotExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramNotExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramNotExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramNotExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramNotExpression
	switch t := that.(type) {
	case *ProgramNotExpression:
		that1 = t
	case ProgramNotExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramAllExpression to the protobuf v3 wire format
func (val *ProgramAllExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramAllExpression from the protobuf v3 wire format
func (val *ProgramAllExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramAllExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramAllExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramAllExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramAllExpression
	switch t := that.(type) {
	case *ProgramAllExpression:
		that1 = t
	case ProgramAllExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramAnyExpression to the protobuf v3 wire format
func (val *ProgramAnyExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramAnyExpression from the protobuf v3 wire format
func (val *ProgramAnyExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramAnyExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramAnyExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramAnyExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramAnyExpression
	switch t := that.(type) {
	case *ProgramAnyExpression:
		that1 = t
	case ProgramAnyExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ProgramExpression to the protobuf v3 wire format
func (val *ProgramExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ProgramExpression from the protobuf v3 wire format
func (val *ProgramExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ProgramExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ProgramExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ProgramExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ProgramExpression
	switch t := that.(type) {
	case *ProgramExpression:
		that1 = t
	case ProgramExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractPathExpression to the protobuf v3 wire format
func (val *ContractPathExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractPathExpression from the protobuf v3 wire format
func (val *ContractPathExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractPathExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractPathExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractPathExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractPathExpression
	switch t := that.(type) {
	case *ContractPathExpression:
		that1 = t
	case ContractPathExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractPresentExpression to the protobuf v3 wire format
func (val *ContractPresentExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractPresentExpression from the protobuf v3 wire format
func (val *ContractPresentExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractPresentExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractPresentExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractPresentExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractPresentExpression
	switch t := that.(type) {
	case *ContractPresentExpression:
		that1 = t
	case ContractPresentExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractEqualsExpression to the protobuf v3 wire format
func (val *ContractEqualsExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractEqualsExpression from the protobuf v3 wire format
func (val *ContractEqualsExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractEqualsExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractEqualsExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractEqualsExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractEqualsExpression
	switch t := that.(type) {
	case *ContractEqualsExpression:
		that1 = t
	case ContractEqualsExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractCompareExpression to the protobuf v3 wire format
func (val *ContractCompareExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractCompareExpression from the protobuf v3 wire format
func (val *ContractCompareExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractCompareExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractCompareExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractCompareExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractCompareExpression
	switch t := that.(type) {
	case *ContractCompareExpression:
		that1 = t
	case ContractCompareExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractNotExpression to the protobuf v3 wire format
func (val *ContractNotExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractNotExpression from the protobuf v3 wire format
func (val *ContractNotExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractNotExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractNotExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractNotExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractNotExpression
	switch t := that.(type) {
	case *ContractNotExpression:
		that1 = t
	case ContractNotExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractAllExpression to the protobuf v3 wire format
func (val *ContractAllExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractAllExpression from the protobuf v3 wire format
func (val *ContractAllExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractAllExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractAllExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractAllExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractAllExpression
	switch t := that.(type) {
	case *ContractAllExpression:
		that1 = t
	case ContractAllExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractAnyExpression to the protobuf v3 wire format
func (val *ContractAnyExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractAnyExpression from the protobuf v3 wire format
func (val *ContractAnyExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractAnyExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractAnyExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractAnyExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractAnyExpression
	switch t := that.(type) {
	case *ContractAnyExpression:
		that1 = t
	case ContractAnyExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ContractExpression to the protobuf v3 wire format
func (val *ContractExpression) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ContractExpression from the protobuf v3 wire format
func (val *ContractExpression) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ContractExpression) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ContractExpression values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ContractExpression) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ContractExpression
	switch t := that.(type) {
	case *ContractExpression:
		that1 = t
	case ContractExpression:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

var (
	InstructionOutcomeField_shorthandValue = map[string]int32{
		"Unspecified":    0,
		"Status":         1,
		"ProtocolCode":   2,
		"SdkFailureCode": 3,
		"Detail":         4,
		"Value":          5,
	}
)

// InstructionOutcomeFieldFromString parses a InstructionOutcomeField value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to InstructionOutcomeField
func InstructionOutcomeFieldFromString(s string) (InstructionOutcomeField, error) {
	if v, ok := InstructionOutcomeField_value[s]; ok {
		return InstructionOutcomeField(v), nil
	} else if v, ok := InstructionOutcomeField_shorthandValue[s]; ok {
		return InstructionOutcomeField(v), nil
	}
	return InstructionOutcomeField(0), fmt.Errorf("%s is not a valid InstructionOutcomeField", s)
}

var (
	ComparisonOperator_shorthandValue = map[string]int32{
		"Unspecified":        0,
		"LessThan":           1,
		"LessThanOrEqual":    2,
		"GreaterThan":        3,
		"GreaterThanOrEqual": 4,
	}
)

// ComparisonOperatorFromString parses a ComparisonOperator value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to ComparisonOperator
func ComparisonOperatorFromString(s string) (ComparisonOperator, error) {
	if v, ok := ComparisonOperator_value[s]; ok {
		return ComparisonOperator(v), nil
	} else if v, ok := ComparisonOperator_shorthandValue[s]; ok {
		return ComparisonOperator(v), nil
	}
	return ComparisonOperator(0), fmt.Errorf("%s is not a valid ComparisonOperator", s)
}

var (
	RunEventField_shorthandValue = map[string]int32{
		"Unspecified":         0,
		"Sequence":            1,
		"ElapsedMilliseconds": 2,
		"Kind":                3,
		"EntrypointId":        4,
		"ActivationId":        5,
		"InstructionId":       6,
		"Attempt":             7,
		"SourceId":            8,
		"RunId":               9,
	}
)

// RunEventFieldFromString parses a RunEventField value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to RunEventField
func RunEventFieldFromString(s string) (RunEventField, error) {
	if v, ok := RunEventField_value[s]; ok {
		return RunEventField(v), nil
	} else if v, ok := RunEventField_shorthandValue[s]; ok {
		return RunEventField(v), nil
	}
	return RunEventField(0), fmt.Errorf("%s is not a valid RunEventField", s)
}
