// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package testpilot

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

// Marshal an object of type InstructionNode to the protobuf v3 wire format
func (val *InstructionNode) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InstructionNode from the protobuf v3 wire format
func (val *InstructionNode) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InstructionNode) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InstructionNode values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InstructionNode) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InstructionNode
	switch t := that.(type) {
	case *InstructionNode:
		that1 = t
	case InstructionNode:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type After to the protobuf v3 wire format
func (val *After) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type After from the protobuf v3 wire format
func (val *After) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *After) Size() int {
	return proto.Size(val)
}

// Equal returns whether two After values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *After) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *After
	switch t := that.(type) {
	case *After:
		that1 = t
	case After:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type Instruction to the protobuf v3 wire format
func (val *Instruction) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type Instruction from the protobuf v3 wire format
func (val *Instruction) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *Instruction) Size() int {
	return proto.Size(val)
}

// Equal returns whether two Instruction values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *Instruction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *Instruction
	switch t := that.(type) {
	case *Instruction:
		that1 = t
	case Instruction:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type InvokeRpc to the protobuf v3 wire format
func (val *InvokeRpc) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InvokeRpc from the protobuf v3 wire format
func (val *InvokeRpc) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InvokeRpc) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InvokeRpc values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InvokeRpc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InvokeRpc
	switch t := that.(type) {
	case *InvokeRpc:
		that1 = t
	case InvokeRpc:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RequestAssignment to the protobuf v3 wire format
func (val *RequestAssignment) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RequestAssignment from the protobuf v3 wire format
func (val *RequestAssignment) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RequestAssignment) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RequestAssignment values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RequestAssignment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RequestAssignment
	switch t := that.(type) {
	case *RequestAssignment:
		that1 = t
	case RequestAssignment:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ResponseRead to the protobuf v3 wire format
func (val *ResponseRead) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ResponseRead from the protobuf v3 wire format
func (val *ResponseRead) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ResponseRead) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ResponseRead values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ResponseRead) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ResponseRead
	switch t := that.(type) {
	case *ResponseRead:
		that1 = t
	case ResponseRead:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type ReadTarget to the protobuf v3 wire format
func (val *ReadTarget) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type ReadTarget from the protobuf v3 wire format
func (val *ReadTarget) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *ReadTarget) Size() int {
	return proto.Size(val)
}

// Equal returns whether two ReadTarget values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *ReadTarget) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *ReadTarget
	switch t := that.(type) {
	case *ReadTarget:
		that1 = t
	case ReadTarget:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type AwaitSlot to the protobuf v3 wire format
func (val *AwaitSlot) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type AwaitSlot from the protobuf v3 wire format
func (val *AwaitSlot) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *AwaitSlot) Size() int {
	return proto.Size(val)
}

// Equal returns whether two AwaitSlot values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *AwaitSlot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *AwaitSlot
	switch t := that.(type) {
	case *AwaitSlot:
		that1 = t
	case AwaitSlot:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type AwaitInstruction to the protobuf v3 wire format
func (val *AwaitInstruction) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type AwaitInstruction from the protobuf v3 wire format
func (val *AwaitInstruction) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *AwaitInstruction) Size() int {
	return proto.Size(val)
}

// Equal returns whether two AwaitInstruction values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *AwaitInstruction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *AwaitInstruction
	switch t := that.(type) {
	case *AwaitInstruction:
		that1 = t
	case AwaitInstruction:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type StartNexusOperation to the protobuf v3 wire format
func (val *StartNexusOperation) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type StartNexusOperation from the protobuf v3 wire format
func (val *StartNexusOperation) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *StartNexusOperation) Size() int {
	return proto.Size(val)
}

// Equal returns whether two StartNexusOperation values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *StartNexusOperation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *StartNexusOperation
	switch t := that.(type) {
	case *StartNexusOperation:
		that1 = t
	case StartNexusOperation:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type CompleteNexusOperation to the protobuf v3 wire format
func (val *CompleteNexusOperation) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type CompleteNexusOperation from the protobuf v3 wire format
func (val *CompleteNexusOperation) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *CompleteNexusOperation) Size() int {
	return proto.Size(val)
}

// Equal returns whether two CompleteNexusOperation values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *CompleteNexusOperation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *CompleteNexusOperation
	switch t := that.(type) {
	case *CompleteNexusOperation:
		that1 = t
	case CompleteNexusOperation:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RespondNexus to the protobuf v3 wire format
func (val *RespondNexus) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RespondNexus from the protobuf v3 wire format
func (val *RespondNexus) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RespondNexus) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RespondNexus values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RespondNexus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RespondNexus
	switch t := that.(type) {
	case *RespondNexus:
		that1 = t
	case RespondNexus:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type Finish to the protobuf v3 wire format
func (val *Finish) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type Finish from the protobuf v3 wire format
func (val *Finish) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *Finish) Size() int {
	return proto.Size(val)
}

// Equal returns whether two Finish values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *Finish) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *Finish
	switch t := that.(type) {
	case *Finish:
		that1 = t
	case Finish:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type InjectFault to the protobuf v3 wire format
func (val *InjectFault) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InjectFault from the protobuf v3 wire format
func (val *InjectFault) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InjectFault) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InjectFault values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InjectFault) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InjectFault
	switch t := that.(type) {
	case *InjectFault:
		that1 = t
	case InjectFault:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type WorkflowCommand to the protobuf v3 wire format
func (val *WorkflowCommand) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type WorkflowCommand from the protobuf v3 wire format
func (val *WorkflowCommand) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *WorkflowCommand) Size() int {
	return proto.Size(val)
}

// Equal returns whether two WorkflowCommand values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *WorkflowCommand) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *WorkflowCommand
	switch t := that.(type) {
	case *WorkflowCommand:
		that1 = t
	case WorkflowCommand:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type NexusHandlerReply to the protobuf v3 wire format
func (val *NexusHandlerReply) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type NexusHandlerReply from the protobuf v3 wire format
func (val *NexusHandlerReply) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *NexusHandlerReply) Size() int {
	return proto.Size(val)
}

// Equal returns whether two NexusHandlerReply values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *NexusHandlerReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *NexusHandlerReply
	switch t := that.(type) {
	case *NexusHandlerReply:
		that1 = t
	case NexusHandlerReply:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type NexusOperationCompletion to the protobuf v3 wire format
func (val *NexusOperationCompletion) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type NexusOperationCompletion from the protobuf v3 wire format
func (val *NexusOperationCompletion) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *NexusOperationCompletion) Size() int {
	return proto.Size(val)
}

// Equal returns whether two NexusOperationCompletion values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *NexusOperationCompletion) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *NexusOperationCompletion
	switch t := that.(type) {
	case *NexusOperationCompletion:
		that1 = t
	case NexusOperationCompletion:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type InstructionLimits to the protobuf v3 wire format
func (val *InstructionLimits) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type InstructionLimits from the protobuf v3 wire format
func (val *InstructionLimits) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *InstructionLimits) Size() int {
	return proto.Size(val)
}

// Equal returns whether two InstructionLimits values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *InstructionLimits) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *InstructionLimits
	switch t := that.(type) {
	case *InstructionLimits:
		that1 = t
	case InstructionLimits:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

var (
	ReadCardinality_shorthandValue = map[string]int32{
		"Unspecified": 0,
		"One":         1,
		"EmitEach":    2,
	}
)

// ReadCardinalityFromString parses a ReadCardinality value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to ReadCardinality
func ReadCardinalityFromString(s string) (ReadCardinality, error) {
	if v, ok := ReadCardinality_value[s]; ok {
		return ReadCardinality(v), nil
	} else if v, ok := ReadCardinality_shorthandValue[s]; ok {
		return ReadCardinality(v), nil
	}
	return ReadCardinality(0), fmt.Errorf("%s is not a valid ReadCardinality", s)
}

var (
	NexusResponseKind_shorthandValue = map[string]int32{
		"Unspecified":  0,
		"Synchronous":  1,
		"Asynchronous": 2,
		"Error":        3,
	}
)

// NexusResponseKindFromString parses a NexusResponseKind value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to NexusResponseKind
func NexusResponseKindFromString(s string) (NexusResponseKind, error) {
	if v, ok := NexusResponseKind_value[s]; ok {
		return NexusResponseKind(v), nil
	} else if v, ok := NexusResponseKind_shorthandValue[s]; ok {
		return NexusResponseKind(v), nil
	}
	return NexusResponseKind(0), fmt.Errorf("%s is not a valid NexusResponseKind", s)
}

var (
	FaultKind_shorthandValue = map[string]int32{
		"Unspecified":  0,
		"WorkerStop":   1,
		"WorkerResume": 2,
	}
)

// FaultKindFromString parses a FaultKind value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to FaultKind
func FaultKindFromString(s string) (FaultKind, error) {
	if v, ok := FaultKind_value[s]; ok {
		return FaultKind(v), nil
	} else if v, ok := FaultKind_shorthandValue[s]; ok {
		return FaultKind(v), nil
	}
	return FaultKind(0), fmt.Errorf("%s is not a valid FaultKind", s)
}

var (
	InstructionOutcomeStatus_shorthandValue = map[string]int32{
		"Unspecified":     0,
		"Succeeded":       1,
		"ProtocolFailure": 2,
		"SdkFailure":      3,
		"TimedOut":        4,
		"Canceled":        5,
	}
)

// InstructionOutcomeStatusFromString parses a InstructionOutcomeStatus value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to InstructionOutcomeStatus
func InstructionOutcomeStatusFromString(s string) (InstructionOutcomeStatus, error) {
	if v, ok := InstructionOutcomeStatus_value[s]; ok {
		return InstructionOutcomeStatus(v), nil
	} else if v, ok := InstructionOutcomeStatus_shorthandValue[s]; ok {
		return InstructionOutcomeStatus(v), nil
	}
	return InstructionOutcomeStatus(0), fmt.Errorf("%s is not a valid InstructionOutcomeStatus", s)
}
