// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/testpilot/v1/outcome.proto

package testpilot

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Instruction outcome Status is normative Testpilot terminology.
// (-- api-linter: core::0191::file-layout=disabled
//
//	core::0216::synonyms=disabled --)
//
// (-- api-linter: core::0216::synonyms=disabled --)
type InstructionOutcomeStatus int32

const (
	INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED          InstructionOutcomeStatus = 0
	INSTRUCTION_OUTCOME_STATUS_SUCCEEDED            InstructionOutcomeStatus = 1
	INSTRUCTION_OUTCOME_STATUS_PROTOCOL_NON_SUCCESS InstructionOutcomeStatus = 2
	INSTRUCTION_OUTCOME_STATUS_SDK_FAILURE          InstructionOutcomeStatus = 3
	INSTRUCTION_OUTCOME_STATUS_TIMED_OUT            InstructionOutcomeStatus = 4
	INSTRUCTION_OUTCOME_STATUS_CANCELED             InstructionOutcomeStatus = 5
)

// Enum value maps for InstructionOutcomeStatus.
var (
	InstructionOutcomeStatus_name = map[int32]string{
		0: "INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED",
		1: "INSTRUCTION_OUTCOME_STATUS_SUCCEEDED",
		2: "INSTRUCTION_OUTCOME_STATUS_PROTOCOL_NON_SUCCESS",
		3: "INSTRUCTION_OUTCOME_STATUS_SDK_FAILURE",
		4: "INSTRUCTION_OUTCOME_STATUS_TIMED_OUT",
		5: "INSTRUCTION_OUTCOME_STATUS_CANCELED",
	}
	InstructionOutcomeStatus_value = map[string]int32{
		"INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED":          0,
		"INSTRUCTION_OUTCOME_STATUS_SUCCEEDED":            1,
		"INSTRUCTION_OUTCOME_STATUS_PROTOCOL_NON_SUCCESS": 2,
		"INSTRUCTION_OUTCOME_STATUS_SDK_FAILURE":          3,
		"INSTRUCTION_OUTCOME_STATUS_TIMED_OUT":            4,
		"INSTRUCTION_OUTCOME_STATUS_CANCELED":             5,
	}
)

func (x InstructionOutcomeStatus) Enum() *InstructionOutcomeStatus {
	p := new(InstructionOutcomeStatus)
	*p = x
	return p
}

func (x InstructionOutcomeStatus) String() string {
	switch x {
	case INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED:
		return "Unspecified"
	case INSTRUCTION_OUTCOME_STATUS_SUCCEEDED:
		return "Succeeded"
	case INSTRUCTION_OUTCOME_STATUS_PROTOCOL_NON_SUCCESS:
		return "ProtocolNonSuccess"
	case INSTRUCTION_OUTCOME_STATUS_SDK_FAILURE:
		return "SdkFailure"
	case INSTRUCTION_OUTCOME_STATUS_TIMED_OUT:
		return "TimedOut"
	case INSTRUCTION_OUTCOME_STATUS_CANCELED:
		return "Canceled"
	default:
		return strconv.Itoa(int(x))
	}

}

func (InstructionOutcomeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_outcome_proto_enumTypes[0].Descriptor()
}

func (InstructionOutcomeStatus) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_outcome_proto_enumTypes[0]
}

func (x InstructionOutcomeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstructionOutcomeStatus.Descriptor instead.
func (InstructionOutcomeStatus) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_outcome_proto_rawDescGZIP(), []int{0}
}

type InstructionOutcome struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Status         InstructionOutcomeStatus `protobuf:"varint,1,opt,name=status,proto3,enum=temporal.server.api.testpilot.v1.InstructionOutcomeStatus" json:"status,omitempty"`
	ProtocolCode   string                   `protobuf:"bytes,2,opt,name=protocol_code,json=protocolCode,proto3" json:"protocol_code,omitempty"`
	SdkFailureCode string                   `protobuf:"bytes,3,opt,name=sdk_failure_code,json=sdkFailureCode,proto3" json:"sdk_failure_code,omitempty"`
	Detail         string                   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Value          *Value                   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstructionOutcome) Reset() {
	*x = InstructionOutcome{}
	mi := &file_temporal_server_api_testpilot_v1_outcome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionOutcome) ProtoMessage() {}

func (x *InstructionOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_outcome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionOutcome.ProtoReflect.Descriptor instead.
func (*InstructionOutcome) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_outcome_proto_rawDescGZIP(), []int{0}
}

func (x *InstructionOutcome) GetStatus() InstructionOutcomeStatus {
	if x != nil {
		return x.Status
	}
	return INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED
}

func (x *InstructionOutcome) GetProtocolCode() string {
	if x != nil {
		return x.ProtocolCode
	}
	return ""
}

func (x *InstructionOutcome) GetSdkFailureCode() string {
	if x != nil {
		return x.SdkFailureCode
	}
	return ""
}

func (x *InstructionOutcome) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *InstructionOutcome) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_temporal_server_api_testpilot_v1_outcome_proto protoreflect.FileDescriptor

const file_temporal_server_api_testpilot_v1_outcome_proto_rawDesc = "" +
	"\n" +
	".temporal/server/api/testpilot/v1/outcome.proto\x12 temporal.server.api.testpilot.v1\x1a,temporal/server/api/testpilot/v1/value.proto\"\x8e\x02\n" +
	"\x12InstructionOutcome\x12R\n" +
	"\x06status\x18\x01 \x01(\x0e2:.temporal.server.api.testpilot.v1.InstructionOutcomeStatusR\x06status\x12#\n" +
	"\rprotocol_code\x18\x02 \x01(\tR\fprotocolCode\x12(\n" +
	"\x10sdk_failure_code\x18\x03 \x01(\tR\x0esdkFailureCode\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12=\n" +
	"\x05value\x18\x05 \x01(\v2'.temporal.server.api.testpilot.v1.ValueR\x05value*\xa4\x02\n" +
	"\x18InstructionOutcomeStatus\x12*\n" +
	"&INSTRUCTION_OUTCOME_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$INSTRUCTION_OUTCOME_STATUS_SUCCEEDED\x10\x01\x123\n" +
	"/INSTRUCTION_OUTCOME_STATUS_PROTOCOL_NON_SUCCESS\x10\x02\x12*\n" +
	"&INSTRUCTION_OUTCOME_STATUS_SDK_FAILURE\x10\x03\x12(\n" +
	"$INSTRUCTION_OUTCOME_STATUS_TIMED_OUT\x10\x04\x12'\n" +
	"#INSTRUCTION_OUTCOME_STATUS_CANCELED\x10\x05B2Z0go.temporal.io/server/api/testpilot/v1;testpilotb\x06proto3"

var (
	file_temporal_server_api_testpilot_v1_outcome_proto_rawDescOnce sync.Once
	file_temporal_server_api_testpilot_v1_outcome_proto_rawDescData []byte
)

func file_temporal_server_api_testpilot_v1_outcome_proto_rawDescGZIP() []byte {
	file_temporal_server_api_testpilot_v1_outcome_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_testpilot_v1_outcome_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_outcome_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_outcome_proto_rawDesc)))
	})
	return file_temporal_server_api_testpilot_v1_outcome_proto_rawDescData
}

var file_temporal_server_api_testpilot_v1_outcome_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_server_api_testpilot_v1_outcome_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_temporal_server_api_testpilot_v1_outcome_proto_goTypes = []any{
	(InstructionOutcomeStatus)(0), // 0: temporal.server.api.testpilot.v1.InstructionOutcomeStatus
	(*InstructionOutcome)(nil),    // 1: temporal.server.api.testpilot.v1.InstructionOutcome
	(*Value)(nil),                 // 2: temporal.server.api.testpilot.v1.Value
}
var file_temporal_server_api_testpilot_v1_outcome_proto_depIdxs = []int32{
	0, // 0: temporal.server.api.testpilot.v1.InstructionOutcome.status:type_name -> temporal.server.api.testpilot.v1.InstructionOutcomeStatus
	2, // 1: temporal.server.api.testpilot.v1.InstructionOutcome.value:type_name -> temporal.server.api.testpilot.v1.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_temporal_server_api_testpilot_v1_outcome_proto_init() }
func file_temporal_server_api_testpilot_v1_outcome_proto_init() {
	if File_temporal_server_api_testpilot_v1_outcome_proto != nil {
		return
	}
	file_temporal_server_api_testpilot_v1_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_outcome_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_outcome_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_testpilot_v1_outcome_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_testpilot_v1_outcome_proto_depIdxs,
		EnumInfos:         file_temporal_server_api_testpilot_v1_outcome_proto_enumTypes,
		MessageInfos:      file_temporal_server_api_testpilot_v1_outcome_proto_msgTypes,
	}.Build()
	File_temporal_server_api_testpilot_v1_outcome_proto = out.File
	file_temporal_server_api_testpilot_v1_outcome_proto_goTypes = nil
	file_temporal_server_api_testpilot_v1_outcome_proto_depIdxs = nil
}
