// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/testpilot/v1/program.proto

package testpilot

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoleKind names what a Role stands for: an RPC or Nexus endpoint, a worker, a task queue, or a
// participant that binds nothing.
// (-- api-linter: core::0191::file-layout=disabled --)
type RoleKind int32

const (
	ROLE_KIND_UNSPECIFIED RoleKind = 0
	ROLE_KIND_ENDPOINT    RoleKind = 1
	ROLE_KIND_WORKER      RoleKind = 2
	ROLE_KIND_TASK_QUEUE  RoleKind = 3
	ROLE_KIND_PARTICIPANT RoleKind = 4
)

// Enum value maps for RoleKind.
var (
	RoleKind_name = map[int32]string{
		0: "ROLE_KIND_UNSPECIFIED",
		1: "ROLE_KIND_ENDPOINT",
		2: "ROLE_KIND_WORKER",
		3: "ROLE_KIND_TASK_QUEUE",
		4: "ROLE_KIND_PARTICIPANT",
	}
	RoleKind_value = map[string]int32{
		"ROLE_KIND_UNSPECIFIED": 0,
		"ROLE_KIND_ENDPOINT":    1,
		"ROLE_KIND_WORKER":      2,
		"ROLE_KIND_TASK_QUEUE":  3,
		"ROLE_KIND_PARTICIPANT": 4,
	}
)

func (x RoleKind) Enum() *RoleKind {
	p := new(RoleKind)
	*p = x
	return p
}

func (x RoleKind) String() string {
	switch x {
	case ROLE_KIND_UNSPECIFIED:
		return "Unspecified"
	case ROLE_KIND_ENDPOINT:
		return "Endpoint"
	case ROLE_KIND_WORKER:
		return "Worker"
	case ROLE_KIND_TASK_QUEUE:
		return "TaskQueue"
	case ROLE_KIND_PARTICIPANT:
		return "Participant"
	default:
		return strconv.Itoa(int(x))
	}

}

func (RoleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_testpilot_v1_program_proto_enumTypes[0].Descriptor()
}

func (RoleKind) Type() protoreflect.EnumType {
	return &file_temporal_server_api_testpilot_v1_program_proto_enumTypes[0]
}

func (x RoleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleKind.Descriptor instead.
func (RoleKind) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{0}
}

// Program is a bounded collection of context-local DAGs and one always-run cleanup graph.
// It declares no environment bindings: the ones it uses are those its roles and expressions reference,
// derived at preparation, and the Profile must supply each.
type Program struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProgramId    string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Roles        []*Role                `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Slots        []*Slot                `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	Observations []*Observation         `protobuf:"bytes,4,rep,name=observations,proto3" json:"observations,omitempty"`
	Entrypoints  []*Entrypoint          `protobuf:"bytes,5,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	Cleanup      *Cleanup               `protobuf:"bytes,6,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	// The kinds of correlated evidence the Program lifts, each declared once.
	Evidence []*EvidenceDeclaration `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence,omitempty"`
	// The dynamic-configuration settings the Program requires of the environment it runs in.
	// Preparation refuses a Profile whose configuration lacks one or sets it to another value.
	RequiredSettings []*RequiredSetting `protobuf:"bytes,8,rep,name=required_settings,json=requiredSettings,proto3" json:"required_settings,omitempty"`
	// The limits an instruction that writes none takes, as the Producer declares them. Absent, such an
	// instruction takes the Profile's instruction defaults.
	InstructionDefaults *InstructionLimits `protobuf:"bytes,9,opt,name=instruction_defaults,json=instructionDefaults,proto3" json:"instruction_defaults,omitempty"`
	// Whether the Run's record order is the causal order of one operation's evidence across sources:
	// set, evidence lifted from one source names the operation's previously lifted evidence, from
	// another source, as its causal parent. Unset, only a source's ordinals order its evidence.
	RunOrderIsCausal            bool                          `protobuf:"varint,10,opt,name=run_order_is_causal,json=runOrderIsCausal,proto3" json:"run_order_is_causal,omitempty"`
	ActivityExternalSettlements []*ActivityExternalSettlement `protobuf:"bytes,11,rep,name=activity_external_settlements,json=activityExternalSettlements,proto3" json:"activity_external_settlements,omitempty"`
	ActivityResetSettlements    []*ActivityResetSettlement    `protobuf:"bytes,12,rep,name=activity_reset_settlements,json=activityResetSettlements,proto3" json:"activity_reset_settlements,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *Program) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Program) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *Program) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *Program) GetEntrypoints() []*Entrypoint {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *Program) GetCleanup() *Cleanup {
	if x != nil {
		return x.Cleanup
	}
	return nil
}

func (x *Program) GetEvidence() []*EvidenceDeclaration {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Program) GetRequiredSettings() []*RequiredSetting {
	if x != nil {
		return x.RequiredSettings
	}
	return nil
}

func (x *Program) GetInstructionDefaults() *InstructionLimits {
	if x != nil {
		return x.InstructionDefaults
	}
	return nil
}

func (x *Program) GetRunOrderIsCausal() bool {
	if x != nil {
		return x.RunOrderIsCausal
	}
	return false
}

func (x *Program) GetActivityExternalSettlements() []*ActivityExternalSettlement {
	if x != nil {
		return x.ActivityExternalSettlements
	}
	return nil
}

func (x *Program) GetActivityResetSettlements() []*ActivityResetSettlement {
	if x != nil {
		return x.ActivityResetSettlements
	}
	return nil
}

// ActivityExternalSettlement binds one pending activity reservation to the controller's bounded
// held read, typed external answer, terminal read and independent cleanup.
type ActivityExternalSettlement struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Carrier              *InstructionReference  `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	ActivityEntrypointId string                 `protobuf:"bytes,2,opt,name=activity_entrypoint_id,json=activityEntrypointId,proto3" json:"activity_entrypoint_id,omitempty"`
	ReservationOrdinal   int64                  `protobuf:"varint,3,opt,name=reservation_ordinal,json=reservationOrdinal,proto3" json:"reservation_ordinal,omitempty"`
	PendingSlotId        string                 `protobuf:"bytes,4,opt,name=pending_slot_id,json=pendingSlotId,proto3" json:"pending_slot_id,omitempty"`
	Held                 *InstructionReference  `protobuf:"bytes,5,opt,name=held,proto3" json:"held,omitempty"`
	Answer               *InstructionReference  `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	RequestCancel        *InstructionReference  `protobuf:"bytes,7,opt,name=request_cancel,json=requestCancel,proto3" json:"request_cancel,omitempty"`
	Settlement           *InstructionReference  `protobuf:"bytes,8,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Cleanup              *InstructionReference  `protobuf:"bytes,9,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActivityExternalSettlement) Reset() {
	*x = ActivityExternalSettlement{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityExternalSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityExternalSettlement) ProtoMessage() {}

func (x *ActivityExternalSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityExternalSettlement.ProtoReflect.Descriptor instead.
func (*ActivityExternalSettlement) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityExternalSettlement) GetCarrier() *InstructionReference {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *ActivityExternalSettlement) GetActivityEntrypointId() string {
	if x != nil {
		return x.ActivityEntrypointId
	}
	return ""
}

func (x *ActivityExternalSettlement) GetReservationOrdinal() int64 {
	if x != nil {
		return x.ReservationOrdinal
	}
	return 0
}

func (x *ActivityExternalSettlement) GetPendingSlotId() string {
	if x != nil {
		return x.PendingSlotId
	}
	return ""
}

func (x *ActivityExternalSettlement) GetHeld() *InstructionReference {
	if x != nil {
		return x.Held
	}
	return nil
}

func (x *ActivityExternalSettlement) GetAnswer() *InstructionReference {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *ActivityExternalSettlement) GetRequestCancel() *InstructionReference {
	if x != nil {
		return x.RequestCancel
	}
	return nil
}

func (x *ActivityExternalSettlement) GetSettlement() *InstructionReference {
	if x != nil {
		return x.Settlement
	}
	return nil
}

func (x *ActivityExternalSettlement) GetCleanup() *InstructionReference {
	if x != nil {
		return x.Cleanup
	}
	return nil
}

// ActivityResetSettlement binds one pending activity reservation's publication to the controller's
// bounded held read and its typed ResetActivityExecution, which a server timer applies. The
// server's next delivery is a first attempt again: the reservation at fresh_reservation_ordinal is
// numbered from the entrypoint's first attempt number, and later ones follow it. A terminal read
// and independent cleanup end it.
type ActivityResetSettlement struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Carrier                 *InstructionReference  `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	ActivityEntrypointId    string                 `protobuf:"bytes,2,opt,name=activity_entrypoint_id,json=activityEntrypointId,proto3" json:"activity_entrypoint_id,omitempty"`
	ReservationOrdinal      int64                  `protobuf:"varint,3,opt,name=reservation_ordinal,json=reservationOrdinal,proto3" json:"reservation_ordinal,omitempty"`
	PendingSlotId           string                 `protobuf:"bytes,4,opt,name=pending_slot_id,json=pendingSlotId,proto3" json:"pending_slot_id,omitempty"`
	Held                    *InstructionReference  `protobuf:"bytes,5,opt,name=held,proto3" json:"held,omitempty"`
	ResetRequest            *InstructionReference  `protobuf:"bytes,6,opt,name=reset_request,json=resetRequest,proto3" json:"reset_request,omitempty"`
	FreshReservationOrdinal int64                  `protobuf:"varint,7,opt,name=fresh_reservation_ordinal,json=freshReservationOrdinal,proto3" json:"fresh_reservation_ordinal,omitempty"`
	Settlement              *InstructionReference  `protobuf:"bytes,8,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Cleanup                 *InstructionReference  `protobuf:"bytes,9,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivityResetSettlement) Reset() {
	*x = ActivityResetSettlement{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResetSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResetSettlement) ProtoMessage() {}

func (x *ActivityResetSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResetSettlement.ProtoReflect.Descriptor instead.
func (*ActivityResetSettlement) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityResetSettlement) GetCarrier() *InstructionReference {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *ActivityResetSettlement) GetActivityEntrypointId() string {
	if x != nil {
		return x.ActivityEntrypointId
	}
	return ""
}

func (x *ActivityResetSettlement) GetReservationOrdinal() int64 {
	if x != nil {
		return x.ReservationOrdinal
	}
	return 0
}

func (x *ActivityResetSettlement) GetPendingSlotId() string {
	if x != nil {
		return x.PendingSlotId
	}
	return ""
}

func (x *ActivityResetSettlement) GetHeld() *InstructionReference {
	if x != nil {
		return x.Held
	}
	return nil
}

func (x *ActivityResetSettlement) GetResetRequest() *InstructionReference {
	if x != nil {
		return x.ResetRequest
	}
	return nil
}

func (x *ActivityResetSettlement) GetFreshReservationOrdinal() int64 {
	if x != nil {
		return x.FreshReservationOrdinal
	}
	return 0
}

func (x *ActivityResetSettlement) GetSettlement() *InstructionReference {
	if x != nil {
		return x.Settlement
	}
	return nil
}

func (x *ActivityResetSettlement) GetCleanup() *InstructionReference {
	if x != nil {
		return x.Cleanup
	}
	return nil
}

// A dynamic-configuration setting a Program requires: its key and its value, each spelled as the
// environment's dynamic configuration spells it.
type RequiredSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredSetting) Reset() {
	*x = RequiredSetting{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredSetting) ProtoMessage() {}

func (x *RequiredSetting) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredSetting.ProtoReflect.Descriptor instead.
func (*RequiredSetting) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{3}
}

func (x *RequiredSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequiredSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Role is a symbolic participant that instructions and activations address. Its bindings resolve to
// the Profile's physical values.
type Role struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoleId string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Kind   RoleKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=temporal.server.api.testpilot.v1.RoleKind" json:"kind,omitempty"`
	// The environment binding holding the namespace of a worker or task-queue role.
	NamespaceBindingId string `protobuf:"bytes,3,opt,name=namespace_binding_id,json=namespaceBindingId,proto3" json:"namespace_binding_id,omitempty"`
	// The environment binding holding the role's resource: a task-queue role's queue, or an endpoint
	// role's Nexus endpoint.
	ResourceBindingId string `protobuf:"bytes,4,opt,name=resource_binding_id,json=resourceBindingId,proto3" json:"resource_binding_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Role) GetKind() RoleKind {
	if x != nil {
		return x.Kind
	}
	return ROLE_KIND_UNSPECIFIED
}

func (x *Role) GetNamespaceBindingId() string {
	if x != nil {
		return x.NamespaceBindingId
	}
	return ""
}

func (x *Role) GetResourceBindingId() string {
	if x != nil {
		return x.ResourceBindingId
	}
	return ""
}

// Slot is private immutable single-assignment execution data with exactly one writer. It holds a
// typed value or an opaque effect handle.
type Slot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SlotId string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Slot_Value
	//	*Slot_OpaqueHandle
	Content       isSlot_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{5}
}

func (x *Slot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Slot) GetContent() isSlot_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Slot) GetValue() *ValueType {
	if x != nil {
		if x, ok := x.Content.(*Slot_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Slot) GetOpaqueHandle() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Content.(*Slot_OpaqueHandle); ok {
			return x.OpaqueHandle
		}
	}
	return nil
}

type isSlot_Content interface {
	isSlot_Content()
}

type Slot_Value struct {
	Value *ValueType `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

type Slot_OpaqueHandle struct {
	// An effect handle issued by the Driver, never an expression or transport value.
	OpaqueHandle *emptypb.Empty `protobuf:"bytes,3,opt,name=opaque_handle,json=opaqueHandle,proto3,oneof"`
}

func (*Slot_Value) isSlot_Content() {}

func (*Slot_OpaqueHandle) isSlot_Content() {}

// Observation is a declared typed value attached to a Run Event and available to the Contract.
type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservationId string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Type          *ValueType             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{6}
}

func (x *Observation) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *Observation) GetType() *ValueType {
	if x != nil {
		return x.Type
	}
	return nil
}

// Entrypoint contains one Driver-activated, context-local acyclic instruction graph.
type Entrypoint struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EntrypointId string                 `protobuf:"bytes,1,opt,name=entrypoint_id,json=entrypointId,proto3" json:"entrypoint_id,omitempty"`
	// Types that are valid to be assigned to Activation:
	//
	//	*Entrypoint_Controller
	//	*Entrypoint_Workflow
	//	*Entrypoint_Activity
	//	*Entrypoint_NexusHandler
	Activation    isEntrypoint_Activation `protobuf_oneof:"activation"`
	Instructions  []*InstructionNode      `protobuf:"bytes,6,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrypoint) Reset() {
	*x = Entrypoint{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrypoint) ProtoMessage() {}

func (x *Entrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrypoint.ProtoReflect.Descriptor instead.
func (*Entrypoint) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{7}
}

func (x *Entrypoint) GetEntrypointId() string {
	if x != nil {
		return x.EntrypointId
	}
	return ""
}

func (x *Entrypoint) GetActivation() isEntrypoint_Activation {
	if x != nil {
		return x.Activation
	}
	return nil
}

func (x *Entrypoint) GetController() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Activation.(*Entrypoint_Controller); ok {
			return x.Controller
		}
	}
	return nil
}

func (x *Entrypoint) GetWorkflow() *WorkflowActivation {
	if x != nil {
		if x, ok := x.Activation.(*Entrypoint_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *Entrypoint) GetActivity() *ActivityActivation {
	if x != nil {
		if x, ok := x.Activation.(*Entrypoint_Activity); ok {
			return x.Activity
		}
	}
	return nil
}

func (x *Entrypoint) GetNexusHandler() *NexusHandlerActivation {
	if x != nil {
		if x, ok := x.Activation.(*Entrypoint_NexusHandler); ok {
			return x.NexusHandler
		}
	}
	return nil
}

func (x *Entrypoint) GetInstructions() []*InstructionNode {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type isEntrypoint_Activation interface {
	isEntrypoint_Activation()
}

type Entrypoint_Controller struct {
	// Activates exactly once when the Run opens.
	Controller *emptypb.Empty `protobuf:"bytes,2,opt,name=controller,proto3,oneof"`
}

type Entrypoint_Workflow struct {
	Workflow *WorkflowActivation `protobuf:"bytes,3,opt,name=workflow,proto3,oneof"`
}

type Entrypoint_Activity struct {
	Activity *ActivityActivation `protobuf:"bytes,4,opt,name=activity,proto3,oneof"`
}

type Entrypoint_NexusHandler struct {
	NexusHandler *NexusHandlerActivation `protobuf:"bytes,5,opt,name=nexus_handler,json=nexusHandler,proto3,oneof"`
}

func (*Entrypoint_Controller) isEntrypoint_Activation() {}

func (*Entrypoint_Workflow) isEntrypoint_Activation() {}

func (*Entrypoint_Activity) isEntrypoint_Activation() {}

func (*Entrypoint_NexusHandler) isEntrypoint_Activation() {}

// WorkflowActivation activates the entrypoint for each workflow of this type the worker role runs on
// the task-queue role.
type WorkflowActivation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType    string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	WorkerRoleId    string                 `protobuf:"bytes,2,opt,name=worker_role_id,json=workerRoleId,proto3" json:"worker_role_id,omitempty"`
	TaskQueueRoleId string                 `protobuf:"bytes,3,opt,name=task_queue_role_id,json=taskQueueRoleId,proto3" json:"task_queue_role_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowActivation) Reset() {
	*x = WorkflowActivation{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActivation) ProtoMessage() {}

func (x *WorkflowActivation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActivation.ProtoReflect.Descriptor instead.
func (*WorkflowActivation) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowActivation) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowActivation) GetWorkerRoleId() string {
	if x != nil {
		return x.WorkerRoleId
	}
	return ""
}

func (x *WorkflowActivation) GetTaskQueueRoleId() string {
	if x != nil {
		return x.TaskQueueRoleId
	}
	return ""
}

// ActivityActivation activates the entrypoint for each attempt of a standalone activity of this type
// the worker role runs on the task-queue role. The entrypoint's instructions are the activity's
// attempts in order, numbered as attempt_numbering declares, and a reservation carrier reserves one
// activation per instruction.
type ActivityActivation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivityType    string                 `protobuf:"bytes,1,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	WorkerRoleId    string                 `protobuf:"bytes,2,opt,name=worker_role_id,json=workerRoleId,proto3" json:"worker_role_id,omitempty"`
	TaskQueueRoleId string                 `protobuf:"bytes,3,opt,name=task_queue_role_id,json=taskQueueRoleId,proto3" json:"task_queue_role_id,omitempty"`
	// How the system numbers the activity's attempts; preparation refuses an activity entrypoint that
	// declares none.
	AttemptNumbering *AttemptNumbering `protobuf:"bytes,4,opt,name=attempt_numbering,json=attemptNumbering,proto3" json:"attempt_numbering,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityActivation) Reset() {
	*x = ActivityActivation{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityActivation) ProtoMessage() {}

func (x *ActivityActivation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityActivation.ProtoReflect.Descriptor instead.
func (*ActivityActivation) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{9}
}

func (x *ActivityActivation) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *ActivityActivation) GetWorkerRoleId() string {
	if x != nil {
		return x.WorkerRoleId
	}
	return ""
}

func (x *ActivityActivation) GetTaskQueueRoleId() string {
	if x != nil {
		return x.TaskQueueRoleId
	}
	return ""
}

func (x *ActivityActivation) GetAttemptNumbering() *AttemptNumbering {
	if x != nil {
		return x.AttemptNumbering
	}
	return nil
}

// AttemptNumbering is how a system numbers the attempts of one activity: the Nth instruction of its
// entrypoint is the attempt numbered first + N - 1, and with one_run every attempt names the run the
// first one named.
type AttemptNumbering struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         int64                  `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	OneRun        bool                   `protobuf:"varint,2,opt,name=one_run,json=oneRun,proto3" json:"one_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptNumbering) Reset() {
	*x = AttemptNumbering{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptNumbering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptNumbering) ProtoMessage() {}

func (x *AttemptNumbering) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptNumbering.ProtoReflect.Descriptor instead.
func (*AttemptNumbering) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{10}
}

func (x *AttemptNumbering) GetFirst() int64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *AttemptNumbering) GetOneRun() bool {
	if x != nil {
		return x.OneRun
	}
	return false
}

// NexusHandlerActivation activates the entrypoint for each call of this Nexus operation the worker
// role handles on the task-queue role.
type NexusHandlerActivation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Service         string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Operation       string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	WorkerRoleId    string                 `protobuf:"bytes,3,opt,name=worker_role_id,json=workerRoleId,proto3" json:"worker_role_id,omitempty"`
	TaskQueueRoleId string                 `protobuf:"bytes,4,opt,name=task_queue_role_id,json=taskQueueRoleId,proto3" json:"task_queue_role_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NexusHandlerActivation) Reset() {
	*x = NexusHandlerActivation{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusHandlerActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusHandlerActivation) ProtoMessage() {}

func (x *NexusHandlerActivation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusHandlerActivation.ProtoReflect.Descriptor instead.
func (*NexusHandlerActivation) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{11}
}

func (x *NexusHandlerActivation) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NexusHandlerActivation) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *NexusHandlerActivation) GetWorkerRoleId() string {
	if x != nil {
		return x.WorkerRoleId
	}
	return ""
}

func (x *NexusHandlerActivation) GetTaskQueueRoleId() string {
	if x != nil {
		return x.TaskQueueRoleId
	}
	return ""
}

// Cleanup is always attempted after ordinary execution with an independent bound.
type Cleanup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity is used by cleanup-local InstructionReferences and Run coordinates.
	EntrypointId  string             `protobuf:"bytes,1,opt,name=entrypoint_id,json=entrypointId,proto3" json:"entrypoint_id,omitempty"`
	Instructions  []*InstructionNode `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cleanup) Reset() {
	*x = Cleanup{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cleanup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cleanup) ProtoMessage() {}

func (x *Cleanup) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cleanup.ProtoReflect.Descriptor instead.
func (*Cleanup) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{12}
}

func (x *Cleanup) GetEntrypointId() string {
	if x != nil {
		return x.EntrypointId
	}
	return ""
}

func (x *Cleanup) GetInstructions() []*InstructionNode {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// ProgramLimits are a Profile's resource ceilings on every Program it admits. A Case declares none of
// them; every limit is positive and within the Driver's hard ceiling.
type ProgramLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entrypoints, not counting cleanup.
	MaxEntrypoints int64 `protobuf:"varint,1,opt,name=max_entrypoints,json=maxEntrypoints,proto3" json:"max_entrypoints,omitempty"`
	// Instruction nodes across every entrypoint and cleanup.
	MaxNodes int64 `protobuf:"varint,2,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	// Dependency references across every instruction node.
	MaxEdges int64 `protobuf:"varint,3,opt,name=max_edges,json=maxEdges,proto3" json:"max_edges,omitempty"`
	// Controller activations plus reserved activations weighted by attempts.
	MaxActivations int64 `protobuf:"varint,4,opt,name=max_activations,json=maxActivations,proto3" json:"max_activations,omitempty"`
	// Instruction attempts dispatched across the Run, and the ceiling of each instruction's attempts.
	MaxAttempts int64 `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Run Events recorded, RUN_CLOSED included, and the ceiling of max_instruction_emitted_events.
	MaxRunEvents int64 `protobuf:"varint,6,opt,name=max_run_events,json=maxRunEvents,proto3" json:"max_run_events,omitempty"`
	// Nesting depth of any expression or path.
	MaxExpressionDepth int64 `protobuf:"varint,7,opt,name=max_expression_depth,json=maxExpressionDepth,proto3" json:"max_expression_depth,omitempty"`
	// Elements a wildcard path or a literal collection may yield.
	MaxPathFanout int64 `protobuf:"varint,8,opt,name=max_path_fanout,json=maxPathFanout,proto3" json:"max_path_fanout,omitempty"`
	// Encoded size of one request, and of the environment binding values together.
	MaxRequestBytes int64 `protobuf:"varint,9,opt,name=max_request_bytes,json=maxRequestBytes,proto3" json:"max_request_bytes,omitempty"`
	// The size of one Observation value, and the ceiling of max_instruction_response_bytes.
	MaxResponseBytes int64 `protobuf:"varint,10,opt,name=max_response_bytes,json=maxResponseBytes,proto3" json:"max_response_bytes,omitempty"`
	// Wall-clock bound on opening the Driver session and ordinary execution.
	MaxDuration *durationpb.Duration `protobuf:"bytes,11,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	// Wall-clock bound on each of settling, cleanup and closing the Driver session.
	CleanupDuration *durationpb.Duration `protobuf:"bytes,12,opt,name=cleanup_duration,json=cleanupDuration,proto3" json:"cleanup_duration,omitempty"`
	// Run Events one instruction's response reads may emit per completion.
	MaxInstructionEmittedEvents int64 `protobuf:"varint,13,opt,name=max_instruction_emitted_events,json=maxInstructionEmittedEvents,proto3" json:"max_instruction_emitted_events,omitempty"`
	// Size bound on one instruction's RPC response.
	MaxInstructionResponseBytes int64 `protobuf:"varint,14,opt,name=max_instruction_response_bytes,json=maxInstructionResponseBytes,proto3" json:"max_instruction_response_bytes,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ProgramLimits) Reset() {
	*x = ProgramLimits{}
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramLimits) ProtoMessage() {}

func (x *ProgramLimits) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_server_api_testpilot_v1_program_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramLimits.ProtoReflect.Descriptor instead.
func (*ProgramLimits) Descriptor() ([]byte, []int) {
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP(), []int{13}
}

func (x *ProgramLimits) GetMaxEntrypoints() int64 {
	if x != nil {
		return x.MaxEntrypoints
	}
	return 0
}

func (x *ProgramLimits) GetMaxNodes() int64 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *ProgramLimits) GetMaxEdges() int64 {
	if x != nil {
		return x.MaxEdges
	}
	return 0
}

func (x *ProgramLimits) GetMaxActivations() int64 {
	if x != nil {
		return x.MaxActivations
	}
	return 0
}

func (x *ProgramLimits) GetMaxAttempts() int64 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ProgramLimits) GetMaxRunEvents() int64 {
	if x != nil {
		return x.MaxRunEvents
	}
	return 0
}

func (x *ProgramLimits) GetMaxExpressionDepth() int64 {
	if x != nil {
		return x.MaxExpressionDepth
	}
	return 0
}

func (x *ProgramLimits) GetMaxPathFanout() int64 {
	if x != nil {
		return x.MaxPathFanout
	}
	return 0
}

func (x *ProgramLimits) GetMaxRequestBytes() int64 {
	if x != nil {
		return x.MaxRequestBytes
	}
	return 0
}

func (x *ProgramLimits) GetMaxResponseBytes() int64 {
	if x != nil {
		return x.MaxResponseBytes
	}
	return 0
}

func (x *ProgramLimits) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

func (x *ProgramLimits) GetCleanupDuration() *durationpb.Duration {
	if x != nil {
		return x.CleanupDuration
	}
	return nil
}

func (x *ProgramLimits) GetMaxInstructionEmittedEvents() int64 {
	if x != nil {
		return x.MaxInstructionEmittedEvents
	}
	return 0
}

func (x *ProgramLimits) GetMaxInstructionResponseBytes() int64 {
	if x != nil {
		return x.MaxInstructionResponseBytes
	}
	return 0
}

var File_temporal_server_api_testpilot_v1_program_proto protoreflect.FileDescriptor

const file_temporal_server_api_testpilot_v1_program_proto_rawDesc = "" +
	"\n" +
	".temporal/server/api/testpilot/v1/program.proto\x12 temporal.server.api.testpilot.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a/temporal/server/api/testpilot/v1/evidence.proto\x1a1temporal/server/api/testpilot/v1/expression.proto\x1a2temporal/server/api/testpilot/v1/instruction.proto\x1a,temporal/server/api/testpilot/v1/value.proto\"\xd2\a\n" +
	"\aProgram\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x12<\n" +
	"\x05roles\x18\x02 \x03(\v2&.temporal.server.api.testpilot.v1.RoleR\x05roles\x12<\n" +
	"\x05slots\x18\x03 \x03(\v2&.temporal.server.api.testpilot.v1.SlotR\x05slots\x12Q\n" +
	"\fobservations\x18\x04 \x03(\v2-.temporal.server.api.testpilot.v1.ObservationR\fobservations\x12N\n" +
	"\ventrypoints\x18\x05 \x03(\v2,.temporal.server.api.testpilot.v1.EntrypointR\ventrypoints\x12C\n" +
	"\acleanup\x18\x06 \x01(\v2).temporal.server.api.testpilot.v1.CleanupR\acleanup\x12Q\n" +
	"\bevidence\x18\a \x03(\v25.temporal.server.api.testpilot.v1.EvidenceDeclarationR\bevidence\x12^\n" +
	"\x11required_settings\x18\b \x03(\v21.temporal.server.api.testpilot.v1.RequiredSettingR\x10requiredSettings\x12f\n" +
	"\x14instruction_defaults\x18\t \x01(\v23.temporal.server.api.testpilot.v1.InstructionLimitsR\x13instructionDefaults\x12-\n" +
	"\x13run_order_is_causal\x18\n" +
	" \x01(\bR\x10runOrderIsCausal\x12\x80\x01\n" +
	"\x1dactivity_external_settlements\x18\v \x03(\v2<.temporal.server.api.testpilot.v1.ActivityExternalSettlementR\x1bactivityExternalSettlements\x12w\n" +
	"\x1aactivity_reset_settlements\x18\f \x03(\v29.temporal.server.api.testpilot.v1.ActivityResetSettlementR\x18activityResetSettlements\"\xa2\x05\n" +
	"\x1aActivityExternalSettlement\x12P\n" +
	"\acarrier\x18\x01 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\acarrier\x124\n" +
	"\x16activity_entrypoint_id\x18\x02 \x01(\tR\x14activityEntrypointId\x12/\n" +
	"\x13reservation_ordinal\x18\x03 \x01(\x03R\x12reservationOrdinal\x12&\n" +
	"\x0fpending_slot_id\x18\x04 \x01(\tR\rpendingSlotId\x12J\n" +
	"\x04held\x18\x05 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\x04held\x12N\n" +
	"\x06answer\x18\x06 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\x06answer\x12]\n" +
	"\x0erequest_cancel\x18\a \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\rrequestCancel\x12V\n" +
	"\n" +
	"settlement\x18\b \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\n" +
	"settlement\x12P\n" +
	"\acleanup\x18\t \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\acleanup\"\x89\x05\n" +
	"\x17ActivityResetSettlement\x12P\n" +
	"\acarrier\x18\x01 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\acarrier\x124\n" +
	"\x16activity_entrypoint_id\x18\x02 \x01(\tR\x14activityEntrypointId\x12/\n" +
	"\x13reservation_ordinal\x18\x03 \x01(\x03R\x12reservationOrdinal\x12&\n" +
	"\x0fpending_slot_id\x18\x04 \x01(\tR\rpendingSlotId\x12J\n" +
	"\x04held\x18\x05 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\x04held\x12[\n" +
	"\rreset_request\x18\x06 \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\fresetRequest\x12:\n" +
	"\x19fresh_reservation_ordinal\x18\a \x01(\x03R\x17freshReservationOrdinal\x12V\n" +
	"\n" +
	"settlement\x18\b \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\n" +
	"settlement\x12P\n" +
	"\acleanup\x18\t \x01(\v26.temporal.server.api.testpilot.v1.InstructionReferenceR\acleanup\"9\n" +
	"\x0fRequiredSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc1\x01\n" +
	"\x04Role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12>\n" +
	"\x04kind\x18\x02 \x01(\x0e2*.temporal.server.api.testpilot.v1.RoleKindR\x04kind\x120\n" +
	"\x14namespace_binding_id\x18\x03 \x01(\tR\x12namespaceBindingId\x12.\n" +
	"\x13resource_binding_id\x18\x04 \x01(\tR\x11resourceBindingId\"\xae\x01\n" +
	"\x04Slot\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12C\n" +
	"\x05value\x18\x02 \x01(\v2+.temporal.server.api.testpilot.v1.ValueTypeH\x00R\x05value\x12=\n" +
	"\ropaque_handle\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\fopaqueHandleB\t\n" +
	"\acontent\"u\n" +
	"\vObservation\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12?\n" +
	"\x04type\x18\x02 \x01(\v2+.temporal.server.api.testpilot.v1.ValueTypeR\x04type\"\xd9\x03\n" +
	"\n" +
	"Entrypoint\x12#\n" +
	"\rentrypoint_id\x18\x01 \x01(\tR\fentrypointId\x128\n" +
	"\n" +
	"controller\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"controller\x12R\n" +
	"\bworkflow\x18\x03 \x01(\v24.temporal.server.api.testpilot.v1.WorkflowActivationH\x00R\bworkflow\x12R\n" +
	"\bactivity\x18\x04 \x01(\v24.temporal.server.api.testpilot.v1.ActivityActivationH\x00R\bactivity\x12_\n" +
	"\rnexus_handler\x18\x05 \x01(\v28.temporal.server.api.testpilot.v1.NexusHandlerActivationH\x00R\fnexusHandler\x12U\n" +
	"\finstructions\x18\x06 \x03(\v21.temporal.server.api.testpilot.v1.InstructionNodeR\finstructionsB\f\n" +
	"\n" +
	"activation\"\x8c\x01\n" +
	"\x12WorkflowActivation\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12$\n" +
	"\x0eworker_role_id\x18\x02 \x01(\tR\fworkerRoleId\x12+\n" +
	"\x12task_queue_role_id\x18\x03 \x01(\tR\x0ftaskQueueRoleId\"\xed\x01\n" +
	"\x12ActivityActivation\x12#\n" +
	"\ractivity_type\x18\x01 \x01(\tR\factivityType\x12$\n" +
	"\x0eworker_role_id\x18\x02 \x01(\tR\fworkerRoleId\x12+\n" +
	"\x12task_queue_role_id\x18\x03 \x01(\tR\x0ftaskQueueRoleId\x12_\n" +
	"\x11attempt_numbering\x18\x04 \x01(\v22.temporal.server.api.testpilot.v1.AttemptNumberingR\x10attemptNumbering\"A\n" +
	"\x10AttemptNumbering\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x03R\x05first\x12\x17\n" +
	"\aone_run\x18\x02 \x01(\bR\x06oneRun\"\xa3\x01\n" +
	"\x16NexusHandlerActivation\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12$\n" +
	"\x0eworker_role_id\x18\x03 \x01(\tR\fworkerRoleId\x12+\n" +
	"\x12task_queue_role_id\x18\x04 \x01(\tR\x0ftaskQueueRoleId\"\x85\x01\n" +
	"\aCleanup\x12#\n" +
	"\rentrypoint_id\x18\x01 \x01(\tR\fentrypointId\x12U\n" +
	"\finstructions\x18\x02 \x03(\v21.temporal.server.api.testpilot.v1.InstructionNodeR\finstructions\"\xea\x05\n" +
	"\rProgramLimits\x12'\n" +
	"\x0fmax_entrypoints\x18\x01 \x01(\x03R\x0emaxEntrypoints\x12\x1b\n" +
	"\tmax_nodes\x18\x02 \x01(\x03R\bmaxNodes\x12\x1b\n" +
	"\tmax_edges\x18\x03 \x01(\x03R\bmaxEdges\x12'\n" +
	"\x0fmax_activations\x18\x04 \x01(\x03R\x0emaxActivations\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x03R\vmaxAttempts\x12$\n" +
	"\x0emax_run_events\x18\x06 \x01(\x03R\fmaxRunEvents\x120\n" +
	"\x14max_expression_depth\x18\a \x01(\x03R\x12maxExpressionDepth\x12&\n" +
	"\x0fmax_path_fanout\x18\b \x01(\x03R\rmaxPathFanout\x12*\n" +
	"\x11max_request_bytes\x18\t \x01(\x03R\x0fmaxRequestBytes\x12,\n" +
	"\x12max_response_bytes\x18\n" +
	" \x01(\x03R\x10maxResponseBytes\x12<\n" +
	"\fmax_duration\x18\v \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\x12D\n" +
	"\x10cleanup_duration\x18\f \x01(\v2\x19.google.protobuf.DurationR\x0fcleanupDuration\x12C\n" +
	"\x1emax_instruction_emitted_events\x18\r \x01(\x03R\x1bmaxInstructionEmittedEvents\x12C\n" +
	"\x1emax_instruction_response_bytes\x18\x0e \x01(\x03R\x1bmaxInstructionResponseBytesR\x1fmax_total_duration_millisecondsR!max_cleanup_duration_milliseconds*\x88\x01\n" +
	"\bRoleKind\x12\x19\n" +
	"\x15ROLE_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROLE_KIND_ENDPOINT\x10\x01\x12\x14\n" +
	"\x10ROLE_KIND_WORKER\x10\x02\x12\x18\n" +
	"\x14ROLE_KIND_TASK_QUEUE\x10\x03\x12\x19\n" +
	"\x15ROLE_KIND_PARTICIPANT\x10\x04B2Z0go.temporal.io/server/api/testpilot/v1;testpilotb\x06proto3"

var (
	file_temporal_server_api_testpilot_v1_program_proto_rawDescOnce sync.Once
	file_temporal_server_api_testpilot_v1_program_proto_rawDescData []byte
)

func file_temporal_server_api_testpilot_v1_program_proto_rawDescGZIP() []byte {
	file_temporal_server_api_testpilot_v1_program_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_testpilot_v1_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_program_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_program_proto_rawDesc)))
	})
	return file_temporal_server_api_testpilot_v1_program_proto_rawDescData
}

var file_temporal_server_api_testpilot_v1_program_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_server_api_testpilot_v1_program_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_temporal_server_api_testpilot_v1_program_proto_goTypes = []any{
	(RoleKind)(0),                      // 0: temporal.server.api.testpilot.v1.RoleKind
	(*Program)(nil),                    // 1: temporal.server.api.testpilot.v1.Program
	(*ActivityExternalSettlement)(nil), // 2: temporal.server.api.testpilot.v1.ActivityExternalSettlement
	(*ActivityResetSettlement)(nil),    // 3: temporal.server.api.testpilot.v1.ActivityResetSettlement
	(*RequiredSetting)(nil),            // 4: temporal.server.api.testpilot.v1.RequiredSetting
	(*Role)(nil),                       // 5: temporal.server.api.testpilot.v1.Role
	(*Slot)(nil),                       // 6: temporal.server.api.testpilot.v1.Slot
	(*Observation)(nil),                // 7: temporal.server.api.testpilot.v1.Observation
	(*Entrypoint)(nil),                 // 8: temporal.server.api.testpilot.v1.Entrypoint
	(*WorkflowActivation)(nil),         // 9: temporal.server.api.testpilot.v1.WorkflowActivation
	(*ActivityActivation)(nil),         // 10: temporal.server.api.testpilot.v1.ActivityActivation
	(*AttemptNumbering)(nil),           // 11: temporal.server.api.testpilot.v1.AttemptNumbering
	(*NexusHandlerActivation)(nil),     // 12: temporal.server.api.testpilot.v1.NexusHandlerActivation
	(*Cleanup)(nil),                    // 13: temporal.server.api.testpilot.v1.Cleanup
	(*ProgramLimits)(nil),              // 14: temporal.server.api.testpilot.v1.ProgramLimits
	(*EvidenceDeclaration)(nil),        // 15: temporal.server.api.testpilot.v1.EvidenceDeclaration
	(*InstructionLimits)(nil),          // 16: temporal.server.api.testpilot.v1.InstructionLimits
	(*InstructionReference)(nil),       // 17: temporal.server.api.testpilot.v1.InstructionReference
	(*ValueType)(nil),                  // 18: temporal.server.api.testpilot.v1.ValueType
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
	(*InstructionNode)(nil),            // 20: temporal.server.api.testpilot.v1.InstructionNode
	(*durationpb.Duration)(nil),        // 21: google.protobuf.Duration
}
var file_temporal_server_api_testpilot_v1_program_proto_depIdxs = []int32{
	5,  // 0: temporal.server.api.testpilot.v1.Program.roles:type_name -> temporal.server.api.testpilot.v1.Role
	6,  // 1: temporal.server.api.testpilot.v1.Program.slots:type_name -> temporal.server.api.testpilot.v1.Slot
	7,  // 2: temporal.server.api.testpilot.v1.Program.observations:type_name -> temporal.server.api.testpilot.v1.Observation
	8,  // 3: temporal.server.api.testpilot.v1.Program.entrypoints:type_name -> temporal.server.api.testpilot.v1.Entrypoint
	13, // 4: temporal.server.api.testpilot.v1.Program.cleanup:type_name -> temporal.server.api.testpilot.v1.Cleanup
	15, // 5: temporal.server.api.testpilot.v1.Program.evidence:type_name -> temporal.server.api.testpilot.v1.EvidenceDeclaration
	4,  // 6: temporal.server.api.testpilot.v1.Program.required_settings:type_name -> temporal.server.api.testpilot.v1.RequiredSetting
	16, // 7: temporal.server.api.testpilot.v1.Program.instruction_defaults:type_name -> temporal.server.api.testpilot.v1.InstructionLimits
	2,  // 8: temporal.server.api.testpilot.v1.Program.activity_external_settlements:type_name -> temporal.server.api.testpilot.v1.ActivityExternalSettlement
	3,  // 9: temporal.server.api.testpilot.v1.Program.activity_reset_settlements:type_name -> temporal.server.api.testpilot.v1.ActivityResetSettlement
	17, // 10: temporal.server.api.testpilot.v1.ActivityExternalSettlement.carrier:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 11: temporal.server.api.testpilot.v1.ActivityExternalSettlement.held:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 12: temporal.server.api.testpilot.v1.ActivityExternalSettlement.answer:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 13: temporal.server.api.testpilot.v1.ActivityExternalSettlement.request_cancel:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 14: temporal.server.api.testpilot.v1.ActivityExternalSettlement.settlement:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 15: temporal.server.api.testpilot.v1.ActivityExternalSettlement.cleanup:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 16: temporal.server.api.testpilot.v1.ActivityResetSettlement.carrier:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 17: temporal.server.api.testpilot.v1.ActivityResetSettlement.held:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 18: temporal.server.api.testpilot.v1.ActivityResetSettlement.reset_request:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 19: temporal.server.api.testpilot.v1.ActivityResetSettlement.settlement:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	17, // 20: temporal.server.api.testpilot.v1.ActivityResetSettlement.cleanup:type_name -> temporal.server.api.testpilot.v1.InstructionReference
	0,  // 21: temporal.server.api.testpilot.v1.Role.kind:type_name -> temporal.server.api.testpilot.v1.RoleKind
	18, // 22: temporal.server.api.testpilot.v1.Slot.value:type_name -> temporal.server.api.testpilot.v1.ValueType
	19, // 23: temporal.server.api.testpilot.v1.Slot.opaque_handle:type_name -> google.protobuf.Empty
	18, // 24: temporal.server.api.testpilot.v1.Observation.type:type_name -> temporal.server.api.testpilot.v1.ValueType
	19, // 25: temporal.server.api.testpilot.v1.Entrypoint.controller:type_name -> google.protobuf.Empty
	9,  // 26: temporal.server.api.testpilot.v1.Entrypoint.workflow:type_name -> temporal.server.api.testpilot.v1.WorkflowActivation
	10, // 27: temporal.server.api.testpilot.v1.Entrypoint.activity:type_name -> temporal.server.api.testpilot.v1.ActivityActivation
	12, // 28: temporal.server.api.testpilot.v1.Entrypoint.nexus_handler:type_name -> temporal.server.api.testpilot.v1.NexusHandlerActivation
	20, // 29: temporal.server.api.testpilot.v1.Entrypoint.instructions:type_name -> temporal.server.api.testpilot.v1.InstructionNode
	11, // 30: temporal.server.api.testpilot.v1.ActivityActivation.attempt_numbering:type_name -> temporal.server.api.testpilot.v1.AttemptNumbering
	20, // 31: temporal.server.api.testpilot.v1.Cleanup.instructions:type_name -> temporal.server.api.testpilot.v1.InstructionNode
	21, // 32: temporal.server.api.testpilot.v1.ProgramLimits.max_duration:type_name -> google.protobuf.Duration
	21, // 33: temporal.server.api.testpilot.v1.ProgramLimits.cleanup_duration:type_name -> google.protobuf.Duration
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_temporal_server_api_testpilot_v1_program_proto_init() }
func file_temporal_server_api_testpilot_v1_program_proto_init() {
	if File_temporal_server_api_testpilot_v1_program_proto != nil {
		return
	}
	file_temporal_server_api_testpilot_v1_evidence_proto_init()
	file_temporal_server_api_testpilot_v1_expression_proto_init()
	file_temporal_server_api_testpilot_v1_instruction_proto_init()
	file_temporal_server_api_testpilot_v1_value_proto_init()
	file_temporal_server_api_testpilot_v1_program_proto_msgTypes[5].OneofWrappers = []any{
		(*Slot_Value)(nil),
		(*Slot_OpaqueHandle)(nil),
	}
	file_temporal_server_api_testpilot_v1_program_proto_msgTypes[7].OneofWrappers = []any{
		(*Entrypoint_Controller)(nil),
		(*Entrypoint_Workflow)(nil),
		(*Entrypoint_Activity)(nil),
		(*Entrypoint_NexusHandler)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_testpilot_v1_program_proto_rawDesc), len(file_temporal_server_api_testpilot_v1_program_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_testpilot_v1_program_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_testpilot_v1_program_proto_depIdxs,
		EnumInfos:         file_temporal_server_api_testpilot_v1_program_proto_enumTypes,
		MessageInfos:      file_temporal_server_api_testpilot_v1_program_proto_msgTypes,
	}.Build()
	File_temporal_server_api_testpilot_v1_program_proto = out.File
	file_temporal_server_api_testpilot_v1_program_proto_goTypes = nil
	file_temporal_server_api_testpilot_v1_program_proto_depIdxs = nil
}
