import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {read,out,sha,git} from './capture.mjs';
import {reconstruct} from './reconstruct.mjs';
import {functionSpans} from './proof.mjs';
const events=label=>read(out+'/'+label+'.stdout').toString().split('\n').flatMap(l=>{try{return [JSON.parse(l)];}catch{return [];}});
const guardPaths=['tools/gomad3/deterministicio/profile.go','tools/gomad3/internal/preparation/preparation.go','tools/gomad3/runner/runner.go'];
import {completionDelta} from './completion-additive.mjs';
const fun=(path,name)=>{const f=functionSpans(read(path).toString()).filter(f=>f.signature.startsWith('func '+name+'('));assert.equal(f.length,1);return {path,...f[0],sha256:sha(f[0].body),actual_owner:git(['log','-1','--format=%H %s','--',path]).toString().trim()};};
export function coverageProof(){
 const labels=['portable-controller','campaign-state-machines','portable-runner-pure-boundaries','portable-package-architecture','canonical-controller-after-mutations'];
 const tests=new Map();for(const label of labels){const receipt=JSON.parse(read(out+'/'+label+'.json'));assert.equal(receipt.exit,0);for(const e of events(label))if(e.Test&&!e.Test.includes('/')&&e.Action==='pass')tests.set(e.Package+'::'+e.Test,{package:e.Package,test:e.Test});}
 const broad=events('portable-runner-boundaries'),terminal=new Set(broad.filter(e=>e.Test&&['pass','fail','skip'].includes(e.Action)).map(e=>e.Test));
 const failed=broad.filter(e=>e.Test&&e.Action==='fail').map(e=>{const outputs=broad.filter(v=>v.Test===e.Test&&v.Output).map(v=>v.Output),descendant=broad.filter(v=>v.Test?.startsWith(e.Test+'/')&&v.OutputType==='error').map(v=>({test:v.Test,output:v.Output}));return {test:e.Test,outputs,descendant_errors:descendant,classification:outputs.some(s=>s.includes('host is linux/arm64'))?'explicit unsupported-host guard':outputs.some(s=>s.includes('preparation.stageError{stage:'))?'pre-executor preparation validation refusal: guard attribution is source-supported inference, raw error formatter hides inner error':descendant.length?'parent aggregates retained refused child cells':'retain exact failure; no green claim'};});
 const hung=broad.filter(e=>e.Action==='run'&&e.Test&&!terminal.has(e.Test)).map(e=>({test:e.Test,classification:'started but no terminal action before 600s capture timeout; periodic test waits executor.started after native preparation refusal; no assertion execution credited'}));
 assert.deepEqual(hung.map(e=>e.test),['TestRunReportsPeriodicProgressWhileTargetIsRunning']);
 const original=reconstruct().images['tools/gomad3/runner/seed_completion_characterization_test.go'];
 const current=[fun('tools/gomad3/runner/seed_completion_characterization_test.go','TestSeedCompletionKeepsCampaignStatistics'),fun('tools/gomad3/runner/seed_completion_characterization_test.go','TestSeedCompletionFaultsKeepCampaignStatistics'),fun('tools/gomad3/runner/completion_characterization_test.go','TestCompletionFaultsKeepReasonPrecedenceAndEvidence'),fun('tools/gomad3/runner/runner_test.go','TestRunRejectsSuccessfulRetentionWithoutReplayTranscript')];
 const rows=[{original:'supervision choice trace malformed',current_function:'TestSeedCompletionFaultsKeepCampaignStatistics',current_cell:'supervision rejected the choice trace',vector:'Attempted:1',exact_trigger:'execution.ErrChoiceTraceMalformed',whole_statistics:true},{original:'prepared target integrity',current_function:'TestSeedCompletionKeepsCampaignStatistics',current_cell:'prepared target integrity',vector:'Attempted:1',exact_trigger:'mutatingExecutor{}',whole_statistics:true},{original:'World record wrong seed8',current_function:'TestCompletionFaultsKeepReasonPrecedenceAndEvidence',current_cell:'World seed mismatch/seed',vector:'Attempted1 Failures0 DistinctFailures1',exact_trigger:'completionWorldRecord(t, 8)',whole_statistics:false,additional_whole_statistics_cell:'TestSeedCompletionFaultsKeepCampaignStatistics/malformed World preserves whole Attempted1 Distinct1 vector on same World-assessment early exit, but is a distinct malformed-payload trigger'},{original:'malformed semantic coverage',current_function:'TestCompletionFaultsKeepReasonPrecedenceAndEvidence',current_cell:'malformed semantic coverage/seed',vector:'Attempted1 Succeeded0 Failures0 Watchdogs0 DistinctFailures0',exact_trigger:'[]byte("not an I/O transcript")',whole_statistics:false,limitation:'shared table pins five completion counts, not independently all eight Statistics fields; exact original whole-statistics assertion and whole seed loop remain retained byte-for-byte as source proof'},{original:'success publication',current_function:'TestRunRejectsSuccessfulRetentionWithoutReplayTranscript',vector:'Attempted:1, every other field zero',exact_trigger:'&fakeExecutor{}, KeepSuccessesAll, limit1, bytes1<<20',whole_statistics:true,additive_restoration:true}];
 completionDelta();for(const row of rows){const f=current.find(f=>f.signature.startsWith('func '+row.current_function+'('));assert(f);if(row.current_cell)assert(f.body.includes(row.current_cell.split('/')[0]));if(['World seed mismatch/seed','malformed semantic coverage/seed'].includes(row.current_cell)){row.whole_statistics=true;row.additive_restoration=true;row.assertion_execution='unexecuted: native preparation guard prevents original completion assertion, then the added whole-statistics assertion';delete row.limitation;}}
 const inventory='.flow/artifacts/fn-110-gomad-minimize-the-runtime-patch/task-2/source-acceptance-20261007/raw/source-inventories-pinned',ireceipt=JSON.parse(read(inventory+'.json'));assert.equal(sha(read(inventory+'.json')),'d467060c7b6af8b4eb05f1d353854c32d76442fa72088031caaa149726cd97d0');assert.equal(sha(read(inventory+'.stdout')),ireceipt.stdout_sha256);assert.equal(ireceipt.stdout_sha256,'e5db8479e0f26b36dcac62da353bd3141aab8747b246d6c031efd6e056260635');assert.equal(ireceipt.exit,0);
 return {unique_portable_top_level_tests:tests.size,tests:[...tests.values()].sort((a,b)=>(a.package+a.test).localeCompare(b.package+b.test)),raw_observation_suites_not_additive:true,broad_gate:{exit:null,signal:'SIGTERM',timeout_seconds:600.117,failed_terminal_actions:failed,unterminated:hung,unstarted_selected_test_names_not_passed:true},original_early_characterization_bytes:original,early_migration_rows:rows,current_functions:current,guard_sources:guardPaths.map(path=>({path,sha256:sha(read(path))})),static_supported_source_inventory:{receipt:inventory+'.json',receipt_sha256:sha(read(inventory+'.json')),stdout_sha256:ireceipt.stdout_sha256,platforms:['darwin/arm64','linux/amd64'],reused:'only exact87 runtime bindings/raw72/archive independently rechecked in final-source-proof; no old whole-tree/full-host pass',native:false},mutation_scope:'Controller behavior sensitivity only; restored Runner publication assertion not reached on this host',native_owners:['fn-149','fn-128']};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const p=coverageProof();writeFileSync(out+'/'+(process.argv[2]??'coverage-preservation.json'),JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({portable_unique:p.unique_portable_top_level_tests,failed_observations:p.broad_gate.failed_terminal_actions.length,hung:p.broad_gate.unterminated.length,original_rows:5}));}
