import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {read,out,git,sha} from './capture.mjs';
import {reconstruct,original} from './reconstruct.mjs';
import {functionSpans} from './proof.mjs';
const parsed=label=>[...read(out+'/'+label+'.stdout').toString().matchAll(/^(tools\/gomad3\/[^:\n]+):(\d+):(\d+): ([^\n]+) \(([^)]+)\)$/gm)].map(m=>({path:m[1],line:+m[2],column:+m[3],message:m[4],rule:m[5],capture:label}));
function patchLines(path){const patch=read(original+'/task-only.patch').toString(),heads=[...patch.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],i=heads.findIndex(h=>h[2]===path);if(i<0)return {hunks:[],added:[]};const lines=patch.slice(heads[i].index+heads[i][0].length,i+1<heads.length?heads[i+1].index:patch.length).split('\n'),hunks=[],added=[];for(let n=0;n<lines.length;n++){const m=/^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/.exec(lines[n]);if(!m)continue;const oc=m[2]===undefined?1:+m[2],nc=m[4]===undefined?1:+m[4];hunks.push(lines[n]);let o=0,k=0,cursor=+m[3];while(o<oc||k<nc){const c=lines[++n][0];if(c==='+')added.push(cursor);if(c!=='-'){k++;cursor++;}if(c!=='+')o++;}}return {hunks,added};}
const name=f=>/^func (?:\([^)]*\) )?(\w+)\(/.exec(f.signature)?.[1];
function locate(source,current,line){let fn=functionSpans(source).filter(f=>f.signature===current.signature);if(!fn.length)fn=functionSpans(source).filter(f=>name(f)===name(current)&&f.signature.startsWith('func (')===current.signature.startsWith('func ('));assert.equal(fn.length,1,name(current));const lines=fn[0].body.split('\n'),hits=lines.flatMap((s,i)=>s===line?[i]:[]);assert.equal(hits.length,1,'unique exact line in function '+name(current));const at=hits[0];return {signature:fn[0].signature,line:fn[0].start+at,context:lines.slice(Math.max(0,at-2),at+3).join('\n')};}
export function buildLint(){
 const r=reconstruct(),fast=parsed('final-configured-fast-lint'),relevant=parsed('final-relevant-unfiltered-lint');assert.equal(fast.length,56);assert.equal(relevant.length,17);
 const unique=[...new Map([...fast,...relevant].map(f=>[f.path+':'+f.line+':'+f.column+':'+f.message,f])).values()];
 const findings=unique.map(f=>{
  const s=read(f.path).toString(),lines=s.split('\n'),current=functionSpans(s).find(fn=>fn.start<=f.line&&fn.end>=f.line);assert(current,f.path+':'+f.line);
  const blame=git(['blame','--porcelain','-L',f.line+','+f.line,'--',f.path]).toString(),commit=blame.split(' ')[0],owner=git(['show','-s','--format=%H%n%s%n%B',commit]).toString();
  const row={...f,current_function:{signature:current.signature,start:current.start,end:current.end,sha256:sha(current.body)},current_line:lines[f.line-1],current_source_sha256:sha(s),actual_git_blame:blame,actual_source_owner:owner,aggregate_correction_owner:'fn109.21 remains open; actual originating commit/function retained, not waived',in_original_task3_paths:Object.hasOwn(r.images,f.path)};
  if(row.in_original_task3_paths){const pre=locate(r.preimages[f.path],current,row.current_line),post=locate(r.images[f.path],current,row.current_line),h=patchLines(f.path);assert.equal(pre.context,post.context);assert(!h.added.includes(post.line));return {...row,original_pre:pre,original_post:post,original_patch_hunks:h.hunks,introduced_by_original_task3:false,proof:'exact unique function-scoped line and five-line context identical in pre/post, outside added patch lines'};}
  if(['tools/gomad3/runner/runner_test.go','tools/gomad3/runner/completion_characterization_test.go'].includes(f.path)){const prior=read(out+(f.path.endsWith('/runner_test.go')?'/runner-test-before.txt':'/completion-test-before.txt')).toString(),old=functionSpans(prior).filter(f=>f.signature===current.signature);assert.equal(old.length,1);assert.equal(old[0].body,current.body,'whole finding-owning function unchanged by additive restoration');const index=f.line-current.start,context=current.body.split('\n').slice(Math.max(0,index-2),index+3).join('\n');return {...row,additive_before:{signature:old[0].signature,line:old[0].start+index,context},additive_after:{signature:current.signature,line:f.line,context},whole_owning_function_sha256:sha(current.body),introduced_by_additive_restoration:false,proof:'exact entire finding-owning function byte-identical in pre/post; precise line offset and five-line context retained, outside the sole admitted edited function in this file'};}
  return {...row,proof:'outside every original task3 patch header and sole admitted test edit; exact current source/function/blame retained'};
 });
 return {configured_fast_base:'48a2c8cd9eafe45e435022838c72864be16453f3',base_derivation:'git parent of actual original rebased task3 transition commit0885a304; retained local task3 Runner preimage additionally contains task2 uncommitted postimage and is separately reconstructed, not substituted by adjacent task2 baseline',fast_findings:fast.length,unfiltered_relevant_findings:relevant.length,unique_findings:findings.length,findings,original_scope_findings:findings.filter(f=>f.in_original_task3_paths).length,waivers_added:[],approved_exact_controller_panic_sites_only:2,global_green:false};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const p=buildLint();writeFileSync(out+'/'+(process.argv[2]??'lint-preservation.json'),JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({fast:p.fast_findings,relevant:p.unfiltered_relevant_findings,unique:p.unique_findings,original_scope:p.original_scope_findings}));}
