import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {read,sha,git,out,sources} from './capture.mjs';
import {original,reconstruct} from './reconstruct.mjs';
import {apply,patchImages} from '../../task-2/source-acceptance-20261008/owner-chain.mjs';
import {reconstruct as task2} from '../../task-2/source-acceptance-20261008/reconstruct.mjs';
export const base='b4dd0531c0a7e0a31a2285d307484f2d41f02559';
export const originalCommit='0885a30436980147d38be484f0e048e1c02f408f';
export const originalBase=git(['rev-parse',originalCommit+'^']).toString().trim();
const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
export function functionSpans(s){const lines=s.split('\n'),starts=lines.flatMap((l,i)=>l.startsWith('func ')?[i]:[]);return starts.map((n,i)=>({signature:lines[n],start:n+1,end:starts[i+1]??lines.length,body:lines.slice(n,starts[i+1]??lines.length).join('\n')}));}
const body=(s,name)=>{const f=functionSpans(s).filter(f=>new RegExp('^func (?:\\([^)]*\\) )?'+name+'\\(').test(f.signature));assert.equal(f.length,1,name);return f[0].body;};
const loop=s=>{const a=s.indexOf('\trecordCompletion := func('),b=s.indexOf('\n\tif coverageHasSemantic(config.Coverage) {',a);assert(a>0&&b>a);return s.slice(a,b);};
export function build(){
 const r=reconstruct(),rp='tools/gomad3/runner/runner.go',cp='tools/gomad3/runner/internal/campaign/controller.go',ct='tools/gomad3/runner/internal/campaign/controller_test.go',sc='tools/gomad3/runner/seed_completion_characterization_test.go',a3='a3b9f80efab9356c0be2080779133337e2471ac0',merge='ca3345469a2541b7686606268b0f19cde030a8fe';
 const two=task2(),five=patchImages(5),six=patchImages(6);assert.equal(r.preimages[rp],two.images[rp]);assert.equal(r.images[rp],five.pre[rp]);assert.equal(five.images[rp],six.pre[rp]);
 const seven=original.replace(/task-3$/,'task-7'),pre7=read(seven+'/preimages/'+rp).toString();assert.equal(pre7,six.images[rp]);const p7=read(seven+'/task-only.patch').toString(),hh=[...p7.matchAll(/^--- (a\/[^\n]+|\/dev\/null)\n\+\+\+ b\/([^\n]+)\n/gm)],j=hh.findIndex(h=>h[2]===rp);assert(j>=0);const post7=apply(p7.slice(hh[j].index+hh[j][0].length,j+1<hh.length?hh[j+1].index:p7.length),pre7,rp);assert.equal(sha(post7),JSON.parse(read(seven+'/final-source.json')).source[rp]);assert.equal(post7,git(['show',a3+':'+rp]).toString());
 const originalLoop=loop(r.images[rp]),a3Loop=loop(post7),currentLoop=loop(read(rp).toString());assert.equal(originalLoop,a3Loop);
 const mappings=[['campaign.Completion{}','campaign.CompletedUnclassified()'],['campaign.Completion{Kind: campaign.CompletionSuccess}','campaign.CompletedSuccess()'],['campaign.Completion{Kind: campaign.CompletionCancelled}','campaign.CompletedCancelled()'],['campaign.Completion{\n\t\t\tKind: campaign.CompletionFailure, Domain: outcome.Domain, Reason: outcome.Reason, DistinctFailures: uint64(len(distinct)),\n\t\t}','campaign.CompletedFailure(outcome.Domain, outcome.Reason, uint64(len(distinct)))'],['MaximumBytes: retention.maximumBytes, TargetPool:','MaximumBytes: retention.maximumBytes, Key: artifact.StoreKeyExecution, TargetPool:']];
 let projected=originalLoop;const replacements=mappings.map(([from,to])=>{const count=projected.split(from).length-1;assert(count>0,from);projected=projected.split(from).join(to);return {from,to,count,owner:from.startsWith('MaximumBytes')?'DONE fn112.16 / 6be0755f via ca334':'rebased fn109.3 / 09c1f3cc via ca334'};});assert.equal(projected,currentLoop,'whole seed completion loop has only exact attributed replacements');
 assert.equal(read(rp).toString(),git(['show',merge+':'+rp]).toString());assert.equal(read(sc).toString(),git(['show',merge+':'+sc]).toString());
 assert.equal(r.images[cp],git(['show',a3+':'+cp]).toString());assert.equal(r.images[ct],git(['show',a3+':'+ct]).toString());
 const changes=r.rows.map(e=>({...e,later_first_parent_commits:git(['log','--first-parent','--format=%H %s',a3+'..HEAD','--',e.path]).toString().trim().split('\n').filter(Boolean),merge_sha256:sha(git(['show',merge+':'+e.path]))}));
 const methods=['Next','Stop','Stopped','Active','Done','Finalize','Statistics'].map(name=>{const before=body(r.images[cp],name),current=body(read(cp).toString(),name);assert.equal(before,current,name);return {name,sha256:sha(current),byte_identical:true};});
 const guard='\tif completion.Kind == CompletionInvalid || completion.Kind > CompletionFailure {\n\t\tpanic("gomad3: completed a campaign attempt without a classification")\n\t}\n';const complete=body(read(cp).toString(),'Complete');assert(complete.indexOf(guard)>0);assert(complete.indexOf(guard)<complete.indexOf('\tcontroller.active--'));assert(complete.indexOf('panic("gomad3: completed an inactive campaign attempt")')<complete.indexOf('\tcontroller.active--'));assert.equal(sha(read(cp)),'043981c7ac6e97713971c62a308693089ec0f0499e75d52d6c7d9474eec843de');
 const callsites=read(rp).toString().split('\n').flatMap((line,i)=>line.includes('recordCompletion(campaign.')?[{line:i+1,body:line,blame:git(['blame','--porcelain','-L',(i+1)+','+(i+1),'--',rp]).toString(),context:read(rp).toString().split('\n').slice(Math.max(0,i-2),i+3).join('\n')}]:[]);assert.equal(callsites.length,21);
 const firstDir='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-21/baseline-reconstruction',be=JSON.parse(read(firstDir+'/evidence.json')),manifest=read(firstDir+'/source.sha256');assert.equal(sha(manifest),'d78601b3176195f8cc06860f5499e757a2d04333b9211f0ed13a92976b017845');const baselineRows=manifest.toString().trim().split('\n').map(l=>{const m=/^([a-f0-9]{64})  (.+)$/.exec(l);assert(m);assert.equal(sha(read(be.scratch_path+'/'+m[2])),m[1]);return {path:m[2],sha256:m[1]};});assert.equal(baselineRows.length,670);
 const bindPath='.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-5/source-acceptance-20261008/source-binding.json',bind=JSON.parse(read(bindPath));assert.equal(bind.exact_bindings.length,87);for(const e of bind.exact_bindings)assert.equal(sha(read(e.path)),e.sha256);assert.equal(sha(read(bind.archive.path)),bind.archive.sha256);const rawPath=bind.retained_raw_manifest.path,raw=JSON.parse(read(rawPath));assert.equal(sha(read(rawPath)),bind.retained_raw_manifest.sha256);let rawBytes=0;for(const e of raw){const b=read(rawPath.replace('/raw-manifest.json','/raw/')+(e.retained_name??e.name));if(e.retained_name)assert.equal(sha(b),e.retained_sha256);const decoded=e.encoding==='utf8-json-string'?Buffer.from(JSON.parse(b).value):b;assert.equal(decoded.length,e.bytes);assert.equal(sha(decoded),e.sha256);rawBytes+=decoded.length;}assert.equal(rawBytes,521317);assert.equal(raw.length,72);
 const changed=bind.input_closure.filter(e=>sha(read(e.path))!==e.current_sha256);assert.equal(changed.length,3);assert.deepEqual(changed.map(e=>e.path).sort(),['tools/gomad3/runner/completion_characterization_test.go','tools/gomad3/runner/internal/campaign/retained_evidence_test.go','tools/gomad3/runner/runner_test.go']);
 const originalEarly=r.images[sc],earlyNames=[...originalEarly.matchAll(/name: "([^"]+)"/g)].map(m=>m[1]);assert.equal(earlyNames.length,5);const refs=[original+'/source-pre.json',original+'/source-post.json',original+'/task-only.patch',original+'/early-return-audit.md',original+'/early-characterization-before.log',firstDir+'/evidence.json',firstDir+'/source.sha256',bindPath,rawPath,bind.archive.path,'.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-9/deferred-cli-runner-mapping.md','.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-28/exact-invariant-exception-20261007/evidence.json','.flow/artifacts/source-unblocking-20261007/owner-decisions.md'].map(ref);
 const userFiles=['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(ref);assert.equal(userFiles[0].sha256,'97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188');assert.equal(userFiles[1].sha256,'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287');
 return {base_commit:base,source_identity_sha256:sha(JSON.stringify(sources())),original_task3:{commit:originalCommit,committed_parent:originalBase,local_preimage_basis:'retained four preimages; Runner is uncommitted retained task2 postimage, not rebased committed parent',four_modified_postimages:4,new_postimages:1,changes},runner_chain:{task2_post_equals_task3_pre:true,task3_post_equals_task5_pre:true,task5_post_equals_task6_pre:true,task6_post_equals_task7_pre:true,task7_post_equals_a3:true,whole_completion_loop_bytes:Buffer.byteLength(currentLoop),original_loop_sha256:sha(originalLoop),current_loop_sha256:sha(currentLoop),attributed_replacements:replacements,callsites},unchanged_methods:methods,invariants:{source:ref(cp),guard_before_mutation:true,exact_two_sites_only:true,owner:'DONE fn109.28 bounded existing exception; no new exception'},early_characterization:{original_exact_bytes:originalEarly,original_sha256:sha(originalEarly),names:earlyNames,original_assertion:originalEarly.slice(originalEarly.indexOf('\t\t\tgot := campaign.CampaignStatistics{')),current_seed_table:ref(sc),current_error_table:ref('tools/gomad3/runner/completion_characterization_test.go'),missing_exact_success_trigger_whole_statistics_assertion:true,original_world_vector:'Attempted=1, Succeeded=0, Failures=0, Watchdogs=0, ReplayDivergences=0, Cancelled=0, DistinctFailures=1, StopReason=""'},first_fn109_baseline:{commit:be.base_revision,kind:be.baseline_kind,inputs:baselineRows.length,manifest:ref(firstDir+'/source.sha256'),later38957053_substitution:false},static_bindings:{inputs:87,raw_files:72,raw_bytes:rawBytes,archive:bind.archive,platforms:['darwin/arm64','linux/amd64'],unchanged_closure:1222,changed_unreused:changed.map(e=>({path:e.path,current_sha256:sha(read(e.path)),owner:'DONE fn112.16',reused:false})),native_qualification:false},references:refs,user_files:userFiles,native_qualification:false,review_verdict:null,product_edits:[]};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const p=build();writeFileSync(out+'/source-proof.json',JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({original_postimages:5,call_sites:p.runner_chain.callsites.length,source_identity:p.source_identity_sha256}));}
