import assert from 'node:assert/strict';
import {read,write,sha,git} from './capture.mjs';
import {patchImages} from '../../task-2/source-acceptance-20261008/owner-chain.mjs';
import {spans} from '../../task-4/source-acceptance-20261008/proof.mjs';
import {alignment} from '../../task-4/source-acceptance-20261008/attribution.mjs';
const dir='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-6/source-acceptance-20261008',patch=patchImages(6),name=f=>/^func (?:\([^)]*\) )?(\w+)/.exec(f.signature)[1],rows=[];
function match(path,current,line,images){const names=[name(current),name(current).replace(/With$/,''),name(current)==='validateCampaignRequest'?'validateConfig':name(current)],old=spans(images[path]??'').find(f=>names.includes(name(f)));if(!old)return null;const pair=alignment(old.body,current.body).find(p=>p.after===line-current.start);return {signature:old.signature,body:old.body,sha256:sha(old.body),matched:!!pair,original_line:pair?old.start+pair.before:null,exact_line:pair?old.body.split('\n')[pair.before]:null};}
for(const label of ['configured-fast-lint','unfiltered-scoped-lint'])for(const m of read(dir+'/'+label+'.stdout').toString().matchAll(/^(tools\/gomad3\/[^:]+):(\d+):(\d+): (.+) \(([^)]+)\)$/gm)){
 const path=m[1],line=Number(m[2]),s=read(path).toString(),f=spans(s).find(f=>line>=f.start&&line<f.end),exact=s.split('\n')[line-1];assert(f,path+':'+line);const pre=match(path,f,line,patch.pre),post=match(path,f,line,patch.images);for(const old of [pre,post])if(old?.matched)assert.equal(old.exact_line,exact);
 const blame=git(['blame','--porcelain','-L',line+','+line,'--',path]).toString(),owner=blame.split(' ')[0];assert(/^[a-f0-9]{40}$/.test(owner)&&!/^0+$/.test(owner));const parents=git(['show','-s','--format=%P',owner]).toString().trim().split(' ').filter(Boolean);
 rows.push({label,path,line,column:Number(m[3]),message:m[4],rule:m[5],exact_line:exact,current_function:{...f,sha256:sha(f.body)},original_task6_pre:pre,original_task6_post:post,blame,owner,owner_metadata:git(['show','-s','--format=%H%n%P%n%B',owner]).toString(),owner_parent_hunks:parents.map(parent=>({parent,patch:git(['diff','--no-ext-diff','--no-renames',parent,owner,'--',path]).toString()})),classification:pre?.matched?'Task6 preimage exact statement':post?.matched?'Task6 original postimage exact statement; no waiver inferred':'Task6 function alignment absent or out of original edit set; actual later/source owner bound, not auto-waived',worker_introduced:false,exception_applied:false});
}
assert.equal(rows.filter(r=>r.label==='configured-fast-lint').length,66);assert.equal(rows.filter(r=>r.label==='unfiltered-scoped-lint').length,91);
write('lint-attribution.json',{findings:rows,counts:{fast:66,scoped:91},worker_product_changes:[],all_source_statement_bytes_preexist_worker:true,global_green:false,full_lint_rerun:false,old263_or261_not_current_full_claim:true,new_waivers:[],method:'Exact named-function line alignment to task6 pre/post; unmatched/out-of-edit paths retain current line blame and actual owner-parent diffs. No lint finding is hidden or suppression added.'});console.log('All 157 actual scoped/fast lint observations bound without waiver.');
