import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {read,write,sha,git} from './capture.mjs';
import {ref} from './proof.mjs';
import {spans} from '../../task-4/source-acceptance-20261008/proof.mjs';
const dir='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-6/source-acceptance-20261008';
const parse=label=>read(dir+'/'+label+'.stdout').toString().split('\n').flatMap(l=>{try{return [JSON.parse(l)];}catch{return [];}});
export function observations(){
 const suites=['portable-private-operations','portable-api-external','portable-execution-controls','portable-minimizer-plan'].map(label=>{const receipt=JSON.parse(read(dir+'/'+label+'.json')),events=parse(label);assert.equal(sha(read(dir+'/'+label+'.stdout')),receipt.stdout_sha256);assert.equal(sha(read(dir+'/'+label+'.stderr')),receipt.stderr_sha256);return {label,receipt:ref(dir+'/'+label+'.json'),exit:receipt.exit,counts:receipt.top_level_counts,identities:receipt.tests,failures:receipt.tests.filter(t=>t.action==='fail').map(test=>{
 const raw=events.filter(e=>e.Action==='output'&&e.Package===test.package&&(e.Test===test.test||e.Test?.startsWith(test.test+'/'))&&e.OutputType==='error');assert(raw.length,'failure must have own or descendant raw assertion '+test.test);const output=raw.map(e=>e.Output).join('');
 const cause=output.includes('stat pinned Go command')?'Direct missing patched-driver diagnostic in artifact construction before operation assertion':output.includes('host is linux/arm64')?'Direct unsupported-host guard diagnostic before operation executor':output.includes('choice trace unterminated')?'Actual stock child execution produced an unterminated choice trace; replay negative branch unverified':test.test.startsWith('TestCancellationIsAHostFailure')?'Raw stageError stage=validation; inner error text not printed. Source-supported inference: common preparation validates profile against actual linux/arm64 before executing injected cancellation fake':test.test.includes('Resume')?'Consequential setup/lifecycle assertion: zero attempted executions or recoverable-failure state. Source-supported host-validation setup inference, not successful resume-supervision execution':'Unclassified raw failure retained; no gate-green inference';
 return {...test,raw_events:raw,causality:cause,source_supported_inference:!output.includes('stat pinned Go command')&&!output.includes('host is linux/arm64')&&!output.includes('choice trace unterminated'),failure_assertion_executed:true,requested_operation_behavior_validated:false};
 })};});
 assert.deepEqual(suites.map(s=>s.counts),[{pass:11,fail:41,skip:0},{pass:9,fail:0,skip:0},{pass:13,fail:4,skip:0},{pass:48,fail:0,skip:0}]);
 const paths=['tools/gomad3/internal/preparation/preparation.go','tools/gomad3/deterministicio/profile.go','tools/gomad3/deterministicio/bootstrap.go','tools/gomad3/runner/completion_characterization_test.go','tools/gomad3/runner/replay_operation_test.go','tools/gomad3/runner/executor_injection_characterization_test.go','tools/gomad3/runner/runner_test.go','tools/gomad3/runner/minimize_operation.go','tools/gomad3/runner/replay_operation.go','tools/gomad3/runner/resume.go','tools/gomad3/runner/internal/execution/process_test.go'];
 const source=paths.map(path=>({binding:ref(path),functions:spans(read(path).toString()).filter(f=>/ValidatePreparedTarget|BootstrapFrame|Prepare|prepareWorkspace|publishReplayArtifact|TestCancellationIsAHostFailure|TestReplayDoesNotStartTarget|Resume|resumeConfiguration|replayWith|replay$/.test(f.signature)).map(f=>({...f,sha256:sha(f.body)}))}));
 return {suites,source,all_top_and_child_identities_retained:true,suites_not_additive_native:false,portable_passes_are_partial:true,native_pass:false,full_host_pass:false,broad_gate_not_repeated:true,earlier_full_host:{exit:2,seconds:179,only_post_delta:'coordinator_transport_test.go',log:ref('.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-6/full-host.log')},task3_broad_hang_transferred_seconds:600,task5_full_cli:'89 pass / 3 host-driver fail; historical separate suite, not rerun or rounded green'};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const value=observations(),p='tools/gomad3/runner/internal/execution/process_test.go',lines=read(p).toString().split('\n');value.stock_runtime_choice_trace_causality={binding:ref(p),exact_lines_981_987:lines.slice(980,987),stock_identity:JSON.parse(read(dir+'/portable-execution-controls.json')).tool_sha256.go,interpretation:'Choice helper executes runChoiceRunnableTarget and os.Exit without manufacturing a trace. Stock-compiled helper does not contain patched-runtime recording. Each of four actual unterminated-trace failures remains failed, not unsupported-host output or skip.'};write('verified-observations.json',value);console.log('Actual top/subtest results and exact raw failure causality retained.');}
