import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {existsSync} from 'node:fs';
import {out,root,sha,read,git,sources,board,write} from './capture.mjs';
import {patchImages} from '../../task-2/source-acceptance-20261008/owner-chain.mjs';
import {spans} from '../../task-4/source-acceptance-20261008/proof.mjs';
import {alignment} from '../../task-4/source-acceptance-20261008/attribution.mjs';
import {staticNarrow,lineage} from '../../task-5/source-acceptance-20261008/proof.mjs';
export const original='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-6';
export const ref=p=>({path:p,bytes:read(p).length,sha256:sha(read(p))});
const name=f=>/^func (?:\([^)]*\) )?(\w+)/.exec(f.signature)[1];
const named=(s,n)=>spans(s).find(f=>name(f)===n);
export function build(){
 const final=JSON.parse(read(original+'/final-source.json')),pre=JSON.parse(read(original+'/preimages.json')),patch=patchImages(6),host=JSON.parse(read(original+'/full-host-source.json'));
 assert.equal(final.files.length,31);assert.equal(patch.paths,31);assert.equal(patch.patch_sha256,final.task_only_patch_sha256??'c2d1f412be6b644540a07b713c6548023f29668ee53893484a5688366ebe36c5');
 for(const e of pre)assert.equal(sha(read(original+'/preimages/'+e.path)),e.sha256,e.path+' retained preimage');
 const hostDelta=final.files.filter(e=>e.post_sha256!==host.files.find(h=>h.path===e.path)?.post_sha256).map(e=>e.path);assert.deepEqual(hostDelta,['tools/gomad3/runner/coordinator_transport_test.go']);
 const local='a3b9f80efab9356c0be2080779133337e2471ac0',rebased=git(['rev-parse','a619f541b8']).toString().trim(),merged=git(['rev-parse','ca334546']).toString().trim();
 const owners=final.files.map(e=>({path:e.path,original_pre_sha256:e.pre_sha256,original_post_sha256:e.post_sha256,local_integrated_sha256:sha(git(['show',local+':'+e.path])),rebased_implementation_sha256:git(['ls-tree',rebased,'--',e.path]).length?sha(git(['show',rebased+':'+e.path])):null,merge_sha256:sha(git(['show',merged+':'+e.path])),current_sha256:sha(read(e.path)),current_equals_original:sha(read(e.path))===e.post_sha256,actual_owner_transitions:lineage(e.path)}));
 const mappings=read('.flow/artifacts/fn-112-gomad-determinism-assurance-and-test/task-9/mapping.tsv').toString().trim().split('\n').map(l=>l.split('\t')),tests=[];
 const currentTests=git(['ls-files','tools/gomad3']).toString().trim().split('\n').filter(p=>p.endsWith('_test.go')).flatMap(path=>spans(read(path).toString()).filter(f=>name(f).startsWith('Test')).map(f=>({path,...f})));
 for(const [phase,images] of [['pre',patch.pre],['post',patch.images]])for(const [path,s] of Object.entries(images))if(path.endsWith('_test.go'))for(const old of spans(s).filter(f=>name(f).startsWith('Test'))){
  const map=mappings.filter(row=>row[1]?.split('/')[0]===name(old)),currentSource=read(path).toString();let current=named(currentSource,name(old));if(!current&&map.length)current=currentTests.find(f=>name(f)===map[0][3]?.split('/')[0]);
  const seedMigration=name(old)==='TestRunEarlyCompletionCountersRemainUnclassified'?JSON.parse(read('.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-3/source-acceptance-20261008/accepted-coverage-proof.json')):null;
  if(seedMigration){current=named(currentSource,'TestSeedCompletionFaultsKeepCampaignStatistics');for(const f of seedMigration.current_functions)assert.equal(named(read(f.path).toString(),name(f)).body,f.body,'accepted task3 current assertion body '+name(f));}
  if(!current&&map.length&&map.every(row=>row[3]==='-')){tests.push({phase,path,test:name(old),original:old,original_sha256:sha(old.body),current:null,consolidation_mapping:map,owner_parent_hunks:lineage(path),interpretation:'Explicit historical fn112.9 deleted characterization row; current task state is Todo, no acceptance waiver inferred. Original complete assertions retained for source review.'});continue;}
  assert(current,path+' unmapped original test '+name(old));const pairs=alignment(old.body,current.body),oldLines=old.body.split('\n'),unmatched=oldLines.flatMap((line,i)=>pairs.some(p=>p.before===i)?[]:[{line:old.start+i,text:line,assertion_candidate:/t\.(Fatal|Error)|^\s*if /.test(line)}]);
  tests.push({phase,path,test:name(old),current_test:name(current),original:old,current,original_sha256:sha(old.body),current_sha256:sha(current.body),exact:old.body===current.body,exact_line_alignment:pairs,unmatched_original_lines:unmatched,consolidation_mapping:map,accepted_task3_assertion_mapping:seedMigration?{receipt:ref('.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/task-3/source-acceptance-20261008/accepted-coverage-proof.json'),rows:seedMigration.early_migration_rows,current_functions:seedMigration.current_functions,current_function_bytes_rechecked:true}:null,owner_path:path,interpretation:seedMigration?'Done task3 five-trigger assertion restoration re-bound to exact current named functions; native assertion execution remains unverified.':map.length?'Retained fn112.9 original/current assertion mapping; fn112.9 remains Todo, no current Done inferred.':'Exact original/current bodies and all unmatched conditions retained for source review; construction migration is not an assertion waiver.'});
 }
 const runner='tools/gomad3/runner/',entries=[['runner.go','Explore','exploreWith'],['resume.go','Resume','resumeWith'],['campaign_shard_execution.go','RunCampaignShard','runCampaignShardWith'],['portable_plan.go','CreateCampaignPlan','createCampaignPlanWith'],['replay_operation.go','Replay','replayWith'],['minimize_operation.go','Minimize','minimizeWith']];
 const wrappers=entries.map(([file,publicName,privateName])=>{const s=read(runner+file).toString(),pub=named(s,publicName),priv=named(s,privateName);assert(pub&&priv);assert(pub.body.includes(privateName+'(ctx, '));assert(pub.body.includes('executionDependencies{}'));assert(priv.signature.includes('dependencies executionDependencies'));return {path:runner+file,public:pub,private:priv,public_sha256:sha(pub.body),private_sha256:sha(priv.body)};});
 const relevant=['runner.go','resume.go','replay_operation.go','minimize_operation.go','campaign_shard_execution.go','portable_plan.go','campaign_options.go'].map(f=>runner+f);
 const contracts=relevant.flatMap(path=>spans(read(path).toString()).filter(f=>/campaignRequestFromSpecWith|campaignRequestForExplore|exploreWith|resumeConfiguration|validateCampaignRequest|simulationCapabilityForJob|replayWith|prepareWorkspace|replay$/.test(name(f))).map(f=>({path,...f,sha256:sha(f.body)})));
 const inventory='.flow/artifacts/fn-109-gomad-deepen-modules-and-tool-interfaces/go-interface-changes.md',inventoryCommit=git(['rev-parse','9b5ae6b39']).toString().trim(),inventoryOriginal=git(['show',inventoryCommit+':'+inventory]).toString();assert(inventoryOriginal.includes('CampaignSpec.Executor'));assert.equal(git(['rev-parse',inventoryCommit+'^']).toString().trim(),git(['rev-parse','8364bd6a0']).toString().trim());
 const beforeRows=JSON.parse(read(original.replace(/task-6$/,'task-2')+'/campaign-options-before.json')),currentRows=JSON.parse(read('tools/gomad3/runner/testdata/campaign-options-before.json')),afterRows=JSON.parse(read('tools/gomad3/runner/testdata/campaign-options-request-after.json'));assert.equal(beforeRows.length,75);assert.equal(currentRows.length,76);assert.equal(afterRows.length,76);for(const row of beforeRows)assert.deepEqual(currentRows.find(c=>c.name===row.name),row);assert.deepEqual(currentRows.filter(c=>!beforeRows.some(b=>b.name===c.name)).map(r=>r.name),['coverage-choice-probes']);
 const hostResult=JSON.parse(read(original+'/full-host-result.json'));assert.equal(hostResult.exit,2);assert.equal(hostResult.duration_seconds,179);assert.equal(sha(read(original+'/full-host.log')),hostResult.log_sha256);assert.equal(hostResult.log_sha256,'a2712309a0554f7e1d620c9159da0e18c7f46656112622ebf0ffd5e92dc6c219');
 const review=JSON.parse(read(original+'/working-tree-review.json'));assert.equal(review.verdict,'SHIP');assert.equal(review.timestamp,'2026-10-03T13:23:49.288652Z');
 const users=['.turbo/plans/gomad3-glossary-update.md','.turbo/technical-debt.md'].map(ref);assert.equal(users[0].sha256,'97868a86c0a263fbea61c336bd9557e4d71cf43ae4390e9a2449e6f7cd815188');assert.equal(users[1].sha256,'c219247c01fb305592f0314ec46971cee30f00e5985dbd280c1c9e3aafe60287');
 return {task:'fn-109-gomad-deepen-modules-and-tool-interfaces.6',base_commit:read('.flow/tmp/fn109-task6-base_commit').toString().trim(),head:git(['rev-parse','HEAD']).toString().trim(),source_identity_sha256:sha(JSON.stringify(sources())),board:board(),inventory:{current:ref(inventory),pre_edit_commit:inventoryCommit,pre_edit_parent:git(['rev-parse',inventoryCommit+'^']).toString().trim(),actual_commit_metadata:git(['show','-s','--format=%H%n%P%n%B',inventoryCommit]).toString(),pre_edit_sha256:sha(inventoryOriginal),pre_edit_body:inventoryOriginal,current_duplicate_section_gap:{start_line:232,claims:'Status implemented and updated to match result',contradictions:['targetExecutor/dependencies instead of executionRunner/executionDependencies','campaignRun embedding instead of campaignRequest','testdata/runnerconsumer/consumer.go and TestRunnerExternalConsumerCompiles instead of conformance/testdata/runner_external/consumer.go and TestRunnerRequestsCompileInExternalModule'],earlier_current_section_start_line:14,worker_edit:false,conductor_notified:true}},original:{snapshot_count:pre.length,preimage_manifest:ref(original+'/preimages.json'),final_count:31,final:ref(original+'/final-source.json'),patch:ref(original+'/task-only.patch'),full_host_source:ref(original+'/full-host-source.json'),full_host_result:ref(original+'/full-host-result.json'),full_host_log:ref(original+'/full-host.log'),full_host_exit:2,full_host_seconds:179,only_original_post_host_delta:hostDelta,actual_original_review:ref(original+'/working-tree-review.json'),historical_review_timestamp:review.timestamp,historical_review_model:review.model,historical_review_only:true},owners,test_function_mapping:tests,private_entrypoints:wrappers,contracts,canonical_options:{original_executed_rows:75,current_total_rows:76,new_row:'coverage-choice-probes',original_rows_byte_equivalent:true,before:ref('tools/gomad3/runner/testdata/campaign-options-before.json'),after:ref('tools/gomad3/runner/testdata/campaign-options-request-after.json'),fixtures_recaptured:false},static_bindings:staticNarrow(),external_fixture:{current:ref('tools/gomad3/internal/gomadtool/conformance/testdata/runner_external/consumer.go'),original:patch.images['tools/gomad3/internal/gomadtool/conformance/testdata/runner_external/consumer.go'],current_body:read('tools/gomad3/internal/gomadtool/conformance/testdata/runner_external/consumer.go').toString(),later_published_evidence_owner:'fn109.19; exact parent hunks in owners',current_equals_original:false},user_files:users,product_edits:[],review_verdict:null,native:false,full_host_pass:false,whole_spec_complete:false};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){write('source-proof.json',build());write('sources-current.json',sources());console.log('task6 source reconstruction and narrow static rebinding retained');}
